from pathlib import Path
p=Path('workflow-engine.js')
s=p.read_text()
# Strengthen confirmation normalization with reviewer observations as evidence inputs, never authority over final determination.
old="""function confirmationDetermination(project,record){const reasons=[],iterationId=String(recordValue(record,'CONFIRMATION_ITERATION_ID')||record?.relationships?.CONFIRMATION_ITERATION_ID||record?.scope?.iterationId||'').trim(),iteration=records(project,'iterations').find(r=>recordId(r,'iterations')===iterationId);if(!iteration){reasons.push('Confirmation iteration identity is missing.');return {determination:'UNDETERMINED',reasons};}const ev=evaluateIteration(project,iterationId,'UNCHANGED_CONFIRMATION');if(!ev.complete)reasons.push(...ev.reasons);const matrix=verificationMatrix(project,iterationId);if(matrix.expected.length===0||matrix.missing.length||matrix.duplicates.length||matrix.invalid.length)reasons.push('Confirmation verification matrix is incomplete or invalid.');const bad=matrix.verification.map(r=>effectiveDetermination('verification',r,testForResult(project,r),project)).filter(x=>x!=='SATISFIED');if(bad.length)reasons.push('Confirmation contains a non-satisfied effective verification result.');const regs=records(project,'regressions').filter(r=>upper(recordValue(r,'ACTIVE_RETIRED_STATE')||'ACTIVE')!=='RETIRED');for(const reg of regs){const id=recordId(reg,'regressions'),exec=currentRegressionExecutions(project,iterationId).filter(x=>String(recordValue(x,'REG_ID')||x.relationships?.REG_ID||'')===id&&upper(recordValue(x,'PHASE'))!=='PRE_CORRECTION');if(exec.length!==1||effectiveRegressionDetermination(project,exec[0]).determination!=='SATISFIED')reasons.push('Active regression '+id+' is not successfully evidenced in confirmation.');}const defects=confirmedDefects(project).filter(d=>String(d.scope?.iterationId||'')===iterationId);if(defects.length)reasons.push('Confirmation iteration has new confirmed defects.');for(const req of mandatoryRequirements(project,scopeForIteration(project,iterationId))){const f=comparisonFacts(project,requirementId(req),iterationId);if(!f.allSatisfied)reasons.push('Confirmation comparison is not all-satisfied for '+requirementId(req)+'.');}return {determination:reasons.length?'UNDETERMINED':'SATISFIED',reasons};}"""
new="""function confirmationObservationFacts(record){const adverse=key=>adjudicationAdverse(recordValue(record,key)),countLike=key=>{const value=recordValue(record,key);if(Array.isArray(value))return value.length;if(typeof value==='number'&&Number.isFinite(value))return value;return adverse(key)?1:0;};return {reportedNewRequirements:countLike('NEW_REQUIREMENTS'),reportedNewFailureCases:countLike('NEW_FAILURE_CASES'),reportedNewDefects:countLike('NEW_DEFECTS'),reportedNewVariance:countLike('NEW_VARIANCE')};}
function confirmationDetermination(project,record){const reasons=[],iterationId=String(recordValue(record,'CONFIRMATION_ITERATION_ID')||record?.relationships?.CONFIRMATION_ITERATION_ID||record?.scope?.iterationId||'').trim(),iteration=records(project,'iterations').find(r=>recordId(r,'iterations')===iterationId);if(!iteration){reasons.push('Confirmation iteration identity is missing.');return {determination:'UNDETERMINED',reasons,observations:confirmationObservationFacts(record)};}const ev=evaluateIteration(project,iterationId,'UNCHANGED_CONFIRMATION');if(!ev.complete)reasons.push(...ev.reasons);const matrix=verificationMatrix(project,iterationId);if(matrix.expected.length===0||matrix.missing.length||matrix.duplicates.length||matrix.invalid.length)reasons.push('Confirmation verification matrix is incomplete or invalid.');const bad=matrix.verification.map(r=>effectiveDetermination('verification',r,testForResult(project,r),project)).filter(x=>x!=='SATISFIED');if(bad.length)reasons.push('Confirmation contains a non-satisfied effective verification result.');const regs=records(project,'regressions').filter(r=>upper(recordValue(r,'ACTIVE_RETIRED_STATE')||'ACTIVE')!=='RETIRED');for(const reg of regs){const id=recordId(reg,'regressions'),exec=currentRegressionExecutions(project,iterationId).filter(x=>String(recordValue(x,'REG_ID')||x.relationships?.REG_ID||'')===id&&upper(recordValue(x,'PHASE'))!=='PRE_CORRECTION');if(exec.length!==1||effectiveRegressionDetermination(project,exec[0]).determination!=='SATISFIED')reasons.push('Active regression '+id+' is not successfully evidenced in confirmation.');}const defects=confirmedDefects(project).filter(d=>String(d.scope?.iterationId||'')===iterationId);if(defects.length)reasons.push('Confirmation iteration has new confirmed defects.');for(const req of mandatoryRequirements(project,scopeForIteration(project,iterationId))){const f=comparisonFacts(project,requirementId(req),iterationId);if(!f.allSatisfied)reasons.push('Confirmation comparison is not all-satisfied for '+requirementId(req)+'.');}const observations=confirmationObservationFacts(record);if(observations.reportedNewRequirements)reasons.push('Independent confirmation reported a newly discovered requirement.');if(observations.reportedNewFailureCases)reasons.push('Independent confirmation reported a newly discovered or missed failure case.');if(observations.reportedNewDefects)reasons.push('Independent confirmation reported a new defect.');if(observations.reportedNewVariance)reasons.push('Independent confirmation reported new correctness-affecting variance.');return {determination:reasons.length?'UNDETERMINED':'SATISFIED',reasons:[...new Set(reasons)],observations};}"""
if old not in s: raise SystemExit('confirmationDetermination anchor missing')
s=s.replace(old,new,1)
# Remove direct agent determination authority in main Stage 19 switch; application helper below remains controlling.
old="""case 19:{requireAccepted();const iteration=latestIteration(project,[19]);const ev=evaluateIteration(project,recordId(iteration,'iterations'),'UNCHANGED_CONFIRMATION');if(!ev.complete)reasons.push(...ev.reasons);requireCount('confirmationRecords',1);if(collection('confirmationRecords').some(r=>upper(recordValue(r,'DETERMINATION'))!=='SATISFIED'))reasons.push('Unchanged confirmation is not affirmatively satisfied.');break;}"""
new="""case 19:{requireAccepted();const iteration=latestIteration(project,[19]);const ev=evaluateIteration(project,recordId(iteration,'iterations'),'UNCHANGED_CONFIRMATION');if(!ev.complete)reasons.push(...ev.reasons);requireCount('confirmationRecords',1);break;}"""
if old not in s: raise SystemExit('Stage 19 gate switch anchor missing')
s=s.replace(old,new,1)
# Replace hard-coded zero facts in Stage 19 derivation.
old="""NEW_REQUIREMENTS_DISCOVERED:0,INJECTED_DEFECTS_NOT_DETECTED:0,NEW_CORRECTNESS_AFFECTING_VARIANCE:ev.stability?.unexplainedVarianceCount||0,CONFIRMATION_ACCEPTANCE_CRITERIA_SATISFIED:determination.determination==='SATISFIED',REQUIRED_RETURN_STAGE:determination.determination==='SATISFIED'?'NONE':'STAGE 14'"""
new="""NEW_REQUIREMENTS_DISCOVERED:determination.observations?.reportedNewRequirements||0,INJECTED_DEFECTS_NOT_DETECTED:determination.observations?.reportedNewFailureCases||0,NEW_CORRECTNESS_AFFECTING_VARIANCE:Math.max(ev.stability?.unexplainedVarianceCount||0,determination.observations?.reportedNewVariance||0),CONFIRMATION_ACCEPTANCE_CRITERIA_SATISFIED:determination.determination==='SATISFIED',REQUIRED_RETURN_STAGE:determination.determination==='SATISFIED'?'NONE':determination.observations?.reportedNewRequirements?'STAGE 04':determination.observations?.reportedNewFailureCases?'STAGE 06':'STAGE 14'"""
if old not in s: raise SystemExit('Stage 19 hard-coded facts anchor missing')
s=s.replace(old,new,1)
p.write_text(s)

# Prompt must make the reviewer observations explicit but final determination application-owned.
p=Path('prompt-engine.js');s=p.read_text()
old='"19":"Perform only the named unchanged-confirmation operation on an unchanged converged candidate. Use the exact source converged iteration, frozen candidate, tests, regressions, current run/verification/comparison data, and operation-specific context supplied. CONFIRM_FREEZE must establish semantic zero-change through application-controlled identity and hashes; EXECUTE_RUN uses a new independent context and the unchanged package; VERIFY runs the complete applicable suite independently; COMPARE covers all ten confirmation runs; REGRESSION_VERIFY executes every applicable regression; CONFIRM determines whether any new requirement, missed failure, material defect, contradiction, or unexplained variance was observed. Do not perform another Stage 19 operation in this response. Never accept changed candidate bytes as unchanged and never reuse prior execution contexts.",'
new='"19":"Perform only the named unchanged-confirmation operation on an unchanged converged candidate. Use the exact source converged iteration, frozen candidate, tests, regressions, current run/verification/comparison data, and operation-specific context supplied. CONFIRM_FREEZE must establish semantic zero-change through application-controlled identity and hashes; EXECUTE_RUN uses a new independent context and the unchanged package; VERIFY runs the complete applicable suite independently; COMPARE covers all ten confirmation runs; REGRESSION_VERIFY executes every applicable regression. In CONFIRM, report every observed new requirement, missed or newly discovered failure case, material defect, contradiction, and correctness-affecting variance explicitly in the confirmation record; do not hide one behind a favorable DETE﻿RMINATION. Your DETE﻿RMINATION is an observation only: the application independently derives the actual confirmation state from current run, verification, regression, comparison, defect, context, candidate/hash, and reported-confirmation evidence. Do not perform another Stage 19 operation in this response. Never accept changed candidate bytes as unchanged and never reuse prior execution contexts.",'
# Remove accidental zero-width marker from replacement after assignment.
new=new.replace('DETE\ufeffRMINATION','DETERMINATION')
if old not in s: raise SystemExit('Stage 19 prompt anchor missing')
s=s.replace(old,new,1)
s=s.replace("const PROMPT_ENGINE_VERSION='closed-loop-prompt-engine/55';", "const PROMPT_ENGINE_VERSION='closed-loop-prompt-engine/56';",1)
p.write_text(s)
for name in ['index.html','app-core.js','test-runtime.js']:
    f=Path(name);f.write_text(f.read_text().replace('runtime-20260830-live-operator-65','runtime-20260830-live-operator-66'))
