from pathlib import Path
import re
p=Path('workflow-engine.js'); text=p.read_text()
pattern=r"function verifyArtifactIdentity\(project,audited,delivery\)\{.*?\}\n\nfunction refreshRecordHashes"
replacement="""function verifyArtifactIdentity(project,audited,delivery){
  ensureShape(project);const release=records(project,'releaseRecords').at(-1);if(upper(recordValue(release,'DETERMINATION'))!=='ACCEPTED')throw new Error('Artifact identity verification is prohibited until Stage 27 is ACCEPTED.');
  const a=safe(audited),d=safe(delivery),duplicate=(list,key)=>{const seen=new Set();for(const x of list){const v=String(x[key]??'');if(!v||seen.has(v))return true;seen.add(v);}return false;};if(duplicate(a,'artifactId')||duplicate(d,'artifactId')||duplicate(a,'name')||duplicate(d,'name'))throw new Error('Duplicate artifact identity or filename is prohibited.');if(a.length!==d.length)throw new Error('Audited and delivery artifact counts differ.');
  const normalized=list=>list.map(x=>({artifactId:String(x.artifactId||''),name:String(x.name||''),version:String(x.version||'UNKNOWN'),storageReference:String(x.storageReference||'INDEXEDDB'),size:Number(x.size),sha256:String(x.sha256||'')})).sort((x,y)=>x.artifactId.localeCompare(y.artifactId)||x.name.localeCompare(y.name));
  const identityEvidenceSha256=hash.sha256Value({releaseId:recordId(release,'releaseRecords'),audited:normalized(a),delivery:normalized(d)}),existing=records(project,'artifactIdentities').filter(r=>r.identityEvidenceSha256===identityEvidenceSha256);if(existing.length){project.release.authorization=existing.every(r=>r.AUTHORIZATION==='AUTHORIZED')?'AUTHORIZED':'NOT AUTHORIZED';project.release.authorizedArtifactIds=existing.map(r=>r.ARTIFACT_ID);recalculate(project);return existing;}
  const supersessionId=`ARTIFACT-IDENTITY-EVIDENCE-${identityEvidenceSha256}`;for(const prior of records(project,'artifactIdentities',{active:false}))if(isActiveRecord(prior)){prior.active=false;prior.validity='SUPERSEDED';prior.invalidatedBy=supersessionId;refreshRecordHashes(prior,'artifactIdentities');}
  const byId=new Map(d.map(x=>[String(x.artifactId),x])),created=[];for(const left of a){const right=byId.get(String(left.artifactId));if(!right)throw new Error('Missing delivery artifact '+left.artifactId+'.');const id=allocateId(project,'artifactIdentities');const fields={IDENTITY_ID:id,ARTIFACT_ID:left.artifactId,AUDITED_FILENAME:left.name,AUDITED_VERSION:left.version||'UNKNOWN',AUDITED_STORAGE_REFERENCE:left.storageReference||'INDEXEDDB',AUDITED_BYTE_SIZE:left.size,AUDITED_SHA256:left.sha256,RELEASE_FILENAME:right.name,RELEASE_VERSION:right.version||'UNKNOWN',RELEASE_STORAGE_REFERENCE:right.storageReference||'INDEXEDDB',RELEASE_BYTE_SIZE:right.size,PRE_DELIVERY_SHA256:right.sha256,EXACT_HASH_MATCH:Boolean(left.sha256&&right.sha256&&left.sha256===right.sha256),EXACT_SIZE_MATCH:Number(left.size)===Number(right.size),POST_AUDIT_MODIFICATION_EVIDENCE:left.sha256===right.sha256?'NONE':'MISMATCH',AUTHORIZATION:'NOT AUTHORIZED'};fields.AUTHORIZATION=fields.EXACT_HASH_MATCH&&fields.EXACT_SIZE_MATCH&&fields.AUDITED_FILENAME===fields.RELEASE_FILENAME?'AUTHORIZED':'NOT AUTHORIZED';const record={id,stage:28,createdAt:now(),active:true,fields,...fields,scope:currentScope(project),identityEvidenceSha256,source:'APPLICATION_DERIVATION',derivationKey:'stage28.artifactIdentity'};refreshRecordHashes(record,'artifactIdentities');project.projectData.artifactIdentities.push(record);created.push(record);}project.release.authorization=created.length&&created.every(r=>r.AUTHORIZATION==='AUTHORIZED')?'AUTHORIZED':'NOT AUTHORIZED';project.release.authorizedArtifactIds=created.map(r=>r.ARTIFACT_ID);addHistory(project,'ARTIFACT_IDENTITY_VERIFIED',{count:created.length,authorization:project.release.authorization,identityEvidenceSha256});recalculate(project);return created;
}

function refreshRecordHashes"""
text,count=re.subn(pattern,replacement,text,count=1,flags=re.S)
if count!=1: raise SystemExit('Stage 28 identity pattern mismatch')
p.write_text(text)
