from pathlib import Path

def read(p): return Path(p).read_text()
def write(p,s): Path(p).write_text(s)
def rep(s,a,b,label):
    if a not in s: raise SystemExit('missing anchor: '+label)
    return s.replace(a,b,1)

# workbook: durable manifest stores and agent-owned accounting fields.
p='workbook.js'; s=read(p)
s=rep(s,"'INPUT_SET_HASH_OR_MANIFEST','JOB_RECORD_STATUS','STATUS_EVIDENCE'],2:","'INPUT_SET_HASH_OR_MANIFEST','JOB_RECORD_STATUS','STATUS_EVIDENCE','INTAKE_ACCOUNTING'],2:",'stage1 field')
s=rep(s,"'BLOCKED_REQUIREMENTS','STAGE_DECISION','DECISION_EVIDENCE'],5:","'BLOCKED_REQUIREMENTS','STAGE_DECISION','DECISION_EVIDENCE','OBLIGATION_ACCOUNTING'],5:",'stage4 field')
s=rep(s,'"INPUT_SET_CONTENTS"\n    ],\n    "application": [','"INPUT_SET_CONTENTS",\n      "INTAKE_ACCOUNTING"\n    ],\n    "application": [','stage1 ownership')
s=rep(s,'"BLOCKED_REQUIREMENTS"\n    ],\n    "application": [','"BLOCKED_REQUIREMENTS",\n      "OBLIGATION_ACCOUNTING"\n    ],\n    "application": [','stage4 ownership')
s=rep(s,'generatedPrompts:[],generatedOutputs:[],outputReceipts:[],freshContexts:[],','generatedPrompts:[],generatedOutputs:[],outputReceipts:[],intakeCoverageManifests:[],obligationManifests:[],freshContexts:[],','manifest stores')
write(p,s)

# engine: application-owned durable manifests and closure evaluator.
p='workflow-engine.js'; s=read(p)
s=rep(s,"'humanInputRequests','humanInputAnswers','stageConfirmations','artifactVersions','generatedPrompts','generatedOutputs','outputReceipts',","'humanInputRequests','humanInputAnswers','stageConfirmations','artifactVersions','generatedPrompts','generatedOutputs','outputReceipts','intakeCoverageManifests','obligationManifests',",'infra stores')
marker="function recordStageConfirmation(project,stage,confirmed,statement,operatorLabel='HUMAN_OPERATOR',options={}){"
if marker not in s: raise SystemExit('engine insertion marker missing')
helpers=r'''function coverageUnits(value){if(value===null||value===undefined)return [];if(Array.isArray(value))return value.flatMap(coverageUnits);if(typeof value==='object')return Object.entries(value).flatMap(([key,item])=>coverageUnits(item).map(text=>`${key}: ${text}`));const text=String(value).trim();if(!text)return [];const paragraphs=text.split(/\r?\n+/).map(x=>x.trim()).filter(Boolean);return paragraphs.length?paragraphs:[text];}
function buildIntakeCoverageManifest(project){ensureShape(project);const inputVersion=String(project.job.CURRENT_INPUT_VERSION||'UNKNOWN'),latest=safe(project.projectData.inputVersions).filter(x=>String(x.version||'')===inputVersion).at(-1),payload=latest?.payload||Object.fromEntries(schema.HUMAN_INTAKE_FIELDS.map(name=>[name,project.job[name]??''])),units=[];for(const name of schema.HUMAN_INTAKE_FIELDS)coverageUnits(payload?.[name]).forEach((text,index)=>{units.push({unitId:`INPUT-UNIT-${hash.sha256Value({inputVersion,name,index,text}).slice(0,20)}`,inputVersion,sourceKind:'HUMAN_FIELD',sourceLocation:`JOB.${name}[${index}]`,sourceField:name,rawValueSha256:hash.sha256Value(text),text});});for(const [index,item] of safe(payload?.clarifications).entries()){const text=typeof item==='string'?item:JSON.stringify(item);if(text.trim())units.push({unitId:`INPUT-UNIT-${hash.sha256Value({inputVersion,clarification:index,text}).slice(0,20)}`,inputVersion,sourceKind:'HUMAN_CLARIFICATION',sourceLocation:`clarifications[${index}]`,sourceField:'CLARIFICATION',rawValueSha256:hash.sha256Value(text),text});}for(const [index,file] of safe(project.stages?.[1]?.authorizedFiles).entries()){const artifactId=String(file?.artifactId||file?.id||''),filename=String(file?.name||file?.filename||'');if(!artifactId&&!filename)continue;const stable={artifactId,filename,sha256:String(file?.sha256||''),size:Number(file?.size||0)};units.push({unitId:`INPUT-UNIT-${hash.sha256Value({inputVersion,file:stable,index}).slice(0,20)}`,inputVersion,sourceKind:'SUPPLIED_MATERIAL',sourceLocation:`STAGE1.authorizedFiles[${index}]`,sourceField:'SUPPLIED_MATERIAL',rawValueSha256:hash.sha256Value(stable),artifactId,filename,text:`Supplied material ${filename||artifactId}`});}const manifestSha256=hash.sha256Value({inputVersion,units:units.map(({text,...x})=>({...x,textSha256:hash.sha256Value(text)}))}),prior=safe(project.projectData.intakeCoverageManifests).find(x=>x.manifestSha256===manifestSha256);if(prior)return prior;const manifest={manifestId:allocateInfrastructureId(project,'INTAKE-MANIFEST','intakeCoverageManifests'),inputVersion,manifestSha256,units,createdAt:now(),source:'APPLICATION'};project.projectData.intakeCoverageManifests.push(manifest);return manifest;}
function buildObligationManifest(project){ensureShape(project);const scope=currentScope(project),items=[],add=(origin,originId,location,value,extra={})=>{for(const [index,text] of coverageUnits(value).entries()){items.push({obligationId:`OBLIGATION-${hash.sha256Value({scope,origin,originId,location,index,text}).slice(0,20)}`,origin,originId:String(originId||''),sourceLocation:`${location}[${index}]`,rawValueSha256:hash.sha256Value(text),text,...extra});}};for(const record of recordsForCurrentScope(project,'intentStatements')){const sid=recordId(record,'intentStatements'),relevance=upper(recordValue(record,'REQUIREMENT_RELEVANCE'));add('HUMAN_INTENT_STATEMENT',sid,`intentStatements.${sid}`,recordValue(record,'EXACT_STATEMENT'),{statementId:sid,requirementRelevance:relevance});}for(const name of ['EXACT_DELIVERABLE_REQUESTED','INPUT_SET_CONTENTS'])add('STAGE_01_JOB_DEFINITION','STAGE-01',`stage01.${name}`,project.stages?.[1]?.agentData?.[name]??project.job?.[name]);for(const record of recordsForCurrentScope(project,'candidateRequirements')){const id=recordId(record,'candidateRequirements');add('STAGE_03_CANDIDATE_OBLIGATION',id,String(recordValue(record,'SOURCE_LOCATION')||`candidateRequirements.${id}`),recordValue(record,'CANDIDATE_OBLIGATION'),{sourceId:String(recordValue(record,'SOURCE_ID')||record.relationships?.SOURCE_ID||'')});}for(const record of recordsForCurrentScope(project,'research')){const id=recordId(record,'research');for(const key of ['MANDATORY_STATEMENTS','RECOMMENDATIONS','OPTIONAL_PRACTICES','PROHIBITIONS','EXCEPTIONS','DEPENDENCIES','APPLICABILITY_FACTS','RESTRICTIONS','INVALIDATING_MATERIAL'])add('STAGE_03_RESEARCH',id,`research.${id}.${key}`,recordValue(record,key),{sourceId:String(recordValue(record,'SOURCE_ID')||record.relationships?.SOURCE_ID||''),researchField:key});}const unique=[...new Map(items.map(x=>[x.obligationId,x])).values()],manifestSha256=hash.sha256Value({scope,items:unique.map(({text,...x})=>({...x,textSha256:hash.sha256Value(text)}))}),prior=safe(project.projectData.obligationManifests).find(x=>x.manifestSha256===manifestSha256);if(prior)return prior;const manifest={manifestId:allocateInfrastructureId(project,'OBLIGATION-MANIFEST','obligationManifests'),inputVersion:scope.inputVersion,sourceSetVersion:scope.sourceSetVersion,requirementsVersion:scope.requirementsVersion,manifestSha256,items:unique,createdAt:now(),source:'APPLICATION'};project.projectData.obligationManifests.push(manifest);return manifest;}
function parseAccountingRows(value){if(Array.isArray(value))return value;if(typeof value==='string'){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed:[];}catch{return [];}}return [];}
function validateAccountingClosure(project,stage,stageData){const n=Number(stage),isIntake=n===1;if(!isIntake&&n!==4)return {valid:true,coverage:1,missing:[],unknown:[],duplicates:[]};const manifest=isIntake?buildIntakeCoverageManifest(project):buildObligationManifest(project),expected=new Set((isIntake?manifest.units:manifest.items).map(x=>isIntake?x.unitId:x.obligationId)),field=isIntake?'INTAKE_ACCOUNTING':'OBLIGATION_ACCOUNTING',rows=parseAccountingRows(stageData?.[field]),seen=new Set(),unknown=[],duplicates=[];for(const row of rows){const id=String(row?.id||row?.unitId||row?.obligationId||'').trim();if(!id||!expected.has(id)){if(id)unknown.push(id);continue;}if(seen.has(id))duplicates.push(id);seen.add(id);}const missing=[...expected].filter(id=>!seen.has(id));return {valid:missing.length===0&&unknown.length===0&&duplicates.length===0,coverage:expected.size?seen.size/expected.size:1,missing,unknown,duplicates,manifestId:manifest.manifestId,manifestSha256:manifest.manifestSha256,rows};}

'''
s=s.replace(marker,helpers+marker,1)
s=rep(s,'recordHumanInputVersion,recordStageConfirmation,','recordHumanInputVersion,buildIntakeCoverageManifest,buildObligationManifest,validateAccountingClosure,recordStageConfirmation,','engine exports')
write(p,s)

# ingestion: reject schema-valid but incomplete accounting before proposal/canonical mutation.
p='response-ingestion.js'; s=read(p)
marker='  const canonicalEnvelopeSha256=hash.canonicalEnvelopeSha256(envelope);'
if marker not in s: raise SystemExit('ingestion marker missing')
insert="""  if(envelope.responseType==='DATA_PROPOSAL'&&(stageNumber===1||stageNumber===4)){const accounting=workflow.validateAccountingClosure(project,stageNumber,envelope.stageData||{}),field=stageNumber===1?'INTAKE_ACCOUNTING':'OBLIGATION_ACCOUNTING';for(const id of accounting.missing)issues.push(issue(stageNumber===1?'INCOMPLETE_INTAKE_ACCOUNTING':'INCOMPLETE_OBLIGATION_ACCOUNTING',`/stageData/${field}`,`Missing application-enumerated identity ${id}.`));for(const id of accounting.unknown)issues.push(issue('UNKNOWN_ACCOUNTING_ID',`/stageData/${field}`,`Unknown accounting identity ${id}.`));for(const id of accounting.duplicates)issues.push(issue('DUPLICATE_ACCOUNTING_ID',`/stageData/${field}`,`Duplicate accounting identity ${id}.`));}\n\n"""+marker
s=s.replace(marker,insert,1)
write(p,s)

# prompt: remove all subject branches, publish application manifests and exact disposition rules.
p='prompt-engine.js'; s=read(p)
start=s.find("${stage===1?`STAGE 01 DOMAIN INTAKE ADAPTATION")
end=s.find("${stage===1?`STAGE 01 CLARIFICATION EXPERIENCE",start)
if start<0 or end<0: raise SystemExit('domain block anchors missing')
generic="""${stage===1?`STAGE 01 SUBJECT-NEUTRAL INTAKE ALGORITHM\nDerive project-specific human-authority questions from the actual request, accessible supplied materials, and current canonical context. Do not select behavior from a hard-coded subject catalogue. Identify every fact, requirement, constraint, decision, prohibition, requested output, acceptance condition, material reference, and genuinely human-only unresolved issue relevant to defining the requested outcome. Do not perform later-stage research, requirement compilation, test design, production, filing, simulation, manufacturing, or product verification.\n`:`SUBJECT-NEUTRAL EXECUTION RULE\nApply domain knowledge only through the actual current project, accepted requirements, governing sources, declared capabilities, and current stage task. Do not select behavior from hard-coded subject labels.\n`}\n\n"""
s=s[:start]+generic+s[end:]
# Remove patent-specific Stage1 fixture text from runtime prompt while leaving generic classification logic.
pat='For PATENT / REGULATED FILING jobs, when not already known from human input or supplied materials, ASK_NOW_NONBLOCKING includes:'
idx=s.find(pat)
if idx>=0:
    stop=s.find('Before Stage 01 submission verify:',idx)
    if stop<0: raise SystemExit('patent fixture stop missing')
    s=s[:idx]+s[stop:]
anchor='AUTHORIZED BOUNDED CONTEXT FOR THIS STAGE\n${contextFor(stage,state,operation,scope)}'
if anchor not in s: raise SystemExit('prompt context anchor missing')
manifest="""${stage===1?`APPLICATION-ENUMERATED INTAKE COVERAGE MANIFEST\n${JSON.stringify(workflow.buildIntakeCoverageManifest(state),null,2)}\nFor a final DATA_PROPOSAL, INTAKE_ACCOUNTING must be a JSON array encoded as the INTAKE_ACCOUNTING stageData string. Include exactly one entry for every unitId above. Each entry must contain id and disposition. Allowed dispositions: INCORPORATED, RETAINED_CONTEXT, UNRESOLVED_HUMAN_ONLY, LATER_RESOLVABLE, INAPPLICABLE. INAPPLICABLE must include a reason. This accounting does not replace the required atomic intentStatements extraction from accessible supplied-material content. No enumerated input unit may be omitted.\n\n`:''}${stage===4?`APPLICATION-ENUMERATED STAGE 04 OBLIGATION MANIFEST\n${JSON.stringify(workflow.buildObligationManifest(state),null,2)}\nThis is the application-selected Stage 04 input universe. Do not rediscover it and do not ask the human for anything already represented here. For a final DATA_PROPOSAL, OBLIGATION_ACCOUNTING must be a JSON array encoded as the OBLIGATION_ACCOUNTING stageData string. Include exactly one entry for every obligationId. Each entry must contain id and disposition. Allowed dispositions: REQUIREMENT, RETAINED_NONNORMATIVE_CONTEXT, INAPPLICABLE, BLOCKED. REQUIREMENT entries must name one or more proposed requirement tempKeys. INAPPLICABLE and BLOCKED require a reason. No obligation may disappear.\n\n`:''}"""+anchor
s=s.replace(anchor,manifest,1)
write(p,s)

# permanent regression covers subject neutrality and machine accounting.
Path('verify-closed-accounting.mjs').write_text(r'''import fs from 'node:fs';
const p=fs.readFileSync('prompt-engine.js','utf8'),e=fs.readFileSync('workflow-engine.js','utf8'),i=fs.readFileSync('response-ingestion.js','utf8'),w=fs.readFileSync('workbook.js','utf8');
const must=(x,m)=>{if(!x)throw new Error(m)};
for(const token of ['PATENT / REGULATED FILING','SOFTWARE / MULTI-FILE SYSTEM','BUILDING / ARCHITECTURE / AEC','PHYSICAL / MECHANICAL / CAD / CAM / CNC / ADDITIVE'])must(!p.includes(token),'hard-coded subject branch remains: '+token);
for(const token of ['buildIntakeCoverageManifest','buildObligationManifest','validateAccountingClosure'])must(e.includes(token),'missing application accounting helper '+token);
must(i.includes('INCOMPLETE_INTAKE_ACCOUNTING'),'Stage 01 omission rejection missing');must(i.includes('INCOMPLETE_OBLIGATION_ACCOUNTING'),'Stage 04 omission rejection missing');must(p.includes('APPLICATION-ENUMERATED INTAKE COVERAGE MANIFEST'),'Stage 01 manifest not published');must(p.includes('APPLICATION-ENUMERATED STAGE 04 OBLIGATION MANIFEST'),'Stage 04 manifest not published');must(w.includes('INTAKE_ACCOUNTING')&&w.includes('OBLIGATION_ACCOUNTING'),'accounting fields absent');console.log('verify-closed-accounting: PASS');
''')
print('patch_closed_accounting: complete')
