from pathlib import Path
root=Path('.')

def replace_once(text, old, new, label):
    count=text.count(old)
    if count!=1:
        raise SystemExit(f'{label}: expected one occurrence, found {count}')
    return text.replace(old,new,1)

for name in ['index.html','app-core.js','test-runtime.js']:
    p=root/name
    t=p.read_text()
    for old in ['runtime-20260830-live-operator-55','runtime-20260830-live-operator-56','runtime-20260830-live-operator-57']:
        t=t.replace(old,'runtime-20260830-live-operator-58')
    p.write_text(t)

p=root/'prompt-engine.js'
s=p.read_text()
s=replace_once(s,"const PROMPT_ENGINE_VERSION='closed-loop-prompt-engine/51';","const PROMPT_ENGINE_VERSION='closed-loop-prompt-engine/52';",'prompt version')
anchor="function parseCapturedInputSet(stageOne){return workflow.parseCapturedInputSet(stageOne);}\n"
projection="""function stage01CaptureProjection(state){const capture=parseCapturedInputSet(state),units=safe(capture?.units).map(unit=>({sourceUnitId:unit?.sourceUnitId||null,sourceRawValueSha256:unit?.sourceRawValueSha256||null,disposition:unit?.disposition||null,reason:unit?.reason||null,extractedStatements:safe(unit?.extractedStatements).map(statement=>({statementKey:statement?.statementKey||null,text:statement?.text??null,statementClass:statement?.statementClass||null}))}));return {format:capture?.format||'EMPTY',schema:capture?.schema||null,inputVersion:capture?.inputVersion||state?.job?.CURRENT_INPUT_VERSION||null,manifestSha256:capture?.manifestSha256||null,units,unitCount:units.length,projectionRule:'Complete accepted Stage 01 semantic accounting. Serialized INPUT_SET_CONTENTS, capture.raw, originalUserJobInput, and duplicate top-level humanAuthority copies are intentionally excluded because their authoritative current values are supplied separately and every accepted semantic statement remains here by source identity and hash.'};}\nfunction stage01DefinitionProjection(state){const stageOne=state?.stages?.[1]||{},agent=stageOne.agentData||stageOne.acceptedData||{};return {agentData:{EXACT_DELIVERABLE_REQUESTED:agent.EXACT_DELIVERABLE_REQUESTED??state?.job?.EXACT_DELIVERABLE_REQUESTED??null,ASSUMPTIONS:agent.ASSUMPTIONS??state?.job?.ASSUMPTIONS??null,UNKNOWN_INFORMATION:agent.UNKNOWN_INFORMATION??state?.job?.UNKNOWN_INFORMATION??null},humanData:stageOne.humanData||{},derivedData:workflow.deriveStageData(state,1)};}\n"""
s=replace_once(s,anchor,anchor+projection,'stage 1 canonical prompt projection')
s=replace_once(s,"  const humanAuthority=Object.fromEntries(humanFieldNames.filter(name=>isolatedReviewer?reviewerHumanFields.has(name):(Number(stage)<=3?false:carryForwardHumanFields.has(name))).map(name=>[name,job?.[name]??null]));","  const humanAuthority=Object.fromEntries(humanFieldNames.filter(name=>isolatedReviewer?reviewerHumanFields.has(name):(Number(stage)<=3?true:carryForwardHumanFields.has(name))).map(name=>[name,job?.[name]??null]));",'human authority projection')
s=replace_once(s,"  const acceptedStage01=isolatedReviewer?{objectiveVerbatim:job.EXACT_USER_OBJECTIVE_VERBATIM??null,detailWithheld:true,withheldReason:'Independent verification receives only the current operation-authorized projection. The complete Stage 01 intake remains canonical and reusable but is not embedded when it is unnecessary to the proposition under review.'}:fullStage01?{capture:parseCapturedInputSet(state),agentData:stageOne.agentData||stageOne.acceptedData||{},humanData:stageOne.humanData||{},derivedData:workflow.deriveStageData(state,1)}:{objective:job.EXACT_DELIVERABLE_REQUESTED||job.EXACT_USER_OBJECTIVE_VERBATIM||null,inputVersion:job.CURRENT_INPUT_VERSION||null,capturePreservedCanonically:true,acceptedChangeIds:safe(stageOne.acceptedDataChangeIds)};","  const acceptedStage01=isolatedReviewer?{objectiveVerbatim:job.EXACT_USER_OBJECTIVE_VERBATIM??null,detailWithheld:true,withheldReason:'Independent verification receives only the current operation-authorized projection. The complete Stage 01 intake remains canonical and reusable but is not embedded when it is unnecessary to the proposition under review.'}:fullStage01?{capture:stage01CaptureProjection(state),definition:stage01DefinitionProjection(state)}:{objective:job.EXACT_DELIVERABLE_REQUESTED||job.EXACT_USER_OBJECTIVE_VERBATIM||null,inputVersion:job.CURRENT_INPUT_VERSION||null,capturePreservedCanonically:true,acceptedChangeIds:safe(stageOne.acceptedDataChangeIds)};",'accepted Stage 1 projection')
start=s.index('function stage4ExhaustedInputs(state)')
end=s.index('\nconst PROMPT_CONTEXT_ADDITIONS',start)
new_func="""function stage4ExhaustedInputs(state){const active=list=>safe(list).filter(r=>r?.active!==false&&!r?.invalidatedBy).map(r=>({id:r?.id||r?.recordId||null,stage:r?.stage??null,scope:r?.scope||{},fields:recordFields(r),relationships:r?.relationships||{},evidenceRefs:r?.evidenceRefs||[]})),humanJobInput=Object.fromEntries(Object.entries(schema.JOB_FIELDS||{}).filter(([,definition])=>['HUMAN','HUMAN_DECISION'].includes(definition?.producer)).map(([name])=>[name,state?.job?.[name]??null])),stageThree=state?.stages?.[3]||{},stageThreeAgent=stageThree.agentData||stageThree.acceptedData||{};return {currentUserJobInput:humanJobInput,stage01AcceptedCapture:stage01CaptureProjection(state),stage01AcceptedDefinition:stage01DefinitionProjection(state),stage03AcceptedData:{agentData:Object.fromEntries(['EXCEPTIONS_AND_EDGE_CONDITIONS','CONFLICTING_OR_INVALIDATING_MATERIAL','RESEARCH_GAPS_AND_BLOCKERS','ALL_KNOWN_CONTROLLING_SOURCES_EXAMINED','SECOND_CONFLICT_AND_EXCEPTION_PASS_COMPLETED','LATEST_PASS_NUMBER','NEW_MATERIAL_CATEGORY_FOUND_IN_LATEST_PASS'].filter(key=>Object.prototype.hasOwnProperty.call(stageThreeAgent,key)).map(key=>[key,stageThreeAgent[key]])),humanData:stageThree.humanData||{},derivedData:workflow.deriveStageData(state,3)},stage03Research:active(state?.projectData?.research),stage03CandidateRequirements:active(state?.projectData?.candidateRequirements),applicableSources:active(state?.projectData?.sources),applicableEvidence:active(state?.projectData?.evidenceRecords).filter(record=>[2,3].includes(Number(record.stage))),projectionRule:'This is the complete Stage 04 input union. Duplicate serialized copies are omitted; no human-authority statement, accepted Stage 01 semantic statement, Stage 03 source finding, candidate obligation, applicable source identity, or applicable evidence record is omitted.'};}"""
s=s[:start]+new_func+s[end:]
s=replace_once(s,"if(stage>1&&![11,12,23,24].includes(stage))","if(stage>2&&stage!==4&&![11,12,23,24].includes(stage))",'prior-stage duplication rule')
s=replace_once(s,"if(stage===4)parts.push(`APPLICATION OBLIGATION MANIFEST — ACCOUNT FOR EVERY OBLIGATION\\n${show(obligationManifest(state))}`);const humanInspectionEvidence=","if(stage===4)parts.push(`APPLICATION OBLIGATION MANIFEST — ACCOUNT FOR EVERY OBLIGATION\\n${show(obligationManifest(state))}`);if(stage===18)parts.push(`APPLICATION-DERIVED CONVERGENCE METRICS — AUTHORITATIVE\\n${show(workflow.convergenceMetrics(state))}`);if(stage===19&&operation==='CONFIRM'&&scope?.iterationId)parts.push(`APPLICATION-DERIVED UNCHANGED-CONFIRMATION ITERATION EVALUATION — AUTHORITATIVE\\n${show(workflow.evaluateIteration(state,scope.iterationId,'UNCHANGED_CONFIRMATION'))}`);if([18,19,26,29].includes(stage)){const contradictions=workflow.detectCurrentContradictions(state);if(contradictions.length)parts.push(`APPLICATION-DERIVED CURRENT CONTRADICTIONS — DO NOT OVERRIDE\\n${show(contradictions)}`);}const humanInspectionEvidence=",'derived prompt facts')
p.write_text(s)

p=root/'workflow-engine.js'
s=p.read_text()
s=replace_once(s,"if(unexplained.length)reasons.push('Unexplained correctness-affecting variance remains.');\n  const stability=executionStability(project,iterationId);","if(unexplained.length)reasons.push('Unexplained correctness-affecting variance remains.');const currentContradictions=detectCurrentContradictions(project).filter(item=>item.severity==='RELEASE_MATERIAL');if(mode==='UNCHANGED_CONFIRMATION'&&currentContradictions.length)reasons.push('Current release-material contradictions remain during unchanged confirmation: '+currentContradictions.map(item=>item.type+':'+item.key).join(', ')+'.');\n  const stability=executionStability(project,iterationId);",'unchanged confirmation contradiction rule')
s=replace_once(s,"case 27:{requireAccepted();const r=recordsForCurrentScope(project,'releaseRecords').at(-1);if(!r)reasons.push('The application has not recorded a current release determination.');else if(!['ACCEPTED','REJECTED','BLOCKED'].includes(upper(recordValue(r,'DETERMINATION'))))reasons.push('Current release determination is invalid.');break;}","case 27:{const r=recordsForCurrentScope(project,'releaseRecords').at(-1);if(!r)reasons.push('The application has not recorded a current release determination.');else{const determination=upper(recordValue(r,'DETERMINATION'));if(!['ACCEPTED','REJECTED','BLOCKED'].includes(determination))reasons.push('Current release determination is invalid.');else if(determination==='REJECTED')reasons.push('Release is rejected by current affirmative nonconformance; correct the evidenced root cause before Stage 28.');else if(determination==='BLOCKED')reasons.push('Release is blocked by incomplete, insufficient, stale, or contradictory current evidence; resolve the blocker before Stage 28.');}break;}",'Stage 27 gate')
s=replace_once(s,"const blocked=questions.length>0||blockers.length>0||executionFailures.length>0;","const releaseDetermination=stage===27?upper(recordValue(recordsForCurrentScope(project,'releaseRecords').at(-1),'DETERMINATION')):'';const blocked=questions.length>0||blockers.length>0||executionFailures.length>0||releaseDetermination==='BLOCKED';",'Stage 27 blocked state')
s=replace_once(s,"if(stage===27&&acceptedChanges(project,27).length&&!recordsForCurrentScope(project,'releaseRecords').length)return actionEnvelope(project,stage,{actionType:'CALCULATE_RELEASE',heading:'Calculate the release determination',explanation:'The advisory Stage 27 review is accepted. No agent or human may select the release state. The application must now evaluate the complete current release evidence, blockers, violations, unknowns, contradictions, baseline identity, product identity, and evidence sufficiency and record exactly one idempotent ACCEPTED, REJECTED, or BLOCKED determination.',primaryButton:'Calculate release'});","if(stage===27){const release=recordsForCurrentScope(project,'releaseRecords').at(-1),determination=upper(recordValue(release,'DETERMINATION'));if(!release)return actionEnvelope(project,stage,{actionType:'CALCULATE_RELEASE',heading:'Calculate the release determination',explanation:'No external advisory response is required. The application evaluates the complete current release evidence, blockers, violations, unknowns, contradictions, baseline identity, product identity, and evidence sufficiency and records exactly one idempotent ACCEPTED, REJECTED, or BLOCKED determination.',primaryButton:'Calculate release'});if(determination==='REJECTED')return actionEnvelope(project,stage,{actionType:'BLOCKED',heading:'Release rejected — correct the evidenced root cause',explanation:'Current evidence establishes mandatory nonconformance. Stage 28 is prohibited. Preserve the rejection evidence and return through root-cause analysis and controlled correction before recalculating release.',blockingReason:'Release is REJECTED by current affirmative nonconformance.'});if(determination==='BLOCKED')return actionEnvelope(project,stage,{actionType:'BLOCKED',heading:'Release blocked — resolve current evidence blockers',explanation:'Current evidence is incomplete, insufficient, stale, or contradictory. Stage 28 is prohibited until the exact blocking evidence condition is resolved and release is recalculated.',blockingReason:'Release is BLOCKED by current evidence.'});}",'application-owned Stage 27 action')
p.write_text(s)
