from pathlib import Path
import hashlib,re

def one(path,old,new):
    p=Path(path);s=p.read_text();n=s.count(old)
    if n!=1: raise SystemExit(f'{path}: expected one anchor, found {n}: {old[:120]!r}')
    p.write_text(s.replace(old,new,1))

# Prompt semantics: strict JSON remains the only response channel, but insufficient human input must produce a complete useful question set rather than an empty/template envelope.
p=Path('prompt-engine.js');s=p.read_text()
old="1:'Initialize only this current job from this current job’s exact user input. Preserve the verbatim objective, requested deliverable, supplied-material inventory and provenance, inspection state, format requirements, temporal and geographic scope, user-supplied authority, tools, prohibitions, explicit user requirements, assumptions, unresolved unknowns, and any human decisions genuinely required to define the work. Determine whether the requested deliverable is feasible in the authorized execution environment and identify the smallest missing human-only information needed to proceed reliably. If direct implementation or fabrication is unavailable or materially too large but a complete reliable self-contained substitute such as an implementation-ready, design-ready, manufacturing-ready, research, architecture, or other specification deliverable can satisfy the underlying objective, propose that feasible substitute as EXACT_DELIVERABLE_REQUESTED for human intent confirmation and state the execution limitation explicitly. The application already owns JOB_ID and controlled input identity; do not assign or invent them. Do not create or prescribe a reusable master job or prompt for unrelated jobs. Do not begin substantive external-source research or downstream production work.',"
new="1:'Initialize only this current job from this current job’s exact user input. Preserve the verbatim objective, requested deliverable, supplied-material inventory and provenance, inspection state, format requirements, temporal and geographic scope, user-supplied authority, tools, prohibitions, explicit user requirements, assumptions, unresolved unknowns, and any human decisions genuinely required to define the work. First determine whether the supplied human-authority information is sufficient to define the current job reliably. If human-only information is required, return HUMAN_INPUT_REQUIRED with the smallest complete set of all currently knowable blocking clarification questions needed to continue; ask concrete questions the human can answer, explain why each answer is required, choose the exact answerType and allowedValues where applicable, identify affected fields/records, set blocking=true, and ask together everything that can already be known together. Do not return an empty DATA_PROPOSAL, the unchanged response skeleton, placeholders, or UNKNOWN values for facts or decisions only the human can supply. A later clarification round is justified only when a human answer reveals a genuinely new dependency, and already answered clarification must not be asked again. If the current human input is sufficient, return the complete Stage 01 DATA_PROPOSAL and do not ask optional or merely nice-to-have questions. Determine whether the requested deliverable is feasible in the authorized execution environment and identify the smallest missing human-only information needed to proceed reliably. If direct implementation or fabrication is unavailable or materially too large but a complete reliable self-contained substitute such as an implementation-ready, design-ready, manufacturing-ready, research, architecture, or other specification deliverable can satisfy the underlying objective, propose that feasible substitute as EXACT_DELIVERABLE_REQUESTED for human intent confirmation and state the execution limitation explicitly. The application already owns JOB_ID and controlled input identity; do not assign or invent them. Do not create or prescribe a reusable master job or prompt for unrelated jobs. Do not begin substantive external-source research or downstream production work.',"
if s.count(old)!=1: raise SystemExit('prompt Stage 1 anchor mismatch')
s=s.replace(old,new,1)
oldrule='- Never set a HUMAN or HUMAN_DECISION-owned field. When unavailable human information is required, return HUMAN_INPUT_REQUIRED and structured humanInputRequests. Do not convert a missing human fact, choice, legal assertion, engineering parameter, or authority decision into an assumption.'
newrule=oldrule+'\n- HUMAN_INPUT_REQUIRED is a complete clarification disposition, not an empty template. Include at least one blocking human-authority question and include the smallest complete set of all currently knowable blocking questions required to continue. Every question must contain concrete question, whyRequired, answerType, allowedValues when applicable, affected targets, and blocking=true. Ask together what can be known together; do not repeat answered questions. Never return the empty response skeleton unchanged as the answer.'
if s.count(oldrule)!=1: raise SystemExit('prompt human-input rule anchor mismatch')
s=s.replace(oldrule,newrule,1)
p.write_text(s)

# Fail closed on a nominal HUMAN_INPUT_REQUIRED response that contains no actually blocking question.
one('response-ingestion.js',
"    if(!safe(envelope.humanInputRequests).length)issues.push(issue('MISSING_HUMAN_INPUT_REQUESTS','/humanInputRequests','HUMAN_INPUT_REQUIRED must include at least one question.'));",
"    if(!safe(envelope.humanInputRequests).length)issues.push(issue('MISSING_HUMAN_INPUT_REQUESTS','/humanInputRequests','HUMAN_INPUT_REQUIRED must include at least one question.'));\n    else if(!safe(envelope.humanInputRequests).some(request=>request.blocking!==false))issues.push(issue('MISSING_BLOCKING_HUMAN_INPUT_REQUEST','/humanInputRequests','HUMAN_INPUT_REQUIRED must include at least one blocking human-authority question.'));")

# Minimal operator-language refinement. The app remains the place where human answers are entered/versioned.
one('app-core.js','<div class="operator-step"><b>2</b><span>Paste full response</span></div>','<div class="operator-step"><b>2</b><span>Paste response / questions</span></div>')
one('app-core.js',
"<div class=\"panel\"><h2 class=\"section-title\">Returned agent response</h2><p class=\"section-intro\">Paste the complete strict JSON response. Parse / validate preserves the raw response first, then validates it without changing canonical project records. If the response declares returned files, attach those exact files in Authorized files for this stage before parsing.</p><textarea class=\"code-text stage-output\" id=\"stage-output\"",
"<div class=\"panel\"><h2 class=\"section-title\">Returned agent response</h2><p class=\"section-intro\">${n===1?'Paste the agent’s complete strict JSON response. If more human information is required, HUMAN_INPUT_REQUIRED is the correct response: after parsing, the application turns those questions into normal typed inputs, versions your answers, and regenerates Stage 01. Do not answer questions by editing the JSON. ':'Paste the complete strict JSON response. '}Parse / validate preserves the raw response first, then validates it without changing canonical project records. If the response declares returned files, attach those exact files in Authorized files for this stage before parsing.</p><textarea class=\"code-text stage-output\" id=\"stage-output\"")

# First-class semantic contradiction proof for the Stage 01 clarification experience.
one('verify-prompt-semantics.mjs',
"  if(record.stage===6){",
"  if(record.stage===1){\n    if(!record.prompt.includes('smallest complete set of all currently knowable blocking clarification questions')||!record.prompt.includes('Do not return an empty DATA_PROPOSAL')||!record.prompt.includes('already answered clarification must not be asked again')||!record.prompt.includes('Never return the empty response skeleton unchanged as the answer'))issues.push('STAGE01_CLARIFICATION_EXPERIENCE_MISSING');\n  }\n  if(record.stage===6){")
one('verify-prompt-semantics.mjs',
"  {...original,prompt:original.prompt.replace('PATENT / REGULATED FILING','GENERAL DOCUMENT')},",
"  {...original,prompt:original.prompt.replace('PATENT / REGULATED FILING','GENERAL DOCUMENT')},\n  {...prompts.buildPromptRecord(1,baseProject(),{operation:'COMPLETE'}),prompt:prompts.buildPromptRecord(1,baseProject(),{operation:'COMPLETE'}).prompt.replace('smallest complete set of all currently knowable blocking clarification questions','some questions')},")

# Ingestion negative: a clarification disposition cannot hide behind only nonblocking questions.
marker='// Clarification loop: structured question -> accepted question record -> human answer -> INPUT version increments.'
p=Path('verify-ingestion.mjs');s=p.read_text()
if s.count(marker)!=1: raise SystemExit('verify-ingestion clarification marker mismatch')
case="""// HUMAN_INPUT_REQUIRED must contain real blocking human-authority work, not a nominal/empty clarification shell.\n{\n  const p=project('JOB-NONBLOCKING-CLARIFICATION'),stage=1,promptRecord=savePrompt(p,stage);\n  const envelope={schema:schema.RESPONSE_SCHEMA,jobId:p.job.JOB_ID,stage,operation:promptRecord.operation,promptIdentity:{instructionId:promptRecord.instructionId,bodySha256:promptRecord.bodySha256,contractSha256:promptRecord.contractSha256,contextSignature:promptRecord.contextSignature},scope:promptRecord.scope,responseType:'HUMAN_INPUT_REQUIRED',humanInputRequests:[{temporaryKey:'question-optional',question:'Optional preference?',whyRequired:'This preference is not required to continue.',affectedStageFields:[],affectedRecords:[],answerType:'TEXT',allowedValues:[],blocking:false}],stageData:{},records:{},evidence:[],unresolved:[],warnings:[],attachments:[]};\n  const prepared=ingestion.prepare(p,{stage,text:JSON.stringify(envelope),promptRecord});\n  if(prepared.validation.valid||!prepared.validation.issues.some(i=>i.code==='MISSING_BLOCKING_HUMAN_INPUT_REQUEST'))throw new Error('HUMAN_INPUT_REQUIRED without a blocking human question was accepted.');\n  if(prepared.project.projectData.acceptedChanges.length)throw new Error('Nominal clarification mutated canonical state.');\n  negativeCount++;\n}\n\n"""
s=s.replace(marker,case+marker,1);p.write_text(s)

# Browser proof: the human sees an intelligible typed clarification form after pasting the strict JSON, then answers there rather than editing JSON.
p=Path('verify-browser.mjs');s=p.read_text()
old=""" assert(newest.job.JOB_ID!==userJob&&newest.job.JOB_ID!=='JOB-20260823144121','New JOB_ID was not unique.');assert(newest.job.CURRENT_STAGE==='STAGE 01'&&(newest.projectData.sources||[]).length===0,'New job did not begin cleanly at Stage 01.');\n // Malformed import does not destroy projects."""
new=""" assert(newest.job.JOB_ID!==userJob&&newest.job.JOB_ID!=='JOB-20260823144121','New JOB_ID was not unique.');assert(newest.job.CURRENT_STAGE==='STAGE 01'&&(newest.projectData.sources||[]).length===0,'New job did not begin cleanly at Stage 01.');\n // Stage 01 clarification is strict JSON at the agent boundary but a normal typed human experience in the application.\n await openStage(cdp,1);text=(await snapshot(cdp)).text;assert(text.includes('Paste response / questions')&&text.includes('turns those questions into normal typed inputs'),'Stage 01 does not explain the clarification handoff.');await click(cdp,'#save-prompt');let stageOne=await activeProject(cdp),stageOnePrompt=stageOne.projectData.generatedPrompts.filter(x=>Number(x.stage)===1&&!x.invalidatedBy).at(-1);const clarification={schema:'closed-loop-stage-response/2',jobId:stageOne.job.JOB_ID,stage:1,operation:stageOnePrompt.operation||'COMPLETE',promptIdentity:{instructionId:stageOnePrompt.instructionId,bodySha256:stageOnePrompt.bodySha256||stageOnePrompt.sha256,contractSha256:stageOnePrompt.contractSha256,contextSignature:stageOnePrompt.contextSignature},scope:stageOnePrompt.scope,responseType:'HUMAN_INPUT_REQUIRED',humanInputRequests:[{temporaryKey:'browser-question-1',question:'What exact output format is required?',whyRequired:'The deliverable format is human-authority input required to define the job.',affectedStageFields:['EXACT_DELIVERABLE_REQUESTED'],affectedRecords:[],answerType:'CHOICE',allowedValues:['PDF','DOCX'],blocking:true}],stageData:{},records:{},evidence:[],unresolved:[],warnings:[],attachments:[]};await fill(cdp,'#stage-output',JSON.stringify(clarification));await click(cdp,'#parse-output');await waitExpr(cdp,`document.body.innerText.includes('Proposed extracted changes')`);await click(cdp,'#accept-proposal');await waitExpr(cdp,`document.body.innerText.includes('Human clarification required')&&document.body.innerText.includes('What exact output format is required?')`);assert(await evalValue(cdp,`document.querySelector('[data-human-answer]')?.tagName==='SELECT'`),'Stage 01 CHOICE clarification did not render as a typed select control.');await evalValue(cdp,`(()=>{const e=document.querySelector('[data-human-answer]');e.value='PDF';e.dispatchEvent(new Event('change',{bubbles:true}));return true})()`);await click(cdp,'#save-human-answers');await waitExpr(cdp,`!document.body.innerText.includes('Human clarification required')`);stageOne=await activeProject(cdp);assert((stageOne.projectData.humanInputAnswers||[]).some(a=>a.answer==='PDF'),'Stage 01 human answer was not versioned canonically.');const regenerated=stageOne.projectData.generatedPrompts.filter(x=>Number(x.stage)===1&&!x.invalidatedBy).at(-1);assert(regenerated?.prompt.includes('PDF')&&regenerated.instructionId!==stageOnePrompt.instructionId,'Stage 01 answer did not regenerate a new controlling prompt containing the exact answer.');\n // Malformed import does not destroy projects."""
if s.count(old)!=1: raise SystemExit('verify-browser new-project anchor mismatch')
p.write_text(s.replace(old,new,1))

# Refresh one shared runtime identity because prompt/ingestion/UI runtime modules changed.
runtime=['workbook.js','hash.js','workflow-schema.js','workflow-engine.js','prompt-engine.js','response-ingestion.js','project-store.js','app-core.js']
def gitblob(path):
    b=Path(path).read_bytes();return hashlib.sha1(f'blob {len(b)}\0'.encode()+b).hexdigest()
manifest=''.join(f'{f}:{gitblob(f)}\n' for f in runtime).encode();token='runtime-'+hashlib.sha256(manifest).hexdigest()[:16]
p=Path('index.html');html=p.read_text();html,n=re.subn(r'(src="(?:workbook|hash|workflow-schema|workflow-engine|prompt-engine|response-ingestion|project-store|app-core)\.js\?v=)runtime-[a-f0-9]{16}(\")',rf'\g<1>{token}\2',html)
if n!=8: raise SystemExit(f'expected 8 runtime tokens, changed {n}')
p.write_text(html)
