from pathlib import Path

def once(text, old, new, name):
    n=text.count(old)
    if n!=1: raise SystemExit(f'{name}: expected one match, found {n}')
    return text.replace(old,new,1)

p=Path('workflow-schema.js'); t=p.read_text()
t=once(t,"  'AVAILABLE_TOOLS','PROHIBITED_ACTIONS','EXPLICIT_USER_REQUIREMENTS'\n]);","  'AVAILABLE_TOOLS','PROHIBITED_ACTIONS','EXPLICIT_USER_REQUIREMENTS','DESIRED_OR_SUGGESTED_SOURCE_COUNT'\n]);",'source count ownership')
p.write_text(t)

p=Path('prompt-engine.js'); t=p.read_text()
t=once(t,"KNOWN AUTHORITATIVE SOURCES:\n${show(j.KNOWN_AUTHORITATIVE_SOURCES)}\n\nAVAILABLE TOOLS:","KNOWN AUTHORITATIVE SOURCES:\n${show(j.KNOWN_AUTHORITATIVE_SOURCES)}\n\nDESIRED OR SUGGESTED SOURCE COUNT (search target only; never authority to invent sources):\n${show(j.DESIRED_OR_SUGGESTED_SOURCE_COUNT)}\n\nAVAILABLE TOOLS:",'source count prompt')
p.write_text(t)

p=Path('app-core.js'); t=p.read_text()
t=once(t,"['PROHIBITED_ACTIONS','Prohibited actions','textarea'],['EXPLICIT_USER_REQUIREMENTS','Explicit user requirements','textarea']","['PROHIBITED_ACTIONS','Prohibited actions','textarea'],['EXPLICIT_USER_REQUIREMENTS','Explicit user requirements','textarea'],['DESIRED_OR_SUGGESTED_SOURCE_COUNT','Desired / suggested source count','input']",'source count UI')
t=once(t,"prohibitedActions:next.job.PROHIBITED_ACTIONS,explicitRequirements:String(next.job.EXPLICIT_USER_REQUIREMENTS||'').split(/\\r?\\n/).filter(Boolean)","prohibitedActions:next.job.PROHIBITED_ACTIONS,explicitRequirements:String(next.job.EXPLICIT_USER_REQUIREMENTS||'').split(/\\r?\\n/).filter(Boolean),desiredOrSuggestedSourceCount:next.job.DESIRED_OR_SUGGESTED_SOURCE_COUNT",'source count user entered')
old="function acceptedStageMarkup(n){const s=current.stages[n],collections=schema.STAGE_CONTRACTS[n].allowedCollections,records=collections.flatMap(c=>engine.records(current,c,{stage:n}).map(r=>({collection:c,...r})));return `<div class=\"panel\"><h2 class=\"section-title\">Accepted canonical stage record</h2><p class=\"section-intro\">Agent-owned and application-derived data are read-only after validated ingestion. If the accepted response is incomplete or wrong, request a corrected response below; the application invalidates that response and dependent work without rewriting history.</p>${engine.acceptedChanges(current,n).length?`<div class=\"field\"><label>Correction / refinement requested</label><textarea id=\"accepted-correction-reason\" placeholder=\"State exactly what is missing, wrong, or should be more complete.\"></textarea></div><div class=\"button-row\"><button id=\"invalidate-accepted-response\">Request corrected / more complete response</button></div>`:''}"
new="function acceptedStageMarkup(n){const s=current.stages[n],collections=schema.STAGE_CONTRACTS[n].allowedCollections,records=collections.flatMap(c=>engine.records(current,c,{stage:n}).map(r=>({collection:c,...r}))),changes=engine.acceptedChanges(current,n);return `<div class=\"panel\"><h2 class=\"section-title\">Accepted canonical stage record</h2><p class=\"section-intro\">Agent-owned and application-derived data are read-only after validated ingestion. If an accepted response is incomplete or wrong, select that exact response and request a corrected result; the application invalidates its dependent work without rewriting history.</p>${changes.length?`<div class=\"field\"><label>Accepted response to correct</label><select id=\"accepted-correction-response\">${changes.map(change=>{const scope=engine.acceptedChangeScope(current,change),operation=engine.acceptedChangeOperation(current,change),run=scope.runId?` · ${scope.runId}`:'';return `<option value=\"${esc(change.changeId)}\">${esc(operation+run+' · '+change.changeId)}</option>`;}).join('')}</select></div><div class=\"field\"><label>Correction / refinement requested</label><textarea id=\"accepted-correction-reason\" placeholder=\"State exactly what is missing, wrong, or should be more complete.\"></textarea></div><div class=\"button-row\"><button id=\"invalidate-accepted-response\">Request corrected / more complete response</button></div>`:''}"
t=once(t,old,new,'accepted correction selector')
t=once(t,"const next=clone(current),change=engine.acceptedChanges(next,current.activeStage).at(-1);engine.invalidateAcceptedResponse(next,{stage:current.activeStage,rawResponseId:change?.rawResponseId,reason","const next=clone(current),changeId=$('#accepted-correction-response')?.value,change=engine.acceptedChanges(next,current.activeStage).find(item=>item.changeId===changeId);if(!change)throw new Error('Select an accepted response to correct.');engine.invalidateAcceptedResponse(next,{stage:current.activeStage,rawResponseId:change.rawResponseId,reason",'accepted correction selected response')
t=once(t,"<p class=\"section-intro\">Current operation: ${esc(plan.operation)}. This exact saved instruction is the controlling request. Its identity and strict response contract are embedded below.</p>","<p class=\"section-intro\">${[17,19].includes(n)?`Current operation: ${esc(plan.operation)}. `:''}This exact saved instruction is the controlling request. Its identity and strict response contract are embedded below.</p>",'ordinary operation wording')
t=once(t,"<button id=\"save-prompt\"${locked?' disabled':''}>Save instruction</button><button id=\"copy-prompt\"${locked?' disabled':''}>Copy instruction</button>","<button id=\"save-prompt\"${locked||plan.blockedReason?' disabled':''}>Save instruction</button><button id=\"copy-prompt\"${locked||plan.blockedReason?' disabled':''}>Copy instruction</button>",'blocked prompt controls')
p.write_text(t)

p=Path('workflow-engine.js'); t=p.read_text()
start=t.index("function invalidateAcceptedResponse(project,")
end=t.index("\nfunction reserveRunBatch",start)
old=t[start:end]
new="""function invalidateAcceptedResponse(project,{stage=project.activeStage,rawResponseId,reason='Corrected response required.',operatorLabel='HUMAN_OPERATOR'}={}){
  ensureShape(project);const number=Number(stage),currentChanges=acceptedChanges(project,number),change=currentChanges.find(item=>!rawResponseId||item.rawResponseId===rawResponseId);if(!change)throw new Error('No current accepted data change exists for invalidation.');
  const operations=schema.STAGE_CONTRACTS[number]?.operations||['COMPLETE'],selectedOperation=acceptedChangeOperation(project,change),selectedIndex=operations.indexOf(selectedOperation);const affected=currentChanges.filter(item=>{if(item.changeId===change.changeId)return true;if(![17,19].includes(number)||selectedIndex<0)return false;const operation=acceptedChangeOperation(project,item),index=operations.indexOf(operation);if(selectedOperation==='EXECUTE_RUN'&&operation==='EXECUTE_RUN')return false;return index>selectedIndex;});
  const affectedIds=new Set(affected.map(item=>item.changeId)),affectedRaw=new Set(affected.map(item=>item.rawResponseId)),affectedProposals=new Set(affected.map(item=>item.proposalId));const event=addHistory(project,'ACCEPTED_RESPONSE_INVALIDATED',{stage:number,rawResponseId:change.rawResponseId,invalidatedChangeIds:[...affectedIds],reason:String(reason||'Corrected response required.'),operatorLabel,identityAssurance:'SELF_ASSERTED'});
  for(const item of affected)item.invalidatedBy=event.eventId;for(const prompt of safe(project.projectData.generatedPrompts).filter(item=>Number(item.stage)===number&&!item.invalidatedBy))prompt.invalidatedBy=event.eventId;for(const pending of safe(project.projectData.responseProposals).filter(item=>Number(item.stage)===number&&item.status==='PENDING_OPERATOR_REVIEW')){pending.status='STALE';pending.invalidatedBy=event.eventId;}
  const invalidEvidence=new Set(records(project,'evidenceRecords',{active:false}).filter(record=>affectedRaw.has(record.rawResponseId)||affectedProposals.has(record.sourceProposalId)).map(record=>recordId(record,'evidenceRecords')));for(const record of records(project,'evidenceRecords',{active:false}))if(invalidEvidence.has(recordId(record,'evidenceRecords'))){record.active=false;record.validity='INVALIDATED';record.invalidatedBy=event.eventId;}
  for(const item of affected){const proposal=safe(project.projectData.responseProposals).find(record=>record.proposalId===item.proposalId);for(const [collection,list] of Object.entries(proposal?.canonicalRecords||{})){for(const canonical of safe(list)){const target=records(project,collection,{active:false}).find(record=>recordId(record,collection)===canonical.id);if(!target)continue;if(canonical.updateTargetId){const def=schema.RECORD_SCHEMAS[collection],snapshot=target.lastAgentUpdate?.proposalId===item.proposalId?target.lastAgentUpdate:null;for(const [name,fieldDef] of Object.entries(def?.fieldDefinitions||{}))if(fieldDef.producer===schema.PRODUCER.AGENT)delete target[name];if(snapshot){target.fields=clone(snapshot.fields||{});Object.assign(target,target.fields);target.relationships=clone(snapshot.relationships||{});target.evidenceRefs=clone(snapshot.evidenceRefs||[]);target.status=snapshot.status;target.completionState=snapshot.completionState;delete target.lastAgentUpdate;}else{for(const [name,fieldDef] of Object.entries(def?.fieldDefinitions||{}))if(fieldDef.producer===schema.PRODUCER.AGENT)delete target.fields?.[name];target.evidenceRefs=safe(target.evidenceRefs).filter(id=>!invalidEvidence.has(id));target.status='RESERVED';target.completionState='AWAITING_AGENT_COMPLETION';}target.contentSha256=hash.contentRecordSha256(target,def.idField);target.recordSha256=hash.recordSha256(target);target.sha256=target.recordSha256;}else{target.active=false;target.validity='INVALIDATED';target.invalidatedBy=event.eventId;}}}}
  if([17,19].includes(number)&&selectedIndex===0){for(const collection of ['iterations','runs','freshContexts',...(number===17?['candidateFreezes']:[])])for(const record of records(project,collection,{stage:number,active:false}))if(!record.invalidatedBy){record.active=false;record.validity='INVALIDATED';record.invalidatedBy=event.eventId;}if(number===17){const prior=latestIteration(project,[10]);project.job.CURRENT_ITERATION=recordId(prior,'iterations')||'';}else{const prior=latestIteration(project,[17]);project.job.CURRENT_ITERATION=recordId(prior,'iterations')||'';}}
  const state=project.stages[number];state.acceptedDataChangeIds=safe(state.acceptedDataChangeIds).filter(id=>!affectedIds.has(id));state.acceptedResponseIds=safe(state.acceptedResponseIds).filter(id=>!affectedRaw.has(id));state.agentData={};for(const remaining of acceptedChanges(project,number).sort((a,b)=>(a.eventSequence||0)-(b.eventSequence||0))){const prior=safe(project.projectData.responseProposals).find(item=>item.proposalId===remaining.proposalId);Object.assign(state.agentData,clone(prior?.proposedStageData||{}));}state.acceptedData=state.agentData;if(number===1)for(const name of schema.AGENT_JOB_FIELDS)project.job[name]=Object.hasOwn(state.agentData,name)?clone(state.agentData[name]):'';invalidateDownstream(project,number,event.eventId,String(reason||'Corrected response required.'));recalculate(project);return event;
}"""
t=t[:start]+new+t[end:]
p.write_text(t)

p=Path('verify-complete.mjs'); t=p.read_text()
insert="""
// Multi-operation correction keeps independent run executions but invalidates dependent later operations.
{
  const p=project('JOB-OP-INVALIDATION');p.projectData.acceptedChanges.push(
    {changeId:'RUN-A',rawResponseId:'RAW-A',proposalId:'P-A',stage:17,status:'COMMITTED',responseType:'DATA_PROPOSAL',operation:'EXECUTE_RUN',scope:{runId:'RUN-1'}},
    {changeId:'RUN-B',rawResponseId:'RAW-B',proposalId:'P-B',stage:17,status:'COMMITTED',responseType:'DATA_PROPOSAL',operation:'EXECUTE_RUN',scope:{runId:'RUN-2'}},
    {changeId:'VERIFY-A',rawResponseId:'RAW-V',proposalId:'P-V',stage:17,status:'COMMITTED',responseType:'DATA_PROPOSAL',operation:'VERIFY',scope:{}}
  );p.projectData.responseProposals.push({proposalId:'P-A',stage:17,canonicalRecords:{}},{proposalId:'P-B',stage:17,canonicalRecords:{}},{proposalId:'P-V',stage:17,canonicalRecords:{}});engine.invalidateAcceptedResponse(p,{stage:17,rawResponseId:'RAW-A',reason:'Correct run 1.'});if(!p.projectData.acceptedChanges.find(x=>x.changeId==='RUN-A').invalidatedBy)throw new Error('Selected run response was not invalidated.');if(p.projectData.acceptedChanges.find(x=>x.changeId==='RUN-B').invalidatedBy)throw new Error('Independent run response was unnecessarily invalidated.');if(!p.projectData.acceptedChanges.find(x=>x.changeId==='VERIFY-A').invalidatedBy)throw new Error('Dependent Stage 17 verification was not invalidated.');
}
"""
t=once(t,"\n// Final operator-path audit:",insert+"\n// Final operator-path audit:",'operation correction test')
p.write_text(t)
