from pathlib import Path
import subprocess

def once(s,old,new,label):
    n=s.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1 match, found {n}')
    return s.replace(old,new,1)

p=Path('prompt-engine.js');s=p.read_text()
old="function scopeFor(stage,state,overrides={}){const j=state?.job||{};const value={projectRevision:Number(state?.revision||0),inputVersion:j.CURRENT_INPUT_VERSION||null,sourceSetVersion:j.CURRENT_SOURCE_SET_VERSION||null,requirementsVersion:j.CURRENT_REQUIREMENTS_VERSION||null,testSuiteVersion:j.CURRENT_TEST_SUITE_VERSION||null,instructionVersion:j.CURRENT_INSTRUCTION_VERSION||null,iterationId:j.CURRENT_ITERATION||null,candidateId:state?.projectData?.candidateFreezes?.filter(x=>x?.active!==false&&!x?.invalidatedBy).at(-1)?.id||null,runId:overrides.runId||null,contextId:overrides.contextId||null,baselineId:j.CURRENT_BASELINE_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_BASELINE_ID))?j.CURRENT_BASELINE_ID:null,productId:j.CURRENT_PRODUCT_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_PRODUCT_ID))?j.CURRENT_PRODUCT_ID:null};return value;}"
new="function scopeFor(stage,state,overrides={}){const j=state?.job||{},has=key=>Object.prototype.hasOwnProperty.call(overrides,key),pick=(key,fallback)=>has(key)?overrides[key]:fallback;return {projectRevision:pick('projectRevision',Number(state?.revision||0)),inputVersion:pick('inputVersion',j.CURRENT_INPUT_VERSION||null),sourceSetVersion:pick('sourceSetVersion',j.CURRENT_SOURCE_SET_VERSION||null),requirementsVersion:pick('requirementsVersion',j.CURRENT_REQUIREMENTS_VERSION||null),testSuiteVersion:pick('testSuiteVersion',j.CURRENT_TEST_SUITE_VERSION||null),instructionVersion:pick('instructionVersion',j.CURRENT_INSTRUCTION_VERSION||null),iterationId:pick('iterationId',j.CURRENT_ITERATION||null),candidateId:pick('candidateId',state?.projectData?.candidateFreezes?.filter(x=>x?.active!==false&&!x?.invalidatedBy).at(-1)?.id||null),runId:pick('runId',null),contextId:pick('contextId',null),baselineId:pick('baselineId',j.CURRENT_BASELINE_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_BASELINE_ID))?j.CURRENT_BASELINE_ID:null),productId:pick('productId',j.CURRENT_PRODUCT_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_PRODUCT_ID))?j.CURRENT_PRODUCT_ID:null)};}"
s=once(s,old,new,'scopeFor exact overrides');p.write_text(s)

p=Path('workflow-schema.js');s=p.read_text()
old="required:['FAILURE_FIXTURE','REPRODUCTION_PROCEDURE','DETECTION_METHOD','PRE_CORRECTION_RESULT','PRE_CORRECTION_EVIDENCE','CORRECTION','POST_CORRECTION_RESULT','POST_CORRECTION_EVIDENCE','PERMANENT_TEST_LOCATION','APPLICABILITY','ACTIVE_RETIRED_STATE']"
new="required:['FAILURE_FIXTURE','REPRODUCTION_PROCEDURE','DETECTION_METHOD','PRE_CORRECTION_RESULT','PRE_CORRECTION_EVIDENCE','PERMANENT_TEST_LOCATION','APPLICABILITY','ACTIVE_RETIRED_STATE']"
s=once(s,old,new,'Stage 15 temporal required fields');p.write_text(s)

p=Path('response-ingestion.js');s=p.read_text()
old="const receipt={receiptId,jobId:project.job.JOB_ID,stage:Number(stage),role:globalThis.closedLoopCore?.STAGES?.[Number(stage)-1]?.role||'UNKNOWN',contextId:'UNKNOWN',iteration:project.job.CURRENT_ITERATION||'NOT APPLICABLE',runId:'NOT APPLICABLE',requestDateTime:promptRecord.generatedAt||'UNKNOWN'"
new="const receipt={receiptId,jobId:project.job.JOB_ID,stage:Number(stage),role:globalThis.closedLoopCore?.STAGES?.[Number(stage)-1]?.role||'UNKNOWN',operation:promptRecord.operation||'COMPLETE',contextId:promptRecord.scope?.contextId||'NOT APPLICABLE',iteration:promptRecord.scope?.iterationId||project.job.CURRENT_ITERATION||'NOT APPLICABLE',runId:promptRecord.scope?.runId||'NOT APPLICABLE',requestDateTime:promptRecord.generatedAt||'UNKNOWN'"
s=once(s,old,new,'receipt exact prompt target')
old="status:'COMMITTED',canonicalRecordIds:committedRecordIds,stageFields:Object.keys(proposal.proposedStageData),promptId:proposal.promptId,bodySha256:proposal.bodySha256||proposal.promptSha256"
new="status:'COMMITTED',operation:proposal.envelope.operation||'COMPLETE',scope:clone(proposal.envelope.scope||{}),canonicalRecordIds:committedRecordIds,stageFields:Object.keys(proposal.proposedStageData),promptId:proposal.promptId,bodySha256:proposal.bodySha256||proposal.promptSha256"
s=once(s,old,new,'accepted change operation/scope');p.write_text(s)

p=Path('workflow-engine.js');s=p.read_text()
old="function invalidateAcceptedResponse(project,{stage=project.activeStage,rawResponseId,reason='Corrected response required.',operatorLabel='HUMAN_OPERATOR'}={}){\n  ensureShape(project);const change=acceptedChanges(project,stage).find(item=>!rawResponseId||item.rawResponseId===rawResponseId);if(!change)throw new Error('No current accepted data change exists for invalidation.');\n  const event=addHistory(project,'ACCEPTED_RESPONSE_INVALIDATED',{stage,rawResponseId:change.rawResponseId,reason,operatorLabel,identityAssurance:'SELF_ASSERTED'});change.invalidatedBy=event.eventId;invalidateDownstream(project,stage,event.eventId,reason);recalculate(project);return event;\n}"
new="function acceptedChangeScope(project,change){if(change?.scope)return clone(change.scope);const proposal=safe(project?.projectData?.responseProposals).find(item=>item.proposalId===change?.proposalId);return clone(proposal?.envelope?.scope||proposal?.scope||{});}\nfunction acceptedChangeOperation(project,change){if(change?.operation)return change.operation;const proposal=safe(project?.projectData?.responseProposals).find(item=>item.proposalId===change?.proposalId);return proposal?.envelope?.operation||'COMPLETE';}\nfunction invalidateAcceptedResponse(project,{stage=project.activeStage,rawResponseId,reason='Corrected response required.',operatorLabel='HUMAN_OPERATOR'}={}){\n  ensureShape(project);const change=acceptedChanges(project,stage).find(item=>!rawResponseId||item.rawResponseId===rawResponseId);if(!change)throw new Error('No current accepted data change exists for invalidation.');\n  const operation=acceptedChangeOperation(project,change),scope=acceptedChangeScope(project,change),event=addHistory(project,'ACCEPTED_RESPONSE_INVALIDATED',{stage,rawResponseId:change.rawResponseId,reason,operation,scope,operatorLabel,identityAssurance:'SELF_ASSERTED'});change.invalidatedBy=event.eventId;\n  const ids=new Set(change.canonicalRecordIds||[]);for(const [collection,list] of Object.entries(project.projectData)){if(!Array.isArray(list)||!schema.RECORD_SCHEMAS[collection])continue;for(const record of list){const id=recordId(record,collection);if(!ids.has(id))continue;if(record.source==='APPLICATION_RESERVATION'||record.reserved){record.status='RESERVED';record.completionState='AWAITING_AGENT_COMPLETION';record.evidenceRefs=[];for(const [name,def] of Object.entries(schema.RECORD_SCHEMAS[collection].fieldDefinitions||{}))if(def.producer===schema.PRODUCER.AGENT){if(record.fields)delete record.fields[name];delete record[name];}}else{record.active=false;record.validity='INVALIDATED';record.invalidatedBy=event.eventId;}}}\n  for(const evidence of records(project,'evidenceRecords',{stage,active:false}).filter(record=>record.rawResponseId===change.rawResponseId)){evidence.active=false;evidence.validity='INVALIDATED';evidence.invalidatedBy=event.eventId;}const state=project.stages[Number(stage)];state.agentData={};state.acceptedData={};state.acceptedDataChangeIds=state.acceptedDataChangeIds.filter(id=>id!==change.changeId);state.acceptedResponseIds=state.acceptedResponseIds.filter(id=>id!==change.rawResponseId);for(const prompt of safe(project.projectData.generatedPrompts).filter(item=>Number(item.stage)===Number(stage)&&!item.invalidatedBy&&item.instructionId===state.currentPromptId))prompt.invalidatedBy=event.eventId;state.currentPromptId=null;invalidateDownstream(project,stage,event.eventId,reason);recalculate(project);return event;\n}"
s=once(s,old,new,'accepted response invalidation')
old="ensureShape(project);if(count!==10)throw new Error('Run batches must contain exactly ten slots.');const resolvedIteration=iterationId||project.job.CURRENT_ITERATION;if(!resolvedIteration)throw new Error('A current iteration is required before reserving runs.');\n  const created=[];for(let i=0;i<count;i++){"
new="ensureShape(project);if(count!==10)throw new Error('Run batches must contain exactly ten slots.');const resolvedIteration=iterationId||project.job.CURRENT_ITERATION;if(!resolvedIteration)throw new Error('A current iteration is required before reserving runs.');const resolvedCandidate=candidateId||iterationCandidateId(project,resolvedIteration);if(!resolvedCandidate||['PENDING','UNKNOWN','UNASSIGNED'].includes(upper(resolvedCandidate)))throw new Error('A current application-frozen candidate is required before reserving runs.');\n  const created=[];for(let i=0;i<count;i++){"
s=once(s,old,new,'run candidate precondition').replace("CANDIDATE_ID:candidateId||'PENDING'","CANDIDATE_ID:resolvedCandidate",1)
marker="function registerArtifactBytes(project,{stage=project.activeStage,artifactId,filename,mediaType,byteSize,sha256,lineage={},role='STAGE_ARTIFACT'}={}){"
insert="function nextPromptOperation(project,stage){ensureShape(project);const n=Number(stage),ops=schema.STAGE_OPERATIONS[n]||['COMPLETE'];if(![17,19].includes(n))return {operation:ops[0],scope:{},blockedReason:null};const changes=acceptedChanges(project,n),has=op=>changes.some(change=>acceptedChangeOperation(project,change)===op),scope=currentScope(project);for(const op of ops){if(op==='EXECUTE_RUN'){const runs=recordsForCurrentScope(project,'runs',{iterationId:scope.iterationId,candidateId:scope.candidateId});if(runs.length!==10)return {operation:op,scope:{},blockedReason:'Reserve exactly ten run/context slots for the current frozen candidate before execution.'};const run=runs.find(record=>upper(recordValue(record,'EXECUTION_STATUS'))!=='COMPLETED');if(run)return {operation:op,scope:{runId:recordId(run,'runs'),contextId:String(recordValue(run,'CONTEXT_ID')||'')},blockedReason:null};continue;}if(!has(op))return {operation:op,scope:{},blockedReason:null};}return {operation:ops.at(-1),scope:{},blockedReason:null,complete:true};}\n"
if marker not in s: raise SystemExit('nextPromptOperation marker missing')
s=s.replace(marker,insert+marker,1)
s=s.replace("records,registerGeneratedPrompt,createHumanBlocker,registerFreshContext,recordHumanDecision,invalidateAcceptedResponse,reserveRunBatch","records,registerGeneratedPrompt,createHumanBlocker,registerFreshContext,recordHumanDecision,acceptedChangeScope,acceptedChangeOperation,nextPromptOperation,invalidateAcceptedResponse,reserveRunBatch",1)
p.write_text(s)

p=Path('app-core.js');s=p.read_text()
old="function promptOptions(n){const operation=selectedOperation(n),options={operation},requiresRun=(schema.operationContract(n,operation)?.scopeRequirements||[]).includes('runId');if(requiresRun){const run=selectedRun(n);if(run){const runId=engine.recordId(run,'runs'),contextId=String(recordValue(run,'CONTEXT_ID')||run.relationships?.CONTEXT_ID||run.scope?.contextId||'');options.scope={runId,contextId};}}return options;}"
new="function promptOptions(n){const plan=engine.nextPromptOperation(current,n),operation=[17,19].includes(Number(n))?plan.operation:selectedOperation(n),options={operation,scope:{...(plan.scope||{})}},requiresRun=(schema.operationContract(n,operation)?.scopeRequirements||[]).includes('runId');if(requiresRun&&!options.scope.runId){const run=selectedRun(n);if(run){const runId=engine.recordId(run,'runs'),contextId=String(recordValue(run,'CONTEXT_ID')||run.relationships?.CONTEXT_ID||run.scope?.contextId||'');options.scope={...options.scope,runId,contextId};}}return options;}"
s=once(s,old,new,'app prompt options')
start=s.index('function operationMarkup(n,locked){');end=s.index('\nfunction validationMarkup',start)
old=s[start:end]
new="function operationMarkup(n,locked){const operations=stageOperations(n);if(operations.length<=1)return '';if([17,19].includes(Number(n))){const plan=engine.nextPromptOperation(current,n);return `<div class=\"panel\"><h2 class=\"section-title\">Current required operation</h2><p class=\"section-intro\">The application selects the next operation from current canonical evidence. The operator does not coordinate internal operation ordering or identities.</p><div class=\"record-row\"><div class=\"record-key\">Operation</div><div class=\"record-value\">${esc(plan.operation.replaceAll('_',' '))}</div></div>${plan.blockedReason?`<div class=\"notice warn\">${esc(plan.blockedReason)}</div>`:''}</div>`;}const active=selectedOperation(n);return `<div class=\"panel\"><h2 class=\"section-title\">Stage operation</h2><div class=\"record-row\"><div class=\"record-key\">Operation</div><div class=\"record-value\">${esc(active.replaceAll('_',' '))}</div></div></div>`;}"
s=s[:start]+new+s[end:]
s=once(s,"const picker=(schema.operationContract(n,selectedOperation(n))?.scopeRequirements||[]).includes('runId')&&runs.length?","const picker=n===11&&(schema.operationContract(n,selectedOperation(n))?.scopeRequirements||[]).includes('runId')&&runs.length?",'run picker scope')
old="const next=clone(current),change=engine.acceptedChanges(next,current.activeStage).at(-1);if(!change)throw new Error('No current accepted response exists to refine.');engine.invalidateAcceptedResponse(next,{stage:current.activeStage,rawResponseId:change.rawResponseId,reason,operatorLabel:$('#operator-label')?.value.trim()||'HUMAN_OPERATOR'});"
new="const next=clone(current),rawResponseId=$('#accepted-refinement-target')?.value||engine.acceptedChanges(next,current.activeStage).at(-1)?.rawResponseId,change=engine.acceptedChanges(next,current.activeStage).find(item=>item.rawResponseId===rawResponseId);if(!change)throw new Error('Select a current accepted response to refine.');engine.invalidateAcceptedResponse(next,{stage:current.activeStage,rawResponseId:change.rawResponseId,reason,operatorLabel:$('#operator-label')?.value.trim()||'HUMAN_OPERATOR'});"
s=once(s,old,new,'refinement handler')
needle='<div class="field"><label>Why refinement is required</label><textarea id="accepted-refinement-reason"></textarea></div><button id="refine-accepted-response">Invalidate accepted result and request refinement</button>'
replacement='<div class="field"><label>Accepted response to refine</label><select id="accepted-refinement-target">${engine.acceptedChanges(current,n).map(change=>`<option value="${esc(change.rawResponseId)}">${esc(engine.acceptedChangeOperation(current,change))}${engine.acceptedChangeScope(current,change).runId?` · ${esc(engine.acceptedChangeScope(current,change).runId)}`:""} · ${esc(change.changeId)}</option>`).join("")}</select></div><div class="field"><label>Why refinement is required</label><textarea id="accepted-refinement-reason"></textarea></div><button id="refine-accepted-response">Invalidate accepted result and request refinement</button>'
s=once(s,needle,replacement,'refinement selector')
s=once(s,'function provenanceMarkup(n){','function evidenceChainControlMarkup(n,locked){if(n!==29)return \'\';return `<div class="panel"><h2 class="section-title">Application evidence graph</h2><p class="section-intro">Build the evidence chains deterministically from current canonical identities. The human does not type routine traceability links.</p><div class="button-row"><button id="build-evidence-chains"${locked?\' disabled\':\'\'}>Build / verify evidence chains</button></div></div>`;}\nfunction provenanceMarkup(n){','evidence control function')
s=once(s,'${acceptedStageMarkup(n)}${artifactControlMarkup(n,locked)}${provenanceMarkup(n)}${controls(d,locked)}`;}','${acceptedStageMarkup(n)}${artifactControlMarkup(n,locked)}${evidenceChainControlMarkup(n,locked)}${provenanceMarkup(n)}${controls(d,locked)}`;}','evidence control render')
s=once(s,"if($('#calculate-release-state'))$('#calculate-release-state').onclick=async()=>{","if($('#build-evidence-chains'))$('#build-evidence-chains').onclick=async()=>{try{const next=clone(current);engine.constructEvidenceChains(next);await persistReplacement(next);announce('evidence chains rebuilt from canonical state');render();}catch(error){alert(error.message||error);}};if($('#calculate-release-state'))$('#calculate-release-state').onclick=async()=>{",'evidence control wire')
p.write_text(s)

spec=subprocess.check_output(['git','show','origin/practical-100/organic-self-spec-acceptance:SELF_SPECIFICATION.md'],text=True)
Path('SELF_SPECIFICATION.md').write_text(spec)
