from pathlib import Path
p=Path('.final-current-patch.py')
s=p.read_text()
old="# Stage 24 declares the exact attack set and uses the existing regression-execution collection.\nrep('workflow-schema.js',\"  24:['adversarialResults'],\",\"  24:['adversarialResults','regressionExecutions'],\")"
new="# Stage 24 declares the exact attack set while retaining its existing adversarial-results write surface."
if old not in s: raise SystemExit('Stage24 collection-model anchor missing')
s=s.replace(old,new,1)
old="Execute every active historical permanent regression against the current product and return exactly one current regressionExecutions record for each active REG_ID. Preserve attack, method, expected behavior, actual result, defect, severity, determination, and evidence."
new="Execute every active historical permanent regression against the current product. Include each one in ATTACKS_EXECUTED using the exact key HISTORICAL_REGRESSION:<REG_ID>, and return exactly one evidenced adversarialResults record whose ATTACK equals that key. Preserve attack, method, expected behavior, actual result, defect, severity, determination, and evidence."
if old not in s: raise SystemExit('Stage24 prompt regression-model anchor missing')
s=s.replace(old,new,1)
old="const activeRegs=records(project,'regressions').filter(r=>upper(recordValue(r,'ACTIVE_RETIRED_STATE')||'ACTIVE')!=='RETIRED'),executions=recordsForCurrentScope(project,'regressionExecutions');for(const reg of activeRegs){const id=recordId(reg,'regressions'),xs=executions.filter(x=>String(recordValue(x,'REG_ID')||x.relationships?.REG_ID||'')===id);if(xs.length!==1||!['SATISFIED','SUCCESS','PASSED'].includes(upper(recordValue(xs[0],'RESULT'))))reasons.push('Active historical regression '+id+' requires exactly one successful current product-scope execution.');}"
new="const activeRegs=records(project,'regressions').filter(r=>upper(recordValue(r,'ACTIVE_RETIRED_STATE')||'ACTIVE')!=='RETIRED');for(const reg of activeRegs){const id=recordId(reg,'regressions'),key='HISTORICAL_REGRESSION:'+id;if(!declaredSet.has(key)||counts.get(key)!==1)reasons.push('Active historical regression '+id+' requires exactly one current evidenced adversarial execution keyed '+key+'.');}"
if old not in s: raise SystemExit('Stage24 gate regression-model anchor missing')
s=s.replace(old,new,1)
old="new=\"data(24,{stageData:{ATTACKS_EXECUTED:['Missing required content']},records:{adversarialResults:[recordProposal(schema,'adversarialResults',{tempKey:'adv',relationships:{PRODUCT_ID:{recordId:productId}},overrides:{ATTACK:'Missing required content',METHOD:'Adversarial omission check',EXPECTED_BEHAVIOR:'Reject missing content',ACTUAL_RESULT:'No defect found',DETERMINATION:'SATISFIED',SEVERITY:'MINOR',EVIDENCE:'Adversarial evidence'}})],regressionExecutions:[recordProposal(schema,'regressionExecutions',{tempKey:'product-regression',relationships:{REG_ID:{recordId:regId},PRODUCT_ID:{recordId:productId}},overrides:{PHASE:'PRODUCT_ADVERSARIAL',RESULT:'SATISFIED'}})]}});complete(24);\""
new="new=\"data(24,{stageData:{ATTACKS_EXECUTED:['Missing required content',`HISTORICAL_REGRESSION:${regId}`]},records:{adversarialResults:[recordProposal(schema,'adversarialResults',{tempKey:'adv',relationships:{PRODUCT_ID:{recordId:productId}},overrides:{ATTACK:'Missing required content',METHOD:'Adversarial omission check',EXPECTED_BEHAVIOR:'Reject missing content',ACTUAL_RESULT:'No defect found',DETERMINATION:'SATISFIED',SEVERITY:'MINOR',EVIDENCE:'Adversarial evidence'}}),recordProposal(schema,'adversarialResults',{tempKey:'historical-regression',relationships:{PRODUCT_ID:{recordId:productId}},overrides:{ATTACK:`HISTORICAL_REGRESSION:${regId}`,METHOD:'Execute active permanent regression against current product',EXPECTED_BEHAVIOR:'Regression remains satisfied',ACTUAL_RESULT:'Regression satisfied',DETERMINATION:'SATISFIED',SEVERITY:'MINOR',EVIDENCE:'Current product historical regression evidence'}})]}});complete(24);\""
if old not in s: raise SystemExit('Stage24 full-cycle regression-model anchor missing')
s=s.replace(old,new,1)
old="const p=project('JOB-STAGE24-EXACT');p.job.CURRENT_PRODUCT_ID='PRODUCT-24';p.stages[24].agentData.ATTACKS_EXECUTED=['CATEGORY-A','CATEGORY-B'];"
new="const p=project('JOB-STAGE24-EXACT');p.job.CURRENT_PRODUCT_ID='PRODUCT-24';p.stages[24].agentData.ATTACKS_EXECUTED=['CATEGORY-A','CATEGORY-B','HISTORICAL_REGRESSION:REG-24'];"
if old not in s: raise SystemExit('Stage24 focused declared-set anchor missing')
s=s.replace(old,new,1)
old="const b=record('adversarialResults',24,{PRODUCT_ID:'PRODUCT-24',ATTACK:'CATEGORY-B',METHOD:'x',EXPECTED_BEHAVIOR:'x',ACTUAL_RESULT:'x',DETERMINATION:'SATISFIED',SEVERITY:'MINOR',EVIDENCE:'e'},'ATTACK-B');b.scope=scope;p.projectData.adversarialResults.push(b);const rx=record('regressionExecutions',24,{REG_ID:'REG-24',PRODUCT_ID:'PRODUCT-24',PHASE:'PRODUCT_ADVERSARIAL',RESULT:'SATISFIED'},'REG-EXEC-24');rx.scope=scope;rx.relationships={REG_ID:'REG-24',PRODUCT_ID:'PRODUCT-24'};p.projectData.regressionExecutions.push(rx);g=engine.gate(24,p);"
new="const b=record('adversarialResults',24,{PRODUCT_ID:'PRODUCT-24',ATTACK:'CATEGORY-B',METHOD:'x',EXPECTED_BEHAVIOR:'x',ACTUAL_RESULT:'x',DETERMINATION:'SATISFIED',SEVERITY:'MINOR',EVIDENCE:'e'},'ATTACK-B');b.scope=scope;p.projectData.adversarialResults.push(b);const rx=record('adversarialResults',24,{PRODUCT_ID:'PRODUCT-24',ATTACK:'HISTORICAL_REGRESSION:REG-24',METHOD:'execute permanent regression',EXPECTED_BEHAVIOR:'satisfied',ACTUAL_RESULT:'satisfied',DETERMINATION:'SATISFIED',SEVERITY:'MINOR',EVIDENCE:'current regression evidence'},'ATTACK-REG-24');rx.scope=scope;p.projectData.adversarialResults.push(rx);g=engine.gate(24,p);"
if old not in s: raise SystemExit('Stage24 focused regression-result anchor missing')
s=s.replace(old,new,1)
p.write_text(s)
