from pathlib import Path

def replace(path,old,new,count=1):
    p=Path(path);s=p.read_text();assert old in s,f'missing target in {path}';p.write_text(s.replace(old,new,count))

# Canonical scope identities must never preserve sentinel prose as identities.
replace('workflow-engine.js',"function currentScope(project){return {inputVersion:project.job.CURRENT_INPUT_VERSION||null,sourceSetVersion:project.job.CURRENT_SOURCE_SET_VERSION||null,requirementsVersion:project.job.CURRENT_REQUIREMENTS_VERSION||null,testSuiteVersion:project.job.CURRENT_TEST_SUITE_VERSION||null,instructionVersion:project.job.CURRENT_INSTRUCTION_VERSION||null,iterationId:recordId(latestIteration(project,[10,17,19]),'iterations')||project.job.CURRENT_ITERATION||null,candidateId:recordId(records(project,'candidateFreezes').at(-1),'candidateFreezes')||null,baselineId:recordId(records(project,'baselines').at(-1),'baselines')||project.job.CURRENT_BASELINE_ID||null,productId:recordId(records(project,'products').at(-1),'products')||project.job.CURRENT_PRODUCT_ID||null};}","const scopeIdentity=value=>{const text=String(value??'').trim();return !text||['NONE','NOT APPLICABLE','UNKNOWN','PENDING','UNASSIGNED'].includes(upper(text))?null:text;};\nfunction currentScope(project){return {inputVersion:scopeIdentity(project.job.CURRENT_INPUT_VERSION),sourceSetVersion:scopeIdentity(project.job.CURRENT_SOURCE_SET_VERSION),requirementsVersion:scopeIdentity(project.job.CURRENT_REQUIREMENTS_VERSION),testSuiteVersion:scopeIdentity(project.job.CURRENT_TEST_SUITE_VERSION),instructionVersion:scopeIdentity(project.job.CURRENT_INSTRUCTION_VERSION),iterationId:scopeIdentity(recordId(latestIteration(project,[10,17,19]),'iterations')||project.job.CURRENT_ITERATION),candidateId:scopeIdentity(recordId(records(project,'candidateFreezes').at(-1),'candidateFreezes')),baselineId:scopeIdentity(recordId(records(project,'baselines').at(-1),'baselines')||project.job.CURRENT_BASELINE_ID),productId:scopeIdentity(recordId(records(project,'products').at(-1),'products')||project.job.CURRENT_PRODUCT_ID)};}")
replace('workflow-engine.js',"function iterationScope(project,iterationId){const id=String(iterationId||'');if(!id)return {};const candidate=records(project,'candidateFreezes').find(record=>String(recordValue(record,'ITERATION_ID')||record.relationships?.ITERATION_ID||record.scope?.iterationId||'')===id);return {iterationId:id,candidateId:recordId(candidate,'candidateFreezes')||undefined};}","function iterationScope(project,iterationId){const id=String(iterationId||'');if(!id)return {};const candidate=records(project,'candidateFreezes').find(record=>String(recordValue(record,'ITERATION_ID')||record.relationships?.ITERATION_ID||record.scope?.iterationId||'')===id);return {iterationId:id,candidateId:recordId(candidate,'candidateFreezes')||undefined,baselineId:null,productId:null};}")
# Stage 20 creates BASELINE_ID; it cannot require the response to echo a not-yet-created baseline identity.
replace('workflow-schema.js',"if(s>=20)keys.push('baselineId');if(s>=21)keys.push('productId');","if(s>=21)keys.push('baselineId','productId');")

p=Path('verify-full-cycle.mjs');s=p.read_text();marker="const result={continuousLifecycle:'STAGES_01_TO_19'"
assert marker in s
block="""// Stage 20: accept current unchanged-confirmation evidence, then human-authorize and application-freeze exact baseline bytes.\npr=savePrompt(20);assert(!schema.operationContract(20,'COMPLETE').scopeRequirements.includes('baselineId'),'Stage 20 response cannot require a baseline ID before application allocation.');accept(20,pr,{stageData:stageData(20),records:{}},'STAGE-20-PROPOSAL');\nconst baseline=engine.freezeBaseline(p,{artifactIds:['ARTIFACT-CORRECTED'],operatorLabel:'FULL_CYCLE_OPERATOR',authorization:'AUTHORIZED'});engine.recalculate(p);assertComplete(19);assertComplete(20);assert(engine.recordId(baseline,'baselines')===p.job.CURRENT_BASELINE_ID,'Stage 20 did not assign the canonical baseline ID.');\n\n"""
s=s.replace(marker,block+marker,1).replace("continuousLifecycle:'STAGES_01_TO_19',stagesCompleted:19","continuousLifecycle:'STAGES_01_TO_20',stagesCompleted:20",1)
p.write_text(s)
