from pathlib import Path
p=Path('verify-full-cycle.mjs')
s=p.read_text()
old="""const result={continuousLifecycle:'STAGES_01_TO_16',stagesCompleted:16,currentStage:p.job.CURRENT_STAGE,revision:p.revision||0,acceptedDataChanges:p.projectData.acceptedChanges.length,rawResponses:p.projectData.rawResponses.length,stage8EvidenceRelationship:true,stage11InitialBoundary:true,verificationTriples:engine.verificationMatrix(p,iterationId).expected.length,confirmedDefect:defectId,permanentRegression:regId};
console.log(JSON.stringify(result,null,2));
"""
assert old in s
new="""// Stage 17: corrected candidate, ten new contexts/runs, full matrix, comparison, and post-correction regression execution.
pr=savePrompt(17,{operation:'FREEZE'});accept(17,pr,{stageData:stageData(17,{PREVIOUS_ITERATION_ID:iterationId,PREVIOUS_CANDIDATE_ID:candidateId,CHANGESET_ID:recordId('changes'),OLD_CONVERSATIONS_CONTINUED:'NO',PRIOR_OUTPUTS_WITHHELD:'YES'}),records:{}},'STAGE-17-FREEZE');
const correctedBytes=new TextEncoder().encode('{\"candidate\":true,\"correction\":1}'),correctedSha=await hash.sha256Bytes(correctedBytes);engine.registerArtifactBytes(p,{stage:17,artifactId:'ARTIFACT-CORRECTED',filename:'candidate-corrected.json',mediaType:'application/json',byteSize:correctedBytes.byteLength,sha256:correctedSha,lineage:{purpose:'corrected iteration'}});
const correctedFreeze=engine.freezeCandidate(p,{stage:17,artifactIds:['ARTIFACT-CORRECTED'],operatorLabel:'FULL_CYCLE_OPERATOR',purpose:'CORRECTED_ITERATION'}),iteration17=correctedFreeze.iteration.id,candidate17=correctedFreeze.candidate.id;
const slots17=engine.reserveRunBatch(p,{stage:17,iterationId:iteration17,candidateId:candidate17,count:10});
for(let i=0;i<slots17.length;i++){const slot=slots17[i];pr=savePrompt(17,{operation:'EXECUTE_RUN',scope:{runId:slot.runId,contextId:slot.contextId,iterationId:iteration17,candidateId:candidate17}});accept(17,pr,{stageData:stageData(17,{EXECUTE_COMPLETED:'YES',TEN_NEW_CONTEXTS_CREATED:'YES',IDENTICAL_PACKAGE_CONFIRMED_FOR_ALL_RUNS:'YES',OLD_CONVERSATIONS_CONTINUED:'NO',PRIOR_OUTPUTS_WITHHELD:'YES'}),records:{runs:[targetUpdate(slot.runId,{FRESH_CONTEXT_RECORD:slot.contextId,STARTED_AT:`2026-08-25T21:${String(i).padStart(2,'0')}:00Z`,ENDED_AT:`2026-08-25T21:${String(i).padStart(2,'0')}:30Z`,CONTAMINATION_CHECK:'NONE',TOOL_CONFIGURATION:'CONTROLLED',EXECUTION_STATUS:'COMPLETE',COMPLETE_OUTPUT:`corrected-run-${i}-output`,OUTPUT_ARTIFACT_IDENTITIES:'ARTIFACT-CORRECTED',TOOL_FAILURES:'NONE',NOTES:'Fresh corrected run.'})]}},`STAGE-17-RUN-${i+1}`);}
const runs17=engine.recordsForCurrentScope(p,'runs',{iterationId:iteration17});
for(let i=0;i<runs17.length;i++){const runId=engine.recordId(runs17[i],'runs');pr=savePrompt(17,{operation:'VERIFY',scope:{iterationId:iteration17,candidateId:candidate17,runId}});accept(17,pr,{stageData:stageData(17,{VERIFY_COMPLETED:'YES'}),records:{verification:[proposal(`verification-17-${i}`,requiredAgentFields('verification',{VERIFIER:`INDEPENDENT_CORRECTED_VERIFIER_${i}`,VERIFIER_CONTEXT_ID:`VERIFY17-CONTEXT-${i}`,INDEPENDENCE_STATUS:'INDEPENDENT',INPUTS:`${reqId}|${runId}|${testId}`,PROCEDURE:'Execute exact deterministic test on corrected run.',EXPECTED_RESULT:'SATISFIED',OBSERVED_RESULT:'SATISFIED',EXACT_EVIDENCE:`Corrected evidence for ${runId}`,DETERMINATION:'SATISFIED',UNDETERMINED_REASON:''}),{REQ_ID:refId(reqId),RUN_ID:refId(runId),TEST_ID:refId(testId)})]}},`STAGE-17-VERIFY-${i+1}`);}
pr=savePrompt(17,{operation:'COMPARE',scope:{iterationId:iteration17,candidateId:candidate17}});accept(17,pr,{stageData:stageData(17,{COMPARE_COMPLETED:'YES'}),records:{comparisons:[proposal('comparison-17',requiredAgentFields('comparisons',{RUN_DETERMINATIONS:runs17.map(r=>`${engine.recordId(r,'runs')}:SATISFIED`).join('|'),INTERPRETATION_VARIANCE:'NONE',OUTPUT_VARIANCE:'NONE',AUTHORIZED_VARIANCE:'NONE',INCONCLUSIVE_TESTS:'NONE',REPEATED_FAILURE_PATTERNS:'NONE',UNIQUE_FAILURES:'NONE',CORRECTNESS_AFFECTING_VARIANCE:'NONE',DEFECT_IDS:'NONE',EVIDENCE:'All ten corrected runs satisfy the current requirement.'}),{REQ_ID:refId(reqId)})]}},'STAGE-17-COMPARE');
pr=savePrompt(17,{operation:'REGRESSION',scope:{iterationId:iteration17,candidateId:candidate17}});accept(17,pr,{stageData:stageData(17,{REGRESSION_TESTS_ADDED:'NO_NEW_DEFINITION_REQUIRED'}),records:{regressionExecutions:[proposal('reg-exec-post',requiredAgentFields('regressionExecutions',{PHASE:'POST_CORRECTION',RESULT:'SATISFIED'}),{REG_ID:refId(regId),ITERATION_ID:refId(iteration17),CANDIDATE_ID:refId(candidate17),EVIDENCE_ID:refTemp('evidence-1')})]}},'STAGE-17-REGRESSION');
engine.recalculate(p);assertComplete(17);const iteration17Evaluation=engine.evaluateIteration(p,iteration17,'CORRECTED');assert(iteration17Evaluation.matrix.coverage===1,'Stage 17 exact verification coverage must equal 1.0.');assert(iteration17Evaluation.regressionExecutionCount>=1,'Stage 17 must include an actual regression execution.');

const result={continuousLifecycle:'STAGES_01_TO_17',stagesCompleted:17,currentStage:p.job.CURRENT_STAGE,revision:p.revision||0,acceptedDataChanges:p.projectData.acceptedChanges.length,rawResponses:p.projectData.rawResponses.length,stage8EvidenceRelationship:true,stage11InitialBoundary:true,verificationTriples:engine.verificationMatrix(p,iterationId).expected.length,correctedVerificationTriples:iteration17Evaluation.matrix.expected.length,confirmedDefect:defectId,permanentRegression:regId,correctedIteration:iteration17,correctedCandidate:candidate17};
console.log(JSON.stringify(result,null,2));
"""
p.write_text(s.replace(old,new,1))
