from pathlib import Path
p=Path('verify-browser-extra.mjs');s=p.read_text();marker="  console.log('extra:support-controls');"
assert marker in s
block=r"""  console.log('extra:blob-cas-rollback');
  // Actual Blob bytes survive IndexedDB read-back with exact byte identity.
  const blobProject=await activeProject(cdp),blobJob=blobProject.job.JOB_ID,blobText='closed-loop-exact-browser-artifact';
  const blobStored=await evalValue(cdp,`(async()=>{const b=new Blob([${JSON.stringify('closed-loop-exact-browser-artifact')}],{type:'text/plain'});const r=await globalThis.closedLoopProjectStore.putArtifact({artifactId:'ARTIFACT-BROWSER-BLOB',jobId:${JSON.stringify(blobProject.job.JOB_ID)},blob:b,filename:'browser-proof.txt',mediaType:'text/plain',lineage:{proof:'browser'}});const g=await globalThis.closedLoopProjectStore.getArtifact('ARTIFACT-BROWSER-BLOB');return {size:g.byteSize,sha:g.sha256,text:await g.blob.text()};})()`);assert(blobStored.text===blobText&&blobStored.size===new TextEncoder().encode(blobText).byteLength&&/^[0-9a-f]{64}$/.test(blobStored.sha),'Actual artifact Blob bytes did not round-trip exactly through IndexedDB.');

  // Two live tabs cannot overwrite a newer project revision.
  const secondTarget=await getJson(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(`${PAGE_URL}?browserExtraTab2=${Date.now()}`)}`,{method:'PUT'}),cdp2=new CDP(secondTarget.webSocketDebuggerUrl);await cdp2.ready;await cdp2.send('Runtime.enable');await cdp2.send('Page.enable');await waitExpr(cdp2,`globalThis.closedLoopAppReady===true`,20000);const shared=await activeProject(cdp),sharedId=shared.job.JOB_ID,baseRevision=Number(shared.revision||0);const firstWrite=await evalValue(cdp,`(async()=>{const all=await globalThis.closedLoopProjectStore.readAll(),p=all.find(x=>x.job.JOB_ID===${JSON.stringify(shared.job.JOB_ID)});p.job.JOB_TITLE='CAS TAB ONE';return (await globalThis.closedLoopProjectStore.writeProject(p,{expectedProjectRevision:${Number(shared.revision||0)}})).revision;})()`);const staleCode=await evalValue(cdp2,`(async()=>{const all=await globalThis.closedLoopProjectStore.readAll(),p=all.find(x=>x.job.JOB_ID===${JSON.stringify(shared.job.JOB_ID)});p.revision=${Number(shared.revision||0)};p.job.JOB_TITLE='STALE TAB TWO';try{await globalThis.closedLoopProjectStore.writeProject(p,{expectedProjectRevision:${Number(shared.revision||0)}});return 'ACCEPTED';}catch(e){return e.code||e.message;}})()`);assert(firstWrite===baseRevision+1&&staleCode==='STALE_PROJECT_REVISION','Second-tab stale revision was not rejected by compare-and-swap.');const afterConflict=(await projects(cdp)).find(x=>x.job.JOB_ID===sharedId);assert(afterConflict.job.JOB_TITLE==='CAS TAB ONE'&&Number(afterConflict.revision)===firstWrite,'Stale second-tab write changed canonical project state.');cdp2.close();

  // Injected storage failure produces no partial canonical commit.
  const beforeFailure=(await projects(cdp)).find(x=>x.job.JOB_ID===sharedId),beforeFailureHash=beforeFailure.projectSha256,beforeFailureRevision=beforeFailure.revision;const failureCode=await evalValue(cdp,`(async()=>{const all=await globalThis.closedLoopProjectStore.readAll(),p=all.find(x=>x.job.JOB_ID===${JSON.stringify(sharedId)});p.job.JOB_TITLE='MUST NOT COMMIT';globalThis.__closedLoopStorageFault='during-project-write';try{await globalThis.closedLoopProjectStore.writeProject(p,{expectedProjectRevision:p.revision});return 'NO_ERROR';}catch(e){return e.code||e.message;}finally{delete globalThis.__closedLoopStorageFault;}})()`);assert(failureCode==='INJECTED_STORAGE_FAILURE','Injected storage failure did not fail closed.');const afterFailure=(await projects(cdp)).find(x=>x.job.JOB_ID===sharedId);assert(afterFailure.revision===beforeFailureRevision&&afterFailure.projectSha256===beforeFailureHash&&afterFailure.job.JOB_TITLE==='CAS TAB ONE','Injected storage failure partially changed canonical state.');
  // The first tab was intentionally made stale by the CAS test. Reload before exercising normal UI commands.
  await evalValue(cdp,`location.reload();true`);await sleep(450);await waitExpr(cdp,`globalThis.closedLoopAppReady===true`,20000);

"""
s=s.replace(marker,block+marker,1)
s=s.replace("runtimeErrors:0},null,2)","actualBlobPersistence:true,multiTabConflictRejected:true,injectedStorageRollback:true,runtimeErrors:0},null,2)",1)
p.write_text(s)
