from pathlib import Path
import re

# Expose exact async startup state so browser tests wait for the application, not only static DOM.
p=Path('app-core.js');s=p.read_text()
needle="if(globalThis.closedLoopCore)load();else addEventListener('closed-loop-core-ready',load,{once:true});"
replacement="globalThis.closedLoopAppReady=false;globalThis.closedLoopAppError=null;const startClosedLoopApp=()=>load().then(()=>{globalThis.closedLoopAppReady=true;}).catch(error=>{globalThis.closedLoopAppError=String(error?.stack||error);console.error(error);announce('storage failed');});if(globalThis.closedLoopCore)startClosedLoopApp();else addEventListener('closed-loop-core-ready',startClosedLoopApp,{once:true});"
assert needle in s;s=s.replace(needle,replacement,1)
s=s.replace("const next=[p,...projects];persistAll(next);current=p;render();}","const next=[p,...projects];await persistAll(next);current=projects.find(x=>x.job?.JOB_ID===p.job.JOB_ID)||p;render();}",1)
s=s.replace("await savePromptRecord(current.activeStage);save();render();","await savePromptRecord(current.activeStage);await save();render();")
s=s.replace("const record=await savePromptRecord(current.activeStage);save();await navigator.clipboard?.writeText(record.prompt);","const record=await savePromptRecord(current.activeStage);await save();await navigator.clipboard?.writeText(record.prompt);")
p.write_text(s)

# Align the primary browser acceptance with IndexedDB and response-contract v2.
p=Path('verify-browser.mjs');s=p.read_text()
s=s.replace("async function activeProject(cdp){return evalValue(cdp,`JSON.parse(localStorage.getItem('closed-loop-reliability-projects-v4'))[0]`);}","async function allProjects(cdp){return evalValue(cdp,`globalThis.closedLoopProjectStore.readAll()`);}async function activeProject(cdp){return evalValue(cdp,`(async()=>{const id=document.querySelector('#current-project-summary')?.textContent?.split(' · ')[0];const all=await globalThis.closedLoopProjectStore.readAll();return all.find(p=>p.job?.JOB_ID===id)||all[0];})()`);}")
s=s.replace("await waitExpr(cdp,`document.readyState==='complete'`);await waitExpr(cdp,`document.body.innerText.includes('Mobile Closed-Loop Agent Reliability Workbook')`);","await waitExpr(cdp,`document.readyState==='complete'`);await waitExpr(cdp,`globalThis.closedLoopAppReady===true`,20000);assert(!(await evalValue(cdp,`globalThis.closedLoopAppError`)),await evalValue(cdp,`globalThis.closedLoopAppError`));")
s=s.replace("await evalValue(cdp,`localStorage.clear();location.reload();true`);await sleep(450);await waitExpr(cdp,`document.body.innerText.includes('1/30 complete')`);","await waitExpr(cdp,`document.querySelector('#project-picker')?.options.length>=1`,20000);")
s=s.replace("await evalValue(cdp,`location.reload();true`);await sleep(450);await waitExpr(cdp,`document.body.innerText.includes('Mobile Closed-Loop Agent Reliability Workbook')`);","await evalValue(cdp,`location.reload();true`);await sleep(450);await waitExpr(cdp,`globalThis.closedLoopAppReady===true`,20000);",1)
# Complete prompt identity, operation, and scope for the Stage 02 v2 envelope.
s=s.replace("stage:2,promptIdentity:{instructionId:promptRecord.instructionId,sha256:promptRecord.sha256},responseType:","stage:2,operation:promptRecord.operation||'COMPLETE',promptIdentity:{instructionId:promptRecord.instructionId,bodySha256:promptRecord.bodySha256||promptRecord.sha256,contractSha256:promptRecord.contractSha256,contextSignature:promptRecord.contextSignature},scope:promptRecord.scope,responseType:",1)
# Existing project injection now uses the one IndexedDB adapter.
old=re.search(r"const userJob='JOB-BROWSER-LEGITIMATE';await evalValue\(cdp,`\(\(\)=>\{const key='closed-loop-reliability-projects-v4'.*?return true\}\)\(\)`\);await sleep\(450\);await waitExpr\(cdp,`document.body.innerText.includes\('Mobile Closed-Loop Agent Reliability Workbook'\)`\);",s,re.S)
assert old
new="const userJob='JOB-BROWSER-LEGITIMATE';await evalValue(cdp,`(async()=>{const a=await globalThis.closedLoopProjectStore.readAll(),p=structuredClone(a[0]);p.isRetainedTestProject=false;p.retainedSpecRevision='';p.job.JOB_ID='${userJob}';p.job.JOB_TITLE='Legitimate Browser Project';p.revision=0;delete p.projectSha256;p.stages[1].status='NOT STARTED';p.job.CURRENT_STAGE='STAGE 01';p.projectData.sources=[];await globalThis.closedLoopProjectStore.writeAll([...a,p]);location.reload();return true})()`);await sleep(450);await waitExpr(cdp,`globalThis.closedLoopAppReady===true`,20000);"
s=s[:old.start()]+new+s[old.end():]
s=s.replace("const afterNew=JSON.parse(await evalValue(cdp,`localStorage.getItem('closed-loop-reliability-projects-v4')`));const newest=afterNew[0];","const afterNew=await allProjects(cdp);const newest=await activeProject(cdp);")
s=s.replace("const afterBad=JSON.parse(await evalValue(cdp,`localStorage.getItem('closed-loop-reliability-projects-v4')`));","const afterBad=await allProjects(cdp);")
p.write_text(s)

# Align the supplemental browser acceptance with IndexedDB, compressed packages, inline controls, and v2 identity.
p=Path('verify-browser-extra.mjs');s=p.read_text()
s=s.replace("async function projects(cdp){return JSON.parse(await evalValue(cdp,`localStorage.getItem('closed-loop-reliability-projects-v4')`));}\nasync function activeProject(cdp){return (await projects(cdp))[0];}","async function projects(cdp){return evalValue(cdp,`globalThis.closedLoopProjectStore.readAll()`);}\nasync function activeProject(cdp){return evalValue(cdp,`(async()=>{const id=document.querySelector('#current-project-summary')?.textContent?.split(' · ')[0];const all=await globalThis.closedLoopProjectStore.readAll();return all.find(p=>p.job?.JOB_ID===id)||all[0];})()`);}")
s=s.replace("await waitExpr(cdp,`document.readyState==='complete'`);await waitExpr(cdp,`document.body.innerText.includes('Mobile Closed-Loop Agent Reliability Workbook')`);","await waitExpr(cdp,`document.readyState==='complete'`);await waitExpr(cdp,`globalThis.closedLoopAppReady===true`,20000);assert(!(await evalValue(cdp,`globalThis.closedLoopAppError`)),await evalValue(cdp,`globalThis.closedLoopAppError`));")
s=s.replace("await evalValue(cdp,`localStorage.clear();location.reload();true`);await sleep(450);await waitExpr(cdp,`document.body.innerText.includes('1/30 complete')`);","await waitExpr(cdp,`document.querySelector('#project-picker')?.options.length>=1`,20000);")
s=s.replace("stage:2,promptIdentity:{instructionId:pr.instructionId,sha256:pr.sha256},responseType:","stage:2,operation:pr.operation||'COMPLETE',promptIdentity:{instructionId:pr.instructionId,bodySha256:pr.bodySha256||pr.sha256,contractSha256:pr.contractSha256,contextSignature:pr.contextSignature},scope:pr.scope,responseType:",1)
s=s.replace("await evalValue(cdp,`location.reload();true`);await sleep(450);await waitExpr(cdp,`document.body.innerText.includes('Mobile Closed-Loop Agent Reliability Workbook')`);","await evalValue(cdp,`location.reload();true`);await sleep(450);await waitExpr(cdp,`globalThis.closedLoopAppReady===true`,20000);",1)
# Export is a gzip Blob; import the exact bytes and verify round-trip.
old=re.search(r"await evalValue\(cdp,`\(\(\)=>\{window.__exportBlob=null;.*?assert\(all.filter\(p=>p.job\?\.JOB_ID==='JOB-20260823144121'\).length===1,'Successful import duplicated retained project.'\);",s,re.S)
assert old
new="""await evalValue(cdp,`(()=>{window.__exportBlob=null;window.__exportDownload='';URL.createObjectURL=b=>{window.__exportBlob=b;return 'blob:closed-loop-verify';};URL.revokeObjectURL=()=>{};HTMLAnchorElement.prototype.click=function(){window.__exportDownload=this.download;};return true})()`);await click(cdp,'#export-project');await waitExpr(cdp,`Boolean(window.__exportBlob)`,12000);const exportedSize=await evalValue(cdp,`window.__exportBlob.size`);assert(exportedSize>0,'Complete compressed project export was not generated.');await evalValue(cdp,`(async()=>{const input=document.querySelector('#import-file'),dt=new DataTransfer(),bytes=await window.__exportBlob.arrayBuffer();dt.items.add(new File([bytes],'roundtrip.closed-loop.json.gz',{type:'application/gzip'}));input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));return true})()`);await sleep(700);let all=await projects(cdp);const imported=all.find(p=>p.job?.JOB_ID===newest.job.JOB_ID);assert(imported&&Object.keys(imported.stages||{}).length===30,'Successful compressed package round trip lost project data.');assert(all.filter(p=>p.job?.JOB_ID==='JOB-20260823144121').length===1,'Successful import duplicated retained project.');"""
s=s[:old.start()]+new+s[old.end():]
# Inline blocker control replaces prompt().
s=s.replace("await openStage(cdp,1);await evalValue(cdp,`(()=>{window.prompt=message=>message.includes('External fresh-context')?'CTX-BROWSER-FRESH':'Controlled missing human input';return true})()`);await click(cdp,'#add-blocker');","await openStage(cdp,1);await fill(cdp,'#blocker-reason','Controlled missing human input');await click(cdp,'#add-blocker');")
p.write_text(s)
