from pathlib import Path
p=Path('project-store.js'); s=p.read_text()
# Keep explicit-storage methods synchronous for existing deterministic migration/rollback tests,
# while default calls use the IndexedDB implementation.
s=s.replace("async function readAll(storage){if(storage)return readAllLegacy(storage);await migrateLegacy();", "async function readAllIndexed(){await migrateLegacy();")
s=s.replace("return valid;}\n\nasync function writeProject", "return valid;}\nfunction readAll(storage){return storage?readAllLegacy(storage):readAllIndexed();}\n\nasync function writeProject",1)
s=s.replace("async function writeAll(projects,storage){if(storage)return writeAllLegacy(projects,storage);if(!Array.isArray(projects))", "async function writeAllIndexed(projects){if(!Array.isArray(projects))")
s=s.replace("return saved;}\n\nasync function replaceProject", "return saved;}\nfunction writeAll(projects,storage){return storage?writeAllLegacy(projects,storage):writeAllIndexed(projects);}\n\nasync function replaceProjectIndexed",1)
# Replace indexed replace signature/body name and add synchronous legacy wrapper.
s=s.replace("async function replaceProjectIndexed(projectsOrProject,projectOrOptions,storage){\n  if(Array.isArray(projectsOrProject)){const projects=projectsOrProject,project=projectOrOptions;if(storage){const next=clone(projects);const id=projectIdentity(project),i=next.findIndex(x=>projectIdentity(x)===id);if(i<0)next.unshift(clone(project));else next[i]=clone(project);writeAllLegacy(next,storage);return next;}return writeProject(project,{expectedProjectRevision:Number(project?.revision||0)});}\n  return writeProject(projectsOrProject,projectOrOptions||{});\n}", "async function replaceProjectIndexed(projectsOrProject,projectOrOptions){\n  if(Array.isArray(projectsOrProject)){const project=projectOrOptions;return writeProject(project,{expectedProjectRevision:Number(project?.revision||0)});}\n  return writeProject(projectsOrProject,projectOrOptions||{});\n}\nfunction replaceProject(projectsOrProject,projectOrOptions,storage){if(Array.isArray(projectsOrProject)&&storage){const next=clone(projectsOrProject),project=projectOrOptions,id=projectIdentity(project),i=next.findIndex(x=>projectIdentity(x)===id);if(i<0)next.unshift(clone(project));else next[i]=clone(project);writeAllLegacy(next,storage);return next;}return replaceProjectIndexed(projectsOrProject,projectOrOptions);}")
# transact explicit-storage synchronous wrapper.
s=s.replace("async function transact(projectsOrJobId,jobIdOrExpected,mutatorOrOptions,storage){\n  if(Array.isArray(projectsOrJobId)&&storage){const next=clone(projectsOrJobId),id=String(jobIdOrExpected||''),i=next.findIndex(x=>projectIdentity(x)===id);if(i<0)throw new Error(`Project ${id} is not available for transaction.`);const before=clone(next[i]),result=mutatorOrOptions(next[i],before);writeAllLegacy(next,storage);return {projects:next,project:next[i],result};}\n", "async function transactIndexed(projectsOrJobId,jobIdOrExpected,mutatorOrOptions){\n")
s=s.replace("return {project:next,result};\n}\n\nasync function removeProject", "return {project:next,result};\n}\nfunction transact(projectsOrJobId,jobIdOrExpected,mutatorOrOptions,storage){if(Array.isArray(projectsOrJobId)&&storage){const next=clone(projectsOrJobId),id=String(jobIdOrExpected||''),i=next.findIndex(x=>projectIdentity(x)===id);if(i<0)throw new Error(`Project ${id} is not available for transaction.`);const before=clone(next[i]),result=mutatorOrOptions(next[i],before);writeAllLegacy(next,storage);return {projects:next,project:next[i],result};}return transactIndexed(projectsOrJobId,jobIdOrExpected,mutatorOrOptions);}\n\nasync function removeProjectIndexed",1)
s=s.replace("async function removeProjectIndexed(projectsOrJobId,jobIdOrStorage,storage){if(Array.isArray(projectsOrJobId)&&storage){const next=clone(projectsOrJobId).filter(p=>projectIdentity(p)!==String(jobIdOrStorage||''));writeAllLegacy(next,storage);return next;}const jobId=String(projectsOrJobId||'')", "async function removeProjectIndexed(projectsOrJobId){const jobId=String(projectsOrJobId||'')")
s=s.replace("await complete(tx);return true;}\n\nasync function putArtifact", "await complete(tx);return true;}\nfunction removeProject(projectsOrJobId,jobIdOrStorage,storage){if(Array.isArray(projectsOrJobId)&&storage){const next=clone(projectsOrJobId).filter(p=>projectIdentity(p)!==String(jobIdOrStorage||''));writeAllLegacy(next,storage);return next;}return removeProjectIndexed(projectsOrJobId);}\n\nasync function putArtifact",1)
# Legacy key compatibility for verification and external recovery tooling.
s=s.replace("const LEGACY_KEYS=Object.freeze([", "const LEGACY_KEYS=Object.freeze([",1)
s=s.replace("const hash=globalThis.closedLoopHash;", "const STORE_KEY=LEGACY_KEYS[0];\nconst hash=globalThis.closedLoopHash;",1)
s=s.replace("stores:Object.freeze({projects:PROJECTS,artifacts:ARTIFACTS,meta:META}),LEGACY_KEYS,", "stores:Object.freeze({projects:PROJECTS,artifacts:ARTIFACTS,meta:META}),STORE_KEY,LEGACY_KEYS,",1)
p.write_text(s)
