from pathlib import Path
import re

p=Path('workflow-engine.js');s=p.read_text()
# Enforce the result of the one schema mutation-authorization function for human/human-decision fields.
match=re.search(r"function recordHumanDecision\(project,.*?\n\}\nfunction invalidateAcceptedResponse",s,re.S)
assert match
replacement=r'''function recordHumanDecision(project,{stage,field,value,operatorLabel='HUMAN_OPERATOR',reason='Explicit human authority input.'}={}){
  ensureShape(project);const number=Number(stage),definition=schema.STAGE_FIELDS?.[number]?.[field];if(!definition)throw new Error(`Unknown Stage ${number} field ${field}.`);
  const actor=definition.producer;const authorization=schema.authorizeMutation({fieldDefinition:definition,actor,mutationType:'SET'});if(authorization===false||authorization?.authorized===false||authorization?.allowed===false)throw new Error(authorization?.reason||`Mutation of ${field} is not authorized for ${actor}.`);
  if(!['HUMAN','HUMAN_DECISION'].includes(String(actor)))throw new Error(`${field} is not human authority.`);project.stages[number].humanData[field]=clone(value);
  const history=addHistory(project,'HUMAN_DECISION_RECORDED',{stage:number,field,value:clone(value),operatorLabel,identityAssurance:'SELF_ASSERTED',reason});const record={decisionId:allocateInfrastructureId(project,'HUMAN-DECISION','humanDecisions'),stage:number,field,value:clone(value),operatorLabel,identityAssurance:'SELF_ASSERTED',reason,eventSequence:history.eventSequence,deviceTimestamp:history.deviceTimestamp,createdAt:history.deviceTimestamp};project.projectData.humanDecisions=safe(project.projectData.humanDecisions);project.projectData.humanDecisions.push(record);return record;
}
function invalidateAcceptedResponse'''
s=s[:match.start()]+replacement+s[match.end():]

# Replace request-only freeze stubs with canonical application-controlled freezes.
old="function freezeCandidate(project,options={}){addHistory(project,'CANDIDATE_FREEZE_REQUESTED',{stage:10,...clone(options)});return options;}\nfunction freezeBaseline(project,options={}){addHistory(project,'BASELINE_FREEZE_REQUESTED',{stage:20,...clone(options)});return options;}"
assert old in s
new=r'''function selectedArtifacts(project,artifactIds){const ids=[...new Set(safe(artifactIds).map(String))],items=records(project,'artifacts',{active:true}).filter(a=>ids.includes(recordId(a,'artifacts')));if(items.length!==ids.length)throw new Error('Every selected artifact must resolve to one active canonical artifact.');for(const a of items)if(upper(recordValue(a,'AVAILABILITY'))!=='BYTES_PERSISTED_AND_VERIFIED'||!recordValue(a,'SHA256')||!Number.isFinite(Number(recordValue(a,'BYTE_SIZE'))))throw new Error(`Artifact ${recordId(a,'artifacts')} does not have verified stored bytes.`);return items;}
function freezeCandidate(project,{artifactIds=[],operatorLabel='HUMAN_OPERATOR',purpose='TEST_CANDIDATE',toolConfiguration='CURRENT AUTHORIZED CONFIGURATION',settings='CURRENT AUTHORIZED SETTINGS',permissions='CURRENT AUTHORIZED PERMISSIONS',limitations='RECORDED LIMITATIONS',roleDistribution='WORKFLOW ROLE MAP',batchChangeRule='ANY MATERIAL CHANGE REQUIRES A NEW CANDIDATE'}={}){
  ensureShape(project);const artifacts=selectedArtifacts(project,artifactIds);if(!artifacts.length)throw new Error('At least one verified artifact is required to freeze a candidate.');const iterationId=allocateId(project,'iterations'),candidateId=allocateId(project,'candidateFreezes'),manifest=artifacts.map(a=>({artifactId:recordId(a,'artifacts'),filename:recordValue(a,'FILENAME'),byteSize:Number(recordValue(a,'BYTE_SIZE')),sha256:recordValue(a,'SHA256'),storageReference:recordValue(a,'STORAGE_REFERENCE')})),componentHashes=Object.fromEntries(manifest.map(a=>[a.artifactId,a.sha256])),createdAt=now();
  const iterationFields={ITERATION_ID:iterationId,CANDIDATE_ID:candidateId,PREVIOUS_ITERATION_ID:recordId(recordsForCurrentScope(project,'iterations').at(-1),'iterations')||'',CHANGESET_ID:recordId(recordsForCurrentScope(project,'changes').at(-1),'changes')||'',PURPOSE:purpose,STATUS:'FROZEN',LINEAGE:hash.sha256Value(manifest),EVIDENCE:`Application freeze from ${manifest.length} verified artifact(s).`};const iteration={id:iterationId,stage:10,createdAt,active:true,scope:currentScope(project),fields:iterationFields,...iterationFields,source:'APPLICATION_DERIVATION'};iteration.contentSha256=hash.contentRecordSha256(iteration,'ITERATION_ID');iteration.recordSha256=hash.recordSha256(iteration);iteration.sha256=iteration.recordSha256;
  const candidateFields={CANDIDATE_ID:candidateId,ITERATION_ID:iterationId,COMPONENT_MANIFEST:manifest,COMPONENT_VERSIONS:Object.fromEntries(manifest.map(a=>[a.artifactId,'APPLICATION-CONTROLLED'])),COMPONENT_HASHES:componentHashes,ROLE_DISTRIBUTION:roleDistribution,IMMUTABLE_LOCATIONS:manifest.map(a=>a.storageReference),TOOL_CONFIGURATION:toolConfiguration,SETTINGS:settings,PERMISSIONS:permissions,LIMITATIONS:limitations,BATCH_CHANGE_RULE:batchChangeRule,STATUS:'FROZEN',EVIDENCE:hash.sha256Value({manifest,operatorLabel})};const candidate={id:candidateId,stage:10,createdAt,active:true,scope:{...currentScope(project),iterationId,candidateId},fields:candidateFields,...candidateFields,source:'APPLICATION_DERIVATION'};candidate.contentSha256=hash.contentRecordSha256(candidate,'CANDIDATE_ID');candidate.recordSha256=hash.recordSha256(candidate);candidate.sha256=candidate.recordSha256;project.projectData.iterations.push(iteration);project.projectData.candidateFreezes.push(candidate);project.job.CURRENT_ITERATION=iterationId;addHistory(project,'CANDIDATE_FROZEN',{stage:10,iterationId,candidateId,artifactIds:manifest.map(a=>a.artifactId),operatorLabel,identityAssurance:'SELF_ASSERTED'});recalculate(project);return {iteration,candidate};
}
function freezeBaseline(project,{artifactIds=[],operatorLabel='HUMAN_OPERATOR',authorization='AUTHORIZED'}={}){
  ensureShape(project);const confirmation=recordsForCurrentScope(project,'confirmationRecords').filter(r=>upper(recordValue(r,'DETERMINATION'))==='SATISFIED').at(-1);if(!confirmation)throw new Error('A current successful unchanged confirmation is required before baseline freeze.');const artifacts=selectedArtifacts(project,artifactIds);if(!artifacts.length)throw new Error('At least one verified artifact is required to freeze a baseline.');const baselineId=allocateId(project,'baselines'),createdAt=now(),approvedVersions={inputVersion:project.job.CURRENT_INPUT_VERSION,sourceSetVersion:project.job.CURRENT_SOURCE_SET_VERSION,requirementsVersion:project.job.CURRENT_REQUIREMENTS_VERSION,testSuiteVersion:project.job.CURRENT_TEST_SUITE_VERSION,instructionVersion:project.job.CURRENT_INSTRUCTION_VERSION,iterationId:project.job.CURRENT_ITERATION,candidateId:recordId(recordsForCurrentScope(project,'candidateFreezes').at(-1),'candidateFreezes')},hashes:Object.fromEntries(artifacts.map(a=>[recordId(a,'artifacts'),recordValue(a,'SHA256')]));const fields={BASELINE_ID:baselineId,SUPPORTING_CONFIRMATION_ID:recordId(confirmation,'confirmationRecords'),APPROVED_VERSIONS:approvedVersions,IMMUTABLE_ARTIFACT_RECORDS:artifacts.map(a=>recordId(a,'artifacts')),HASHES:approvedVersions.hashes,HUMAN_AUTHORIZATION:authorization,AUTHORIZED_RECIPIENT_ROLES:'CURRENT AUTHORIZED ROLES',CONTROLLED_STORAGE:'INDEXEDDB VERIFIED BYTES',STATUS:'FROZEN',EVIDENCE:hash.sha256Value({approvedVersions,operatorLabel})};const record={id:baselineId,stage:20,createdAt,active:true,scope:{...currentScope(project),baselineId},fields,...fields,source:'APPLICATION_DERIVATION'};record.contentSha256=hash.contentRecordSha256(record,'BASELINE_ID');record.recordSha256=hash.recordSha256(record);record.sha256=record.recordSha256;project.projectData.baselines.push(record);project.job.CURRENT_BASELINE_ID=baselineId;addHistory(project,'BASELINE_FROZEN',{stage:20,baselineId,artifactIds:fields.IMMUTABLE_ARTIFACT_RECORDS,operatorLabel,identityAssurance:'SELF_ASSERTED'});recalculate(project);return record;
}
function reserveProductExecution(project,{operatorLabel='HUMAN_OPERATOR'}={}){ensureShape(project);const baseline=recordsForCurrentScope(project,'baselines').at(-1);if(!baseline)throw new Error('A current frozen baseline is required.');const contexts=recordsForCurrentScope(project,'freshContexts').filter(r=>!recordValue(r,'RUN_ID')),context=contexts.at(-1);if(!context)throw new Error('A current fresh production context is required.');const productId=allocateId(project,'products'),executionId=allocateInfrastructureId(project,'EXECUTION','products'),createdAt=now(),fields={PRODUCT_ID:productId,PRODUCT_VERSION:'PRODUCT-v001',BASELINE_ID:recordId(baseline,'baselines'),EXECUTION_ID:executionId,PRODUCTION_CONTEXT_ID:recordId(context,'freshContexts'),INSTRUCTION_VERSION:project.job.CURRENT_INSTRUCTION_VERSION,BASELINE_MATERIALS:recordValue(baseline,'IMMUTABLE_ARTIFACT_RECORDS')||[],EXECUTION_TIMESTAMPS:{reservedAt:createdAt},TOOL_CONFIGURATION:'PENDING AGENT COMPLETION',DEVIATIONS:'NONE RECORDED',FAILURES:'NONE RECORDED',GENERATED_ARTIFACT_INVENTORY:[],STATUS:'RESERVED'};const record={id:productId,stage:21,createdAt,active:true,reserved:true,completionState:'AWAITING_AGENT_COMPLETION',scope:{...currentScope(project),baselineId:fields.BASELINE_ID,productId},fields,...fields,source:'APPLICATION_RESERVED'};record.contentSha256=hash.contentRecordSha256(record,'PRODUCT_ID');record.recordSha256=hash.recordSha256(record);record.sha256=record.recordSha256;project.projectData.products.push(record);project.job.CURRENT_PRODUCT_ID=productId;addHistory(project,'PRODUCT_EXECUTION_RESERVED',{stage:21,productId,executionId,contextId:fields.PRODUCTION_CONTEXT_ID,operatorLabel,identityAssurance:'SELF_ASSERTED'});recalculate(project);return record;}
function createNewJobReset(project){ensureShape(project);const id=allocateInfrastructureId(project,'NEW-JOB-RESET','newJobResets'),createdAt=now(),fields={NEW_JOB_ID:project.job.JOB_ID,OLD_JOB_MATERIAL_REUSED:'FALSE',AUTHORIZED_REUSED_ARTIFACTS:'NONE',NEW_JOB_START_STAGE:'STAGE 01',RESET_COMPLETED_BY:'APPLICATION',RESET_DATE_AND_TIME:createdAt,RESET_EVIDENCE:'A clean 30-stage project was created without carrying active state from another job.'},record={id,stage:1,createdAt,active:true,fields,...fields,source:'APPLICATION_DERIVATION'};record.sha256=hash.sha256Value(fields);project.projectData.newJobResets.push(record);addHistory(project,'NEW_JOB_RESET_RECORDED',{stage:1,recordId:id});return record;}
'''
s=s.replace(old,new,1)
anchor='createHumanBlocker,registerFreshContext,recordHumanDecision,invalidateAcceptedResponse,reserveRunBatch,registerArtifactBytes,freezeCandidate,freezeBaseline,'
assert anchor in s
s=s.replace(anchor,'createHumanBlocker,registerFreshContext,recordHumanDecision,invalidateAcceptedResponse,reserveRunBatch,registerArtifactBytes,freezeCandidate,freezeBaseline,reserveProductExecution,createNewJobReset,',1)
p.write_text(s)

p=Path('app-core.js');s=p.read_text()
# Route human stage writes through the engine command.
match=re.search(r"async function saveHumanStageFields\(\)\{.*?\}\nasync function saveHumanAnswers",s,re.S)
assert match
replacement=r'''async function saveHumanStageFields(){const next=clone(current),stage=next.activeStage,changed=[];for(const x of document.querySelectorAll('[data-human-stage-field]')){const field=x.dataset.humanStageField,value=x.value;if(next.stages[stage].humanData[field]!==value){engine.recordHumanDecision(next,{stage,field,value,operatorLabel:$('#operator-label')?.value.trim()||'HUMAN_OPERATOR'});changed.push(field);}}if(changed.length){engine.recordHumanInputVersion(next,changed.map(x=>`STAGE_${stage}:${x}`),'HUMAN_OPERATOR');if(current.stages[stage].status==='COMPLETE'){const id=engine.allocateInfrastructureId(next,'HUMAN-STAGE-CHANGE','changes');engine.invalidateDownstream(next,stage,id,'Human-owned stage input changed after completion.');}await persistReplacement(next);}render();}
async function saveHumanAnswers'''
s=s[:match.start()]+replacement+s[match.end():]
# Focus the first invalid typed answer.
s=s.replace("}catch(error){alert(error.message||error);}}\nasync function confirmStageOne", "}catch(error){const target=error?.requestId?document.querySelector(`[data-human-answer=\"${CSS.escape(error.requestId)}\"]`):null;target?.focus();alert(error.message||error);}}\nasync function confirmStageOne",1)
# Validation report is focusable.
s=s.replace("return `<div class=\"notice danger\"><strong>Response rejected before canonical mutation.</strong>","return `<div class=\"notice danger\" id=\"validation-report\" tabindex=\"-1\"><strong>Response rejected before canonical mutation.</strong>",1)
# Engine-owned new-job reset.
match=re.search(r"async function addNew\(\)\{.*?\}\nasync function load",s,re.S)
assert match
replacement=r'''async function addNew(){const p=ensureState(core.createBlankState(createUniqueJobId()));p.job.DATE_OPENED=new Date().toISOString();p.activeView='Project';engine.createNewJobReset(p);const next=[p,...projects];await persistAll(next);current=projects.find(x=>x.job?.JOB_ID===p.job.JOB_ID)||p;render();}
async function load'''
s=s[:match.start()]+replacement+s[match.end():]
# Reusable artifact, run-batch, and provenance controls.
insert='function workflow(){'
assert insert in s
components=r'''function selectedArtifactIds(stage=current.activeStage){return safe(current.stages[stage]?.authorizedFiles).map(x=>String(x.artifactId||x.id||'')).filter(Boolean);}
function artifactControlMarkup(n,locked){const applicable=[10,20,21,25,28].includes(n),files=safe(current.stages[n].authorizedFiles);return `<div class="panel"><h2 class="section-title">${applicable?'Artifact control':'Authorized files for this stage'}</h2><p class="section-intro">Actual selected bytes are stored in IndexedDB, hashed by the application, read back, and rehashed before becoming canonical artifact identities.</p><div class="field"><label>Select exact files</label><input id="stage-files" type="file" multiple${locked?' disabled':''}></div>${files.length?details('Verified artifact bytes',files,true):'<div class="empty-state">No verified stage artifact bytes.</div>'}<div class="button-row">${n===10?`<button id="freeze-candidate"${locked?' disabled':''}>Freeze selected candidate</button>`:''}${n===20?`<button id="freeze-baseline"${locked?' disabled':''}>Freeze selected baseline</button>`:''}${n===21?`<button id="reserve-product-execution"${locked?' disabled':''}>Reserve product execution</button>`:''}</div></div>`;}
function runBatchMarkup(n){if(![11,12,17,19].includes(n))return '';const runs=engine.records(current,'runs').filter(r=>Number(r.stage)===n||String(recordValue(r,'ITERATION_ID')||'')===String(current.job.CURRENT_ITERATION||'')),rows=runs.map(r=>({RUN_ID:engine.recordId(r,'runs'),CONTEXT_ID:recordValue(r,'CONTEXT_ID'),ITERATION_ID:recordValue(r,'ITERATION_ID'),CANDIDATE_ID:recordValue(r,'CANDIDATE_ID'),operation:r.operation||'EXECUTE_RUN',promptIdentity:r.promptInstructionId||r.currentPromptId||'NOT YET GENERATED',rawResponseStatus:r.rawResponseStatus||'NOT RECEIVED',validationStatus:r.validationStatus||'NOT VALIDATED',proposalStatus:r.proposalStatus||'NONE',acceptedStatus:r.completionState||r.EXECUTION_STATUS||'RESERVED',receipt:r.receiptId||'NONE'}));return `<div class="panel"><h2 class="section-title">Run batch</h2>${rows.length?details('Application-reserved run/context slots',rows,true):'<div class="empty-state">No run batch has been reserved.</div>'}</div>`;}
function provenanceMarkup(n){const manifests=safe(current.projectData.extractionManifests).filter(m=>Number(m.stage)===n),rows=manifests.flatMap(m=>safe(m.entries||m.changes).map(e=>({canonicalField:`${e.canonicalCollection||e.canonicalRecordType||''}/${e.canonicalRecordId||''}/${e.canonicalField||''}`,manifestId:m.manifestId,responsePointer:e.jsonPointer||e.JSON_POINTER_IN_RESPONSE||'',rawResponseId:m.rawResponseId||m.RAW_RESPONSE_ID,promptId:m.promptId||m.PROMPT_ID,evidenceIds:e.evidenceIds||[]})));return rows.length?`<div class="panel"><h2 class="section-title">Provenance navigation</h2><p class="section-intro">Canonical field → extraction manifest → response JSON pointer → raw response → controlling prompt → evidence.</p>${details('Traceable accepted values',rows)}</div>`:'';}
'''
s=s.replace(insert,components+insert,1)
# Replace the stage's one-off file panel with the shared component and add run/provenance components.
pattern=r"\$\{acceptedStageMarkup\(n\)\}<div class=\"panel\"><h2 class=\"section-title\">Authorized files for this stage</h2>.*?</div>\$\{controls\(d,locked\)\}`;\}"
match=re.search(pattern,s,re.S)
assert match
replacement='${acceptedStageMarkup(n)}${artifactControlMarkup(n,locked)}${runBatchMarkup(n)}${provenanceMarkup(n)}${controls(d,locked)}`;}'
s=s[:match.start()]+replacement+s[match.end():]
# Wire engine-owned freeze/reservation commands.
needle="if($('#reserve-run-batch'))$('#reserve-run-batch').onclick=reserveRunBatch;"
assert needle in s
addition=needle+"if($('#freeze-candidate'))$('#freeze-candidate').onclick=async()=>{try{const next=clone(current);engine.freezeCandidate(next,{artifactIds:selectedArtifactIds(),operatorLabel:$('#operator-label')?.value.trim()||'HUMAN_OPERATOR'});await persistReplacement(next);announce('saved');render();}catch(error){alert(error.message||error);}};if($('#freeze-baseline'))$('#freeze-baseline').onclick=async()=>{try{const next=clone(current);engine.freezeBaseline(next,{artifactIds:selectedArtifactIds(),operatorLabel:$('#operator-label')?.value.trim()||'HUMAN_OPERATOR'});await persistReplacement(next);announce('saved');render();}catch(error){alert(error.message||error);}};if($('#reserve-product-execution'))$('#reserve-product-execution').onclick=async()=>{try{const next=clone(current);engine.reserveProductExecution(next,{operatorLabel:$('#operator-label')?.value.trim()||'HUMAN_OPERATOR'});await persistReplacement(next);announce('saved');render();}catch(error){alert(error.message||error);}};"
s=s.replace(needle,addition,1)
p.write_text(s)
