from pathlib import Path

p=Path('prompt-engine.js')
s=p.read_text()

def rep(old,new):
    global s
    n=s.count(old)
    if n!=1: raise SystemExit(f'Expected exactly one procedure text; found {n}: {old[:120]!r}')
    s=s.replace(old,new,1)

rep("4:'Compile atomic requirements for this current job from authorized User Job Input plus legitimately applicable Stage 03 external-source research, preserving provenance for each obligation. Propose one independently testable obligation per requirement where possible and record type, mandatory/optional status, governing source or user-input relationship, exact source location when applicable, authority, applicability, dependencies, prohibitions, defined terms, observable satisfaction condition, intended verification method, expected evidence, failure condition, severity, and notes. The application assigns REQ_ID and controlled requirement-set version. Do not derive requirements from the target product or an existing implementation merely because that implementation contains a behavior.',",
"4:'Compile atomic requirements for this current job from authorized User Job Input plus legitimately applicable Stage 03 external-source research, preserving provenance for each obligation. Propose one independently testable obligation per requirement where possible and record type, mandatory/optional status, external-source or user-input provenance, exact source location when applicable, authority or evidentiary role, applicability, dependencies, prohibitions, defined terms, observable satisfaction condition, intended verification method, expected evidence, failure condition, severity, and notes. The application assigns REQ_ID and controlled requirement-set version. Do not derive requirements from the target product or an existing implementation merely because that implementation contains a behavior.',")
rep("5:'Resolve the current job’s requirement set. Detect duplicate or conflicting requirements, impossible combinations, undefined terms, circular dependencies, missing prerequisites, unsupported requirements, uncertain applicability, and requirements lacking a verification method. Preserve the substantive defect, governing evidence, proposed resolution or unresolved state, affected requirement, and blockers. Human authority decides genuine user tradeoffs; the application owns controlled versions and downstream invalidation. Never silently guess away a conflict or manufacture authority.',",
"5:'Resolve the current job’s requirement set. Detect duplicate or conflicting requirements, impossible combinations, undefined terms, circular dependencies, missing prerequisites, unsupported requirements, uncertain applicability, and requirements lacking a verification method. Preserve the substantive defect, controlling or evidentiary basis, proposed resolution or unresolved state, affected requirement, and blockers. Human authority decides genuine user tradeoffs; the application owns controlled versions and downstream invalidation. Never silently guess away a conflict or manufacture authority.',")
rep("8:'Author this job’s production instruction only from the resolved current requirement set and verification architecture. Define objective, authorized inputs, authority rules, failure handling, scope, prohibitions, defined terms, ordered procedure, branches, tool requirements, output contract, TRUE/FALSE/UNKNOWN handling, rejection/blocking rules, completion conditions, and requirement traceability. Do not copy or imitate an existing target implementation as authority. Do not turn this job’s production instruction into a reusable instruction for unrelated jobs unless the current user input explicitly requires such a deliverable. The application assigns the controlled instruction version after accepted ingestion.',",
"8:'Author this job’s production instruction only from the resolved current requirement set and verification architecture. Define objective, authorized inputs, authority rules, failure handling, scope, prohibitions, defined terms, ordered procedure, branches, tool requirements, output contract, TRUE/FALSE/UNKNOWN handling, rejection/blocking rules, completion conditions, and requirement traceability. Adapt the procedure to the actual domain, artifact types, toolchain, and scale rather than assuming a prose-only deliverable. For multi-file or tool-generated work, define exact artifacts, filenames or logical components, interfaces, dependencies, required tools, transformations, and verification. Do not copy or imitate an existing target implementation as authority. Do not turn this job’s production instruction into a reusable instruction for unrelated jobs unless the current user input explicitly requires such a deliverable. The application assigns the controlled instruction version after accepted ingestion.',")
rep("9:'Preflight this job’s production instruction in an independent context where required. Review each material clause for multiple interpretations, undefined objects, unsupplied dependencies, internal conflicts, unavailable capabilities, objective verifiability, responsible operation, ordering, defined failure behavior, and traceability. Preserve findings and evidence. If correction is required, identify the exact correction; the application controls versioning and repeated-review state. Do not execute target production during preflight.',",
"9:'Preflight this job’s production instruction in an independent context where required. Review each material clause for multiple interpretations, undefined objects, unsupplied dependencies, internal conflicts, unavailable capabilities, objective verifiability, responsible operation, ordering, defined failure behavior, domain/toolchain completeness, and traceability. Preserve findings and evidence. If correction is required, identify the exact correction; the application controls versioning and repeated-review state. Do not execute target production during preflight.',")
rep("10:'Review the exact candidate freeze for this job and iteration. The human selects authorized canonical components and the application assigns CANDIDATE_ID and ITERATION_ID, freezes the exact component manifest, and calculates hashes from verified bytes. Preserve substantive observations about role distribution, immutable locations, tool configuration, settings, permissions, and limitations. The agent must not invent or assign candidate identity, versions, hashes, or lifecycle state. The same candidate package must be used unchanged across the ten-run batch.',",
"10:'Review the exact candidate freeze for this job and iteration. The human selects authorized canonical components and the application assigns CANDIDATE_ID and ITERATION_ID, freezes the exact component manifest, and calculates hashes from verified bytes. Report substantive observations about component completeness, role distribution, immutable locations, tool configuration, settings, permissions, limitations, and whether the candidate can actually be executed unchanged. Do not assign candidate identity, versions, hashes, or lifecycle state. The same candidate package must be used unchanged across the ten-run batch.',")
rep("11:'Run exactly ten independent executions for this job using the identical frozen candidate in ten fresh contexts. For each application-reserved RUN_ID, report the actual execution observations, contamination state, tool configuration, complete output, tool failures, and evidence. The application owns run/context IDs, timestamps, lifecycle state, and hashes calculated from actual bytes. Runs may not see another run’s output, reviewer comments, prior failure explanations, or proposed corrections. Never select a preferred run to discard the others.',",
"11:'Run the application-reserved ten independent execution targets using the identical frozen candidate in fresh contexts. For each supplied RUN_ID and CONTEXT_ID, perform only that exact execution lane and report contamination state, tool configuration, complete output, actual tool failures, substantive output observations, and evidence. Echo application-reserved target identities exactly; do not create replacements. The application owns run/context identities, canonical timestamps, lifecycle state, artifact identities, byte sizes, and hashes. Runs may not see another run’s output, reviewer comments, prior failure explanations, or proposed corrections. Never select a preferred run to discard the others.',")
rep("12:'Verify each of this job’s ten executions independently. Create exactly one current applicable verification record for every required REQ_ID × RUN_ID × TEST_ID triple. Preserve verifier and verifier-context identity, independence status, inputs, procedure, expected result, observed result, exact evidence, substantive determination, defect reference where applicable, and reason for UNDETERMINED. Do not omit, duplicate, substitute wrong-version/wrong-iteration records, or self-validate. The application reconciles matrix counts and completeness mathematically.',",
"12:'Verify each current execution independently. Produce one substantive verification proposal for every required REQ_ID × RUN_ID × TEST_ID triple in the current operation scope, preserving verifier and verifier-context identity, independence status, inputs, procedure, expected result, observed result, exact evidence, SATISFIED/VIOLATED/UNDETERMINED, defect reference where applicable, and reason for UNDETERMINED. Do not omit or duplicate required triples, substitute wrong-version or wrong-iteration records, or self-validate. The application reconciles matrix counts and completeness mathematically.',")
rep("17:'After a material upstream correction, execute the declared Stage 17 operation against the new application-assigned iteration and candidate. Use ten new independent contexts for execution, withhold prior outputs, use one identical corrected candidate package across all ten runs, and perform verification, comparison, RCA, regression execution, and any required correction through the declared operation subcontracts. Do not invent iteration, candidate, run, or context identities.',",
"17:'After a material upstream correction, perform only the declared Stage 17 operation against the application-assigned corrected iteration and candidate. Use the exact supplied iteration, candidate, run, and context identities where the operation requires them. Execute ten new independent contexts across the batch, withhold prior outputs, use one identical corrected candidate package, and perform verification, comparison, RCA, regression execution, and any required correction through the declared operation subcontracts. Do not invent iteration, candidate, run, or context identities.',")
rep("19:'After convergence, perform the declared unchanged-confirmation operations using the exact converged component versions and hashes with zero material changes. Use ten new independent contexts, rerun the complete verification matrix and applicable regression suite, compare all runs, and report any new defect, missed requirement, missed failure case, or correctness-affecting variance. The application owns iteration/run/context identities and evaluates unchanged-confirmation completion.',",
"19:'After convergence, perform only the declared unchanged-confirmation operations using the exact application-supplied converged component versions and hashes with zero material changes. Use the supplied new run/context identities, rerun the complete verification matrix and applicable regression suite across ten new independent contexts, compare all runs, and report any new defect, missed requirement, missed failure case, or correctness-affecting variance. The application evaluates unchanged-confirmation completion and owns iteration/run/context identity.',")
rep("21:'Produce the job’s finished deliverable only when the actual authorized execution environment can do so reliably from the approved baseline. The application itself does not connect to or modify an external repository. If implementation depends on repository, runtime, account, network, deployment, or other execution access absent from the authorized environment, do not claim implementation or fabricate product bytes; provide the complete implementation-ready specification or patch plan when that satisfies the feasible deliverable, or return the appropriate BLOCKED or EXECUTION_FAILED disposition. For a self-contained deliverable that can actually be generated here, use a fresh production context and only approved baseline materials. The application assigns PRODUCT_ID and execution identity and is authoritative for actual file bytes, filenames, media types, sizes, hashes, storage references, and lineage after bytes are persisted and verified.',",
"21:'Produce the job’s approved deliverable only when the actual authorized execution environment can do so reliably from the approved baseline. For self-contained work that can be generated here, create the complete deliverable and every required artifact. For repository, CAD/CAM, simulation, build, deployment, manufacturing, or other tool-dependent work, use those capabilities only when the external execution context actually provides the required tools and access; otherwise do not claim implementation or fabrication occurred and instead produce the complete implementation-ready or manufacturing-ready specification or patch plan required by the approved deliverable mode, or return the appropriate BLOCKED/EXECUTION_FAILED disposition. The application itself does not connect to or modify an external repository. Use a fresh production context and only approved baseline materials. The application assigns PRODUCT_ID and execution identity and is authoritative for persisted file bytes, filenames, media types, sizes, hashes, storage references, and lineage.',")
rep("22:'Perform the substantive deterministic verification work that is actually supported against the finished product and report procedures, expected results, actual observed results, evidence, and defects. Objective artifact identities, byte sizes, cryptographic hashes, expected test-set completeness, counts, and final gate calculations are application-owned. Never claim an unexecuted deterministic check ran.',",
"22:'Perform the substantive deterministic verification work that is actually supported against the finished product and report procedures, expected results, actual observed results, evidence, and defects. Use specialized deterministic tools when the authorized execution context provides them. Objective artifact identities, byte sizes, cryptographic hashes, expected test-set completeness, counts, and final gate calculations are application-owned. Never claim an unexecuted deterministic check ran.',")
rep("23:'Perform independent meaning/content verification on this job’s actual finished product where deterministic checks cannot establish substantive satisfaction. For each applicable requirement preserve requirement identity, product location, external-source evidence where applicable, required meaning, observed meaning, evidence-based comparison, SATISFIED/VIOLATED/UNDETERMINED, defect, and reason a determination could not be made. Use human-facing terminology such as Meaning Verification or Content Verification.',",
"23:'Perform independent meaning/content verification on this job’s actual finished product where deterministic checks cannot establish substantive satisfaction. For each applicable requirement preserve requirement identity, product location, external-source evidence where applicable, required meaning, observed meaning, evidence-based comparison, SATISFIED/VIOLATED/UNDETERMINED, defect, and reason a determination could not be made. For engineering artifacts, meaning review includes whether dimensions, tolerances, interfaces, notes, symbols, manufacturing intent, and other human-interpreted meaning communicate the required design unambiguously. Use human-facing terminology such as Meaning Verification or Content Verification.',")
rep("25:'Inspect the exact final delivered representation and package. Report substantive rendering/opening observations, clipping, missing or blank content, broken layout, graphics, font substitution, overlap, hidden content, ordering, export corruption, package problems, defects, and irreducible human/reviewer judgments. The application derives filenames, canonical artifact inventory, byte sizes, SHA-256 values, and other objective file facts from actual stored bytes; do not overwrite those facts.',",
"25:'Inspect the exact final delivered representation and package. Report substantive rendering/opening observations, clipping, missing or blank content, broken layout, graphics, font substitution, overlap, hidden content, ordering, export corruption, package problems, defects, and irreducible human/reviewer judgments. For drawings, CAD/CAM, CNC, and additive-manufacturing artifacts, inspect every required view/representation and verify that human-visible units, scales, datums/coordinates, dimensions/tolerances, notes, revision identifiers, and manufacturing information are present and coherent where applicable. The application derives filenames, canonical artifact inventory, byte sizes, SHA-256 values, and other objective file facts from actual stored bytes; do not overwrite those facts.',")
p.write_text(s)

# Semantic acceptance: prevent these specific regressions from returning.
p=Path('verify-prompt-semantics.mjs'); t=p.read_text(); marker='// Specialist stage-procedure regression checks.'
if marker not in t:
    t += r'''

// Specialist stage-procedure regression checks.
{
 const p=baseProject();
 const checks=[
  [8,['actual domain, artifact types, toolchain, and scale','multi-file or tool-generated work']],
  [9,['domain/toolchain completeness']],
  [10,['component completeness','executed unchanged']],
  [11,['RUN_ID and CONTEXT_ID','exact execution lane']],
  [12,['current operation scope']],
  [17,['exact supplied iteration, candidate, run, and context identities']],
  [19,['supplied new run/context identities']],
  [21,['repository, CAD/CAM, simulation, build, deployment, manufacturing']],
  [22,['specialized deterministic tools']],
  [23,['dimensions, tolerances, interfaces','manufacturing intent']],
  [25,['datums/coordinates','dimensions/tolerances','manufacturing information']]
 ];
 for(const [stage,needles] of checks){const q=prompts.buildPromptRecord(stage,p).prompt;for(const needle of needles)if(!q.includes(needle))throw new Error(`Stage ${stage} lost specialist prompt semantics: ${needle}`);}
}
'''
    p.write_text(t)
