from pathlib import Path
import hashlib,re

def patch(path, old, new, count=1):
    p=Path(path); s=p.read_text(); n=s.count(old)
    if n!=count: raise SystemExit(f'{path}: expected {count} exact match(es), found {n}: {old[:140]!r}')
    p.write_text(s.replace(old,new,count))

# 1) Keep the existing TEST record; add only application-owned custody of verified test-artifact bytes.
patch('workflow-schema.js',
'''    "application": [\n      "TEST_ID",\n      "REQ_ID",\n      "STATUS"\n    ]\n  },\n  "failureTests"''',
'''    "application": [\n      "TEST_ID",\n      "REQ_ID",\n      "TEST_ARTIFACT_IDS",\n      "STATUS"\n    ]\n  },\n  "failureTests"''')
patch('workflow-schema.js',
'''    REQUIRED_CAPABILITY:Object.freeze({valueType:'STRING',enumValues:Object.freeze([]),nullable:false,normalizerKey:null,closedProperties:null}),\n    ARTIFACT_REQUIREMENTS:Object.freeze({valueType:'STRING',enumValues:Object.freeze([]),nullable:false,normalizerKey:null,closedProperties:null})''',
'''    REQUIRED_CAPABILITY:Object.freeze({valueType:'STRING',enumValues:Object.freeze([]),nullable:false,normalizerKey:null,closedProperties:null}),\n    ARTIFACT_REQUIREMENTS:Object.freeze({valueType:'STRING',enumValues:Object.freeze([]),nullable:false,normalizerKey:null,closedProperties:null}),\n    TEST_ARTIFACT_IDS:Object.freeze({valueType:'REFERENCE_ARRAY',enumValues:Object.freeze([]),nullable:false,normalizerKey:null,closedProperties:null})''')
patch('workflow-schema.js',
'''    'TEST_ID','REQ_ID','TEST_TYPE','EXECUTION_MODE','REQUIRED_CAPABILITY','ARTIFACT_REQUIREMENTS','INPUTS','TOOLS','PROCEDURE','EXPECTED_RESULT','FAILURE_CONDITION','EVIDENCE_TO_PRESERVE','STATUS'\n  ],required:''',
'''    'TEST_ID','REQ_ID','TEST_TYPE','EXECUTION_MODE','REQUIRED_CAPABILITY','ARTIFACT_REQUIREMENTS','TEST_ARTIFACT_IDS','INPUTS','TOOLS','PROCEDURE','EXPECTED_RESULT','FAILURE_CONDITION','EVIDENCE_TO_PRESERVE','STATUS'\n  ],required:''')

# 2) Resolve TEST_ARTIFACT_IDS only from evidence that already resolved to application-verified attachment bytes.
patch('response-ingestion.js',
'''    evidenceRecord.fields.SHA256=evidenceRecord.SHA256=hash.sha256Text(String(evidenceRecord.CONTENT||''));evidenceRecord.sha256=hash.sha256Value(evidenceRecord.fields);\n  }\n  for(const [collection,items] of Object.entries(canonicalRecords))for(const record of items){const def=schema.RECORD_SCHEMAS[collection];record.contentSha256=hash.contentRecordSha256(record,def.idField);record.recordSha256=hash.recordSha256(record);record.sha256=record.recordSha256;}''',
'''    evidenceRecord.fields.SHA256=evidenceRecord.SHA256=hash.sha256Text(String(evidenceRecord.CONTENT||''));evidenceRecord.sha256=hash.sha256Value(evidenceRecord.fields);\n  }\n  for(const testRecord of safe(canonicalRecords.tests)){const evidenceIds=new Set(safe(testRecord.evidenceRefs).map(String));const artifactIds=[...new Set(evidence.filter(item=>evidenceIds.has(String(item.id))).map(item=>String(item.ATTACHMENT_ID||item.fields?.ATTACHMENT_ID||'')).filter(id=>id&&!['UNKNOWN','NONE','NOT APPLICABLE'].includes(id.toUpperCase())))];testRecord.fields.TEST_ARTIFACT_IDS=artifactIds;testRecord.TEST_ARTIFACT_IDS=artifactIds;}\n  for(const [collection,items] of Object.entries(canonicalRecords))for(const record of items){const def=schema.RECORD_SCHEMAS[collection];record.contentSha256=hash.contentRecordSha256(record,def.idField);record.recordSha256=hash.recordSha256(record);record.sha256=record.recordSha256;}''')
patch('response-ingestion.js',
'''  evidence.forEach((record,index)=>{const source=safe(envelope.evidence)[index];''',
'''  for(const record of safe(canonicalRecords.tests))changes.push({origin:'APPLICATION_RELATIONSHIP_RESOLUTION',jsonPointer:null,rawValueHash:null,normalizerUsed:null,canonicalCollection:'tests',canonicalRecordType:'tests',canonicalRecordId:record.id,canonicalField:'TEST_ARTIFACT_IDS',relationshipTargetId:null,evidenceIds:record.evidenceRefs||[],normalizedValue:clone(record.TEST_ARTIFACT_IDS||[]),temporaryResponseKey:record.temporaryKey});\n  evidence.forEach((record,index)=>{const source=safe(envelope.evidence)[index];''')

# 3) Stage 6 must fail closed when a test says an artifact is required but no verified bytes are linked.
patch('workflow-engine.js',
'''      const unavailable=mandatoryTests.filter(test=>upper(recordValue(test,'EXECUTION_MODE'))==='UNAVAILABLE');\n      if(unavailable.length)reasons.push(`${unavailable.length} mandatory test definition(s) have unavailable execution capability and remain blocked.`);\n      break;''',
'''      const unavailable=mandatoryTests.filter(test=>upper(recordValue(test,'EXECUTION_MODE'))==='UNAVAILABLE');\n      if(unavailable.length)reasons.push(`${unavailable.length} mandatory test definition(s) have unavailable execution capability and remain blocked.`);\n      const missingArtifactBytes=mandatoryTests.filter(test=>{const requirement=upper(recordValue(test,'ARTIFACT_REQUIREMENTS'));return requirement&& !['NONE','NOT APPLICABLE','N/A'].includes(requirement)&&!safe(recordValue(test,'TEST_ARTIFACT_IDS')).length;});\n      if(missingArtifactBytes.length)reasons.push(`${missingArtifactBytes.length} mandatory test definition(s) require executable/input artifact bytes that are not application-verified and canonically linked.`);\n      break;''')
patch('workflow-engine.js',
'''    return {testId:recordId(test,'tests'),requirementId:testRequirementId(test),testType:upper(recordValue(test,'TEST_TYPE'))||'UNKNOWN',executionMode:mode,requiredCapability:String(recordValue(test,'REQUIRED_CAPABILITY')||'').trim(),artifactRequirements:String(recordValue(test,'ARTIFACT_REQUIREMENTS')||'').trim(),operatorAction:TEST_EXECUTION_ACTIONS[mode]||'Execution responsibility is not validly classified.'};''',
'''    const artifactRequirements=String(recordValue(test,'ARTIFACT_REQUIREMENTS')||'').trim(),testArtifactIds=safe(recordValue(test,'TEST_ARTIFACT_IDS')).map(String).filter(Boolean),artifactRequired=Boolean(artifactRequirements&&!['NONE','NOT APPLICABLE','N/A'].includes(artifactRequirements.toUpperCase()));\n    return {testId:recordId(test,'tests'),requirementId:testRequirementId(test),testType:upper(recordValue(test,'TEST_TYPE'))||'UNKNOWN',executionMode:mode,requiredCapability:String(recordValue(test,'REQUIRED_CAPABILITY')||'').trim(),artifactRequirements,testArtifactIds,artifactRequired,operatorAction:artifactRequired&&!testArtifactIds.length?'Attach the exact returned test artifact bytes to this stage. The application must hash and canonically link them before this test definition is complete.':TEST_EXECUTION_ACTIONS[mode]||'Execution responsibility is not validly classified.'};''')
patch('workflow-engine.js',
'''  const unavailableTestIds=items.filter(item=>item.executionMode==='UNAVAILABLE').map(item=>item.testId);\n  return {total:items.length,counts,incompleteTestIds,unavailableTestIds,items};''',
'''  const unavailableTestIds=items.filter(item=>item.executionMode==='UNAVAILABLE').map(item=>item.testId);\n  const missingArtifactTestIds=items.filter(item=>item.artifactRequired&&!item.testArtifactIds.length).map(item=>item.testId);\n  return {total:items.length,counts,incompleteTestIds,unavailableTestIds,missingArtifactTestIds,items};''')

# 4) Prompt and operator UI state the enforceable boundary without adding a new subsystem.
patch('prompt-engine.js',
'''Use ARTIFACT_REQUIREMENTS = NONE when no separate executable/input artifact is required. If the required capability is unavailable''',
'''Use ARTIFACT_REQUIREMENTS = NONE when no separate executable/input artifact is required. When ARTIFACT_REQUIREMENTS is not NONE, Stage 6 remains incomplete until the declared returned artifact is supplied as actual bytes, verified by the application, and linked to the TEST record as canonical TEST_ARTIFACT_IDS. If the required capability is unavailable''')
patch('app-core.js',
'''${plan.unavailableTestIds.length?`<div class="notice warn">${plan.unavailableTestIds.length} test${plan.unavailableTestIds.length===1?' is':'s are'} blocked by unavailable capability. Do not claim execution until a valid capability or equivalent verification path exists.</div>`:''}${actionRows.length?details('Who performs the current tests',actionRows):''',
'''${plan.unavailableTestIds.length?`<div class="notice warn">${plan.unavailableTestIds.length} test${plan.unavailableTestIds.length===1?' is':'s are'} blocked by unavailable capability. Do not claim execution until a valid capability or equivalent verification path exists.</div>`:''}${plan.missingArtifactTestIds.length?`<div class="notice warn">${plan.missingArtifactTestIds.length} test${plan.missingArtifactTestIds.length===1?' requires':'s require'} returned artifact bytes. Attach the exact files in Artifact control; a filename or claimed hash cannot satisfy this gate.</div>`:''}${actionRows.length?details('Who performs the current tests',actionRows):''')

# 5) Documentation: describe the now-enforced custody rule.
patch('README.md',
'''If the external environment returns a real test file, fixture, CAD model, report, archive, or other artifact, the response declares it in `attachments`, the operator attaches the exact returned file, and the application verifies the actual bytes before the proposal can rely on that artifact. A filename, claimed SHA-256, code block, or repository path is not file possession.''',
'''If the external environment returns a real test file, fixture, CAD model, report, archive, or other artifact, the response declares it in `attachments`, the operator attaches the exact returned file, and the application verifies the actual bytes before the proposal can rely on that artifact. A filename, claimed SHA-256, code block, or repository path is not file possession. When a TEST has `ARTIFACT_REQUIREMENTS` other than `NONE`, the application derives `TEST_ARTIFACT_IDS` only from evidence linked to those verified bytes, and Stage 6 remains blocked until that canonical custody link exists.''')

# 6) Acceptance proof: direct ingestion linkage, gate failure, semantic/schema/UI coverage.
patch('verify-ingestion.mjs',
'''// Duplicate response is semantic, not whitespace-sensitive.''',
'''// A Stage 6 test that requires a returned artifact receives canonical TEST_ARTIFACT_IDS only from verified attachment bytes linked through evidence.\n{\n  const p=project('JOB-TEST-ARTIFACT-CUSTODY'),stage=6,pr=savePrompt(p,stage),e=validEnvelope(p,stage,pr),exactFile={artifactId:'ARTIFACT-TEST-FIXTURE-1',name:'test-fixture.bin',type:'application/octet-stream',size:4,sha256:'c'.repeat(64)};\n  const test=e.records.tests[0];test.fields.ARTIFACT_REQUIREMENTS='Exact executable fixture test-fixture.bin';test.evidenceRefs=['evidence-1'];e.attachments=[{temporaryKey:'test-artifact-1',filename:exactFile.name,mediaType:exactFile.type,byteSize:exactFile.size,sha256:exactFile.sha256,required:true}];e.evidence[0].attachmentRef={tempKey:'test-artifact-1'};\n  const prepared=ingestion.prepare(p,{stage,text:JSON.stringify(e),promptRecord:pr,files:[exactFile]});if(!prepared.validation.valid)throw new Error('Stage 6 verified test artifact fixture rejected: '+JSON.stringify(prepared.validation.issues));const proposed=prepared.proposal.canonicalRecords.tests[0];if(JSON.stringify(proposed.TEST_ARTIFACT_IDS)!==JSON.stringify([exactFile.artifactId])||JSON.stringify(proposed.fields.TEST_ARTIFACT_IDS)!==JSON.stringify([exactFile.artifactId]))throw new Error('Verified test artifact bytes did not become canonical TEST_ARTIFACT_IDS.');if(!prepared.proposal.changes.some(x=>x.canonicalCollection==='tests'&&x.canonicalField==='TEST_ARTIFACT_IDS'&&x.origin==='APPLICATION_RELATIONSHIP_RESOLUTION'))throw new Error('TEST_ARTIFACT_IDS lacks application-derived extraction provenance.');\n}\n\n// Duplicate response is semantic, not whitespace-sensitive.''')
patch('verify-complete.mjs',
'''// Stage 11 initial execution completion does not depend on Stage 12 verification triples.''',
'''// Stage 6 artifact custody: declaring required test artifacts without verified bytes must fail closed.\n{const p=core.createBlankState('JOB-TEST-ARTIFACT-GATE');Object.assign(p.job,{CURRENT_INPUT_VERSION:'INPUT-v001',CURRENT_SOURCE_SET_VERSION:'SOURCE-SET-v001',CURRENT_REQUIREMENTS_VERSION:'REQUIREMENTS-v001',CURRENT_TEST_SUITE_VERSION:'TEST-SUITE-v001'});engine.ensureShape(p);p.projectData.requirements.push({id:'REQ-000001',stage:4,active:true,scope:{inputVersion:'INPUT-v001',sourceSetVersion:'SOURCE-SET-v001',requirementsVersion:'REQUIREMENTS-v001'},fields:{REQ_ID:'REQ-000001',MANDATORY_OPTIONAL_STATUS:'MANDATORY',STATUS:'ACTIVE'}});const test={id:'TEST-000001',stage:6,active:true,scope:{inputVersion:'INPUT-v001',sourceSetVersion:'SOURCE-SET-v001',requirementsVersion:'REQUIREMENTS-v001',testSuiteVersion:'TEST-SUITE-v001'},fields:{TEST_ID:'TEST-000001',REQ_ID:'REQ-000001',TEST_TYPE:'DETERMINISTIC',EXECUTION_MODE:'EXTERNAL_AGENT_TOOL',REQUIRED_CAPABILITY:'EXACT_TOOL',ARTIFACT_REQUIREMENTS:'test-fixture.bin',TEST_ARTIFACT_IDS:[],STATUS:'READY'},relationships:{REQ_ID:'REQ-000001'}};p.projectData.tests.push(test);p.projectData.acceptedChanges.push({changeId:'ACCEPTED-6',stage:6,status:'COMMITTED',responseType:'DATA_PROPOSAL'});let g=engine.evaluateStageGate(p,6);if(g.complete||!g.reasons.some(x=>x.includes('not application-verified and canonically linked')))throw new Error('Stage 6 accepted a required test artifact without verified canonical bytes.');test.fields.TEST_ARTIFACT_IDS=['ARTIFACT-VERIFIED-1'];g=engine.evaluateStageGate(p,6);if(!g.complete)throw new Error('Stage 6 rejected a complete test artifact custody record: '+g.reasons.join(' | '));}\n\n// Stage 11 initial execution completion does not depend on Stage 12 verification triples.''')
patch('verify-prompt-semantics.mjs',
'''if(!testFields.EXECUTION_MODE||!testFields.REQUIRED_CAPABILITY||!testFields.ARTIFACT_REQUIREMENTS)throw new Error('TEST execution responsibility is not explicit in the canonical schema.');''',
'''if(!testFields.EXECUTION_MODE||!testFields.REQUIRED_CAPABILITY||!testFields.ARTIFACT_REQUIREMENTS)throw new Error('TEST execution responsibility is not explicit in the canonical schema.');if(testFields.TEST_ARTIFACT_IDS?.producer!==schema.PRODUCER.APPLICATION||testFields.TEST_ARTIFACT_IDS?.valueType!=='REFERENCE_ARRAY')throw new Error('TEST artifact custody is not application-owned canonical identity.');''')
patch('verify-prompt-semantics.mjs',
'''if(!appSource.includes('Verification execution')||!appSource.includes('Who performs the current tests'))throw new Error('Operator UI does not explain test execution responsibility.');''',
'''if(!appSource.includes('Verification execution')||!appSource.includes('Who performs the current tests'))throw new Error('Operator UI does not explain test execution responsibility.');if(!appSource.includes('returned artifact bytes')||!appSource.includes('filename or claimed hash cannot satisfy this gate'))throw new Error('Operator UI does not explain required test-artifact custody.');''')

# 7) Refresh the exact shared runtime identity using the formula enforced by verify-hash.mjs.
def git_blob_sha(path):
    data=Path(path).read_bytes(); return hashlib.sha1(f'blob {len(data)}\0'.encode()+data).hexdigest()
runtime=['workbook.js','hash.js','workflow-schema.js','workflow-engine.js','prompt-engine.js','response-ingestion.js','project-store.js','app-core.js']
manifest=''.join(f'{f}:{git_blob_sha(f)}\n' for f in runtime)
build='runtime-'+hashlib.sha256(manifest.encode()).hexdigest()[:16]
p=Path('index.html'); s=p.read_text(); s,n=re.subn(r'(<script defer src="(?:workbook|hash|workflow-schema|workflow-engine|prompt-engine|response-ingestion|project-store|app-core)\.js\?v=)[^\"]+(\"></script>)',lambda m:m.group(1)+build+m.group(2),s)
if n!=8: raise SystemExit(f'Expected 8 runtime script tokens; found {n}')
p.write_text(s)
