from pathlib import Path
p=Path('prompt-engine.js');s=p.read_text().replace('EXECUTABLE_KIND = CUSTOM_PIPELINE','EXECUTABLE_KIND = TEST_IR').replace('Capture every material human-authority statement that is actually available and relevant to the job definition in the accepted Stage 01 job definition so later stages can consume it canonically.','Exhaust the complete application-enumerated intake-unit manifest before finalizing. Every intake-unit identity must be classified exactly once and every material human-authority statement must be preserved without weakening, omission, or substitution in the accepted Stage 01 canonical ledger so later stages can consume it without asking the human again.').replace('Repeat discovery passes until saturation is actually supported by the evidence.','Repeat source examination, conflict/exception discovery, and candidate-obligation extraction until the current Stage 02 source set and every requirement-relevant Stage 01 intake statement are exhaustively covered. Do not return final Stage 03 JSON while a current source, exception, conflict, applicability fact, restriction, invalidating item, or candidate obligation remains unexamined.')
a=s.find("${stage===1?`STAGE 01 DOMAIN INTAKE ADAPTATION");b=s.find("${stage===1?`STAGE 01 CLARIFICATION EXPERIENCE",a)
generic="""${stage===1?`STAGE 01 SUBJECT-NEUTRAL INTAKE ADAPTATION\nDerive the complete set of human-only questions from the actual request, the complete application-enumerated intake-unit manifest, and any supplied material actually available. Do not use a hard-coded project-subject catalogue. For every intake unit, preserve its meaning and classify it. Identify every foreseeable human-only fact, constraint, decision, prohibition, acceptance condition, requested output, material reference, and unresolved issue needed to define the requested outcome. Ask only human-only questions; never ask the human to repeat information already present in the intake manifest or accessible supplied material. Do not perform source research, requirement atomization, test design, production design, artifact generation, filing, simulation, manufacturing, or product verification.\n`:`SUBJECT-NEUTRAL STAGE ADAPTATION\nInfer the domain-specific work only from current canonical project data, governing sources, and the stage contract. Do not use or depend on a hard-coded catalogue of project subjects. Artifact generation and downstream execution/verification are separate capability claims; never claim an operation occurred without evidence.\n`}\n\n"""
if a>=0 and b>=0:s=s[:a]+generic+s[b:]
idx=s.find('For PATENT / REGULATED FILING jobs, when not already known from human input or supplied materials, ASK_NOW_NONBLOCKING includes:')
if idx>=0:s=s[:idx]+s[s.find('\n',idx)+1:]
marker="${stage===4?`ACCEPTED STAGE 01 JOB DEFINITION — CURRENT CANONICAL VALUES";i=s.find(marker)
block="""${stage===1?`APPLICATION-ENUMERATED INTAKE COVERAGE MANIFEST — EXHAUST THIS SET\n${show(workflow.intakeCoverageManifest(state))}\nEvery unitId above is application-owned. Before final JSON, classify every unit exactly once. Each intentStatements record SOURCE_LOCATION must equal the exact unitId it came from. Omission of any unit fails Stage 01. Do not ask the human to repeat any content already present here.\n\n`:''}${stage===4?`APPLICATION-ENUMERATED STAGE 04 OBLIGATION UNIVERSE — EXHAUST THIS SET\n${show(workflow.obligationManifest(state))}\nThis is the complete current obligation universe selected by the application from exhausted Stage 01 human/material intent and Stage 03 research/candidate obligations. Account for every obligationId. Convert it to one or more atomic requirements, or return an explicit retained-context, inapplicable, or blocked disposition with reason. No obligation may disappear and the human must not resupply any prior information.\n\n`:''}"""
if i>=0:s=s[:i]+block+s[i:]
p.write_text(s)
p=Path('index.html');s=p.read_text().replace("connect-src 'self'; object-src","connect-src 'self'; worker-src 'self'; object-src").replace('<script defer src="workflow-engine.js?v=runtime-5859ee5a07f239ae"></script>','<script defer src="test-runtime.js?v=runtime-5859ee5a07f239ae"></script>\n<script defer src="workflow-engine.js?v=runtime-5859ee5a07f239ae"></script>');p.write_text(s)
p=Path('test-worker.js');p.write_text(p.read_text().replace("importScripts('test-runtime.js');","importScripts('test-runtime.js?v=runtime-5859ee5a07f239ae');\nself.fetch=undefined;self.XMLHttpRequest=undefined;self.WebSocket=undefined;"))