(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.ClosedLoopCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const STAGES=[
['DEFINE JOB','Create the authoritative job record. Preserve the exact user objective, exact requested deliverable, supplied files/messages/links/data, explicit constraints, required output format, deadline/temporal scope, known authorities, available tools, prohibited actions, unknowns, explicit requirements, assumptions, and INPUT-vN. Do not research or produce the final deliverable in this stage.'],
['INVENTORY SOURCES','Inspect every supplied file and identify every source that may govern correctness. Record source identifier, title/description, source type, origin, version, publication/effective date where relevant, authority, role, relevant portions, and conflicts. Research current authoritative sources when current external facts govern correctness. Unresolved authoritative conflicts are blockers.'],
['RESEARCH REQUIREMENTS','Read the controlling source set and extract every obligation, restriction, exception, required element, prohibited element, numerical condition, structural condition, procedural condition, dependency, applicability fact, and user-created requirement. Continue until another pass yields no new material requirement category.'],
['COMPILE ATOMIC REQUIREMENTS','Create one independently testable requirement per obligation. Each record must identify its requirement, source, source location, authority, applicability, dependencies, prohibitions, verification method, expected evidence, failure condition, and status. Split compound requirements into atomic requirements.'],
['RESOLVE CONFLICTS','Check the complete requirement set for duplicates, conflicts, impossible combinations, undefined terms, circular dependencies, missing prerequisites, unsupported requirements, uncertain applicability, and unverifiable requirements. Resolve what can be resolved and block what cannot.'],
['BUILD ACCEPTANCE TESTS','Create at least one verification procedure for every mandatory requirement. Mandatory verification coverage must equal 100 percent. Prefer deterministic methods whenever the property is deterministic.'],
['BUILD FAILURE/MUTATION TESTS','For every requirement where a violating case is constructible, create at least one violating case, define the required rejection/detection behavior, and prove the validator rejects the invalid case before continuing.'],
['AUTHOR PRODUCTION INSTRUCTION','Write the production instruction directly from the approved requirements. Include objective, inputs, authorities, scope, definitions, ordered procedure, decision rules, tool rules, output contract, failure behavior, truth semantics, and exact completion criteria.'],
['PREFLIGHT INSTRUCTION','Inspect the production instruction without executing the target work. Detect ambiguity, undefined objects, missing inputs, conflicts, unavailable capability, unverifiability, unclear responsibility/order/failure behavior, and missing traceability. Correct defects and version the instruction.'],
['FREEZE CANDIDATE','Freeze the exact input, source set, requirement set, test suite, instruction, and tool configuration together as one candidate version. Hash immutable files when practical. Any material change creates a new version.'],
['RUN 10 INDEPENDENT EXECUTIONS','Run ten fresh independent execution contexts using exactly the frozen candidate. Each run must contain its own actual output. No run may see another run output, reviewer comment, prior failure, or proposed correction.'],
['VERIFY EVERY RUN AGAINST EVERY REQUIREMENT','Apply the complete verification suite independently to every run and every mandatory requirement. Record run, requirement, test, result, evidence, and defect identifier where applicable.'],
['COMPARE ALL RUNS','Compare the ten independently verified outputs requirement-by-requirement. Identify violations, inconsistent interpretations, prohibited variance, inconclusive tests, repeated failures, and unique failures. Correctness-affecting variance is a defect.'],
['ROOT-CAUSE EVERY DEFECT','Trace every confirmed defect to the earliest defective layer: source, research, requirement, test, instruction, input, execution, tool, or audit. Do not patch only the final output when an earlier layer is defective.'],
['ADD REGRESSION TESTS','For every confirmed defect, preserve a reproducer, create a test that fails before correction, apply the correction, prove the test succeeds afterward, and preserve the regression test while the requirement remains applicable.'],
['CORRECT RESPONSIBLE LAYER','Revise only the established defective layer and every dependent artifact. Increment every changed artifact version. Never edit a frozen version in place.'],
['FREEZE NEW VERSION','Freeze the corrected input/source/requirements/tests/instruction/tool configuration as a new candidate before another execution batch.'],
['RUN 10 NEW INDEPENDENT EXECUTIONS','Run a fresh ten-execution batch under the new frozen candidate. The ten responses must be actual independent run outputs. Verify, compare, root-cause, regress, and correct as required.'],
['REPEAT UNTIL CONVERGED','Repeat correction and fresh ten-run batches until mandatory requirement coverage is 100 percent, mandatory verification coverage is 100 percent, regression success is 100 percent, critical defects are 0, major defects are 0, mandatory unknowns are 0, correctness contradictions are 0, correctness ambiguities are 0, and unexplained correctness variance is 0.'],
['RUN UNCHANGED 10-EXECUTION CONFIRMATION','Change nothing. Run another ten fresh independent executions against the exact converged candidate. Any new critical/major defect, requirement, validator miss, contradiction, or ambiguity returns the workflow to the earliest responsible stage.'],
['FREEZE APPROVED BASELINE','Record the exact approved input, source set, requirements, instruction, test suite, validator configuration, and tool configuration under one baseline identifier with hashes where practical.'],
['GENERATE FINISHED PRODUCT','Create a fresh production execution using only approved baseline materials required for production. Generate the actual requested deliverable, not a placeholder or description. Record product identifier, baseline identifier, execution identifier, output files, and hashes.'],
['DETERMINISTIC PRODUCT VERIFICATION','Run every applicable deterministic validator against the actual generated artifact: arithmetic, counts, schemas, filenames, inventory, hashes, sections/order, identifiers, references, links, dates, enumerations, tables, required/prohibited text, package contents, structural constraints, and formatting dimensions. Any mandatory failure rejects the product.'],
['INDEPENDENT SEMANTIC VERIFICATION','Use a separate evaluator context with the finished product, requirement registry, source evidence, and rubric. For every semantic requirement record product location, source evidence, observed meaning, required meaning, and SATISFIED, VIOLATED, or UNDETERMINED.'],
['ADVERSARIAL PRODUCT VERIFICATION','Attempt to disprove correctness by searching for missing/prohibited material, contradictions, impossible logic, unsupported facts, source misrepresentation, wrong versions, broken references, hidden assumptions, partial completion, semantic nonsense, inconsistent terminology, unhandled exceptions, stale facts, malformed files, hidden content, export corruption, and merely-mentioned-but-unsatisfied requirements.'],
['FINAL REPRESENTATION INSPECTION','Inspect the exact bytes and rendered form that will be delivered, including downstream conversions and packages. Verify clipping, missing content, blank pages, broken tables, misplaced graphics, material font substitution, corruption, package inventory, filenames, and versions.'],
['PROCESS AUDIT','Audit the process evidence independently: approved inputs, frozen instruction, tools, tests, execution isolation, version transitions, defect records, regressions, no unauthorized modifications, and full traceability.'],
['PRODUCT AUDIT','Audit the product independently: every mandatory requirement has affirmative evidence, every mandatory test passed, semantic evidence exists, and no unresolved critical or major defect remains.'],
['ACCEPTED / REJECTED / BLOCKED','Assign exactly one release decision. ACCEPTED requires affirmative evidence for every mandatory requirement and success of every mandatory validator. REJECTED means a mandatory requirement is demonstrably violated. BLOCKED means a mandatory requirement cannot be established.'],
['VERIFY RELEASE HASH','Hash every artifact that completed final verification and hash it again immediately before release. RELEASE_HASH must equal AUDITED_HASH byte-for-byte. Any mismatch stops release and requires a new product version and affected revalidation.'],
['RELEASE ONLY THE EXACT ACCEPTED ARTIFACT','Preserve the complete source-to-requirement-to-instruction-to-execution-to-product-element-to-test-to-result-to-evidence-to-release-decision chain. Release only the exact bytes that were accepted and whose release hash matches the audited hash.']
].map((x,i)=>({number:i+1,id:`STAGE-${String(i+1).padStart(2,'0')}`,name:x[0],instruction:x[1]}));
const requiredEvidence={
1:[/JOB[_ -]?ID/i,/EXACT.*OBJECTIVE/i,/EXACT.*DELIVERABLE/i,/INPUT[-_ ]?v\d+/i],
2:[/SOURCE[_ -]?ID|SRC[-_ ]?\d+/i,/SOURCE.*ROLE|MANDATORY|INFORMATIVE|EVIDENTIARY/i],
4:[/REQ[-_ ]?\d+/i,/VERIFICATION/i],
6:[/TEST[-_ ]?\d+/i,/REQ[-_ ]?\d+/i],
10:[/INPUT[-_ ]?v\d+/i,/REQUIREMENTS[-_ ]?v\d+/i,/INSTRUCTION[-_ ]?v\d+/i,/TEST[-_ ]?SUITE[-_ ]?v\d+/i],
11:[/RUN[-_ ]?001/i,/RUN[-_ ]?010/i],
12:[/SATISFIED|VIOLATED|UNDETERMINED/i,/RUN[-_ ]?001/i],
18:[/RUN[-_ ]?001/i,/RUN[-_ ]?010/i],
19:[/100%|100 percent/i,/critical\s+defects?\s*[:=]\s*0/i,/major\s+defects?\s*[:=]\s*0/i],
20:[/RUN[-_ ]?001/i,/RUN[-_ ]?010/i,/unchanged/i],
21:[/BASELINE[-_ ]?ID/i],
22:[/PRODUCT[-_ ]?ID/i,/OUTPUT|ARTIFACT/i],
29:[/ACCEPTED|REJECTED|BLOCKED/i],
30:[/RELEASE[_ -]?HASH/i,/AUDITED[_ -]?HASH/i],
31:[/SOURCE/i,/REQUIREMENT/i,/TEST/i,/RELEASE/i]
};
function uid(prefix){if(typeof crypto!=='undefined'&&crypto.randomUUID)return `${prefix}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;return `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;}
function createProject(input){for(const k of ['name','objective','deliverable'])if(!String(input[k]||'').trim())throw new Error(`${k} is required.`);const now=new Date().toISOString();return{schemaVersion:2,projectId:uid('PRJ'),jobId:uid('JOB'),name:String(input.name).trim(),objective:String(input.objective).trim(),deliverable:String(input.deliverable).trim(),suppliedInputs:String(input.suppliedInputs||'').trim(),constraints:String(input.constraints||'').trim(),outputFormat:String(input.outputFormat||'UNSPECIFIED').trim(),deadline:String(input.deadline||'NONE SUPPLIED').trim(),createdAt:now,updatedAt:now,releaseState:'UNSET',finalArtifact:'',auditedHash:'',releaseHash:'',stages:STAGES.map(s=>({stageId:s.id,status:'NOT_STARTED',agentResponse:'',evidence:'',completedAt:null}))};}
function stage(project,n){if(!project||!Array.isArray(project.stages))throw new Error('Invalid project.');if(!Number.isInteger(n)||n<1||n>STAGES.length)throw new Error('Invalid stage number.');return project.stages[n-1];}
function validateSequentialAccess(project,n){for(let i=0;i<n-1;i++)if(project.stages[i].status!=='COMPLETE')throw new Error(`Stage ${i+1} must be COMPLETE before Stage ${n}.`);return true;}
function validateStageResponse(project,n,response){validateSequentialAccess(project,n);const text=String(response||'').trim();if(!text)throw new Error('Agent response is required. Empty responses cannot complete a stage.');if(text.length<80)throw new Error('Agent response is too short to be credible completed stage work.');for(const rx of(requiredEvidence[n]||[]))if(!rx.test(text))throw new Error(`Stage ${n} response is missing required evidence: ${rx}.`);return true;}
function completeStage(project,n,response,evidence){validateStageResponse(project,n,response);const s=stage(project,n);s.agentResponse=String(response).trim();s.evidence=String(evidence||'').trim();s.status='COMPLETE';s.completedAt=new Date().toISOString();project.updatedAt=s.completedAt;return project;}
function saveStageDraft(project,n,response,evidence){validateSequentialAccess(project,n);const s=stage(project,n);s.agentResponse=String(response||'');s.evidence=String(evidence||'');if(s.status==='NOT_STARTED')s.status='IN_PROGRESS';project.updatedAt=new Date().toISOString();return project;}
function completionPercent(project){return Math.round(project.stages.filter(s=>s.status==='COMPLETE').length/STAGES.length*100);}
function canRelease(project){return project.stages.every(s=>s.status==='COMPLETE')&&project.releaseState==='ACCEPTED'&&String(project.finalArtifact||'').length>0&&project.auditedHash&&project.releaseHash&&project.auditedHash===project.releaseHash;}
function buildPrompt(project,n){validateSequentialAccess(project,n);const d=STAGES[n-1];const prior=n===1?'NONE':project.stages.slice(0,n-1).map((s,i)=>`===== STAGE ${i+1} COMPLETED RESULT =====\n${s.agentResponse}`).join('\n\n');return `CLOSED-LOOP AGENT RELIABILITY WORKFLOW\n\nJOB_ID: ${project.jobId}\nPROJECT: ${project.name}\nEXACT USER OBJECTIVE: ${project.objective}\nEXACT DELIVERABLE REQUESTED: ${project.deliverable}\nSUPPLIED FILES / MESSAGES / LINKS / DATA: ${project.suppliedInputs||'NONE SUPPLIED'}\nCONSTRAINTS / PROHIBITED ACTIONS: ${project.constraints||'NONE SUPPLIED'}\nREQUIRED OUTPUT FORMAT: ${project.outputFormat||'UNSPECIFIED'}\nDEADLINE / TEMPORAL SCOPE: ${project.deadline||'NONE SUPPLIED'}\n\nSTAGE ${n}: ${d.name}\n\nREQUIRED WORK\n${d.instruction}\n\nPRIOR COMPLETED WORKFLOW STATE\n${prior}\n\nEXECUTE THIS STAGE NOW\nDo the stage work now. Use supplied files and available tools when required. Return the actual completed stage deliverable and evidence; do not return a plan, generic template, placeholder, or instructions for somebody else. Do not perform a later stage. If a mandatory fact remains genuinely unavailable after using the available sources/tools, return BLOCKED and identify the exact missing fact.\n`;
}
async function sha256(text){if(typeof crypto!=='undefined'&&crypto.subtle){const b=new TextEncoder().encode(String(text));const h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('');}try{const c=require('node:crypto');return c.createHash('sha256').update(String(text)).digest('hex');}catch{return '';}}
function makeVerificationJob(){return createProject({name:'Verified E2E Inventory Reconciliation',objective:'Reconcile a fixed three-line inventory ledger and release the exact audited text artifact after completing every workflow stage.',deliverable:'inventory-reconciliation.txt containing A=3, B=4, C=5, TOTAL=12',suppliedInputs:'Authoritative input data: A=3; B=4; C=5. Required total is arithmetic sum. Output must be exactly four lines: A=3, B=4, C=5, TOTAL=12.',constraints:'No omitted stage. No empty agent response. No stage skipping. Artifact bytes must match audited bytes.',outputFormat:'UTF-8 plain text',deadline:'NONE'});}
function demoResponse(p,n){const h=`STAGE ${n} COMPLETED WORK for ${p.jobId}. This is stored stage evidence for the deterministic inventory reconciliation verification job.`;const x={1:`\nJOB_ID: ${p.jobId}\nEXACT USER OBJECTIVE: ${p.objective}\nEXACT DELIVERABLE REQUESTED: ${p.deliverable}\nINPUT-v001: A=3; B=4; C=5; exact four-line UTF-8 output required.`,2:`\nSOURCE_ID: SRC-0001; source role MANDATORY; authoritative user input A=3, B=4, C=5. SOURCE_ID: SRC-0002; source role MANDATORY; exact output contract.`,4:`\nREQ-0001: total SHALL equal 12; VERIFICATION_METHOD EXACT_COMPUTATION. REQ-0002: output SHALL exactly contain four required lines; VERIFICATION_METHOD EXACT_BYTE_COMPARISON.`,6:`\nTEST-0001 verifies REQ-0001 by 3+4+5=12. TEST-0002 verifies REQ-0002 by exact UTF-8 byte comparison.`,10:`\nINPUT-v001 SOURCE-SET-v001 REQUIREMENTS-v001 TEST-SUITE-v001 INSTRUCTION-v001 TOOL-CONFIGURATION-v001 frozen together.`,11:`\nRUN-001, RUN-002, RUN-003, RUN-004, RUN-005, RUN-006, RUN-007, RUN-008, RUN-009, RUN-010 each independently produced A=3 B=4 C=5 TOTAL=12.`,12:`\nRUN-001 REQ-0001 SATISFIED by TEST-0001. RUN-010 REQ-0002 SATISFIED by TEST-0002. All ten runs SATISFIED all mandatory requirements.`,18:`\nFresh RUN-001 through RUN-010 were executed from the new frozen candidate independently and each returned the required four-line artifact.`,19:`\nmandatory requirement coverage = 100%\nmandatory verification coverage = 100%\nregression success = 100%\ncritical defects = 0\nmajor defects = 0\nmandatory unknowns = 0`,20:`\nUnchanged confirmation performed with fresh RUN-001 through RUN-010 using unchanged frozen versions; all tests passed.`,21:`\nBASELINE_ID: BASELINE-INV-001; approved frozen versions recorded with no unresolved defects.`,22:`\nPRODUCT_ID: PRODUCT-INV-001; OUTPUT ARTIFACT created exactly as A=3\\nB=4\\nC=5\\nTOTAL=12\\n.`,29:`\nRelease decision: ACCEPTED. Every mandatory requirement has affirmative evidence and every mandatory validator passed.`,30:`\nAUDITED_HASH: computed SHA-256 over exact artifact bytes. RELEASE_HASH: recomputed SHA-256 immediately before release and required to equal AUDITED_HASH.`,31:`\nPreserved SOURCE -> REQUIREMENT -> INSTRUCTION -> EXECUTION -> PRODUCT -> TEST -> EVIDENCE -> RELEASE traceability. Exact ACCEPTED bytes only are releasable.`};return h+(x[n]||`\nCompleted the required operations for ${STAGES[n-1].name}. Evidence is recorded in this stage response and no later stage was performed.`);}
async function runVerificationJob(){const p=makeVerificationJob();const trace=[];for(let n=1;n<=STAGES.length;n++){const response=demoResponse(p,n);completeStage(p,n,response,`E2E validator used the same stage gate as the interactive UI for Stage ${n}.`);trace.push({stage:n,responseLength:response.length,status:p.stages[n-1].status});}p.finalArtifact='A=3\nB=4\nC=5\nTOTAL=12\n';p.releaseState='ACCEPTED';p.auditedHash=await sha256(p.finalArtifact);p.releaseHash=await sha256(p.finalArtifact);if(!canRelease(p))throw new Error('E2E release gate failed.');return{project:p,trace};}
return{STAGES,createProject,validateSequentialAccess,validateStageResponse,completeStage,saveStageDraft,completionPercent,canRelease,buildPrompt,sha256,makeVerificationJob,demoResponse,runVerificationJob};
});