import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawn,spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {chromium} from 'playwright-core';
const root=path.dirname(fileURLToPath(import.meta.url));const port=4173;const origin=`http://127.0.0.1:${port}`;const server=spawn('python3',['-m','http.server',String(port),'--bind','127.0.0.1'],{cwd:root,stdio:['ignore','pipe','pipe']});const sleep=ms=>new Promise(r=>setTimeout(r,ms));await sleep(700);
let chrome=process.env.CHROME_PATH;for(const p of ['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'])if(!chrome&&fs.existsSync(p))chrome=p;if(!chrome)throw new Error('System Chromium/Chrome is required for the real UI test.');
const browser=await chromium.launch({headless:true,executablePath:chrome,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:393,height:852},acceptDownloads:true});await context.grantPermissions(['clipboard-read','clipboard-write'],{origin});const page=await context.newPage();const consoleErrors=[];page.on('pageerror',e=>consoleErrors.push(String(e)));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
const agent=(n,role,prompt,run=0)=>{const r=spawnSync(process.execPath,[path.join(root,'e2e-agent.mjs'),String(n),role,String(run),Buffer.from(prompt).toString('base64')],{encoding:'utf8'});if(r.status!==0)throw new Error(`External agent failed stage ${n} ${role} ${run}: ${r.stderr}`);assert.ok(r.stdout.length>=80);return r.stdout};
const copyMain=async()=>{await page.locator('#copyMain').click();return await page.evaluate(()=>navigator.clipboard.readText())};const copyRun=async(role,i)=>{await page.locator(`[data-rprompt="${role}:${i}"]`).click();return await page.evaluate(()=>navigator.clipboard.readText())};const message=async()=>page.locator('#stageMsg').textContent();
try{
 await page.goto(`${origin}/app-v11.html`,{waitUntil:'networkidle'});assert.equal(await page.locator('body').evaluate(el=>el.scrollWidth),393,'phone layout must not overflow horizontally');assert.match(await page.locator('#status').textContent(),/Ready/);assert.equal(await page.locator('#projects .card').count(),1);assert.match(await page.locator('#projects').textContent(),/No projects/);
 await page.locator('#newBtn').click();await page.locator('#name').fill('REAL BROWSER E2E — Inventory Reconciliation');await page.locator('#objective').fill('Reconcile the authoritative inventory values A=3, B=4, C=5 through the complete closed-loop workflow and release only the exact accepted artifact.');await page.locator('#deliverable').fill('inventory-reconciliation.txt containing exactly four UTF-8 lines: A=3, B=4, C=5, TOTAL=12');await page.locator('#inputs').fill('Authoritative user data: A=3; B=4; C=5. TOTAL=A+B+C. Required exact artifact bytes: A=3\\nB=4\\nC=5\\nTOTAL=12\\n');await page.locator('#constraints').fill('No skipped stage. Every required stage, producer-run, and verifier field must contain a pasted completed response. Release bytes must equal audited bytes.');await page.locator('#format').fill('UTF-8 plain text, exact four lines');await page.locator('#createBtn').click();assert.match(await page.locator('#pTitle').textContent(),/REAL BROWSER E2E/);assert.match(await page.locator('#pct').textContent(),/0\/31/);
 // Prove a later stage cannot be completed or even supplied a usable prompt before Stage 1.
 await page.locator('[data-stage="2"]').click();assert.match(await page.locator('#stagePanel').textContent(),/LOCKED: Stage 1 must be COMPLETE before Stage 2/);await page.locator('[data-stage="1"]').click();
 const standardStages=[1,2,3,4,5,6,7,8,9,10,13,14,15,16,17,21,22,23,24,25,26,27,28,29];
 for(let n=1;n<=31;n++){
   await page.locator(`[data-stage="${n}"]`).click();
   if(n===11||n===18){for(let i=0;i<10;i++){const pr=await copyRun('producer',i);assert.match(pr,new RegExp(`RUN-${String(i+1).padStart(3,'0')}`));await page.locator(`[data-producer="${i}"]`).fill(agent(n,'producer',pr,i+1));}await page.locator('#notes').fill(`Browser UI evidence: all ten Stage ${n} producer fields were populated through rendered textareas.`);await page.locator('#completeBatch').click();}
   else if(n===12){for(let i=0;i<10;i++){const pr=await copyRun('verifier',i);await page.locator(`[data-verifier="${i}"]`).fill(agent(n,'verifier',pr,i+1));}await page.locator('#notes').fill('Browser UI evidence: ten independent verifier fields were populated and validated.');await page.locator('#completeVerify').click();}
   else if(n===19){for(let i=0;i<10;i++){const pr=await copyRun('verifier',i);await page.locator(`[data-verifier="${i}"]`).fill(agent(n,'verifier',pr,i+1));}await page.locator('#response').fill('CONVERGENCE LEDGER: mandatory requirement coverage 100%; mandatory verification coverage 100%; regression success 100%; CRITICAL defects 0; MAJOR defects 0; mandatory unknowns 0; correctness contradictions 0; correctness ambiguities 0; unexplained correctness variance 0. Exact converged candidate: CANDIDATE-v002. Evidence includes all ten new-run verifier records.');await page.locator('#notes').fill('Convergence evidence entered through the rendered Stage 19 controls.');await page.locator('#completeVerify').click();}
   else if(n===20){for(let i=0;i<10;i++){let pr=await copyRun('producer',i);await page.locator(`[data-producer="${i}"]`).fill(agent(n,'producer',pr,i+1));pr=await copyRun('verifier',i);await page.locator(`[data-verifier="${i}"]`).fill(agent(n,'verifier',pr,i+1));}await page.locator('#response').fill('UNCHANGED CONFIRMATION completed against exact CANDIDATE-v002. Ten fresh independent confirmation runs and ten independent verifier records establish 100% mandatory verification coverage with no new critical defect, major defect, requirement, validator miss, contradiction, ambiguity, or unexplained correctness variance. The candidate remained unchanged throughout confirmation.');await page.locator('#notes').fill('Stage 20 producer and verifier fields were all filled through the rendered UI.');await page.locator('#completeConfirm').click();}
   else if(n===30){const p=await page.evaluate(()=>window.__CLR_V11__.getCurrent());const actual=await page.evaluate(async()=>{const p=window.__CLR_V11__.getCurrent(),b=new TextEncoder().encode(p.artifact),d=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')});const pr=await copyMain();assert.match(pr,/VERIFY RELEASE HASH/);const resp=`AUDITED_HASH: ${actual}. RELEASE_HASH: ${actual}. Equality result: TRUE. The exact finished inventory-reconciliation.txt artifact bytes were hashed after the product audit and the identical proposed release bytes were hashed immediately before release. No byte changed, so both recorded hashes equal the app-computed SHA-256.`;await page.locator('#response').fill(resp);await page.locator('#notes').fill('Hash values pasted through Stage 30 UI and checked against app-computed artifact bytes.');await page.locator('#completeStandard').click();}
   else if(n===31){const pr=await copyMain();await page.locator('#response').fill(agent(n,'stage',pr));await page.locator('#notes').fill('Final release record entered through rendered Stage 31 UI.');await page.locator('#completeStandard').click();}
   else if(standardStages.includes(n)){const pr=await copyMain();assert.match(pr,new RegExp(`STAGE ${n} OF 31`));await page.locator('#response').fill(agent(n,'stage',pr));await page.locator('#notes').fill(`Browser UI evidence for Stage ${n}: prompt was copied from the rendered app and response was pasted into its required field.`);await page.locator('#completeStandard').click();}
   else throw new Error(`Unhandled stage ${n}`);
   const msg=await message().catch(()=> '');assert.ok(!/required|blocked|error|must /i.test(msg||''),`Stage ${n} emitted error: ${msg}`);
 }
 assert.match(await page.locator('#pct').textContent(),/31\/31/);await page.locator('[data-view="release"]').click();assert.match(await page.locator('#release').textContent(),/Release gate\s*PASS/);const project=await page.evaluate(()=>window.__CLR_V11__.getCurrent());assert.equal(project.stages.filter(s=>s.status==='COMPLETE').length,31);assert.equal(project.releaseDecision,'ACCEPTED');assert.equal(project.stages[10].producers.filter(Boolean).length,10);assert.equal(project.stages[11].verifiers.filter(Boolean).length,10);assert.equal(project.stages[17].producers.filter(Boolean).length,10);assert.equal(project.stages[18].verifiers.filter(Boolean).length,10);assert.equal(project.stages[19].producers.filter(Boolean).length,10);assert.equal(project.stages[19].verifiers.filter(Boolean).length,10);assert.equal(project.artifact,'A=3\nB=4\nC=5\nTOTAL=12\n');assert.equal(project.auditedHash,'51368207f534cfb908522b1fb6451bf26c701c8c9dca2b11da75a8012c38c353');assert.equal(project.releaseHash,project.auditedHash);
 const dl=page.waitForEvent('download');await page.locator('#downloadArtifact').click();const download=await dl;assert.equal(download.suggestedFilename(),'released-artifact.txt');const dlPath=await download.path();assert.equal(fs.readFileSync(dlPath,'utf8'),project.artifact,'downloaded release bytes differ from audited artifact');
 fs.writeFileSync(path.join(root,'verified-e2e-project.json'),JSON.stringify(project,null,2)+'\n');fs.writeFileSync(path.join(root,'verified-e2e-artifact.txt'),project.artifact);
 // Persistence proof: reload the actual app, then verify the same completed project survives and remains 31/31.
 await page.reload({waitUntil:'networkidle'});assert.match(await page.locator('#status').textContent(),/1 project/);await page.locator('[data-open]').click();assert.match(await page.locator('#pct').textContent(),/31\/31/);assert.equal(consoleErrors.length,0,`Browser errors: ${consoleErrors.join(' | ')}`);
 console.log(JSON.stringify({status:'PASS',testType:'Chromium UI end-to-end',viewport:'393x852',projectId:project.projectId,jobId:project.jobId,stagesCompleted:31,producerResponsesPasted:30,verifierResponsesPasted:30,standardStageResponsesPasted:24,stageSkippingRejected:true,persistenceAfterReload:true,releaseDecision:project.releaseDecision,artifactSha256:project.auditedHash,artifactDownloadBytesVerified:true,projectExport:'verified-e2e-project.json'},null,2));
}finally{await browser.close();server.kill('SIGTERM');}
