import fs from 'node:fs';
let s=fs.readFileSync('app-v11.html','utf8');
const replaceBetween=(text,start,end,replacement)=>{const a=text.indexOf(start),b=text.indexOf(end,a);if(a<0||b<0)throw new Error(`Patch anchor missing: ${start} / ${end}`);return text.slice(0,a)+replacement+text.slice(b)};
s=replaceBetween(s,'function prior(p,n){','function batchDigest(s){',`function prior(p,n){if(n===1)return'NONE';return p.stages.slice(0,n-1).map((s,i)=>{const batch=batchDigest(s);return \`===== STAGE \${i+1} — \${STAGES[i][0]} =====\\n\${s.response||'NO STAGE SUMMARY'}\${batch?\`\\n\\nBATCH RECORDS\\n\${batch}\`:''}\\n\\nEVIDENCE / NOTES\\n\${s.notes||'NONE'}\`}).join('\\n\\n')}
`);
s=replaceBetween(s,'function runPrompt(p,n,i,role){','function requireText(t,label,min=100){',`function runPrompt(p,n,i,role,targetOverride=''){gate(p,n);const rid=\`RUN-\${String(i+1).padStart(3,'0')}\`,base=prompt(p,n);let target='';if(role==='verifier'){if(n===12)target=p.stages[10].producers[i]||'';else if(n===19)target=p.stages[17].producers[i]||'';else if(n===20)target=targetOverride||p.stages[19].producers[i]||'';if(!String(target).trim())throw Error(\`Verifier prompt for \${rid} is blocked until that run's actual producer output exists.\`)}return \`\${base}\\n\\n\${role==='producer'?'INDEPENDENT EXECUTION':'INDEPENDENT VERIFICATION'} RECORD \${rid}\\n\${role==='producer'?\`Execute \${rid} in a fresh context. Do not read or reuse any other run output. Return this run's complete actual output and evidence.\`:\`Verify \${rid} independently against every mandatory requirement and approved test. Do not trust the producing run's conclusion.\\n\\nTARGET RUN OUTPUT TO VERIFY:\\n\${target}\`}\`}
`);
const oldRequire="function requireText(t,label,min=100){t=String(t||'').trim();if(t.length<min)throw Error(`${label} is required and must contain a substantive completed result (minimum ${min} characters).`);return t}";
const newRequire="function requireText(t,label,min=100){const raw=String(t??''),checked=raw.trim();if(checked.length<min)throw Error(`${label} is required and must contain a substantive completed result (minimum ${min} characters).`);return raw}";
if(!s.includes(oldRequire))throw new Error('requireText exact-byte preservation patch anchor missing');
s=s.replace(oldRequire,newRequire);
const oldHandler=`document.querySelectorAll('[data-rprompt]').forEach(b=>b.onclick=()=>{const [role,i]=b.dataset.rprompt.split(':');copyText(runPrompt(p,n,Number(i),role))});`;
const newHandler=`document.querySelectorAll('[data-rprompt]').forEach(b=>b.onclick=()=>{const [role,i]=b.dataset.rprompt.split(':'),idx=Number(i),target=role==='verifier'&&n===20?(document.querySelector(\`[data-producer="\${idx}"]\`)?.value||''):'';try{copyText(runPrompt(p,n,idx,role,target))}catch(e){$('stageMsg').textContent=e.message;setStatus(e.message,true)}});`;
if(!s.includes(oldHandler))throw new Error('Run-prompt click handler patch anchor missing');s=s.replace(oldHandler,newHandler);
s=s.replaceAll('Closed-Loop Reliability v11','Closed-Loop Reliability v12').replaceAll('Closed-Loop Agent Reliability v11','Closed-Loop Agent Reliability v12').replaceAll('schemaVersion:11','schemaVersion:12').replaceAll("schemaVersion!==11","schemaVersion!==12").replaceAll("closedLoopReliability.projects.v11","closedLoopReliability.projects.v12").replaceAll("closedLoopReliability.selected.v11","closedLoopReliability.selected.v12").replaceAll('__CLR_V11__','__CLR_V12__').replaceAll('valid v11 project export','valid v12 project export');
fs.writeFileSync('app-v12.html',s);
console.log(JSON.stringify({status:'BUILT',input:'app-v11.html',output:'app-v12.html',bytes:Buffer.byteLength(s),verifierTargetBinding:s.includes('TARGET RUN OUTPUT TO VERIFY:'),fullPriorContext:s.includes("p.stages.slice(0,n-1)"),exactArtifactBytes:s.includes('const raw=String(t??\'\')')},null,2));
