(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const text=e=>(e?.textContent||'').trim();
function clickView(name){const b=$$('[data-view]').find(x=>x.dataset.view===name);b?.click();}
function clickStage(n){const b=$$('[data-stage]').find(x=>Number(x.dataset.stage)===Number(n));if(b)b.click();else{clickView('Workflow');setTimeout(()=>{const s=$('#stage-picker');if(s){s.value=String(n);s.dispatchEvent(new Event('change',{bubbles:true}));}},60);}}
function currentStageNumber(){const fact=$$('.fact').find(x=>/Current stage/i.test(text($('span',x))));const m=text($('strong',fact)).match(/\d+/);if(m)return Number(m[0]);const m2=text($('.hero h2')).match(/Stage\s+(\d+)/i);return m2?Number(m2[1]):1;}
function addButton(row,label,fn,kind=''){const b=document.createElement('button');b.type='button';b.className=`compact-button ${kind}`.trim();b.textContent=label;b.addEventListener('click',fn);row.appendChild(b);return b;}
function sectionByTitle(title,root=document){return $$('.panel',root).find(p=>text($(':scope > .section-title',p))===title);}
function ensureAnchor(panel,id){if(panel&&!panel.id)panel.id=id;}
function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});}
function enhanceHeader(){const h=$('.brand h1');if(h&&text(h)!=='Reliability Workbook')h.textContent='Reliability Workbook';const p=$('.brand p');if(p&&!p.dataset.experienceLabel){p.dataset.experienceLabel='1';p.insertAdjacentHTML('beforebegin','<div class="brand-kicker">Mobile closed-loop control</div>');}}
function enhanceOverview(screen){if($('.overview-actions',screen))return;
 const hero=$('.hero',screen);if(hero){hero.classList.add('project-hero');const p=$('.hero p',hero);if(p)p.classList.add('objective-preview');}
 const next=sectionByTitle('Next action',screen);if(next){next.classList.add('next-action-panel');const row=document.createElement('div');row.className='button-row overview-actions';addButton(row,'Continue current stage',()=>clickStage(currentStageNumber()),'primary');addButton(row,'View project information',()=>clickView('Project'));addButton(row,'View complete record',()=>clickView('Records'));next.appendChild(row);}
 const contents=sectionByTitle('Project contents',screen);if(contents){const grid=$('.grid-3',contents);if(grid&&!$('.fact[data-controlled-stages]',grid)){const extra=document.createElement('div');extra.className='fact';extra.dataset.controlledStages='1';extra.innerHTML='<strong>30</strong><span>Controlled stages</span>';grid.appendChild(extra);grid.classList.add('overview-counts');}}
 const workflow=sectionByTitle('30-stage workflow',screen);if(workflow&&!workflow.dataset.compacted){workflow.dataset.compacted='1';const list=$('.workflow-list',workflow);if(list){const wrap=document.createElement('details');wrap.className='workflow-disclosure';const done=($('#progress-label')?.textContent||'').split(' ')[0]||'';wrap.innerHTML=`<summary><span>All 30 stages</span><strong>${done} complete</strong></summary>`;list.replaceWith(wrap);wrap.appendChild(list);const row=document.createElement('div');row.className='button-row';addButton(row,'Open workflow',()=>clickView('Workflow'),'primary');workflow.appendChild(row);}}
 if($('#current-project-summary')?.textContent.includes('JOB-20260823144121')&&!$('.completed-work-panel',screen)){const quick=document.createElement('div');quick.className='panel completed-work-panel';quick.innerHTML='<h2 class="section-title">Completed work</h2><p class="section-intro">Operation 01 is preserved as the completed job definition. Open the exact stage record, instruction, output, or receipt from the project record.</p><div class="button-row" data-completed-actions></div>';const target=next?.nextElementSibling||contents;screen.insertBefore(quick,target||null);const row=$('[data-completed-actions]',quick);addButton(row,'Open Stage 01',()=>clickStage(1));addButton(row,'Instruction',()=>openRecordGroup('Generated instructions'));addButton(row,'Output',()=>openRecordGroup('Generated outputs'));addButton(row,'Output receipt',()=>openRecordGroup('Output receipts'));}
}
function openRecordGroup(name){clickView('Records');setTimeout(()=>{const d=$$('details.record-card').find(x=>text($(':scope > summary',x)).includes(name));if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'start'});}},80);}
function groupProjectFields(panel){if(!panel||panel.dataset.grouped)return;panel.dataset.grouped='1';const grid=$(':scope > .grid-2',panel);if(!grid)return;const fields=$$('.field',grid);const byLabel=new Map(fields.map(f=>[text($('label',f)),f]));const group=(title,labels,open=false)=>{const d=document.createElement('details');d.className='project-field-group';if(open)d.open=true;const s=document.createElement('summary');s.innerHTML=`<span>${title}</span><span>${labels.filter(l=>byLabel.has(l)).length} fields</span>`;d.appendChild(s);const body=document.createElement('div');body.className='grid-2 project-field-grid';for(const l of labels){const f=byLabel.get(l);if(f)body.appendChild(f);}d.appendChild(body);return d;};
 const identity=['Job ID','Project title','Owner','Date opened'];
 const input=['Exact user objective','Exact deliverable requested','Supplied materials inventory','Required output format','Deadline or time scope','Known governing sources','Available tools','Prohibited actions','Explicit user requirements','Assumptions','Unknown information','Input set contents','Input set hash or manifest'];
 const control=['Job record status','Status evidence','Current iteration','Input version','Source set version','Requirements version','Test suite version','Instruction version','Baseline ID','Product ID','Current blockers','Next required action','Latest evidence reference'];
 const shell=document.createElement('div');shell.className='project-groups';shell.append(group('Project identity',identity,true),group('Authorized job input',input,true),group('Workflow control',control,false));grid.replaceWith(shell);}
function enhanceProject(screen){if($('.project-groups',screen))return;const panel=sectionByTitle('Project information',screen);groupProjectFields(panel);if(panel){const intro=$('.section-intro',panel);if(intro)intro.textContent='Edit the human job definition here. Workflow-control fields are available separately so the primary project information stays readable.';}}
function enhanceWorkflow(screen){if($('.stage-jumpbar',screen))return;const hero=$('.hero',screen);if(hero){hero.classList.add('stage-hero');const n=currentStageNumber();if(!$('.stage-action-strip',hero)){const strip=document.createElement('div');strip.className='stage-action-strip';strip.innerHTML=`<span>Stage ${String(n).padStart(2,'0')}</span><span>${text($('.status',hero))}</span>`;hero.appendChild(strip);}}
 const work=sectionByTitle('Stage information',screen),instruction=sectionByTitle('Generated instruction',screen),output=sectionByTitle('Agent output or response',screen),decision=sectionByTitle('Stage decision',screen);ensureAnchor(work,'stage-work');ensureAnchor(instruction,'stage-instruction');ensureAnchor(output,'stage-output-section');ensureAnchor(decision,'stage-decision-section');if(work){$('.section-title',work).textContent='Work for this stage';const intro=$('.section-intro',work);if(intro)intro.textContent='Enter only information established for this stage. Save records separately so evidence and relationships remain traceable.';}
 if(instruction){$('.section-title',instruction).textContent='Instruction to run';const pre=$('#generated-prompt',instruction);if(pre){pre.classList.add('expandable-prompt');const row=$('.button-row',instruction);if(row&&!$('[data-toggle-prompt]',row)){const b=document.createElement('button');b.type='button';b.dataset.togglePrompt='1';b.textContent='Expand instruction';b.onclick=()=>{pre.classList.toggle('expanded');b.textContent=pre.classList.contains('expanded')?'Collapse instruction':'Expand instruction';};row.appendChild(b);}}}
 if(output){$('.section-title',output).textContent='Returned output';const intro=$('.section-intro',output);if(intro)intro.textContent='Paste the complete returned result. Saving it creates a permanent project output and linked receipt.';}
 if(decision){$('.section-title',decision).textContent='Stage decision and evidence';}
 const controls=$$(':scope > details.record-card',screen).filter(d=>['Human completion checks','Stage completion gate','Evidence preserved'].some(x=>text($(':scope > summary',d)).startsWith(x)));if(controls.length){const shell=document.createElement('details');shell.className='record-card completion-controls';const counts=controls.map(d=>text($(':scope > summary span',d))).filter(Boolean).join(' · ');shell.innerHTML=`<summary>Completion controls<span>${counts||'Review when ready'}</span></summary><div class="record-body completion-control-body"></div>`;controls[0].before(shell);const body=$('.completion-control-body',shell);controls.forEach(d=>body.appendChild(d));}
 const support=$$(':scope > details.record-card',screen).find(d=>text($(':scope > summary',d)).startsWith('Add supporting record'));if(support){support.id='stage-support';const summary=$(':scope > summary',support);if(summary&&summary.childNodes[0])summary.childNodes[0].textContent='Supporting records';}
 const nav=document.createElement('div');nav.className='stage-jumpbar';[['Work','stage-work'],['Instruction','stage-instruction'],['Output','stage-output-section'],['Decision','stage-decision-section'],['Support','stage-support']].forEach(([label,id])=>addButton(nav,label,()=>go(id)));const navPanel=$('.stage-nav',screen)?.closest('.panel');if(navPanel)navPanel.appendChild(nav);
}
function enhanceRecords(screen){if($('#record-filter',screen))return;const panel=sectionByTitle('Complete project record',screen);if(!panel)return;const stack=$('.record-stack',panel);if(!stack)return;const tools=document.createElement('div');tools.className='record-tools';tools.innerHTML='<label for="record-filter">Find project information</label><input id="record-filter" type="search" placeholder="Search saved records, IDs, evidence, stages…"><div class="button-row record-shortcuts" data-record-shortcuts></div>';stack.before(tools);const input=$('#record-filter',tools);input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();$$(':scope > details.record-card',stack).forEach(d=>{const hay=text($(':scope > summary',d)).toLowerCase()+' '+text(d).toLowerCase();d.hidden=Boolean(q)&&!hay.includes(q);});});const row=$('[data-record-shortcuts]',tools);for(const name of ['Stage records','Generated instructions','Generated outputs','Output receipts','Blockers','Changes','History'])addButton(row,name.replace('Generated ','').replace(' records',''),()=>openRecordGroup(name));}
function enhanceFiles(screen){const p=sectionByTitle('Project files',screen);if(!p||p.dataset.experienceFiles)return;p.dataset.experienceFiles='1';const intro=$('.section-intro',p);if(intro)intro.textContent='File identity records preserve name, size, type, stage, and SHA-256 when bytes were available. Browser-retained metadata does not imply the file bytes are stored.';}
function enhanceRelease(screen){const hero=$('.hero',screen);if(!hero||hero.classList.contains('release-hero'))return;hero.classList.add('release-hero');}
function enhance(){enhanceHeader();const screen=$('#screen');if(!screen)return;if($('#stage-picker',screen))enhanceWorkflow(screen);else if($('[data-job]',screen))enhanceProject(screen);else if(sectionByTitle('Complete project record',screen))enhanceRecords(screen);else if(sectionByTitle('Project files',screen))enhanceFiles(screen);else if(sectionByTitle('Release gate',screen))enhanceRelease(screen);else if(sectionByTitle('Next action',screen))enhanceOverview(screen);}
let queued=false;const queue=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance();});};new MutationObserver(queue).observe(document.documentElement,{childList:true,subtree:true});addEventListener('load',queue);document.addEventListener('click',e=>{if(e.target.closest('[data-view],[data-stage]'))setTimeout(queue,0);});document.addEventListener('change',e=>{if(e.target.id==='stage-picker')setTimeout(queue,0);});queue();
})();
