from pathlib import Path
import re

p=Path('prompt-engine.js')
text=p.read_text()

procedures = r'''const procedures={
1:'Perform complete human-authority intake and nothing later. Read the entire current human job input and every supplied material that is actually accessible in this execution context. Preserve every materially relevant human-supplied fact, requirement, constraint, decision, prohibition, requested output, acceptance condition, material reference, dependency, exception, and unresolved human-only issue without collapsing distinct meaning. For each APPLICATION INTAKE MANIFEST unit, classify it exactly once and extract every distinct material statement it contains into INPUT_SET_CONTENTS. If a supplied artifact is accessible, inspect it deeply enough to capture all human-authority statements needed to define the job; if its bytes are unavailable, preserve the material reference and do not infer contents from its filename. Derive the complete foreseeable set of genuinely human-only questions required to define the requested outcome. Ask BLOCKING_NOW and ASK_NOW_NONBLOCKING questions conversationally before final JSON; ASK_NOW_NONBLOCKING may be answered UNKNOWN or DEFERRED but may not be silently skipped. Do not ask questions that supplied material, authorized research, or a later stage can resolve. Do not perform source research, authority ranking, requirement atomization, test design, production design, generation, filing, simulation, manufacturing, or verification. Do not return final JSON until objective, deliverable, material set, intake accounting, and every foreseeable ask-now human-only issue are closed or explicitly deferred. The accepted semantic capture is durable project memory for every later stage, so later stages must not ask the human to resupply the original intent or repeat captured project information.',
2:'Build only the independent external source inventory for the current job. Use the complete accepted Stage 01 project definition and current human-authority memory to determine what external authority or evidence could govern, inform, or prove correctness. Do not treat supplied project artifacts, the target product, this application, its repository, generated prompts, generated outputs, or prior target versions as independent external authority merely because they exist. Inspect legitimate external sources deeply enough to establish identity, issuer/author, publication origin, source type, authority level and role, relevance, applicable portions, currency, supersession, controlling state, and material conflicts. Prefer primary/official/controlling authority where it exists; otherwise use the most direct reputable current evidence appropriate to the proposition. Do not invent a source to satisfy a count. If no applicable independent external source exists after supported inspection, return the explicit no-applicable-source determination. Do not perform Stage 03 requirement research or derive requirements.',
3:'Research only the complete current accepted Stage 02 external source set and exhaust it before Stage 04. For every current source, inspect every applicable portion needed for this job and preserve mandatory statements, recommendations, optional practices, examples, explanatory material, prohibitions, exceptions, dependencies, applicability facts, restrictions, invalidating material, conflicts, supersession, source evidence, candidate obligations, and unresolved gaps without compressing away distinct meaning. Perform an initial extraction pass, then a complete conflict/exception/completeness pass across the entire current source set. If any pass discovers a new material category, obligation, exception, restriction, dependency, conflict, applicability fact, or invalidating condition, perform another complete pass. Stage 03 is not complete until the latest complete pass discovers no new material category and every current Stage 02 source has current coverage, unless Stage 02 validly established NO_APPLICABLE_EXTERNAL_SOURCE. Do not invent findings, use project artifacts as authority, atomize the final requirement specification, design tests, or perform production work.',
4:'Compile the complete atomic requirement specification and nothing later. Consume the entire APPLICATION OBLIGATION MANIFEST, complete accepted Stage 01 semantic job definition, complete current human-authority project memory, complete exhausted Stage 03 research/candidate obligations, applicable source identities, and evidence included in this prompt. Never ask the human to repeat, restate, summarize, reconstruct, reattach, or resend information already captured. Do not rediscover an unspecified input universe. For every obligationId, either map it to one or more proposed requirements or give exactly one valid non-requirement disposition: RETAINED_NONNORMATIVE_CONTEXT, INAPPLICABLE, or BLOCKED, with a reason. No obligation may disappear. Split compound obligations until each resulting requirement is independently testable to the extent the proposition permits. Preserve every original obligation identity independently even when materially equivalent obligations map to one requirement. For each requirement define obligation, type, mandatory/optional status, provenance/source relationship, applicability, dependencies, prohibitions, defined terms, observable satisfaction condition, intended verification semantics, expected evidence, failure condition, severity, and notes needed to prevent semantic loss. Do not perform Stage 05 resolution, Stage 06 test design, or production.',
5:'Resolve the current requirement set and nothing later. Review every current requirement and the complete Stage 04 accounting for duplicates, semantic overlap, conflicts, impossible combinations, undefined terms, circular dependencies, missing prerequisites, unsupported requirements, uncertain applicability, and requirements lacking a viable verification path. Preserve every defect and governing evidence. Resolve what can be resolved from current authority; when a genuine human tradeoff is required, ask only that human-only decision and do not ask for already captured facts. Any changed requirement must preserve provenance and trigger the application-controlled new requirements version and downstream invalidation. Do not design tests or production instructions.',
6:'Build the verification suite before production instructions exist. For every current active mandatory requirement, create at least one complete test that can actually establish the proposition. Define verification semantics, exact execution mode, required capability, exact artifacts/inputs, tools, procedure, expected result, failure condition, and evidence to preserve. For every mandatory requirement explicitly analyze false-positive paths: boundary conditions, partial-success states, stale state, malformed input/state, incorrect authority, wrong artifact, and capability substitution; put direct verification checks here and route realistic invalid/mutation fixtures to Stage 07. Use APPLICATION_DETERMINISTIC only when the proposition is faithfully expressible by the exact registered Test IR capabilities published in this prompt; in that case produce valid Test IR and bindings. If deterministic representation would lose meaning, choose the correct non-native route. Do not execute tests in this stage. Do not claim unavailable capability. Do not author the production instruction.',
7:'Build and execute the failure/mutation tests required to prove invalid states are rejected. For every applicable requirement and validator boundary, define realistic invalid fixtures and expected rejection, then execute them only through a route that actually has the required capability and exact bytes. Fixture definition is not execution. Preserve the actual observed result and sufficient evidence. If invalid input is accepted, identify the linked validator defect. Cover applicable missing inputs, invalid values, wrong versions, duplicates, contradictions, omitted mandatory material, prohibited material, corrupt references, malformed files/state, conflicting authority, unavailable capability substitution, injected source instructions, and known-invalid artifacts. If execution cannot occur, return the correct blocker or execution failure instead of a synthetic pass.',
8:'Author the complete current production instruction from the resolved requirements and verification architecture. Include objective, authorized inputs, authority rules, input-failure rules, scope, prohibitions, defined terms, ordered procedure, branches/decision rules, exact tool rules, output contract, factual-state handling, rejection/blocking behavior, verification/failure handling, completion criteria, and complete requirement traceability. Adapt the instruction to the actual artifact types, interfaces, toolchain, transformations, scale, and delivery requirements derived from the project; do not inject a hard-coded project-subject checklist. Every current mandatory requirement must be implemented or explicitly blocked in the instruction trace. Do not execute production.',
9:'Independently preflight the complete current production instruction and nothing later. Review every material clause in an independent context from the author for ambiguity, multiple interpretations, undefined objects, unsupplied dependencies, internal conflict, unavailable capability, objective verifiability, responsible operation, ordering, failure behavior, completeness, and requirement traceability. Review all material clauses; do not sample. Preserve findings and exact corrections. If any material correction is required, the instruction must receive a new controlled version and preflight must repeat. Do not execute target production.',
10:'Freeze the exact test candidate. The human selects the authorized components; the application assigns iteration/candidate identity, freezes exact current component identities and verified bytes, calculates hashes, and prevents in-place mutation. Review only substantive candidate completeness, component roles, immutable locations, required tool configuration/settings/permissions/limitations, and whether the exact frozen package is sufficient to execute unchanged. Do not invent IDs, hashes, versions, or change the selected components.',
11:'Execute exactly the application-reserved ten-run batch. For the current reserved RUN_ID and CONTEXT_ID, use only the identical frozen candidate and authorized inputs. Do not expose outputs from other runs, reviewer feedback, failure explanations, RCA, or corrections. Preserve complete output, actual tool configuration, actual tool failures, contamination facts, output artifacts, and evidence for this lane. Never create substitute run/context identities. Across the batch, exactly ten fresh distinct contexts must execute the same candidate; the application calculates the batch counts, equality, and independence consequences.',
12:'Verify every currently missing REQ_ID × RUN_ID × TEST_ID cell independently, only in the application-provided VERIFICATION BATCH PLAN and listed order. Use the exact test definition, executor, capability, artifacts, and evidence requirements. Do not substitute executors. A reviewer may not self-validate the generating run, reuse the generator context, see another verifier conclusion, Stage 13 comparison, RCA, or proposed corrections. If a required executor/capability/artifact is unavailable, do not claim execution; return the correct undetermined/blocking/failure disposition. For each executed cell preserve required/observed result, exact evidence, determination, and defect link where applicable. The application owns independence determination where observable, evidence-sufficiency consequence, counts, and matrix completion.',
13:'Compare the complete ten-run iteration requirement-by-requirement. Include all ten current valid runs and preserve substantive variance, interpretation differences, output differences, authorized versus prohibited variance evidence, inconclusive tests, repeated/unique failure patterns, correctness-affecting disagreement, and linked defects. Do not discard inconvenient runs or recalculate application-owned counts. The application derives all-ten satisfaction, violation/undetermined flags, stability metrics, and defect counts.',
14:'Root-cause every current material defect. Trace backward through the relevant product/output, execution, instruction, requirement, research, source, human input, tool/configuration, and evidence chain until the earliest defective layer is identified. Preserve category, trace, earliest defective layer, evidence-supported root cause, and required invalidation/rework. Unknown RCA remains blocked. Do not patch only the symptom or change an upstream layer without evidence.',
15:'Convert every confirmed defect into a permanent regression definition and prove the original failure with an actual pre-correction execution. Preserve the exact failure fixture, reproduction procedure, detection method, sufficient pre-correction evidence, and permanent applicability. The pre-correction execution must actually fail in the expected way; a statement that the test would detect the defect is insufficient. Do not claim post-correction success in this stage. The later correction must be proven by a distinct later execution.',
16:'Correct only the earliest responsible layer identified by the accepted RCA. For every confirmed root cause, propose the exact controlled correction or blocker, identify affected artifacts/records, preserve old versions, state required reruns, and distinguish execution-only failure from instruction/requirement/test/source defects. Do not ask the human to determine the responsible layer. Ask the human only for genuine authority/authorization that cannot come from canonical state. Never modify controlled material in place. The application owns IDs, new versions, hashes, invalidation, and rerun selection.',
17:'Run the complete corrected ten-execution iteration through the declared Stage 17 operation only. Use the application-assigned corrected iteration/candidate and reserved run/context identities. Freeze the corrected candidate, execute exactly ten new independent contexts with prior outputs withheld, verify the complete applicable matrix, compare all runs, root-cause every new material defect, execute required regressions, and perform only evidence-supported corrections through their declared suboperations. Completion flags/counts are application-derived; do not shortcut the cycle.',
18:'Evaluate convergence only from the latest completed current iteration. Explain remaining defects, blockers, mandatory unknowns, contradictions, ambiguities, missing evidence, or unexplained correctness-affecting variance. Do not set application-owned metrics. Convergence requires complete mandatory specification/verification coverage, all applicable regressions successful, and simultaneous zero counts for critical/major defects, mandatory unresolved unknowns, correctness-affecting contradictions/ambiguities, and unexplained correctness-affecting execution variance. If not converged, identify the earliest return stage supported by evidence.',
19:'Perform the unchanged confirmation iteration with zero material changes to the converged candidate. First confirm the semantic freeze using the exact application operation/identity; then use ten new distinct contexts, the exact same frozen package/versions/hashes, the complete current verification suite, and every applicable regression. Compare all runs and report any new requirement, missed failure, material defect, contradiction, or correctness-affecting variance. Do not alter the candidate. The application derives unchanged status, completeness, counts, and final confirmation determination.',
20:'Freeze the production baseline only after successful unchanged confirmation and explicit human baseline authorization. Review the exact approved components for substantive discrepancy or blocker. The application assigns baseline identity, freezes the approved versions and exact bytes, calculates hashes, preserves immutable baseline identity, and separates baseline material from working files. Do not invent baseline identity, hash, approval, or status.',
21:'Generate the complete approved finished product from the exact production baseline in a fresh production context using only approved baseline materials. Produce every required actual artifact that the authorized environment can reliably construct; do not downgrade the deliverable merely because a downstream consuming tool is unavailable. Treat import/open validation, compilation, simulation, post-processing, machine execution, deployment, filing/submission, fabrication, and physical testing as separate operations unless they actually occur in a capable authorized environment. Preserve actual output artifacts and execution observations. The application owns product/execution IDs, exact stored bytes, filenames, sizes, hashes, and lineage.',
22:'Handle only deterministic finished-product verification work that is not executed natively by the application. Native supported Test IR tests are run by the application worker and produce application-owned results; an external agent must never impersonate, repeat, or fabricate native execution. For each externally routed deterministic test, use exactly the declared external capability, exact product bytes, test specification, and evidence contract. Preserve actual observations, tool/system metadata, returned artifacts, and evidence so the application can normalize the result. Unsupported or unavailable deterministic capability must remain blocked/undetermined rather than being synthesized as a pass.',
23:'Perform independent meaning-based verification only for requirements whose substantive meaning cannot be established by deterministic checks. Use a fresh independent reviewer context and only the authorized bounded projection. For each applicable requirement preserve exact product location, governing source evidence where applicable, required meaning, observed meaning, evidence-based comparison, determination, defect, and reason for any undetermined result. Derive the review dimensions from the current requirements, artifact semantics, interfaces, and acceptance conditions; do not inject a project-subject checklist. Do not rely on generator self-evaluation or unnecessary deterministic conclusions.',
24:'Perform independent adversarial verification of the finished product using only authorized context. Deliberately challenge every applicable attack category and every active historical regression/failure pattern that applies. Test for missing/prohibited material, contradictions, impossible logic, unsupported facts, authority misrepresentation, wrong versions, broken references, hidden assumptions, partial completion, semantic nonsense, terminology inconsistency, unhandled exceptions, stale facts/state, malformed artifacts, hidden content, representation/export corruption, superficial keyword compliance, and project-derived failure modes. Preserve actual attack method, expected behavior, observed result, severity, evidence, and defect/blocker. Do not claim attacks not executed and do not expose generator reasoning or prior conclusions that bias the attack.',
25:'Inspect the exact final representation and delivery package. Open or inspect every required product/delivery artifact, representation, page/view, transformation, and packaged file using the correct capable route. Derive required inspection dimensions from the current requirements and governing evidence rather than a hard-coded subject checklist. Preserve substantive rendering/opening observations, missing/blank content, clipping, overlap, layout/graphics/font issues, hidden content, ordering, transformation/export/package corruption, and irreducible human/reviewer judgments. The application owns objective filename, version, byte size, hash, transformation identity, and counts.',
26:'Reconcile current process evidence and current product evidence as separate propositions. Review the complete current process audit and product audit, identify discrepancies, unauthorized modification, chain-of-custody issues, missing evidence links, contradictions, defects, blockers, and unsupported conclusions. Do not treat process correctness as proof of product correctness or vice versa. The application owns current identities, counts, contradiction effects, and reconciled gate consequences.',
27:'Provide advisory release-evidence analysis only. Review the complete current release evidence for substantive blockers, violations, missing/insufficient evidence, stale evidence, contradictions, unresolved defects, and unsupported conclusions. Do not set release state, controlling rule, counts, or authorization. The application alone derives exactly one idempotent ACCEPTED, REJECTED, or BLOCKED release result from current sufficient noncontradictory evidence.',
28:'Support artifact-identity investigation only where human/agent interpretation is genuinely needed. The application performs authoritative immediate pre-delivery byte identity: exact canonical artifact relationship, authorized filename, byte size, and SHA-256 from actual bytes, independent of file order. Do not assert identity from a filename, metadata claim, agent hash, array position, or stale audit. Human authority may select/authorize delivery artifacts; the application calculates identity and delivery-authorization consequence.',
29:'Investigate only evidence-chain links the application identifies as missing, uncertain, or insufficient. For every mandatory requirement, reason about the current chain from human/external authority through requirement, instruction trace, execution/product element, every applicable test, every required result, sufficient canonical evidence, current release, and applicable released artifact identity. Do not fabricate links, substitute raw response IDs for evidence IDs, or treat structural existence as proof when evidence cannot establish the proposition. The application constructs and gates the canonical evidence graph.',
30:'Preserve permanent defect/regression meaning and provide substantive findings/correction evidence only where needed. Never rewrite history. Every confirmed defect must retain a permanent regression definition, preserved failure evidence, and applicable execution history. Corrections are new superseding records, not edits to prior history. Latest applicable regression execution must succeed before baseline approval. The application owns registry identity, append-only lifecycle, counts, integrity, and final registry determination.'
};'''
text, count = re.subn(r"const procedures=\{.*?\n\};\nconst recordId=", procedures + "\nconst recordId=", text, count=1, flags=re.S)
if count != 1:
    raise SystemExit('procedures block replacement failed')

# Make durable captured project memory visible to every later stage without asking the human again.
old = "function contextFor(stage,state,operation,scope={}){\n const parts=[];\n if(stage===1)parts.push('APPLICATION INTAKE MANIFEST\\n'+show(workflow.intakeCoverageManifest(state)));"
new = "function contextFor(stage,state,operation,scope={}){\n const parts=[];\n if(stage===1)parts.push('APPLICATION INTAKE MANIFEST\\n'+show(workflow.intakeCoverageManifest(state)));\n if(stage>1){parts.push('DURABLE PROJECT MEMORY — HUMAN AUTHORITY AND ACCEPTED STAGE 01 SEMANTIC CAPTURE — DO NOT ASK THE HUMAN TO RESUPPLY IT\\n'+show({humanJobInput:Object.fromEntries(Object.entries(schema.JOB_FIELDS||{}).filter(([,d])=>['HUMAN','HUMAN_DECISION'].includes(d?.producer)).map(([name])=>[name,state?.job?.[name]??null])),stage01:{agentData:state?.stages?.[1]?.agentData||state?.stages?.[1]?.acceptedData||{},humanData:state?.stages?.[1]?.humanData||{},derivedData:state?.stages?.[1]?.derivedData||{}},currentInputVersion:state?.job?.CURRENT_INPUT_VERSION||null}));}"
if old not in text:
    raise SystemExit('contextFor anchor missing')
text=text.replace(old,new,1)

# Remove duplicate Stage 01 block in Stage 04 now that durable project memory is universal.
text=text.replace(" if(stage===4&&state?.stages?.[1]){const intake={agentData:state.stages[1].agentData||state.stages[1].acceptedData||{},humanData:state.stages[1].humanData||{},derivedData:state.stages[1].derivedData||{}};parts.push(`ACCEPTED STAGE 01 JOB DEFINITION — CURRENT HUMAN-AUTHORITY CAPTURE\\n${show(intake)}`);}\n","")

# Strengthen Stage 04's explicit dependency payload.
text=text.replace("COMPLETE EXHAUSTED STAGE 03 STAGE DATA — USE IT ALL\\n'+show({agentData:state?.stages?.[3]?.agentData||{},humanData:state?.stages?.[3]?.humanData||{},derivedData:state?.stages?.[3]?.derivedData||{}})","COMPLETE EXHAUSTED STAGE 03 STAGE DATA — USE IT ALL\\n'+show({agentData:state?.stages?.[3]?.agentData||{},humanData:state?.stages?.[3]?.humanData||{},derivedData:state?.stages?.[3]?.derivedData||{},research:(state?.projectData?.research||[]).filter(x=>x?.active!==false&&!x?.invalidatedBy),candidateRequirements:(state?.projectData?.candidateRequirements||[]).filter(x=>x?.active!==false&&!x?.invalidatedBy),sources:(state?.projectData?.sources||[]).filter(x=>x?.active!==false&&!x?.invalidatedBy),evidenceRecords:(state?.projectData?.evidenceRecords||[]).filter(x=>x?.active!==false&&!x?.invalidatedBy)}))")

# Subject-neutral wording and exact application/native boundary.
repls={
"This static browser is not a universal compiler, script runner, CAD/CAE tool, lab, or machine controller.":"This static browser is not a universal compiler, arbitrary script runner, specialized external tool, laboratory, or physical machine controller.",
"Never claim that a web search, repository edit, build, test, CAD operation, simulation, CNC post-processing step, physical measurement, fabrication, filing, submission, or other external action occurred unless it actually occurred":"Never claim that a search, repository edit, build, test, specialized tool operation, external-system operation, physical observation, submission, or other external action occurred unless it actually occurred"
}
for old,new in repls.items(): text=text.replace(old,new)
text=re.sub(r"const PROMPT_ENGINE_VERSION='closed-loop-prompt-engine/\d+';","const PROMPT_ENGINE_VERSION='closed-loop-prompt-engine/34';",text,1)
p.write_text(text)

# Preserve established visuals: this repair intentionally does not modify index.html or app-core rendering/CSS.

# Correct the Stage 02 workbook gate wording only; do not alter visual/UI structure.
p=Path('workbook.js')
text=p.read_text().replace("'Every relied-upon supplied file was inspected'","'Supplied project material was not misclassified as independent external authority'",1)
p.write_text(text)
