(()=>{
'use strict';
const STORE='mobile-closed-loop-agent';
const REGISTRY='closed-loop-project-registry-v3';
const LEGACY_REGISTRY='closed-loop-project-registry-v2';
const ACTIVE='closed-loop-active-project-v3';
const TEST_KEY='test-project';
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const now=()=>new Date().toISOString();
const makeId=(prefix='JOB')=>`${prefix}-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;
const label=s=>String(s||'').replace(/([a-z0-9])([A-Z])/g,'$1 $2').replace(/[_-]+/g,' ').replace(/^./,c=>c.toUpperCase());
const readState=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}};
const writeState=s=>localStorage.setItem(STORE,JSON.stringify(s));
const readRegistry=()=>{try{return JSON.parse(localStorage.getItem(REGISTRY)||'{}')}catch{return {}}};
const writeRegistry=r=>localStorage.setItem(REGISTRY,JSON.stringify(r));
const activeKey=()=>localStorage.getItem(ACTIVE)||Object.keys(readRegistry())[0]||'';
const setActive=k=>localStorage.setItem(ACTIVE,k);
const entries=s=>Object.entries(s?.stages||{}).map(([k,v])=>[Number(k),v]).filter(([n,v])=>Number.isFinite(n)&&v).sort((a,b)=>a[0]-b[0]);
const stageTitle=(s,n)=>s?.stages?.[n]?.title||s?.stages?.[n]?.name||`Stage ${pad(n)}`;
const stateClass=v=>/BLOCK|VIOLAT|REJECT|OPEN|FAIL/i.test(v||'')?'blocked':/SATISF|ACCEPT|COMPLETE|READY|CONFIRM|RESOLVED|FROZEN/i.test(v||'')?'satisfied':/UNKNOWN|UNDETERMINED|NOT STARTED|NOT READY/i.test(v||'')?'warn':'';
const isFilled=v=>v!==undefined&&v!==null&&String(v).trim()!==''&&!/<<[^>]+>>/.test(String(v));
const normalizeOutcome=v=>['UNKNOWN','NONE','NOT APPLICABLE','SATISFIED','VIOLATED','UNDETERMINED','ACCEPTED','REJECTED','BLOCKED'].includes(String(v||'').toUpperCase())?String(v).toUpperCase():v;
function ensureData(s){
  if(!s.projectData)s.projectData=s.testProject?.spec?clone(s.testProject.spec):{};
  const d=s.projectData;
  for(const k of ['sourceInventory','research','requirements','requirementResolution','tests','mutations','generatedPrompts','generatedOutputs','runRecords','freshContexts','verificationRecords','comparisons','defects','regressions','changes','blockers','artifacts','evidenceChains','history'])if(!Array.isArray(d[k]))d[k]=[];
  for(const k of ['productionInstruction','convergence','confirmation','baseline','product','audits','representation','release'])if(!d[k]||typeof d[k]!=='object'||Array.isArray(d[k]))d[k]={};
  if(!d.userEnteredData)d.userEnteredData={};
  if(!d.objective)d.objective={exactUserObjective:s?.job?.EXACT_USER_OBJECTIVE_VERBATIM||'',deliverable:s?.job?.EXACT_DELIVERABLE_REQUESTED||''};
  if(!d.unknowns)d.unknowns=[]; if(!d.assumptions)d.assumptions=[];
  d.title=d.title||s?.job?.JOB_TITLE||'Untitled project';
  d.currentStage=Number(s.activeStage||d.currentStage||1); d.currentState=s?.job?.CURRENT_STATE||d.currentState||'NOT STARTED';
  return s;
}
function recordHistory(s,type,summary,details={}){ensureData(s);s.projectData.history.unshift({id:makeId('HIST'),dateTime:now(),type,summary,details});}
function completeCount(s){return entries(s).filter(([,st])=>/COMPLETE|ACCEPTED|CONFIRMED|FROZEN/i.test(`${st?.status||''} ${st?.decision||''}`)).length;}
function openBlockers(s){return ensureData(s).projectData.blockers.filter(b=>String(b.currentStatus||b.status||'OPEN').toUpperCase()==='OPEN');}
function unresolvedDefects(s){return ensureData(s).projectData.defects.filter(d=>!/CLOSED|RESOLVED|CORRECTED.*VERIFIED/i.test(String(d.status||d.defectStatus||'')));}
function migrateRegistry(){
  let r=readRegistry(); if(Object.keys(r).length)return r;
  let legacy={}; try{legacy=JSON.parse(localStorage.getItem(LEGACY_REGISTRY)||'{}')}catch{}
  const current=readState();
  if(legacy.working)r[legacy.working?.job?.JOB_ID||'working-job']=ensureData(clone(legacy.working));
  if(legacy.retained)r[TEST_KEY]=ensureData(clone(legacy.retained));
  if(!Object.keys(r).length&&current)r[current?.job?.JOB_ID||'working-job']=ensureData(clone(current));
  writeRegistry(r); return r;
}
function saveActive(){const s=readState();const k=activeKey();if(!s||!k)return;ensureData(s);const r=readRegistry();r[k]=clone(s);writeRegistry(r);}
function blankFrom(template){
  const s=clone(template||readState()||{}); ensureData(s);
  const id=makeId('JOB');
  s.createdAt=now(); s.activeStage=1; s.activeView='project'; s.jobRevisions=[]; s.snapshots=[];
  s.job={...(s.job||{}),JOB_ID:id,JOB_TITLE:'',JOB_OWNER:'',DATE_OPENED:now(),CURRENT_ITERATION:'NONE',CURRENT_STAGE:'STAGE 01',CURRENT_STATE:'NOT STARTED',CURRENT_INPUT_VERSION:'INPUT-v001',CURRENT_SOURCE_SET_VERSION:'NONE',CURRENT_REQUIREMENTS_VERSION:'NONE',CURRENT_TEST_SUITE_VERSION:'NONE',CURRENT_INSTRUCTION_VERSION:'NONE',CURRENT_BASELINE_ID:'NONE',CURRENT_PRODUCT_ID:'NONE',CURRENT_BLOCKERS:'NONE',NEXT_REQUIRED_ACTION:'Enter the exact objective and supplied materials.',LATEST_EVIDENCE_REFERENCE:'NONE',EXACT_USER_OBJECTIVE_VERBATIM:'',EXACT_DELIVERABLE_REQUESTED:'',REQUIRED_OUTPUT_FORMAT:'',DEADLINE_OR_TEMPORAL_SCOPE:'',KNOWN_AUTHORITATIVE_SOURCES:'NONE',AVAILABLE_TOOLS:'',PROHIBITED_ACTIONS:''};
  for(const [n,st] of entries(s)){s.stages[n]={...st,status:'NOT STARTED',decision:'',decisionEvidence:'',nextStage:'',decidedBy:'',dateTime:'',responseDraft:'',runId:'',contextId:'',revisions:[],invalidatedBy:[],copyReceipts:[],authorizedFiles:[],humanChecks:{},gateChecks:{},evidenceChecks:{}};}
  s.release={gateState:'',auditedDraft:[],releaseDraft:[],comparisons:[],authorization:'NOT AUTHORIZED',authorizedArtifactIds:[]};
  s.projectData={title:'',objective:{exactUserObjective:'',deliverable:''},userEnteredData:{},sourceInventory:[],research:[],requirements:[],requirementResolution:[],tests:[],mutations:[],productionInstruction:{},generatedPrompts:[],generatedOutputs:[],runRecords:[],freshContexts:[],verificationRecords:[],comparisons:[],defects:[],regressions:[],changes:[],blockers:[],artifacts:[],convergence:{},confirmation:{},baseline:{},product:{},audits:{},representation:{},release:{},evidenceChains:[],unknowns:[],assumptions:[],history:[],currentStage:1,currentState:'NOT STARTED'};
  recordHistory(s,'project-created','New clean project created at Stage 01.');
  return s;
}
async function ensureTestProject(){let r=readRegistry();if(r[TEST_KEY])return;try{const res=await fetch(`TEST_PROJECT.json?v=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(String(res.status));const raw=await res.json();const s=ensureData(raw.state||raw.project||raw);s.projectData.isTestProject=true;s.projectData.title=s.projectData.title||s.job?.JOB_TITLE||'Reliability test project';recordHistory(s,'test-project-loaded','Retained test project loaded through the ordinary project model.');r=readRegistry();r[TEST_KEY]=s;writeRegistry(r);}catch(e){console.error('Test project unavailable',e)}}
function updateHeader(){const s=readState();if(!s)return;ensureData(s);const c=completeCount(s),n=Number(s.activeStage||1);$('#job').textContent=`${s.job?.JOB_TITLE||s.projectData.title||'Untitled project'} · Stage ${pad(n)}`;$('#count').textContent=`${c}/30 complete`;$('#bar').style.width=`${Math.round(c/30*100)}%`;renderPicker();}
function renderPicker(){const picker=$('#project-picker');if(!picker)return;const r=readRegistry(),k=activeKey();picker.innerHTML=Object.entries(r).map(([id,s])=>`<option value="${esc(id)}">${esc(s?.job?.JOB_TITLE||s?.projectData?.title||(id===TEST_KEY?'Test project':'Untitled project'))}</option>`).join('');picker.value=k;}
function showWorkspace(which){for(const id of ['workspace-workbook','workspace-project','workspace-guide'])$(`#${id}`)?.setAttribute('hidden','');$(`#workspace-${which}`)?.removeAttribute('hidden');$$('.header-actions button').forEach(b=>b.dataset.active='false');if(which==='project')$('#project-data-button').dataset.active='true';if(which==='guide')$('#guide-button').dataset.active='true';}
function switchProject(k){saveActive();const r=readRegistry();if(!r[k])return;setActive(k);writeState(clone(r[k]));renderProject('overview');showWorkspace('project');updateHeader();}
function newProject(){saveActive();const r=readRegistry(),template=Object.values(r)[0]||readState(),s=blankFrom(template),key=s.job.JOB_ID;r[key]=s;writeRegistry(r);setActive(key);writeState(clone(s));renderProject('overview');showWorkspace('project');updateHeader();setTimeout(()=>$('#project-title-input')?.focus(),0);}
function removeProject(){const k=activeKey();if(k===TEST_KEY)return alert('The retained test project is part of application verification and cannot be deleted from this control.');const r=readRegistry();if(Object.keys(r).length<=1)return alert('Create another project before deleting this one.');if(!confirm('Delete this project from this browser? Export it first if you need a copy.'))return;delete r[k];const next=Object.keys(r)[0];writeRegistry(r);setActive(next);writeState(clone(r[next]));renderProject('overview');updateHeader();}
function exportProject(){saveActive();const s=readState(),blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${s?.job?.JOB_ID||'project'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function importProject(file){const fr=new FileReader();fr.onload=()=>{try{const s=ensureData(JSON.parse(fr.result));const r=readRegistry(),key=s?.job?.JOB_ID||makeId('JOB');r[key]=s;writeRegistry(r);setActive(key);writeState(clone(s));renderProject('overview');updateHeader()}catch(e){alert(`Import failed: ${e.message}`)}};fr.readAsText(file);}
function value(v,depth=0){
  if(v===null||v===undefined||v==='')return '<span class="muted">None recorded</span>';
  if(Array.isArray(v))return v.length?`<div class="record-stack">${v.map((x,i)=>`<details class="record-card"><summary>${esc(x?.title||x?.outputId||x?.receiptId||x?.reqId||x?.testId||x?.mutationId||x?.defectId||x?.regId||x?.sourceId||x?.artifactId||x?.runId||x?.changeId||x?.blockerId||x?.chainRecordId||x?.id||`Record ${i+1}`)}</summary><div class="record-body">${value(x,depth+1)}</div></details>`).join('')}</div>`:'<span class="muted">None recorded</span>';
  if(typeof v==='object')return `<div class="data-list">${Object.entries(v).map(([k,x])=>`<div class="data-row"><div class="data-key">${esc(label(k))}</div><div class="data-value">${typeof x==='object'&&x!==null?(depth>4?`<pre class="copy">${esc(JSON.stringify(x,null,2))}</pre>`:value(x,depth+1)):esc(normalizeOutcome(x))}</div></div>`).join('')}</div>`;
  return esc(normalizeOutcome(v));
}
const section=(title,body,open=false)=>`<details class="record-card" ${open?'open':''}><summary>${esc(title)}</summary><div class="record-body">${body}</div></details>`;
function actionBanner(s){const blockers=openBlockers(s),d=ensureData(s).projectData,n=Number(s.activeStage||1);if(blockers.length)return `<div class="action-banner danger"><strong>Work is blocked</strong><span>${esc(blockers[0].missingItem||blockers[0].missingEvidenceAuthorityInputOrCapability||blockers[0].whyMandatorySatisfactionCannotBeEstablished||'Mandatory evidence or capability is unavailable.')}</span><button data-project-view="issues">Review blocker</button></div>`;if(d.nextRequiredAction||s.job?.NEXT_REQUIRED_ACTION)return `<div class="action-banner"><strong>Next action</strong><span>${esc(d.nextRequiredAction||s.job.NEXT_REQUIRED_ACTION)}</span><button data-stage-open="${n}">Open Stage ${pad(n)}</button></div>`;return ''}
function projectHero(s){const d=ensureData(s).projectData,b=openBlockers(s),req=d.requirements.length,runs=d.runRecords.length,n=Number(s.activeStage||1);return `<section class="project-hero"><div class="project-hero-top"><div><h2>${esc(s.job?.JOB_TITLE||d.title||'Untitled project')}</h2><p>${esc(s.job?.EXACT_USER_OBJECTIVE_VERBATIM||d.objective?.exactUserObjective||'Enter the exact objective in Stage 01.')}</p></div><span class="status-chip ${stateClass(s.job?.CURRENT_STATE||d.currentState)}">${esc(s.job?.CURRENT_STATE||d.currentState||'NOT STARTED')}</span></div><div class="project-facts"><div class="fact"><strong>${pad(n)}</strong><span>Current stage</span></div><div class="fact"><strong>${b.length}</strong><span>Open blockers</span></div><div class="fact"><strong>${req}</strong><span>Requirements</span></div><div class="fact"><strong>${runs}</strong><span>Runs</span></div></div>${d.isTestProject?'<div class="notice" style="margin-top:9px"><strong>Retained test project.</strong> This is persisted through the same project model and screens as every other project. Its records remain inspectable and unsupported work is not shown as completed.</div>':''}</section>`}
function overview(s){const d=s.projectData;return `<div class="project-panel"><h2>Project</h2>${actionBanner(s)}<div class="edit-grid"><label>Project title<input id="project-title-input" value="${esc(s.job?.JOB_TITLE||d.title||'')}"></label><label>Exact user objective<textarea id="project-objective-input">${esc(s.job?.EXACT_USER_OBJECTIVE_VERBATIM||d.objective?.exactUserObjective||'')}</textarea></label><label>Requested deliverable<textarea id="project-deliverable-input">${esc(s.job?.EXACT_DELIVERABLE_REQUESTED||d.objective?.deliverable||'')}</textarea></label><label>Restrictions / prohibited actions<textarea id="project-restrictions-input">${esc(s.job?.PROHIBITED_ACTIONS||d.prohibitedActions||'')}</textarea></label><div class="inline-actions"><button class="primary-action" id="save-project-basics">Save project</button>${activeKey()!==TEST_KEY?'<button id="delete-project">Delete project</button>':''}</div></div>${section('Supplied materials and authoritative sources',value(d.sourceInventory||[]),true)}${section('Unknowns and assumptions',value({unknowns:d.unknowns,assumptions:d.assumptions}),true)}${section('Current project state',value({currentStage:d.currentStage||s.activeStage,currentState:d.currentState||s.job?.CURRENT_STATE,nextRequiredAction:d.nextRequiredAction||s.job?.NEXT_REQUIRED_ACTION,latestEvidence:d.latestEvidenceReference||s.job?.LATEST_EVIDENCE_REFERENCE}),true)}</div>`}
function workflow(s){return `<div class="project-panel"><h2>Workflow</h2><p class="muted">All 30 stages remain in the project. The normal view shows the human action and evidence state; detailed records remain available inside each stage.</p><div class="workflow-list">${entries(s).map(([n,st])=>`<article class="workflow-row ${n===Number(s.activeStage)?'current':''}"><button type="button" data-stage-open="${n}"><span class="workflow-num">${pad(n)}</span><span class="workflow-copy"><strong>${esc(stageTitle(s,n))}</strong><small>${esc(st.decisionEvidence||'No decision evidence recorded yet.')}</small></span><span class="status-chip ${stateClass(`${st.status} ${st.decision}`)}">${esc(st.status||st.decision||'NOT STARTED')}</span></button></article>`).join('')}</div></div>`}
function stagePanel(s,n){const d=s.projectData,st=s.stages[n]||{},prompt=st.generatedPrompt||d.generatedPrompts.find(p=>Number(p.stage)===n)?.prompt||'',outputs=d.generatedOutputs.filter(o=>Number(o.stage)===n);return `<div class="project-panel"><div class="stage-head"><div><button class="back-link" data-project-view="workflow">← Workflow</button><h2>Stage ${pad(n)} · ${esc(stageTitle(s,n))}</h2></div><span class="status-chip ${stateClass(`${st.status} ${st.decision}`)}">${esc(st.status||'NOT STARTED')}</span></div>${openBlockers(s).some(b=>Number(b.stageDiscovered||b.stage)===n)?'<div class="notice danger">This stage has an unresolved blocker. Affected downstream work remains stopped.</div>':''}<div class="stage-actions"><button id="open-stage-controls" class="primary-action">Open stage controls</button>${[11,12,17,19,21,23,24].includes(n)?'<button id="prepare-context">Prepare independent context</button>':''}<button id="new-blocker">Add blocker</button><button id="record-change">Record change</button></div>${section('Generated instruction / prompt',`<pre class="copy">${esc(prompt||'No generated instruction has been captured yet.')}</pre>`,true)}${section('Authorized inputs',value(st.authorizedFiles||d.freshContexts.filter(c=>Number(c.stage)===n).map(c=>c.authorizedFilesAndVersionsAttached)||[]),true)}${section('Stage record',`<pre class="copy">${esc(st.draftRecord||'No stage record saved.')}</pre>`)}${section('Generated / captured outputs',value(outputs),true)}<div class="capture-card"><h3>Capture work from this stage</h3><label>Complete response / output<textarea id="stage-response">${esc(st.responseDraft||'')}</textarea></label><label>Decision evidence<textarea id="stage-evidence">${esc(st.decisionEvidence||'')}</textarea></label><div class="two-col"><label>Status<select id="stage-status">${['NOT STARTED','IN PROGRESS','BLOCKED','READY','COMPLETE'].map(x=>`<option ${String(st.status).toUpperCase()===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Decision<select id="stage-decision"><option value="">No decision</option>${['READY TO PROCEED','BLOCKED','NOT READY - CORRECTION REQUIRED','SATISFIED','VIOLATED','UNDETERMINED','ACCEPTED','REJECTED'].map(x=>`<option ${String(st.decision).toUpperCase()===x?'selected':''}>${x}</option>`).join('')}</select></label></div><button id="save-stage-work" class="primary-action">Save stage work</button></div></div>`}
function work(s){const d=s.projectData;return `<div class="project-panel"><h2>Requirements and verification</h2>${section('Source-by-source research',value(d.research),true)}${section('Atomic requirements',value(d.requirements),true)}${section('Requirement-set defects and resolution',value(d.requirementResolution),false)}${section('Verification procedures',value(d.tests),true)}${section('Failure and mutation tests',value(d.mutations),true)}${section('Production instruction',value(d.productionInstruction),true)}${section('Generated prompts and instructions',value(d.generatedPrompts),true)}</div>`}
function runs(s){const d=s.projectData,groups=[...new Set(d.runRecords.map(r=>r.iterationId).filter(Boolean))];return `<div class="project-panel"><h2>Independent runs and reviews</h2><p class="muted">Each run is preserved separately. Fresh-context identity, authorized inputs, contamination state, output, and receipt remain inspectable.</p>${groups.map(g=>section(g,value(d.runRecords.filter(r=>r.iterationId===g)),true)).join('')}${!groups.length?'<div class="notice">No independent runs have been recorded for this project.</div>':''}${section('Prepared contexts',value(d.freshContexts),true)}${section('Verification records',value(d.verificationRecords),true)}${section('Cross-run comparisons',value(d.comparisons),true)}${section('Output receipts',value(d.generatedOutputs),true)}</div>`}
function issues(s){const d=s.projectData;return `<div class="project-panel"><h2>Blockers, defects, and changes</h2><div class="stage-actions"><button id="new-blocker" class="primary-action">Add blocker</button><button id="record-change">Record material change</button></div>${section('Open and resolved blockers',value(d.blockers),true)}${section('Defects and root cause',value(d.defects),true)}${section('Permanent regression tests',value(d.regressions),true)}${section('Change and invalidation history',value(d.changes),true)}</div>`}
function releaseMetrics(s){const d=s.projectData,mandatory=d.requirements.filter(r=>!/OPTIONAL/i.test(String(r.mandatoryStatus||r.class||'MANDATORY'))),satisfied=mandatory.filter(r=>/SATISFIED|ACTIVE/i.test(String(r.result||r.determination||r.verificationResult||''))&&isFilled(r.evidence||r.expectedEvidence||r.sourceLocation)),tests=d.tests.filter(t=>!/OPTIONAL/i.test(String(t.mandatoryStatus||'MANDATORY'))),testOK=tests.filter(t=>/SATISFIED|SUCCESS|READY|EFFECTIVE/i.test(String(t.result||t.status||t.determination||''))),crit=unresolvedDefects(s).filter(x=>/CRITICAL/i.test(String(x.severity))).length,major=unresolvedDefects(s).filter(x=>/MAJOR/i.test(String(x.severity))).length,block=openBlockers(s).length;return {mandatoryRequirements:mandatory.length,mandatoryWithAffirmativeEvidence:satisfied.length,mandatoryVerificationProcedures:tests.length,mandatoryVerificationSucceeded:testOK.length,openBlockers:block,criticalDefects:crit,majorDefects:major,releaseState:block?'BLOCKED':(crit||major?'REJECTED':(mandatory.length&&satisfied.length===mandatory.length&&tests.length===testOK.length?'ACCEPTED':'BLOCKED'))};}
function releaseView(s){const d=s.projectData,m=releaseMetrics(s);return `<div class="project-panel"><h2>Release readiness</h2><div class="release-summary"><span class="status-chip ${stateClass(m.releaseState)}">${m.releaseState}</span><p>Release state is derived from project evidence. Missing mandatory evidence remains BLOCKED; demonstrated mandatory violation or unresolved material defects prevent acceptance.</p></div>${section('Derived gate metrics',value(m),true)}${section('Convergence',value(d.convergence),true)}${section('Unchanged confirmation',value(d.confirmation),true)}${section('Frozen baseline',value(d.baseline),true)}${section('Finished product',value(d.product),true)}${section('Process and product audits',value(d.audits),true)}${section('Final representation inspection',value(d.representation),true)}${section('Release gate and SHA-256 identity',value(d.release),true)}${section('Complete evidence chains',value(d.evidenceChains),true)}</div>`}
function history(s){const d=s.projectData;return `<div class="project-panel"><h2>Complete history</h2><p class="muted">Original work is never replaced by a status label. Stage instructions, responses, evidence, outputs, defects, changes, and receipts remain accessible.</p>${section('Project events',value(d.history),true)}<div class="stage-record-list">${entries(s).map(([n,st])=>`<details class="record-card"><summary><span>Stage ${pad(n)} · ${esc(stageTitle(s,n))}</span><span class="status-chip ${stateClass(`${st.status} ${st.decision}`)}">${esc(st.status||'NOT STARTED')}</span></summary><div class="record-body">${section('Generated instruction',`<pre class="copy">${esc(st.generatedPrompt||d.generatedPrompts.find(p=>Number(p.stage)===n)?.prompt||'None captured.')}</pre>`,true)}${section('Stage record',`<pre class="copy">${esc(st.draftRecord||'None captured.')}</pre>`)}${section('Response / output',`<pre class="copy">${esc(st.responseDraft||'None captured.')}</pre>`,true)}${section('Evidence and decision',value({status:st.status,decision:st.decision,decisionEvidence:st.decisionEvidence,nextStage:st.nextStage,dateTime:st.dateTime,invalidatedBy:st.invalidatedBy,revisions:st.revisions}))}</div></details>`).join('')}</div></div>`}
function renderProject(view='overview',stageNumber=null){saveActive();const s=ensureData(readState());if(!s)return;const host=$('#workspace-project');host.innerHTML=`<div class="human-project">${projectHero(s)}<nav class="project-tabs">${[['overview','Overview'],['workflow','Workflow'],['work','Work'],['runs','Runs'],['issues','Issues'],['release','Release'],['history','History']].map(([id,t])=>`<button type="button" data-project-view="${id}" aria-selected="${view===id}">${t}</button>`).join('')}</nav><div id="project-view"></div></div>`;const out=$('#project-view');if(stageNumber)out.innerHTML=stagePanel(s,stageNumber);else if(view==='overview')out.innerHTML=overview(s);else if(view==='workflow')out.innerHTML=workflow(s);else if(view==='work')out.innerHTML=work(s);else if(view==='runs')out.innerHTML=runs(s);else if(view==='issues')out.innerHTML=issues(s);else if(view==='release')out.innerHTML=releaseView(s);else out.innerHTML=history(s);wireProjectActions(s,view,stageNumber);}
function openStage(n){const s=readState();s.activeStage=n;ensureData(s).projectData.currentStage=n;s.job.CURRENT_STAGE=`STAGE ${pad(n)}`;writeState(s);saveActive();updateHeader();renderProject('workflow',n);}
function openCoreStage(n){const s=readState();s.activeStage=n;writeState(s);const sel=$('#stage-select');if(sel){sel.value=String(n);sel.dispatchEvent(new Event('change',{bubbles:true}))}showWorkspace('workbook');}
function saveBasics(){const s=readState(),d=ensureData(s).projectData,title=$('#project-title-input').value.trim(),objective=$('#project-objective-input').value,deliverable=$('#project-deliverable-input').value,restrictions=$('#project-restrictions-input').value;s.job.JOB_TITLE=title;s.job.EXACT_USER_OBJECTIVE_VERBATIM=objective;s.job.EXACT_DELIVERABLE_REQUESTED=deliverable;s.job.PROHIBITED_ACTIONS=restrictions;d.title=title;d.objective={...d.objective,exactUserObjective:objective,deliverable};d.prohibitedActions=restrictions;d.userEnteredData={...d.userEnteredData,projectTitle:title,exactUserObjective:objective,deliverable,prohibitedActions:restrictions};if(title||objective)s.job.CURRENT_STATE='IN PROGRESS';recordHistory(s,'project-updated','Project objective and user-entered job information updated.');writeState(s);saveActive();renderProject('overview');updateHeader();}
function saveStageWork(n){const s=readState(),d=ensureData(s).projectData,st=s.stages[n],before=clone({status:st.status,decision:st.decision,decisionEvidence:st.decisionEvidence,responseDraft:st.responseDraft});st.responseDraft=$('#stage-response').value;st.decisionEvidence=$('#stage-evidence').value;st.status=$('#stage-status').value;st.decision=$('#stage-decision').value;st.dateTime=now();st.revisions=st.revisions||[];st.revisions.push({dateTime:st.dateTime,before});if(st.responseDraft.trim()){const receipt={receiptId:makeId('RECEIPT'),stage:n,agentRole:'Captured external or generated output',contextId:st.contextId||'UNKNOWN',iterationId:s.job?.CURRENT_ITERATION||'NOT APPLICABLE',runId:st.runId||'NOT APPLICABLE',requestDateTime:'UNKNOWN',responseDateTime:st.dateTime,inputVersions:[s.job?.CURRENT_INPUT_VERSION||'UNKNOWN'],sourceSetVersion:s.job?.CURRENT_SOURCE_SET_VERSION||'NOT APPLICABLE',requirementsVersion:s.job?.CURRENT_REQUIREMENTS_VERSION||'NOT APPLICABLE',instructionVersion:s.job?.CURRENT_INSTRUCTION_VERSION||'NOT APPLICABLE',testSuiteVersion:s.job?.CURRENT_TEST_SUITE_VERSION||'NOT APPLICABLE',outputId:makeId('OUTPUT'),completeResponseSaved:true,response:st.responseDraft,toolFailures:'NONE',otherDeviations:'NONE',nextRequiredVerificationStage:n<30?`STAGE ${pad(n+1)}`:'NONE'};d.generatedOutputs.push(receipt);}d.currentStage=n;d.currentState=st.status;s.job.CURRENT_STATE=st.status;s.job.LATEST_EVIDENCE_REFERENCE=st.decisionEvidence||'NONE';recordHistory(s,'stage-work-saved',`Stage ${pad(n)} work, output, and decision evidence saved.`,{stage:n,status:st.status,decision:st.decision});writeState(s);saveActive();renderProject('workflow',n);updateHeader();}
function createBlocker(stage=Number(readState()?.activeStage||1)){const missing=prompt('What mandatory evidence, authority, input, capability, or decision rule is missing?');if(!missing)return;const why=prompt('Why does this prevent an affirmative determination?')||'Mandatory satisfaction cannot be established.';const s=readState(),d=ensureData(s).projectData,b={blockerId:makeId('BLOCKER'),dateOpened:now(),currentStatus:'OPEN',stageDiscovered:stage,affectedReqIds:[],affectedTestIds:[],affectedArtifactsAndVersions:[],missingItemType:'OTHER',missingEvidenceAuthorityInputOrCapability:missing,whyMandatorySatisfactionCannotBeEstablished:why,attemptsToResolve:[],downstreamWorkStopped:[`Stage ${pad(stage+1)} and affected downstream work`],resolution:'NOT RESOLVED'};d.blockers.push(b);s.stages[stage].status='BLOCKED';s.stages[stage].decision='BLOCKED';s.job.CURRENT_STATE='BLOCKED';s.job.CURRENT_BLOCKERS=d.blockers.filter(x=>x.currentStatus==='OPEN').map(x=>x.blockerId).join(', ');recordHistory(s,'blocker-opened',`Blocker ${b.blockerId} opened at Stage ${pad(stage)}.`,b);writeState(s);saveActive();renderProject('issues');updateHeader();}
function resolveBlocker(id){const s=readState(),d=ensureData(s).projectData,b=d.blockers.find(x=>x.blockerId===id||x.id===id);if(!b)return;const evidence=prompt('Resolution evidence:');if(!evidence)return;b.currentStatus='RESOLVED';b.resolution=evidence;b.resolutionEvidence=evidence;b.dateResolved=now();b.downstreamValidationRerun=['Required affected validation must be rerun before stale results count as current.'];s.job.CURRENT_BLOCKERS=d.blockers.filter(x=>x.currentStatus==='OPEN').map(x=>x.blockerId).join(', ')||'NONE';if(!openBlockers(s).length)s.job.CURRENT_STATE='IN PROGRESS';recordHistory(s,'blocker-resolved',`Blocker ${b.blockerId||id} resolved; affected work requires revalidation.`,b);writeState(s);saveActive();renderProject('issues');updateHeader();}
function recordChange(stage=Number(readState()?.activeStage||1)){const what=prompt('What materially changed?');if(!what)return;const reason=prompt('Why did it change?')||'User or workflow correction';const s=readState(),d=ensureData(s).projectData,change={changeId:makeId('CHANGE'),dateTime:now(),trigger:'USER CHANGE',earliestResponsibleLayer:'UNKNOWN',affectedArtifactId:`STAGE-${pad(stage)}`,oldVersion:'CURRENT',newVersion:'NEW CONTROLLED VERSION',exactChange:what,reason,materialChange:true,downstreamArtifactsInvalidated:[],downstreamDeterminationsInvalidated:[],testsToRerun:[],iterationsToRerun:[],auditsToRerun:[],releaseGateMustBeRerun:true,hashIdentityMustBeRerun:true,revalidationComplete:false,changeStatus:'IMPLEMENTED_NOT_REVALIDATED'};for(const [n,st] of entries(s)){if(n>stage&&/COMPLETE|READY|ACCEPTED|CONFIRMED|FROZEN/i.test(`${st.status} ${st.decision}`)){change.downstreamDeterminationsInvalidated.push(`Stage ${pad(n)} ${st.status||st.decision}`);st.invalidatedBy=st.invalidatedBy||[];st.invalidatedBy.push(change.changeId);st.status='NOT STARTED';st.decision='';}}d.changes.push(change);s.activeStage=stage;d.currentStage=stage;s.job.CURRENT_STAGE=`STAGE ${pad(stage)}`;s.job.CURRENT_STATE='IN PROGRESS';recordHistory(s,'material-change',`Material change ${change.changeId} recorded and downstream determinations invalidated.`,change);writeState(s);saveActive();renderProject('issues');updateHeader();}
function prepareContext(stage){const s=readState(),d=ensureData(s).projectData,runNeeded=[11,12,17,19,21,23,24].includes(stage),runId=runNeeded?(s.stages[stage].runId||`RUN-${String((d.runRecords.filter(r=>Number(r.stage)===stage).length+1)).padStart(3,'0')}`):'NOT APPLICABLE',context={contextId:makeId('CTX'),stage,role:stage===12?'Independent verifier':stage===23?'Independent semantic evaluator':stage===24?'Adversarial reviewer':'Independent execution',iterationId:s.job?.CURRENT_ITERATION||'ITERATION-001',runId,contextStartDateAndTime:now(),authorizedFilesAndVersionsAttached:s.stages[stage].authorizedFiles||[],frozenInputVersion:s.job?.CURRENT_INPUT_VERSION||'UNKNOWN',frozenSourceSetVersion:s.job?.CURRENT_SOURCE_SET_VERSION||'NOT APPLICABLE',frozenRequirementsVersion:s.job?.CURRENT_REQUIREMENTS_VERSION||'NOT APPLICABLE',frozenInstructionVersion:s.job?.CURRENT_INSTRUCTION_VERSION||'NOT APPLICABLE',frozenTestSuiteVersion:s.job?.CURRENT_TEST_SUITE_VERSION||'NOT APPLICABLE',otherRunOutputVisible:false,reviewerCommentVisible:false,priorFailureExplanationVisible:false,proposedCorrectionVisible:false,requiredToolsAvailable:'UNKNOWN',contextContaminated:false,runUsable:'UNKNOWN'};d.freshContexts.push(context);s.stages[stage].contextId=context.contextId;s.stages[stage].runId=runId;recordHistory(s,'context-prepared',`Fresh independent context ${context.contextId} prepared for Stage ${pad(stage)}.`,context);writeState(s);saveActive();renderProject('workflow',stage);}
function wireProjectActions(s,view,stage){$$('[data-project-view]').forEach(b=>b.onclick=()=>renderProject(b.dataset.projectView));$$('[data-stage-open]').forEach(b=>b.onclick=()=>openStage(Number(b.dataset.stageOpen)));$('#save-project-basics')?.addEventListener('click',saveBasics);$('#delete-project')?.addEventListener('click',removeProject);$('#save-stage-work')?.addEventListener('click',()=>saveStageWork(stage));$('#open-stage-controls')?.addEventListener('click',()=>openCoreStage(stage));$('#prepare-context')?.addEventListener('click',()=>prepareContext(stage));$$('#new-blocker').forEach(b=>b.onclick=()=>createBlocker(stage||Number(s.activeStage||1)));$$('#record-change').forEach(b=>b.onclick=()=>recordChange(stage||Number(s.activeStage||1)));if(view==='issues'){$$('.record-card summary').forEach(sum=>{const text=sum.textContent||'';const id=(text.match(/BLOCKER-[A-Z0-9-]+/)||[])[0];if(id){sum.parentElement.querySelector('.record-body')?.insertAdjacentHTML('beforeend',`<div class="inline-actions"><button type="button" data-resolve-blocker="${esc(id)}">Resolve blocker</button></div>`)}});$$('[data-resolve-blocker]').forEach(b=>b.onclick=()=>resolveBlocker(b.dataset.resolveBlocker));}}
function renderGuide(){const host=$('#workspace-guide');host.innerHTML=`<div class="project-panel"><h2>Workflow behavior</h2><p class="muted">The workbook is implemented as project behavior, records, evidence, gates, and contextual actions—not as a wall of duplicated checkboxes.</p><div class="guide-grid"><div class="guide-card"><h3>Independent contexts</h3><p>Prepare the role, frozen inputs, run identity, contamination controls, and output receipt only when a workflow stage requires independence.</p></div><div class="guide-card"><h3>Blockers</h3><p>Missing mandatory evidence, authority, input, capability, or decision rules stop affected downstream work until evidence-backed resolution and revalidation.</p></div><div class="guide-card"><h3>Changes and invalidation</h3><p>Material changes preserve history, invalidate stale dependent determinations, and identify revalidation instead of silently overwriting prior evidence.</p></div><div class="guide-card"><h3>Release</h3><p>Release readiness derives from requirements, validation, defects, blockers, audits, evidence chains, and exact artifact identity.</p></div><div class="guide-card"><h3>New projects</h3><p>New Project creates a clean Stage 01 project with no inherited requirements, tests, evidence, baseline, product, or release decision.</p></div><div class="guide-card"><h3>Output receipts</h3><p>Captured responses are preserved with stage, context, iteration/run, input versions, failures, deviations, and next verification step.</p></div></div></div>`}
function injectStyles(){if($('#human-ui-runtime-style'))return;const st=document.createElement('style');st.id='human-ui-runtime-style';st.textContent=`.primary-action{background:#181818!important;color:#fff!important;border-color:#181818!important}.action-banner{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:8px;border-left:3px solid #1557c9;background:#edf3ff;padding:8px;border-radius:8px;margin-bottom:10px;font-size:11px}.action-banner.danger{border-left-color:#a42318;background:#fff0ef}.action-banner button,.stage-actions button,.inline-actions button,.capture-card button,.back-link{min-height:30px;border:1px solid #999;border-radius:7px;background:#fff;padding:4px 8px;font-size:10.5px;font-weight:700}.stage-actions,.inline-actions{display:flex;gap:5px;flex-wrap:wrap;margin:8px 0}.stage-head{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.stage-head h2{margin:4px 0 0}.back-link{border:0!important;padding:0!important;min-height:auto!important;color:#1557c9;background:transparent!important}.capture-card{border:1px solid #d9d9d4;border-radius:9px;padding:9px;margin-top:8px;background:#fafaf8}.capture-card h3{margin:0 0 5px;font-size:12px}.edit-grid{display:grid;gap:4px}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:7px}.release-summary{display:flex;gap:8px;align-items:flex-start;margin-bottom:8px}.release-summary p{margin:0;font-size:11px;color:#555}@media(max-width:560px){.action-banner{grid-template-columns:1fr}.two-col{grid-template-columns:1fr}.stage-actions{display:grid;grid-template-columns:1fr 1fr}.stage-actions button{width:100%}}`;document.head.appendChild(st);}
function wire(){
  $('#project-picker').onchange=e=>switchProject(e.target.value);
  $('#new-job-button').onclick=newProject;
  $('#project-data-button').onclick=()=>{renderProject('overview');showWorkspace('project')};
  $('#guide-button').onclick=()=>{renderGuide();showWorkspace('guide')};
  $('#export-button').onclick=exportProject;
  $('#import-button').onclick=()=>$('#imp').click();
  $('#imp').onchange=e=>{if(e.target.files?.[0])importProject(e.target.files[0])};
  $('#previous-stage')?.addEventListener('click',()=>setTimeout(()=>{const s=readState();if(s){ensureData(s).projectData.currentStage=Number(s.activeStage||1);writeState(s);saveActive();updateHeader()}},0));
  $('#next-stage')?.addEventListener('click',()=>setTimeout(()=>{const s=readState();if(s){ensureData(s).projectData.currentStage=Number(s.activeStage||1);writeState(s);saveActive();updateHeader()}},0));
  setInterval(()=>{saveActive();updateHeader()},1500);addEventListener('pagehide',saveActive);addEventListener('beforeunload',saveActive);
}
async function init(){injectStyles();let tries=0;while(!readState()&&tries++<80)await new Promise(r=>setTimeout(r,100));if(!readState())return;migrateRegistry();await ensureTestProject();let r=readRegistry(),k=activeKey();if(!r[k]){k=Object.keys(r)[0];setActive(k)}if(r[k])writeState(clone(r[k]));wire();renderProject('overview');showWorkspace('project');updateHeader();}
addEventListener('closed-loop-core-ready',()=>init(),{once:true});setTimeout(()=>{if(readState())init()},800);
})();