(()=>{'use strict';
const STORE='closed-loop-reliability-projects-v3';
const controlled=['EXACT_USER_OBJECTIVE_VERBATIM','EXACT_DELIVERABLE_REQUESTED','SUPPLIED_MATERIALS_INVENTORY','REQUIRED_OUTPUT_FORMAT','DEADLINE_OR_TEMPORAL_SCOPE','KNOWN_AUTHORITATIVE_SOURCES','AVAILABLE_TOOLS','PROHIBITED_ACTIONS','EXPLICIT_USER_REQUIREMENTS','ASSUMPTIONS','UNKNOWN_INFORMATION','INPUT_SET_CONTENTS','INPUT_SET_HASH_OR_MANIFEST','CURRENT_INPUT_VERSION'];
const readProjects=()=>{try{const raw=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(raw)?raw:(raw&&typeof raw==='object'?[raw]:[]);}catch{return [];}};
const currentId=()=>String(document.querySelector('#current-project-summary')?.textContent||'').split(' · ')[0].trim();
function lockJobId(){const input=document.querySelector('[data-job="JOB_ID"]');if(!input)return;input.readOnly=true;input.setAttribute('aria-readonly','true');input.title='Project identity is immutable. Create or import a different project to use another JOB_ID.';}
function repairInvalidatedStageOne(id){const list=readProjects(),project=list.find(p=>String(p?.job?.JOB_ID||'').trim()===id);if(!project)return false;const stage=project.stages?.[1]||project.stages?.['1'],record=project.projectData?.stageRecords?.[1]||project.projectData?.stageRecords?.['1'];if(!stage||!record||stage.status==='COMPLETE'||record.status!=='COMPLETE')return false;record.status=stage.status||'NOT READY';record.decision=stage.decision||'';record.decisionEvidence=stage.decisionEvidence||'';record.nextStage=stage.nextStage||'';record.decidedBy=stage.decidedBy||'';record.dateTime=stage.dateTime||'';localStorage.setItem(STORE,JSON.stringify(list));return true;}
function wrapSaveJob(){const button=document.querySelector('#save-job');if(!button||button.dataset.integrityGuard==='1'||typeof button.onclick!=='function')return;button.dataset.integrityGuard='1';const original=button.onclick;button.onclick=async function(event){const id=currentId(),idInput=document.querySelector('[data-job="JOB_ID"]'),draftId=String(idInput?.value||'').trim();if(!id||draftId!==id){if(idInput)idInput.value=id;alert('JOB_ID is immutable and cannot be blank or changed. Create or import a different project instead.');return;}const projects=readProjects(),before=projects.find(p=>String(p?.job?.JOB_ID||'').trim()===id),changed=!!before&&controlled.some(k=>String(before.job?.[k]??'')!==String(document.querySelector(`[data-job="${k}"]`)?.value??'')),stageOneWasComplete=before?.stages?.[1]?.status==='COMPLETE'||before?.stages?.['1']?.status==='COMPLETE';await original.call(this,event);if(changed&&stageOneWasComplete&&repairInvalidatedStageOne(id))location.reload();};}
function wrapImport(){const input=document.querySelector('#import-file');if(!input||input.dataset.integrityGuard==='1'||typeof input.onchange!=='function')return;input.dataset.integrityGuard='1';const original=input.onchange;input.onchange=async function(event){const file=event.target.files?.[0];if(!file)return original.call(this,event);try{const raw=JSON.parse(await file.text()),id=String(raw?.job?.JOB_ID||raw?.jobId||'').trim();if(!id)throw new Error('JOB_ID is required.');if(readProjects().some(p=>String(p?.job?.JOB_ID||'').trim()===id))throw new Error(`JOB_ID ${id} already exists. Import requires a unique project identity.`);}catch(error){alert(`Import rejected without changing existing projects: ${error.message}`);event.target.value='';return;}return original.call(this,event);};}
function apply(){lockJobId();wrapSaveJob();wrapImport();}
new MutationObserver(apply).observe(document.documentElement,{subtree:true,childList:true});
apply();
globalThis.closedLoopIntegrityGuard={storeKey:STORE,controlledFields:[...controlled]};
})();
