(()=>{'use strict';
const STORE='closed-loop-reliability-projects-v3';
const controlled=['EXACT_USER_OBJECTIVE_VERBATIM','EXACT_DELIVERABLE_REQUESTED','SUPPLIED_MATERIALS_INVENTORY','REQUIRED_OUTPUT_FORMAT','DEADLINE_OR_TEMPORAL_SCOPE','KNOWN_AUTHORITATIVE_SOURCES','AVAILABLE_TOOLS','PROHIBITED_ACTIONS','EXPLICIT_USER_REQUIREMENTS','ASSUMPTIONS','UNKNOWN_INFORMATION','INPUT_SET_CONTENTS','INPUT_SET_HASH_OR_MANIFEST','CURRENT_INPUT_VERSION'];
const derivedCollections=['sources','sourceConflicts','research','candidateRequirements','requirements','tests','failureTests','preflightRecords','candidateFreezes','runs','verification','comparisons','defects','rootCauses','regressions','baselines','products','deterministicResults','meaningResults','adversarialResults','representationInspections','processAudits','productAudits','releaseRecords','artifactIdentities','evidenceChains'];
const requiredRecordFields={sources:['SOURCE_ID','TYPE','ORIGIN','REFERENCE','INSPECTION_STATE','CURRENCY_STATE','CONTROLLING_STATUS'],requirements:['REQ_ID','OBLIGATION','MANDATORY','SATISFACTION_CONDITION','VERIFICATION_METHOD','STATUS'],tests:['TEST_ID','REQ_ID','PROCEDURE','EXPECTED_RESULT','FAILURE_CONDITION','STATUS']};
let stageDirty=false,pendingAudited=[],pendingRelease=[],storageGuardInstalled=false,alertingStorage=false;
const safe=v=>Array.isArray(v)?v:[];
const readProjects=()=>{try{const raw=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(raw)?raw:(raw&&typeof raw==='object'?[raw]:[]);}catch{return [];}};
const selectedIndex=()=>{const n=Number(document.querySelector('#project-picker')?.value);return Number.isInteger(n)&&n>=0?n:0;};
const selectedProject=(list=readProjects())=>list[selectedIndex()]||list[0]||null;
const currentId=()=>String(selectedProject()?.job?.JOB_ID||document.querySelector('#current-project-summary')?.textContent?.split(' · ')[0]||'').trim();
const rv=(r,k)=>r?.[k]??r?.fields?.[k]??r?.[k.toLowerCase()]??r?.fields?.[k.toLowerCase()]??'';
const upper=v=>String(v??'').trim().toUpperCase();
function persistProjects(list){localStorage.setItem(STORE,JSON.stringify(list));}
function installStorageGuard(){if(storageGuardInstalled)return;storageGuardInstalled=true;const proto=globalThis.Storage?.prototype;if(!proto)return;const original=proto.setItem;if(original?.__closedLoopVerified)return;function guardedSetItem(key,value){try{original.call(this,key,value);const actual=this.getItem(key);if(actual!==String(value))throw new Error('Browser storage did not retain the saved value.');}catch(error){if(!alertingStorage){alertingStorage=true;try{alert(`Save failed: ${error.message||error}. No successful save was recorded.`);}finally{alertingStorage=false;}}throw error;}}guardedSetItem.__closedLoopVerified=true;try{Object.defineProperty(proto,'setItem',{configurable:true,writable:true,value:guardedSetItem});}catch{}}
function lockJobId(){const input=document.querySelector('[data-job="JOB_ID"]');if(!input)return;input.readOnly=true;input.setAttribute('aria-readonly','true');input.title='Project identity is immutable. Create or import a different project to use another JOB_ID.';}
function repairInvalidatedStageOne(id){const list=readProjects(),project=list.find(p=>String(p?.job?.JOB_ID||'').trim()===id);if(!project)return false;const stage=project.stages?.[1]||project.stages?.['1'],record=project.projectData?.stageRecords?.[1]||project.projectData?.stageRecords?.['1'];if(!stage||!record||stage.status==='COMPLETE'||record.status!=='COMPLETE')return false;record.status=stage.status||'NOT READY';record.decision=stage.decision||'';record.decisionEvidence=stage.decisionEvidence||'';record.nextStage=stage.nextStage||'';record.decidedBy=stage.decidedBy||'';record.dateTime=stage.dateTime||'';persistProjects(list);return true;}
function invalidateDerivedRecords(id){const list=readProjects(),project=list.find(p=>String(p?.job?.JOB_ID||'').trim()===id);if(!project)return false;const data=project.projectData||(project.projectData={}),registry=data.permanentRegistry||(data.permanentRegistry={}),archive=registry.invalidatedRecords||(registry.invalidatedRecords=[]),at=new Date().toISOString();let changed=false;for(const name of derivedCollections){const records=safe(data[name]);if(!records.length)continue;archive.push(...records.map(record=>({collection:name,invalidatedAt:at,reason:'Controlling project input changed; downstream evidence requires revalidation.',record})));data[name]=[];changed=true;}project.release={...(project.release||{}),gateState:'',authorization:'NOT AUTHORIZED',auditedDraft:[],releaseDraft:[],comparisons:[],authorizedArtifactIds:[]};Object.assign(project.job||{}, {CURRENT_SOURCE_SET_VERSION:'',CURRENT_REQUIREMENTS_VERSION:'',CURRENT_TEST_SUITE_VERSION:'',CURRENT_INSTRUCTION_VERSION:'',CURRENT_BASELINE_ID:'NONE',CURRENT_PRODUCT_ID:'NONE'});persistProjects(list);return changed;}
function latestBlockers(project){const records=safe(project?.projectData?.blockers),latest=new Map();for(const r of records){const id=String(rv(r,'BLOCKER_ID')||r.id||'').trim();if(!id)continue;const prior=latest.get(id);if(!prior||Number(r.revision||0)>=Number(prior.revision||0)||String(r.createdAt||'')>String(prior.createdAt||''))latest.set(id,r);}return [...latest.values()];}
function syncBlockerJobState(){const list=readProjects(),project=selectedProject(list);if(!project)return false;const open=latestBlockers(project).filter(r=>upper(rv(r,'CURRENT_STATUS'))==='OPEN'),ids=open.map(r=>String(rv(r,'BLOCKER_ID')||r.id)).filter(Boolean);let changed=false;const job=project.job||(project.job={});const desired=ids.length?ids.join(', '):'NONE';if(job.CURRENT_BLOCKERS!==desired){job.CURRENT_BLOCKERS=desired;changed=true;}if(ids.length){if(job.CURRENT_STATE!=='BLOCKED'){job.CURRENT_STATE='BLOCKED';changed=true;}const next=`Resolve blocker ${ids[0]} before continuing.`;if(job.NEXT_REQUIRED_ACTION!==next){job.NEXT_REQUIRED_ACTION=next;changed=true;}}else if(job.CURRENT_STATE==='BLOCKED'){const n=Number(String(job.CURRENT_STAGE||'').match(/\d+/)?.[0]||1),s=project.stages?.[n]||project.stages?.[String(n)],status=upper(s?.status);const state=status==='COMPLETE'?'READY':status==='NOT STARTED'?'READY':'NOT READY';job.CURRENT_STATE=state;job.NEXT_REQUIRED_ACTION=`Proceed to ${job.CURRENT_STAGE||'the current stage'}.`;changed=true;}if(changed)persistProjects(list);return changed;}
function wrapSaveJob(){const button=document.querySelector('#save-job');if(!button||button.dataset.integrityGuard==='1'||typeof button.onclick!=='function')return;button.dataset.integrityGuard='1';const original=button.onclick;button.onclick=async function(event){const id=currentId(),idInput=document.querySelector('[data-job="JOB_ID"]'),draftId=String(idInput?.value||'').trim();if(!id||draftId!==id){if(idInput)idInput.value=id;alert('JOB_ID is immutable and cannot be blank or changed. Create or import a different project instead.');return;}const projects=readProjects(),before=projects.find(p=>String(p?.job?.JOB_ID||'').trim()===id),changed=!!before&&controlled.some(k=>String(before.job?.[k]??'')!==String(document.querySelector(`[data-job="${k}"]`)?.value??'')),stageOneWasComplete=before?.stages?.[1]?.status==='COMPLETE'||before?.stages?.['1']?.status==='COMPLETE';await original.call(this,event);if(changed&&stageOneWasComplete){repairInvalidatedStageOne(id);invalidateDerivedRecords(id);location.reload();}};}
function wrapImport(){const input=document.querySelector('#import-file');if(!input||input.dataset.integrityGuard==='1'||typeof input.onchange!=='function')return;input.dataset.integrityGuard='1';const original=input.onchange;input.onchange=async function(event){const file=event.target.files?.[0];if(!file)return original.call(this,event);try{const raw=JSON.parse(await file.text()),id=String(raw?.job?.JOB_ID||raw?.jobId||'').trim();if(!id)throw new Error('JOB_ID is required.');if(readProjects().some(p=>String(p?.job?.JOB_ID||'').trim()===id))throw new Error(`JOB_ID ${id} already exists. Import requires a unique project identity.`);}catch(error){alert(`Import rejected without changing existing projects: ${error.message}`);event.target.value='';return;}return original.call(this,event);};}
function markStageDirty(){if(stageDirty)return;stageDirty=true;applyDirtyLocks();}
function applyDirtyLocks(){const selectors=['#save-stage','[data-add-record]','[data-save-appendix]','#stage-files'];for(const el of document.querySelectorAll(selectors.join(','))){if(el.id==='save-stage-work')continue;el.disabled=stageDirty;el.title=stageDirty?'Save stage work first so the instruction and supporting records correspond to the visible stage fields.':'';}const save=document.querySelector('#save-stage-work');if(save&&stageDirty)save.title='Save these stage-field edits and regenerate the instruction before any dependent action.';}
function wrapSaveStageWork(){const button=document.querySelector('#save-stage-work');if(!button||button.dataset.integrityGuard==='1'||typeof button.onclick!=='function')return;button.dataset.integrityGuard='1';const original=button.onclick;button.onclick=async function(event){await original.call(this,event);stageDirty=false;applyDirtyLocks();};}
function wrapDependentActions(){for(const selector of ['#save-prompt','#copy-prompt','#record-output']){const button=document.querySelector(selector);if(!button||button.dataset.draftGuard==='1'||typeof button.onclick!=='function')continue;button.dataset.draftGuard='1';const original=button.onclick;button.onclick=async function(event){if(!stageDirty)return original.call(this,event);const save=document.querySelector('#save-stage-work');if(!save||typeof save.onclick!=='function'){alert('Save stage work before using this action.');return;}await save.onclick(new Event('click'));await new Promise(r=>setTimeout(r,0));const fresh=document.querySelector(selector);if(fresh&&fresh!==button)fresh.click();};}}
function guardNavigation(event){if(!stageDirty)return;const target=event.target.closest?.('[data-view],[data-stage],#project-picker');if(!target)return;event.preventDefault();event.stopImmediatePropagation();alert('Save stage work before leaving this stage. Unsaved stage edits are intentionally protected from being discarded.');}
function validateStructuredButtons(){for(const button of document.querySelectorAll('[data-add-record]')){if(button.dataset.structureGuard==='1'||typeof button.onclick!=='function')continue;const collection=button.dataset.addRecord,required=requiredRecordFields[collection];if(!required)continue;button.dataset.structureGuard='1';const original=button.onclick;button.onclick=async function(event){const missing=required.filter(name=>!String(document.querySelector(`[data-record-collection="${collection}"][data-record-field="${name}"]`)?.value||'').trim());if(missing.length){alert(`Complete required ${collection} fields before saving: ${missing.join(', ')}.`);return;}return original.call(this,event);};}}
function deriveReleaseGate(project){const data=project?.projectData||{},requirements=safe(data.requirements),tests=safe(data.tests),defects=safe(data.defects),open=latestBlockers(project).filter(r=>upper(rv(r,'CURRENT_STATUS'))==='OPEN');if(Array.from({length:26},(_,i)=>project?.stages?.[i+1]||project?.stages?.[String(i+1)]).some(s=>upper(s?.status)!=='COMPLETE')||open.length)return 'BLOCKED';if(!requirements.length||!tests.length)return 'BLOCKED';const violated=new Set(['VIOLATED','FAILED','DEFECTIVE','REJECTED']);if(requirements.some(r=>violated.has(upper(rv(r,'STATUS')||rv(r,'DETERMINATION')||rv(r,'RESULT'))))||tests.some(r=>violated.has(upper(rv(r,'STATUS')||rv(r,'DETERMINATION')||rv(r,'RESULT')))))return 'REJECTED';const closed=new Set(['CLOSED_VERIFIED','RESOLVED','CLOSED']);if(defects.some(r=>['CRITICAL','MAJOR'].includes(upper(rv(r,'SEVERITY')))&&!closed.has(upper(rv(r,'STATUS')||rv(r,'DEFECT_STATUS')))))return 'REJECTED';const reqOkay=new Set(['SATISFIED']),testOkay=new Set(['SATISFIED','SUCCESS','EFFECTIVE']);if(requirements.some(r=>upper(rv(r,'MANDATORY'))!=='FALSE'&&!reqOkay.has(upper(rv(r,'STATUS')||rv(r,'DETERMINATION')||rv(r,'RESULT')))))return 'BLOCKED';if(tests.some(r=>upper(rv(r,'MANDATORY'))!=='FALSE'&&!testOkay.has(upper(rv(r,'STATUS')||rv(r,'DETERMINATION')||rv(r,'RESULT')))))return 'BLOCKED';return 'ACCEPTED';}
function wrapReleaseGate(){const button=document.querySelector('#calculate-release-state');if(!button||button.dataset.integrityGuard==='1')return;button.dataset.integrityGuard='1';button.onclick=()=>{const list=readProjects(),project=selectedProject(list);if(!project)return;project.release=project.release||{};project.release.gateState=deriveReleaseGate(project);project.release.authorization='NOT AUTHORIZED';persistProjects(list);location.reload();};}
async function hashFile(file,kind){const bytes=await file.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes),sha256=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');return {artifactId:crypto.randomUUID?.()||`FILE-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name:file.name,type:file.type||'UNKNOWN',size:file.size,sha256,stage:'RELEASE',role:kind,retainedBytes:false,availability:'File bytes are not stored by this browser application; metadata and SHA-256 are retained.',inspected:true,addedAt:new Date().toISOString()};}
function bindReleaseInputs(){const a=document.querySelector('#audited-files'),r=document.querySelector('#release-files');if(a&&a.dataset.integrityGuard!=='1'){a.dataset.integrityGuard='1';a.addEventListener('change',()=>{pendingAudited=Array.from(a.files||[]);});}if(r&&r.dataset.integrityGuard!=='1'){r.dataset.integrityGuard='1';r.addEventListener('change',()=>{pendingRelease=Array.from(r.files||[]);});}}
function addArtifactCopies(project,items,kind){const data=project.projectData||(project.projectData={}),artifacts=data.artifacts||(data.artifacts=[]);for(const item of items){if(artifacts.some(x=>x.sha256===item.sha256&&x.name===item.name&&x.releaseRole===kind))continue;artifacts.push({...item,releaseRole:kind});}}
function wrapHashButtons(){bindReleaseInputs();const pairs=[['#hash-audited','auditedDraft','VERIFIED',()=>pendingAudited],['#hash-release','releaseDraft','DELIVERY',()=>pendingRelease]];for(const [selector,key,kind,getFiles] of pairs){const button=document.querySelector(selector);if(!button||button.dataset.integrityGuard==='1')continue;button.dataset.integrityGuard='1';button.onclick=async()=>{const files=getFiles();if(!files.length){alert(`Select ${kind==='VERIFIED'?'verified':'delivery'} files before hashing.`);return;}const list=readProjects(),project=selectedProject(list);if(!project)return;project.release=project.release||{};const items=await Promise.all(files.map(file=>hashFile(file,kind)));project.release[key]=items;addArtifactCopies(project,items,kind);const otherFiles=kind==='VERIFIED'?pendingRelease:pendingAudited,otherKey=kind==='VERIFIED'?'releaseDraft':'auditedDraft',otherKind=kind==='VERIFIED'?'DELIVERY':'VERIFIED';if(otherFiles.length){const otherItems=await Promise.all(otherFiles.map(file=>hashFile(file,otherKind)));project.release[otherKey]=otherItems;addArtifactCopies(project,otherItems,otherKind);}persistProjects(list);location.reload();};}}
function sameFileSet(a,b){const norm=list=>safe(list).map(x=>({name:String(x.name||''),size:Number(x.size||0),sha256:String(x.sha256||'')})).sort((x,y)=>x.name.localeCompare(y.name)||x.size-y.size||x.sha256.localeCompare(y.sha256));const x=norm(a),y=norm(b);return x.length>0&&x.length===y.length&&x.every((v,i)=>v.name===y[i].name&&v.size===y[i].size&&v.sha256===y[i].sha256);}
function wrapCompareRelease(){const button=document.querySelector('#compare-release');if(!button||button.dataset.integrityGuard==='1')return;button.dataset.integrityGuard='1';button.onclick=()=>{const list=readProjects(),project=selectedProject(list);if(!project)return;project.release=project.release||{};const gate=deriveReleaseGate(project),audited=safe(project.release.auditedDraft),delivery=safe(project.release.releaseDraft),identical=sameFileSet(audited,delivery),authorization=gate==='ACCEPTED'&&identical?'AUTHORIZED':'NOT AUTHORIZED',createdAt=new Date().toISOString();project.release.gateState=gate;project.release.authorization=authorization;project.release.authorizedArtifactIds=authorization==='AUTHORIZED'?audited.map(x=>x.artifactId):[];project.release.comparisons=project.release.comparisons||[];project.release.comparisons.push({createdAt,gateState:gate,authorization,filenamesIdentical:identical,reason:authorization==='AUTHORIZED'?'Verified and delivery file sets match exactly by filename, size, and SHA-256.':gate!=='ACCEPTED'?`Release gate is ${gate}.`:'Verified and delivery file sets do not match exactly.',comparisons:audited.map(a=>{const r=delivery.find(x=>x.name===a.name);return {artifactId:a.artifactId,auditedFile:a.name,releaseFile:r?.name||'',auditedSize:a.size,releaseSize:r?.size??null,auditedSha256:a.sha256,releaseSha256:r?.sha256||'',match:!!r&&a.size===r.size&&a.sha256===r.sha256};})});persistProjects(list);location.reload();};}
function wrapBlockerSaves(){for(const button of document.querySelectorAll('[data-save-appendix="B"]')){if(button.dataset.blockerGuard==='1'||typeof button.onclick!=='function')continue;button.dataset.blockerGuard='1';const original=button.onclick;button.onclick=async function(event){await original.call(this,event);if(syncBlockerJobState())location.reload();};}}
function addAccessibleNames(){for(const el of document.querySelectorAll('input,textarea,select')){if(el.getAttribute('aria-label')||el.getAttribute('aria-labelledby')||el.labels?.length)continue;let name=el.closest('.field')?.querySelector('label')?.textContent?.trim()||el.closest('label')?.textContent?.trim();if(!name&&el.dataset.job)name=el.dataset.job.replaceAll('_',' ');if(!name&&el.dataset.stageField)name=el.dataset.stageField.replaceAll('_',' ');if(!name&&el.dataset.recordField)name=el.dataset.recordField.replaceAll('_',' ');if(!name&&el.dataset.appendixField)name=el.dataset.appendixField.replaceAll('_',' ');if(name)el.setAttribute('aria-label',name);}}
function hideDeadRecordShortcuts(){const row=document.querySelector('.record-shortcuts');if(!row)return;const summaries=[...document.querySelectorAll('details.record-card > summary')].map(x=>x.textContent.trim().toLowerCase());for(const button of row.querySelectorAll('button')){const label=button.textContent.trim().toLowerCase();const aliases=label==='instructions'?['generated instructions']:label==='outputs'?['generated outputs']:label==='stage'?['stage records']:[label];button.hidden=!summaries.some(s=>aliases.some(a=>s.includes(a)));}}
function apply(){installStorageGuard();lockJobId();wrapSaveJob();wrapImport();wrapSaveStageWork();wrapDependentActions();validateStructuredButtons();wrapReleaseGate();wrapHashButtons();wrapCompareRelease();wrapBlockerSaves();addAccessibleNames();hideDeadRecordShortcuts();applyDirtyLocks();}
document.addEventListener('input',e=>{if(e.target.matches?.('[data-stage-field]'))markStageDirty();},true);
document.addEventListener('click',guardNavigation,true);
document.addEventListener('change',e=>{if(stageDirty&&(e.target.id==='stage-picker'||e.target.id==='project-picker')){e.preventDefault();e.stopImmediatePropagation();alert('Save stage work before changing stages or projects. Unsaved stage edits are intentionally protected from being discarded.');}},true);
new MutationObserver(apply).observe(document.documentElement,{subtree:true,childList:true});
apply();
globalThis.closedLoopIntegrityGuard={storeKey:STORE,controlledFields:[...controlled],deriveReleaseGate,sameFileSet};
})();
