from pathlib import Path
import json,re

# Keep the existing browser fixture current with /3 and proposal DOM semantics.
p=Path('verify-browser-extra.mjs')
t=p.read_text()
t=t.replace("const envelope={schema:'closed-loop-stage-response/2',","const envelope={schema:'closed-loop-stage-response/3',",1)
t=t.replace("await waitExpr(cdp,`document.body.innerText.includes('Proposed extracted changes')`);retained=await activeProject(cdp);assert(retained.projectData.sources.length===0,'Pending proposal mutated canonical state.');", "await waitExpr(cdp,`Boolean(document.querySelector('#proposal-heading'))`);retained=await activeProject(cdp);assert(retained.projectData.sources.length===0,'Pending proposal mutated canonical state.');",1)
t=t.replace("await openStage(cdp,2);await waitExpr(cdp,`document.body.innerText.includes('Proposed extracted changes')`);retained=await activeProject(cdp);", "await openStage(cdp,2);await waitExpr(cdp,`Boolean(document.querySelector('#proposal-heading'))`);retained=await activeProject(cdp);",1)
p.write_text(t)

# Every stage gets an explicit semantic procedure. No stage is allowed to fall back to a generic title/result sentence.
stages={
1:"Perform complete human-authority intake only. Exhaust the human-authority intake before Stage 01 can complete: capture every materially relevant fact, requirement, constraint, decision, prohibition, requested output, acceptance condition, material reference, and unresolved human-only issue present in current user input or accessible supplied materials. The user supplies project information once; if information is already present, capture and reuse it rather than asking for it again or asking the user to resupply it. Ask every foreseeable genuinely human-only issue now using BLOCKING_NOW or ASK_NOW_NONBLOCKING; classify research/later-resolvable matters as LATER_RESOLVABLE and do not ask the human for those. Do not return DATA_PROPOSAL until every application-enumerated intake unit is accounted for and every required human-only issue has been supplied, asked and answered, or explicitly deferred. Inspect accessible supplied material deeply enough to capture human authority relevant to defining the job, but do not perform external research, requirement atomization, test design, production, filing, simulation, manufacturing, or product verification. Classify every APPLICATION INTAKE MANIFEST unit exactly once. INPUT_SET_CONTENTS must preserve the complete durable meaning needed by later stages so the original intent or project material is not repeatedly requested.",
2:"Build only the independent external-source inventory for the already-defined current job. Use the current User Job Input and accepted Stage 01 job definition already present in this prompt; do not ask the user to repeat them. Discover and inspect every reasonably possible controlling, governing, evidentiary, or informative external source needed for this project; distinguish authority level, role, applicability, currency, supersession, and conflicts. A supplied project artifact is project input, not automatically an independent authority. Resolve source conflicts when objectively possible; otherwise block with exact evidence. If no legitimate external authority applies, return an evidence-supported NO_APPLICABLE_EXTERNAL_SOURCE determination. Never invent a source and do not perform Stage 03 source extraction or Stage 04 requirement compilation.",
3:"Research only the current accepted Stage 02 independent external source universe supplied in this prompt. Use the current User Job Input and accepted upstream definition to determine relevance, but never ask the user to repeat available project facts. Inspect every current source and every applicable portion deeply enough to extract all mandatory statements, recommendations, optional practices, examples, explanatory material, prohibitions, exceptions, dependencies, applicability facts, restrictions, invalidating material, and candidate obligations with exact source evidence. Perform the required conflict/exception pass and a second complete pass. Do not complete while any current Stage 02 source lacks current research coverage or the latest complete pass still finds a new material requirement category. Do not atomize requirements or design tests here.",
4:"Compile the requirement specification only from the complete application-enumerated obligation universe supplied in this prompt: current User Job Input, accepted Stage 01 job definition and captured human/material obligations, accepted Stage 03 research and candidate external-source obligations, applicable source identities, and applicable evidence. Do not ask the user to attach, restate, summarize, retype, or otherwise resupply any project information already captured. Process every obligationId exactly once. Map each obligation to one or more atomic independently testable requirements, or explicitly dispose it as retained nonnormative context, inapplicable with reason, or blocked with reason. Multiple obligations may merge only when materially equivalent without semantic loss, and every original identity must remain traceable. Every requirement must preserve provenance and define applicability, dependencies, prohibitions, observable satisfaction, expected evidence, failure condition, verification semantics, and severity. Do not perform Stage 05 resolution or Stage 06 test construction.",
5:"Resolve only defects in the complete current Stage 04 requirement set supplied in this prompt. Review every requirement for duplication, conflict, impossible combinations, undefined terms, circular dependencies, missing prerequisites, unsupported propositions, indeterminate applicability, non-atomic wording, and absence of a verification path. Use the governing research, source authority, source conflicts, and evidence supplied in current context; do not ask the user to repeat already-known project information. Preserve every valid requirement. Propose semantic corrections only where required, identify affected requirement identities and downstream work, and block unresolved mandatory defects. Do not design tests or production instructions. The application owns resulting version identity, counts, status, invalidation, and gate calculations.",
6:"Build the complete verification suite before any production instruction is authored. Use the complete current resolved requirements and relevant current artifacts/bindings supplied in the prompt; do not ask the user to repeat project information. Every active mandatory requirement must have at least one complete verification test with verification semantics, exact executor route, required capability, required artifacts/inputs, procedure, expected result, failure condition, and evidence to preserve. For every mandatory requirement analyze how a defective product could falsely appear compliant, including boundary, partial-success, stale-state, malformed-input, incorrect-authority, wrong-artifact, and capability-substitution cases, and decide what belongs in normal verification versus Stage 07 failure testing. Publish and obey the supplied closed-loop-test-spec/1 grammar, registered primitives, argument contracts, bindings, limits, and prohibited constructs. Select APPLICATION_DETERMINISTIC and valid Test IR whenever the proposition is faithfully expressible; otherwise select the exact non-native route. Never invent runtime semantics or execute the tests in this stage.",
7:"Build and execute failure tests only. Use the current requirements, Stage 06 tests, exact current artifacts, capabilities, and evidence context already supplied. For every applicable requirement create invalid or adversarial fixtures that exercise false-positive risks identified in Stage 06, then actually execute each fixture through a capable route. Fixture definition is not execution. Record expected rejection, actual observed result, and evidence sufficient to prove the rejection behavior. If invalid input is accepted, identify and link the validator defect. Do not claim a failure test passed without execution, do not design production instructions, and do not ask the user to recreate project information already present.",
8:"Author the production instruction only. Use the complete current resolved requirement registry, verification suite, failure-test findings, requirement resolutions, current User Job Input, and authoritative project context already supplied. Produce one internally coherent instruction that implements every current mandatory requirement and includes objective, authorized inputs, input-failure rules, source authority, scope, defined terms, ordered procedure, decision rules, tool rules, output contract, verification/failure handling, and completion criteria. Create complete requirement-to-instruction trace records for every mandatory requirement. Resolve no new requirement semantics here unless a genuine blocker is discovered; do not execute production. Never ask the user to repeat available project data. The instruction text returned here is the production instruction; agent instructions about this stage must come from this prompt, not UI prose.",
9:"Perform an independent preflight review of the complete current production instruction supplied in this prompt. Review every sentence and material clause without executing the target work. Detect multiple interpretations, undefined objects, unsupplied dependencies, internal conflicts, unavailable capabilities, unverifiable instructions, unclear ordering, missing failure behavior, and broken traceability against current requirements and tests. Preserve reviewer independence. If a correction is needed, propose the exact correction and require a new instruction version followed by a full repeated preflight; do not silently edit application-owned version state. Do not perform production or later verification.",
10:"Freeze the exact test candidate only. Use the preflight-approved production instruction, tests, failure tests, and current available artifacts supplied in this prompt. Identify the exact components and tool configuration that must be frozen so every one of the ten executions receives identical material. Do not invent candidate, iteration, byte hash, or version identities; the human selects authorized components where required and the application creates identities, reads actual bytes, hashes them, and prevents in-place mutation. Do not execute the candidate here. If a required component is missing, identify the exact blocker rather than asking the user to re-enter existing project information.",
11:"Execute exactly one application-reserved run lane of the frozen candidate. Use only the candidate, run identity, context identity, authorized inputs, tool configuration, and exact handoff supplied for this run. Do not use or request another run's output, reviewer feedback, comparison findings, defects discovered after freeze, RCA, or proposed corrections. Do not invent or replace application-reserved run/context identities. Perform the production instruction completely, preserve the complete output and returned artifacts, report tool failures and contamination honestly, and return only this run's permitted records/evidence. Do not compare or verify runs here.",
12:"Verify only the application-listed current missing REQ_ID × RUN_ID × TEST_ID cells supplied for this verification operation. Use the exact target run, requirement, test, required artifacts, governing evidence, and independent verifier context supplied in the prompt. Execute each applicable test through its declared capable route and preserve evidence sufficient to establish that proposition. Do not self-validate. Do not receive or use generator self-evaluation, another verifier's conclusion, Stage 13 comparison, RCA, or correction proposals. Return observations and evidence only within agent authority; the application determines independence where observable, matrix completeness, evidence-sufficiency consequences, counts, and canonical identities.",
13:"Compare the ten current verified executions requirement-by-requirement only after the complete verification data supplied in this prompt is available. Cover all ten current runs for every mandatory requirement. Identify interpretation variance, output variance, prohibited variance, inconclusive tests, repeated failure patterns, unique failures, and every correctness-affecting disagreement. Every correctness-affecting variance must result in a defect relationship rather than being averaged away or discarded. Do not recompute application-owned all-ten, violation, undetermined, stability, or count fields and do not perform RCA yet.",
14:"Root-cause every current material defect supplied in this prompt. Trace backward through comparison evidence, verification observations, requirements, tests, instructions, run evidence, and other supplied current causal records to identify the earliest layer that became incorrect. Distinguish requirement, source/research, instruction, test, execution, configuration/export, artifact, human-authority, or other supported causes based on evidence rather than convenience. For every defect provide an evidence-supported causal trace, earliest defective layer, root cause, and downstream invalidation implications. Unknown root cause remains blocked. Do not implement the correction in this stage.",
15:"Convert every confirmed current defect into a permanent regression definition and prove the original failure before correction. Use the defect, RCA, applicable requirement/test, preserved failure fixture/artifact, and evidence supplied in this prompt. Define exact reproduction and detection, preserve the fixture, and actually execute the pre-correction case through the capable route. The pre-correction result must demonstrate the defect with sufficient evidence; a statement that the test would have detected it is insufficient. Do not claim post-correction success here and never use the same execution as both pre- and post-correction proof.",
16:"Correct the root cause only at the earliest defective layer already identified by Stage 14. Use the complete current defect, RCA, regression, execution, affected requirements/instructions/tests/artifacts, and prior changes supplied in this prompt. Do not ask the user to determine the responsible layer. Propose or perform only the authorized correction type: deterministic application recalculation/versioning, agent-proposed correction requiring legitimate review, human-authority question, exact external action, or blocker. Preserve old versions, create new versions rather than editing in place, identify downstream invalidation and reruns, and keep execution-only failures from causing unsupported specification changes. Do not bypass the regression requirement.",
17:"Perform only the named Stage 17 operation for the new corrected ten-run iteration. Use the exact current change set, prior/current candidate and iteration state, tests, regressions, executions, and other operation-specific records supplied by the application. Never continue old execution conversations and never reuse contaminated prior outputs. Each operation must preserve the same rules as its original stage: FREEZE creates the corrected immutable candidate through application control; EXECUTE_RUN executes only its reserved fresh run; VERIFY fills only required independent verification cells; COMPARE covers all ten current runs; ROOT_CAUSE analyzes every material defect; REGRESSION creates and executes required regression proof; CORRECT fixes only evidenced root causes. Do not perform another Stage 17 operation in the current response. The application owns completion flags, counts, candidate equality, context distinctness, and gate state.",
18:"Evaluate convergence only from the latest completed current iteration and the complete current metrics/evidence supplied in this prompt. Do not substitute narrative confidence for application calculations. Review whether mandatory requirement coverage, mandatory verification coverage, and applicable regression success are complete and whether critical defects, major defects, mandatory unknowns, correctness-affecting contradictions, ambiguities, and unexplained execution variance are all zero simultaneously. Explain any failed condition and the correct return stage using current evidence. Do not set CONVERGED or any counts; the application owns all metrics and the convergence determination.",
19:"Perform only the named unchanged-confirmation operation on an unchanged converged candidate. Use the exact source converged iteration, frozen candidate, tests, regressions, current run/verification/comparison data, and operation-specific context supplied. CONFIRM_FREEZE must establish semantic zero-change through application-controlled identity and hashes; EXECUTE_RUN uses a new independent context and the unchanged package; VERIFY runs the complete applicable suite independently; COMPARE covers all ten confirmation runs; REGRESSION_VERIFY executes every applicable regression; CONFIRM determines whether any new requirement, missed failure, material defect, contradiction, or unexplained variance was observed. Do not perform another Stage 19 operation in this response. Never accept changed candidate bytes as unchanged and never reuse prior execution contexts.",
20:"Freeze the production baseline only after the supplied unchanged-confirmation evidence is complete and successful. Use the exact confirmed candidate, iteration, component identities, versions, and available bytes supplied. Human baseline authorization is required only as the genuine authorization decision; do not ask the human to transcribe IDs, versions, or hashes. The application assigns baseline identity, verifies exact bytes, calculates hashes, separates the baseline package from working files, and invalidates baseline status on change. Do not generate the finished product in this stage.",
21:"Generate the actual finished product only from the approved production baseline supplied in this prompt. Use the complete approved production instruction and exact baseline artifacts/bytes handed off by the application; do not ask the user to resend project intent or reconstruct prior requirements. Execute in the fresh production context only, create every requested deliverable, and return the exact output files and execution observations required by the contract. Do not edit outside the controlled workflow, do not self-verify the product, and do not invent product identity, output hashes, lineage, or application-owned execution facts. The exact returned bytes become the product under test.",
22:"Run deterministic verification on the actual current finished-product bytes only. The application automatically executes every current ready APPLICATION_DETERMINISTIC Test IR test in its worker and records application-owned results. For deterministic tests that require a supported external capability, use only the exact route, files, test specification, and evidence requirements supplied in the handoff; never ask an AI to pretend it ran application-native code and never synthesize a pass for unsupported Test IR. Every mandatory applicable deterministic test must have exactly one current sufficient result. Execution failure, undetermined result, and violation remain distinct. Do not perform meaning or adversarial review here.",
23:"Perform independent meaning-based verification only. Use the current product, governing requirement, applicable test/rubric, source evidence, and exact allowed context supplied. For every applicable meaning requirement identify the product location, required meaning, observed meaning, evidence-based comparison, and proposed determination. Do not receive or use generator correctness claims, unnecessary deterministic pass status, adversarial findings, or prior meaning-review conclusions. Preserve reviewer independence and return evidence capable of supporting the semantic proposition. Do not set application-owned independence, counts, or normalized gate results.",
24:"Perform independent adversarial verification only. Deliberately try to disprove correctness of the current product against the supplied applicable requirements, tests, authorized historical regression patterns, and failure patterns. Exercise every applicable attack category and active historical regression pattern through the correct route, preserving counterexamples and sufficient evidence. Do not receive generator reasoning, generator self-evaluation, prior reviewer conclusions that tell you what to find, or unauthorized history. Every unresolved mandatory finding must identify a defect or blocker and route back to root-cause analysis. Do not set application-owned counts, independence, or return decision.",
25:"Inspect the exact final representation and delivery package only. Use the current product, exact delivery artifacts, applicable requirements/representation expectations, and transformation/package context supplied. Open and inspect every required product representation, page, view, transformation, and packaged file; distinguish objective byte/file facts that the application establishes from irreducible semantic or visual observations assigned to the correct human/reviewer authority. Record exact locations and evidence for defects or unknowns. Do not treat an unopened package, filename, or hash as visual/representation inspection, and do not perform release gating here.",
26:"Reconcile process evidence and product evidence only. Use the complete current product/baseline identity and all supplied current deterministic, meaning, adversarial, representation, regression, process, trace, defect, blocker, and supporting evidence needed for reconciliation. Establish process correctness and product correctness as separate semantic reviews, then identify discrepancies, missing links, and conflicts between them. Do not hide contradictory evidence in aggregate counts. Return semantic audit observations and evidence; the application owns current-scope selection, missing-link detection, contradiction consequences, identities, counts, and final reconciled gate effect. Do not issue release authorization.",
27:"Review the complete current release evidence only. Consider every mandatory requirement, applicable test/result, regression execution, process/product audit, defect, blocker, contradiction, baseline/product identity, and evidence-sufficiency fact supplied. Identify advisory blockers, violations, missing evidence, and rule implications, but do not choose or write the release state. The application alone creates exactly one idempotent ACCEPTED, REJECTED, or BLOCKED release result from current sufficient noncontradictory evidence. Never represent acceptance while a current mandatory violation, blocker, contradiction, or insufficient required evidence exists.",
28:"Verify release artifact identity only after the current release gate is accepted. Use the exact audited artifacts, selected delivery artifacts, canonical artifact identities, authorized filenames, actual available bytes, and current release record supplied. Compare by canonical ARTIFACT_ID and authorized filename, never array order. The application rehashes actual bytes and requires one-to-one matching byte size and SHA-256; missing, extra, duplicate, multiply matched, renamed without authorization, stale, modified, or unknown comparisons cannot authorize delivery. Human input is limited to genuine artifact selection/authorization. Do not ask anyone to calculate hashes manually.",
29:"Preserve and investigate the complete evidence chain only. For every mandatory requirement use the supplied current authority/human authority, requirement, instruction trace, execution/product element, every applicable test/result, sufficient canonical evidence, release, baseline/product, regression where applicable, and released artifact identity. Locate any missing or insufficient link; do not fabricate it and do not treat structural existence as proof. The application constructs the canonical evidence chain and marks it complete only when every link is current and the evidence can establish its proposition. Agent work here is limited to finding and explaining missing evidence; do not rewrite history or release state.",
30:"Preserve failures permanently only. Use the complete append-only current defect, RCA, regression, regression-execution, change, baseline, and related evidence history supplied. Ensure every confirmed defect remains represented by a stable permanent defect history and a reproducible regression, that the latest applicable regression execution succeeded before the relevant baseline approval, and that any retirement is legitimate and preserved as a superseding record rather than deletion. Do not rewrite or delete prior defect/regression history and do not re-run unrelated workflow stages here."
}
ops={
17:{
'FREEZE':'Stage 17 operation FREEZE only: freeze the corrected candidate through application-controlled identities and exact component bytes after the approved change set; do not execute, verify, compare, root-cause, regress, or correct in this response.',
'EXECUTE_RUN':'Stage 17 operation EXECUTE_RUN only: execute the single application-reserved fresh run of the corrected frozen candidate; withhold prior outputs/reviewer feedback; do not verify, compare, RCA, regress, or correct in this response.',
'VERIFY':'Stage 17 operation VERIFY only: independently verify only the application-listed missing current matrix cells for the corrected iteration with sufficient evidence; do not execute a production run, compare, RCA, regress, or correct in this response.',
'COMPARE':'Stage 17 operation COMPARE only: compare all ten current corrected-run verification results requirement-by-requirement and identify correctness-affecting variance; do not execute, verify new cells, RCA, regress, or correct in this response.',
'ROOT_CAUSE':'Stage 17 operation ROOT_CAUSE only: root-cause every material current corrected-iteration defect to the earliest defective layer using evidence; do not execute, verify, compare again, create regressions, or correct in this response.',
'REGRESSION':'Stage 17 operation REGRESSION only: define and actually execute required regression proof for confirmed defects; do not execute production runs, compare, RCA again, or correct in this response.',
'CORRECT':'Stage 17 operation CORRECT only: correct evidenced root causes under change control, preserving versions and invalidation; do not execute the next iteration in this response.'
},
19:{
'CONFIRM_FREEZE':'Stage 19 operation CONFIRM_FREEZE only: confirm the candidate is semantically and byte-identically unchanged from the converged candidate using application-owned identities/hashes; do not run executions in this response.',
'EXECUTE_RUN':'Stage 19 operation EXECUTE_RUN only: execute one reserved fresh confirmation run using the unchanged frozen package and no prior-run context; do not verify or compare in this response.',
'VERIFY':'Stage 19 operation VERIFY only: independently execute the complete applicable verification cells for the confirmation iteration; do not compare or conclude confirmation in this response.',
'COMPARE':'Stage 19 operation COMPARE only: compare all ten confirmation-run verification results and expose any variance or defects; do not perform regression verification or final confirmation in this response.',
'REGRESSION_VERIFY':'Stage 19 operation REGRESSION_VERIFY only: execute every still-applicable regression against the unchanged confirmation candidate and preserve sufficient evidence; do not perform final confirmation in this response.',
'CONFIRM':'Stage 19 operation CONFIRM only: evaluate supplied confirmation observations for new requirements, missed failures, defects, contradictions, or unexplained variance; the application owns the final confirmation determination.'
}}

p=Path('prompt-engine.js')
t=p.read_text()
new_stage='const stageSpecial=Object.freeze('+json.dumps(stages,ensure_ascii=False,separators=(',',':'))+');\nconst operationSpecial=Object.freeze('+json.dumps(ops,ensure_ascii=False,separators=(',',':'))+');\nfunction procedureFor(stage,operation){return operationSpecial?.[stage]?.[operation]||stageSpecial[stage];}\nconst procedures=stageSpecial;'
t,n=re.subn(r"const stageSpecial=Object\.freeze\(\{.*?\}\);\nconst procedures=Object\.freeze\(Object\.fromEntries\(core\.STAGES\.map\(stage=>\[stage\.number,stageSpecial\[stage\.number\]\|\|`Perform only Stage .*?\]\)\)\);",new_stage,t,count=1,flags=re.S)
if n!=1: raise SystemExit('Could not replace stage procedure map/fallback')
t=t.replace('${procedures[stage]}','${procedureFor(stage,operation)}',1)
t=t.replace('buildPromptRecord,procedures,contextFor','buildPromptRecord,procedures,procedureFor,contextFor',1)
p.write_text(t)

# Expand only stage read contracts that were missing evidence/material required by the controlling stage semantics.
p=Path('workflow-schema.js')
t=p.read_text()
old="const READ_COLLECTIONS=Object.freeze({1:[],2:[],3:['sources','sourceConflicts'],4:['research','candidateRequirements','sources'],5:['requirements','research','sourceConflicts'],6:['requirements','requirementResolutions'],7:['requirements','tests'],8:['requirements','tests','failureTests','requirementResolutions'],9:['instructions','instructionTraces','requirements','tests'],10:['instructions','preflightRecords','tests','failureTests'],11:['candidateFreezes','iterations','runs','freshContexts'],12:['runs','requirements','tests','freshContexts'],13:['verification','runs','requirements'],14:['defects','comparisons','verification'],15:['defects','rootCauses'],16:['defects','rootCauses','regressions','regressionExecutions'],17:['changes','candidateFreezes','iterations','tests','regressions','regressionExecutions'],18:['iterations','runs','verification','comparisons','defects','regressions','regressionExecutions','blockers'],19:['convergenceRecords','candidateFreezes','tests','regressions','regressionExecutions'],20:['confirmationRecords','candidateFreezes','iterations'],21:['baselines','freshContexts'],22:['products','tests','artifacts'],23:['products','requirements','tests','sources'],24:['products','requirements','tests','regressions','regressionExecutions'],25:['products','artifacts'],26:['products','baselines','deterministicResults','meaningResults','adversarialResults','representationInspections'],27:['requirements','tests','deterministicResults','meaningResults','adversarialResults','representationInspections','processAudits','productAudits','defects','blockers','regressionExecutions'],28:['releaseRecords','artifactIdentities','artifacts'],29:['sources','requirements','instructions','instructionTraces','runs','products','tests','verification','deterministicResults','meaningResults','releaseRecords','artifactIdentities','evidenceRecords'],30:['defects','rootCauses','regressions','regressionExecutions','changes','baselines']});"
new="const READ_COLLECTIONS=Object.freeze({1:[],2:[],3:['sources','sourceConflicts'],4:['research','candidateRequirements','sources','evidenceRecords'],5:['requirements','research','sources','sourceConflicts','evidenceRecords'],6:['requirements','requirementResolutions','artifacts'],7:['requirements','tests','artifacts','evidenceRecords'],8:['requirements','tests','failureTests','requirementResolutions','sources'],9:['instructions','instructionTraces','requirements','tests'],10:['instructions','preflightRecords','tests','failureTests','artifacts'],11:['candidateFreezes','iterations','runs','freshContexts'],12:['runs','requirements','tests','freshContexts'],13:['verification','runs','requirements','tests'],14:['defects','comparisons','verification','requirements','tests','instructions','runs'],15:['defects','rootCauses','requirements','tests','artifacts','evidenceRecords'],16:['defects','rootCauses','regressions','regressionExecutions','requirements','requirementResolutions','instructions','tests','failureTests','artifacts','changes'],17:['changes','candidateFreezes','iterations','tests','regressions','regressionExecutions'],18:['iterations','runs','verification','comparisons','defects','regressions','regressionExecutions','blockers'],19:['convergenceRecords','candidateFreezes','tests','regressions','regressionExecutions'],20:['confirmationRecords','candidateFreezes','iterations'],21:['baselines','instructions','artifacts','freshContexts'],22:['products','tests','artifacts'],23:['products','requirements','tests','sources','evidenceRecords'],24:['products','requirements','tests','regressions','regressionExecutions','evidenceRecords'],25:['products','artifacts','requirements'],26:['products','baselines','requirements','instructions','tests','runs','verification','deterministicResults','meaningResults','adversarialResults','representationInspections','regressions','regressionExecutions','defects','blockers','evidenceRecords'],27:['requirements','tests','products','baselines','deterministicResults','meaningResults','adversarialResults','representationInspections','processAudits','productAudits','defects','blockers','regressionExecutions','evidenceRecords'],28:['releaseRecords','artifactIdentities','artifacts'],29:['sources','requirements','instructions','instructionTraces','runs','products','baselines','tests','verification','deterministicResults','meaningResults','adversarialResults','representationInspections','processAudits','productAudits','regressions','regressionExecutions','releaseRecords','artifactIdentities','evidenceRecords'],30:['defects','rootCauses','regressions','regressionExecutions','changes','baselines','evidenceRecords']});"
if old not in t: raise SystemExit('READ_COLLECTIONS baseline not found')
p.write_text(t.replace(old,new,1))

# Full prompt audit: every stage explicit, every operation precise, every prompt retains human authority and current upstream contract.
Path('verify-all-stage-prompts.mjs').write_text(r'''import fs from 'node:fs';
import vm from 'node:vm';
const assert=(v,m)=>{if(!v)throw new Error(m)};
globalThis.Event=globalThis.Event||class Event{constructor(type){this.type=type;}};globalThis.dispatchEvent=globalThis.dispatchEvent||(()=>true);
for(const f of ['workbook.js','hash.js','workflow-schema.js','test-runtime.js','workflow-engine.js','prompt-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const core=globalThis.closedLoopCore,schema=globalThis.closedLoopWorkflowSchema,engine=globalThis.closedLoopWorkflowEngine,prompts=globalThis.closedLoopPromptEngine;
assert(core&&schema&&engine&&prompts,'prompt runtime load failed');
assert(Object.keys(prompts.procedures).length===30,'Every one of 30 stages must have an explicit prompt procedure.');
for(let s=1;s<=30;s++){const p=String(prompts.procedures[s]||'');assert(p.length>120,`Stage ${s} procedure is not substantive.`);assert(!p.includes('Perform only Stage '+String(s).padStart(2,'0')+' —'),`Stage ${s} still uses generic fallback.`);}
const operationMarkers={17:{FREEZE:'operation FREEZE only',EXECUTE_RUN:'operation EXECUTE_RUN only',VERIFY:'operation VERIFY only',COMPARE:'operation COMPARE only',ROOT_CAUSE:'operation ROOT_CAUSE only',REGRESSION:'operation REGRESSION only',CORRECT:'operation CORRECT only'},19:{CONFIRM_FREEZE:'operation CONFIRM_FREEZE only',EXECUTE_RUN:'operation EXECUTE_RUN only',VERIFY:'operation VERIFY only',COMPARE:'operation COMPARE only',REGRESSION_VERIFY:'operation REGRESSION_VERIFY only',CONFIRM:'operation CONFIRM only'}};
for(const [s,ops] of Object.entries(operationMarkers))for(const [op,marker] of Object.entries(ops))assert(prompts.procedureFor(Number(s),op).includes(marker),`Stage ${s} ${op} is not operation-specific.`);
const requiredReads={4:['research','candidateRequirements','sources','evidenceRecords'],5:['requirements','research','sources','sourceConflicts','evidenceRecords'],6:['requirements','requirementResolutions','artifacts'],7:['requirements','tests','artifacts','evidenceRecords'],8:['requirements','tests','failureTests','requirementResolutions','sources'],10:['instructions','preflightRecords','tests','failureTests','artifacts'],13:['verification','runs','requirements','tests'],14:['defects','comparisons','verification','requirements','tests','instructions','runs'],15:['defects','rootCauses','requirements','tests','artifacts','evidenceRecords'],16:['defects','rootCauses','regressions','regressionExecutions','requirements','instructions','tests','artifacts'],21:['baselines','instructions','artifacts','freshContexts'],23:['products','requirements','tests','sources','evidenceRecords'],24:['products','requirements','tests','regressions','regressionExecutions','evidenceRecords'],25:['products','artifacts','requirements'],26:['products','baselines','requirements','instructions','tests','runs','verification','deterministicResults','meaningResults','adversarialResults','representationInspections','regressions','regressionExecutions','defects','blockers','evidenceRecords'],27:['requirements','tests','products','baselines','deterministicResults','meaningResults','adversarialResults','representationInspections','processAudits','productAudits','defects','blockers','regressionExecutions','evidenceRecords'],29:['sources','requirements','instructions','instructionTraces','runs','products','baselines','tests','verification','deterministicResults','meaningResults','adversarialResults','representationInspections','processAudits','productAudits','regressions','regressionExecutions','releaseRecords','artifactIdentities','evidenceRecords'],30:['defects','rootCauses','regressions','regressionExecutions','changes','baselines','evidenceRecords']};
for(const [s,needed] of Object.entries(requiredReads)){const got=new Set(schema.STAGE_CONTRACTS[Number(s)].readCollections);for(const c of needed)assert(got.has(c),`Stage ${s} context contract omits required ${c}.`)}
const state=core.createBlankState('JOB-ALL-STAGE-PROMPTS');Object.assign(state.job,{EXACT_USER_OBJECTIVE_VERBATIM:'USER-INTENT-SENTINEL: build exactly the requested project.',EXPLICIT_USER_REQUIREMENTS:'USER-REQUIREMENT-SENTINEL: never request project data twice.',SUPPLIED_MATERIALS_INVENTORY:'NONE',CURRENT_INPUT_VERSION:'INPUT-ALL-STAGES',CURRENT_SOURCE_SET_VERSION:'SOURCE-ALL-STAGES',CURRENT_REQUIREMENTS_VERSION:'REQ-ALL-STAGES',CURRENT_TEST_SUITE_VERSION:'TEST-ALL-STAGES',CURRENT_INSTRUCTION_VERSION:'INSTRUCTION-ALL-STAGES'});engine.ensureShape(state);engine.recalculate(state);
const intake=prompts.intakeCoverageManifest(state);state.stages[1].agentData={EXACT_DELIVERABLE_REQUESTED:'DELIVERABLE-SENTINEL',ASSUMPTIONS:'NONE',UNKNOWN_INFORMATION:'NONE',INPUT_SET_CONTENTS:JSON.stringify({units:intake.units.map((u,i)=>({sourceUnitId:u.unitId,disposition:'incorporated into the job definition',extractedStatements:[{statementKey:'S'+i,text:'captured '+u.label,statementClass:'CONTEXT'}]}))})};state.stages[1].status='COMPLETE';state.stages[1].gate={complete:true};state.stages[2].agentData={SOURCE_APPLICABILITY_DETERMINATION:'NO_APPLICABLE_EXTERNAL_SOURCE'};state.stages[2].status='COMPLETE';state.stages[2].gate={complete:true};state.stages[3].agentData={ALL_KNOWN_CONTROLLING_SOURCES_EXAMINED:true,SECOND_CONFLICT_AND_EXCEPTION_PASS_COMPLETED:true,NEW_MATERIAL_CATEGORY_FOUND_IN_LATEST_PASS:false};state.stages[3].status='COMPLETE';state.stages[3].gate={complete:true};
for(let s=1;s<=30;s++){for(const op of schema.STAGE_CONTRACTS[s].operations){const scope=s===11?{runId:'RUN-AUDIT',contextId:'CONTEXT-AUDIT'}:{};const r=prompts.buildPromptRecord(s,state,{operation:op,scope});const text=r.prompt;assert(text.includes('USER-INTENT-SENTINEL'),`Stage ${s}/${op} omitted current User Job Input.`);assert(text.includes('USER-REQUIREMENT-SENTINEL'),`Stage ${s}/${op} omitted explicit user requirements.`);assert(text.includes('STAGE PROCEDURE'),`Stage ${s}/${op} omitted stage procedure.`);assert(text.includes(prompts.procedureFor(s,op).slice(0,80)),`Stage ${s}/${op} did not embed its exact explicit procedure.`);assert(!text.includes('Perform only Stage '+String(s).padStart(2,'0')+' —'),`Stage ${s}/${op} generated generic fallback.`);assert(text.includes('HUMAN COLLABORATION MODE — APPLIES TO EVERY STAGE'),`Stage ${s}/${op} omitted universal no-repeat human collaboration contract.`);}}
const s4=prompts.buildPromptRecord(4,state,{operation:'COMPLETE'}).prompt;for(const x of ['current User Job Input','accepted Stage 01','accepted Stage 03','APPLICATION OBLIGATION MANIFEST'])assert(s4.includes(x),`Stage 4 missing ${x}`);assert(/Do not ask the user to attach|do not ask the user to attach/i.test(s4),'Stage 4 does not prohibit repeated intent/material supply.');
const src=fs.readFileSync('prompt-engine.js','utf8');assert(!src.includes('stageSpecial[stage.number]||`Perform only Stage'),'Generic stage fallback remains in source.');
const html=fs.readFileSync('index.html','utf8');assert(html.includes('height:clamp(260px,45vh,520px)')&&html.includes('.expandable-prompt{max-height:280px}.expandable-prompt.expanded{max-height:none}')&&!html.includes('#prompt-heading .expandable-prompt:not(.expanded){max-height:88px}'),'Prompt visual dimensions changed.');
console.log(JSON.stringify({all30StageProceduresExplicit:true,allStageOperationsExplicit:true,currentUserAuthorityInEveryGeneratedPrompt:true,upstreamReadContractsAudited:true,stage4CompletePriorData:true,noGenericFallback:true,visualsPreserved:true},null,2));
''')
