(()=>{
'use strict';

const DB_NAME='closed-loop-reliability';
const DB_VERSION=1;
const PROJECTS='projects';
const ARTIFACTS='artifacts';
const META='meta';
const LEGACY_KEYS=Object.freeze(['closed-loop-reliability-projects-v4','closed-loop-reliability-projects-v3','closed-loop-reliability-projects-v2','closed-loop-reliability-projects']);
const STORE_KEY=LEGACY_KEYS[0];
const hash=globalThis.closedLoopHash;
const clone=value=>value===undefined?undefined:(typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value)));
const projectIdentity=project=>String(project?.job?.JOB_ID||project?.jobId||'').trim();
const now=()=>new Date().toISOString();
const fault=phase=>{const configured=globalThis.__closedLoopStorageFault;if(configured===phase||configured?.phase===phase){const error=new Error(`Injected storage failure at ${phase}.`);error.code='INJECTED_STORAGE_FAILURE';throw error;}};
const request=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB request failed.'));});
const complete=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('IndexedDB transaction failed.'));tx.onabort=()=>reject(tx.error||new Error('IndexedDB transaction aborted.'));});
const canonicalProject=project=>{const copy=clone(project);delete copy.projectSha256;return copy;};
const projectSha256=project=>hash.sha256Value(canonicalProject(project));
const storageError=(message,code)=>Object.assign(new Error(message),{code});
const runSynchronousMutator=(mutator,next,before)=>{const result=mutator(next,before);if(result&&typeof result.then==='function')throw storageError('Project transaction mutators must be synchronous. Complete asynchronous work before opening the canonical IndexedDB transaction.','ASYNC_TRANSACTION_MUTATOR');return result;};
const PLACEHOLDER_REFERENCES=new Set(['','NONE','NOT APPLICABLE','UNKNOWN','PENDING','UNASSIGNED']);
const equivalent=(left,right)=>hash.sha256Value(left)===hash.sha256Value(right);
function validateProjectIntegrity(project,{verifyDerived=true}={}){
  const issues=[],schemaApi=globalThis.closedLoopWorkflowSchema,engine=globalThis.closedLoopWorkflowEngine;
  if(!project||typeof project!=='object')return {valid:false,issues:['Project is not an object.']};
  if(!schemaApi||!engine)return {valid:false,issues:['Workflow schema and engine are required for canonical project integrity validation.']};
  if(project.schema!==schemaApi.PROJECT_SCHEMA)issues.push(`Project schema ${project.schema||'UNKNOWN'} does not match ${schemaApi.PROJECT_SCHEMA}.`);
  if(project.workflow!==schemaApi.WORKFLOW_ID)issues.push(`Workflow ${project.workflow||'UNKNOWN'} does not match ${schemaApi.WORKFLOW_ID}.`);
  if(Number(project.stageCount)!==Number(schemaApi.STAGE_COUNT))issues.push(`Stage count ${project.stageCount} does not match ${schemaApi.STAGE_COUNT}.`);
  if(Object.keys(project.stages||{}).length!==Number(schemaApi.STAGE_COUNT))issues.push('Canonical project does not contain exactly the declared workflow stages.');
  if(!projectIdentity(project))issues.push('Canonical project has no JOB_ID.');
  const idsByCollection=new Map();
  for(const [collection,definition] of Object.entries(schemaApi.RECORD_SCHEMAS)){
    const list=project.projectData?.[collection];if(list!==undefined&&!Array.isArray(list)){issues.push(`${collection} is not an array.`);continue;}
    const seen=new Set();for(const record of Array.isArray(list)?list:[]){const id=engine.recordId(record,collection),fieldId=String(engine.recordValue(record,definition.idField)||'').trim();if(!id){issues.push(`${collection} contains a record without ${definition.idField}.`);continue;}if(seen.has(id))issues.push(`${collection} contains duplicate canonical ID ${id}.`);seen.add(id);if(record?.id&&fieldId&&String(record.id)!==fieldId)issues.push(`${collection} record ${id} contradicts its ${definition.idField}.`);}
    idsByCollection.set(collection,seen);
  }
  for(const [collection,definition] of Object.entries(schemaApi.RECORD_SCHEMAS))for(const record of Array.isArray(project.projectData?.[collection])?project.projectData[collection]:[])for(const [fieldName,targetCollection] of Object.entries(definition.relationships||{})){const raw=record?.relationships?.[fieldName]??engine.recordValue(record,fieldName);for(const value of Array.isArray(raw)?raw:[raw]){const ref=String(value??'').trim();if(PLACEHOLDER_REFERENCES.has(ref.toUpperCase()))continue;if(!idsByCollection.get(targetCollection)?.has(ref))issues.push(`${collection}.${fieldName} references missing ${targetCollection} record ${ref}.`);}}
  let previousSequence=0;const eventIds=new Set();for(const event of Array.isArray(project.projectData?.history)?project.projectData.history:[]){const sequence=Number(event?.eventSequence);if(!Number.isInteger(sequence)||sequence<=previousSequence)issues.push('History eventSequence is missing, duplicated, or non-monotonic.');previousSequence=Math.max(previousSequence,Number.isFinite(sequence)?sequence:0);const eventId=String(event?.eventId||'');if(eventId&&eventIds.has(eventId))issues.push(`History contains duplicate event ID ${eventId}.`);if(eventId)eventIds.add(eventId);}if(Number(project.projectData?.eventSequence||0)<previousSequence)issues.push('Project eventSequence is behind committed history.');
  if(verifyDerived){const expected=clone(project);delete expected.projectSha256;engine.ensureShape(expected);engine.recalculate(expected);for(const name of ['CURRENT_STAGE','CURRENT_STATE','CURRENT_BLOCKERS','NEXT_REQUIRED_ACTION','JOB_RECORD_STATUS','STATUS_EVIDENCE'])if(!equivalent(project.job?.[name],expected.job?.[name]))issues.push(`Application-derived job field ${name} does not match deterministic recalculation.`);for(let stage=1;stage<=Number(schemaApi.STAGE_COUNT);stage++){if(String(project.stages?.[stage]?.status||'')!==String(expected.stages?.[stage]?.status||''))issues.push(`Stage ${stage} status does not match deterministic recalculation.`);if(!equivalent(project.stages?.[stage]?.derivedData||{},expected.stages?.[stage]?.derivedData||{}))issues.push(`Stage ${stage} derivedData does not match deterministic recalculation.`);}const releaseRecords=(project.projectData?.releaseRecords||[]).filter(record=>record?.active!==false&&!record?.invalidatedBy),latestRelease=releaseRecords.at(-1);if(latestRelease){const actual=String(engine.recordValue(latestRelease,'DETERMINATION')||''),calculated=String(engine.releaseMetrics(expected).determination||'');if(actual!==calculated)issues.push(`Current release determination ${actual||'UNKNOWN'} does not match deterministic release calculation ${calculated||'UNKNOWN'}.`);}}
  const artifacts=new Map((project.projectData?.artifacts||[]).map(record=>[engine.recordId(record,'artifacts'),record]));for(const identity of (project.projectData?.artifactIdentities||[]).filter(record=>record?.active!==false&&!record?.invalidatedBy)){const artifact=artifacts.get(String(engine.recordValue(identity,'ARTIFACT_ID')||''));const auditedHash=String(engine.recordValue(identity,'AUDITED_SHA256')||''),deliveryHash=String(engine.recordValue(identity,'PRE_DELIVERY_SHA256')||''),auditedSize=Number(engine.recordValue(identity,'AUDITED_BYTE_SIZE')),deliverySize=Number(engine.recordValue(identity,'RELEASE_BYTE_SIZE')),sameHash=Boolean(auditedHash&&deliveryHash&&auditedHash===deliveryHash),sameSize=Number.isFinite(auditedSize)&&Number.isFinite(deliverySize)&&auditedSize===deliverySize,sameName=String(engine.recordValue(identity,'AUDITED_FILENAME')||'')===String(engine.recordValue(identity,'RELEASE_FILENAME')||''),authorized=sameHash&&sameSize&&sameName;if(Boolean(engine.recordValue(identity,'EXACT_HASH_MATCH'))!==sameHash||Boolean(engine.recordValue(identity,'EXACT_SIZE_MATCH'))!==sameSize||String(engine.recordValue(identity,'AUTHORIZATION')||'')!==(authorized?'AUTHORIZED':'NOT AUTHORIZED'))issues.push(`Artifact identity ${engine.recordId(identity,'artifactIdentities')||'UNKNOWN'} contradicts its deterministic comparison.`);if(artifact){if(String(engine.recordValue(artifact,'SHA256')||'')!==auditedHash||Number(engine.recordValue(artifact,'BYTE_SIZE'))!==auditedSize||String(engine.recordValue(artifact,'FILENAME')||'')!==String(engine.recordValue(identity,'AUDITED_FILENAME')||''))issues.push(`Artifact identity ${engine.recordId(identity,'artifactIdentities')||'UNKNOWN'} does not match its canonical artifact.`);}}
  return {valid:issues.length===0,issues};
}
function assertProjectIntegrity(project,options){const result=validateProjectIntegrity(project,options);if(!result.valid){const error=storageError(`Canonical project integrity validation failed: ${result.issues.join(' | ')}`,'PROJECT_INTEGRITY_FAILED');error.issues=result.issues;throw error;}return result;}

let databasePromise=null;
function openDatabase(){
  if(!globalThis.indexedDB)return Promise.reject(Object.assign(new Error('IndexedDB is required by the supported browser contract.'),{code:'INDEXEDDB_REQUIRED'}));
  if(databasePromise)return databasePromise;
  databasePromise=new Promise((resolve,reject)=>{
    const req=indexedDB.open(DB_NAME,DB_VERSION);
    req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(PROJECTS))db.createObjectStore(PROJECTS,{keyPath:'jobId'});if(!db.objectStoreNames.contains(ARTIFACTS))db.createObjectStore(ARTIFACTS,{keyPath:'artifactId'});if(!db.objectStoreNames.contains(META))db.createObjectStore(META,{keyPath:'key'});};
    req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB open failed.'));req.onblocked=()=>reject(Object.assign(new Error('IndexedDB upgrade is blocked by another tab.'),{code:'INDEXEDDB_BLOCKED'}));
  });
  return databasePromise;
}

function parseLegacy(storage=globalThis.localStorage){const out=[],seen=new Set();if(!storage)return out;for(const key of LEGACY_KEYS){let raw=null;try{raw=storage.getItem(key);}catch{}if(!raw)continue;try{const parsed=JSON.parse(raw);for(const item of Array.isArray(parsed)?parsed:[parsed]){if(!item||typeof item!=='object')continue;const id=projectIdentity(item)||hash.sha256Value(item);if(seen.has(id))continue;seen.add(id);out.push(item);}}catch{}}return out;}
function readAllLegacy(storage){return parseLegacy(storage);}
function writeAllLegacy(projects,storage){if(!storage)throw new Error('Legacy test storage is unavailable.');const payload=JSON.stringify(projects),prior=storage.getItem(STORE_KEY);try{fault('before-final-write');storage.setItem(STORE_KEY,payload);fault('after-final-write');return {changed:prior!==payload};}catch(error){try{if(prior===null)storage.removeItem(STORE_KEY);else storage.setItem(STORE_KEY,prior);}catch{}throw error;}}

async function metaPut(key,value,tx=null){const db=tx?null:await openDatabase();const own=tx||db.transaction(META,'readwrite');own.objectStore(META).put({key,value,updatedAt:now()});if(!tx)await complete(own);return value;}
async function metaGet(key){const db=await openDatabase(),tx=db.transaction(META,'readonly');const row=await request(tx.objectStore(META).get(key));await complete(tx);return row?.value;}
async function quarantine(row,reason){const db=await openDatabase(),tx=db.transaction([PROJECTS,META],'readwrite'),projects=tx.objectStore(PROJECTS),meta=tx.objectStore(META);try{const current=await request(projects.get(String(row?.jobId||'')));if(!current){await complete(tx);return false;}const currentStoredHash=String(current.projectSha256||''),rowStoredHash=String(row?.projectSha256||'');if(currentStoredHash!==rowStoredHash){await complete(tx);return false;}const corruptHash=rowStoredHash||projectSha256(row.project),key=`quarantine:${row?.jobId||'UNKNOWN'}:${corruptHash}`;meta.put({key,value:{reason,row:clone(row)},updatedAt:now()});projects.delete(String(row.jobId));await complete(tx);return true;}catch(error){try{tx.abort();}catch{}throw error;}}

async function migrateLegacy(){
  const db=await openDatabase();const count=await request(db.transaction(PROJECTS,'readonly').objectStore(PROJECTS).count());if(count)return {migrated:0};
  const legacy=parseLegacy();if(!legacy.length){await metaPut('migrationStatus',{status:'NONE',at:now()});return {migrated:0};}
  const tx=db.transaction([PROJECTS,META],'readwrite');let migrated=0;
  try{fault('before-legacy-migration');for(const source of legacy){const project=clone(source);const id=projectIdentity(project);if(!id)continue;const revision=Number(project.revision||0);tx.objectStore(PROJECTS).put({jobId:id,revision,project,projectSha256:projectSha256(project),updatedAt:now()});migrated++;}tx.objectStore(META).put({key:'migrationStatus',value:{status:'COMPLETE',migrated,at:now()},updatedAt:now()});fault('during-legacy-migration');await complete(tx);for(const key of LEGACY_KEYS)try{localStorage.removeItem(key);}catch{}return {migrated};}catch(error){try{tx.abort();}catch{}await metaPut('migrationStatus',{status:'FAILED',message:String(error.message||error),originalPreserved:true,at:now()});throw error;}
}

async function readAllIndexed(){await migrateLegacy();const db=await openDatabase(),tx=db.transaction(PROJECTS,'readonly'),rows=await request(tx.objectStore(PROJECTS).getAll());await complete(tx);const valid=[];for(const row of rows){const actual=projectSha256(row.project);if(actual!==row.projectSha256){await quarantine(row,'PROJECT_HASH_MISMATCH');continue;}const project=clone(row.project);project.revision=Number(row.revision||project.revision||0);project.projectSha256=row.projectSha256;valid.push(project);}return valid;}
function readAll(storage){return storage?readAllLegacy(storage):readAllIndexed();}

async function writeProject(project,{expectedProjectRevision=null,incrementRevision=true}={}){
  const id=projectIdentity(project);if(!id)throw new Error('A project without a JOB_ID cannot be committed.');const db=await openDatabase();fault('before-project-transaction');const tx=db.transaction([PROJECTS,META],'readwrite');const store=tx.objectStore(PROJECTS);try{const prior=await request(store.get(id));const currentRevision=Number(prior?.revision||0);if(expectedProjectRevision!==null&&Number(expectedProjectRevision)!==currentRevision){const e=new Error(`Project revision conflict for ${id}: expected ${expectedProjectRevision}, found ${currentRevision}.`);e.code='STALE_PROJECT_REVISION';throw e;}const next=clone(project);next.revision=incrementRevision?currentRevision+1:currentRevision;delete next.projectSha256;const digest=projectSha256(next);fault('during-project-write');store.put({jobId:id,revision:next.revision,project:next,projectSha256:digest,updatedAt:now()});tx.objectStore(META).put({key:'selectedProject',value:id,updatedAt:now()});tx.objectStore(META).put({key:'lastCommittedRevision',value:{jobId:id,revision:next.revision,projectSha256:digest},updatedAt:now()});fault('before-transaction-commit');await complete(tx);next.projectSha256=digest;try{new BroadcastChannel('closed-loop-reliability').postMessage({type:'PROJECT_CHANGED',jobId:id,revision:next.revision});}catch{}return next;}catch(error){try{tx.abort();}catch{}throw error;}
}

async function writeAllIndexed(projects){if(!Array.isArray(projects))throw new TypeError('Project storage payload must be an array.');const saved=[];for(const project of projects){const id=projectIdentity(project);if(!id)continue;const db=await openDatabase(),tx=db.transaction(PROJECTS,'readonly'),prior=await request(tx.objectStore(PROJECTS).get(id));await complete(tx);const incoming=clone(project);delete incoming.projectSha256;const digest=projectSha256(incoming);if(prior?.projectSha256===digest){incoming.revision=Number(prior.revision||0);incoming.projectSha256=digest;saved.push(incoming);}else saved.push(await writeProject(incoming,{expectedProjectRevision:Number(prior?.revision||0),incrementRevision:Boolean(prior)}));}return saved;}
function writeAll(projects,storage){return storage?writeAllLegacy(projects,storage):writeAllIndexed(projects);}

async function replaceProjectIndexed(projectsOrProject,projectOrOptions){
  if(Array.isArray(projectsOrProject)){const project=projectOrOptions;return writeProject(project,{expectedProjectRevision:Number(project?.revision||0)});}
  return writeProject(projectsOrProject,projectOrOptions||{});
}
function replaceProject(projectsOrProject,projectOrOptions,storage){if(Array.isArray(projectsOrProject)&&storage){const next=clone(projectsOrProject),project=projectOrOptions,id=projectIdentity(project),i=next.findIndex(x=>projectIdentity(x)===id);if(i<0)next.unshift(clone(project));else next[i]=clone(project);writeAllLegacy(next,storage);return next;}return replaceProjectIndexed(projectsOrProject,projectOrOptions);}

async function transactIndexed(projectsOrJobId,jobIdOrExpected,mutatorOrOptions){
  const jobId=String(projectsOrJobId||''),expected=Number(jobIdOrExpected);const mutator=mutatorOrOptions;if(typeof mutator!=='function')throw new TypeError('Transaction mutator must be a function.');const db=await openDatabase(),tx=db.transaction([PROJECTS,META],'readwrite'),store=tx.objectStore(PROJECTS);try{const prior=await request(store.get(jobId));if(!prior)throw new Error(`Project ${jobId} is not available for transaction.`);if(Number(prior.revision)!==expected){const e=new Error(`Project revision conflict for ${jobId}: expected ${expected}, found ${prior.revision}.`);e.code='STALE_PROJECT_REVISION';throw e;}const before=clone(prior.project),next=clone(prior.project),result=runSynchronousMutator(mutator,next,before);const engine=globalThis.closedLoopWorkflowEngine;engine?.ensureShape?.(next);engine?.recalculate?.(next);next.revision=expected+1;const digest=projectSha256(next);store.put({jobId,revision:next.revision,project:next,projectSha256:digest,updatedAt:now()});tx.objectStore(META).put({key:'lastCommittedRevision',value:{jobId,revision:next.revision,projectSha256:digest},updatedAt:now()});await complete(tx);next.projectSha256=digest;return {project:next,result};}catch(error){try{tx.abort();}catch{}throw error;}
}
function transact(projectsOrJobId,jobIdOrExpected,mutatorOrOptions,storage){if(Array.isArray(projectsOrJobId)&&storage){const next=clone(projectsOrJobId),id=String(jobIdOrExpected||''),i=next.findIndex(x=>projectIdentity(x)===id);if(i<0)throw new Error(`Project ${id} is not available for transaction.`);const before=clone(next[i]),result=runSynchronousMutator(mutatorOrOptions,next[i],before);writeAllLegacy(next,storage);return {projects:next,project:next[i],result};}return transactIndexed(projectsOrJobId,jobIdOrExpected,mutatorOrOptions);}

async function removeProjectIndexed(projectsOrJobId){const jobId=String(projectsOrJobId||''),db=await openDatabase(),tx=db.transaction([PROJECTS,ARTIFACTS],'readwrite');tx.objectStore(PROJECTS).delete(jobId);const artifacts=await request(tx.objectStore(ARTIFACTS).getAll());for(const a of artifacts)if(a.jobId===jobId)tx.objectStore(ARTIFACTS).delete(a.artifactId);await complete(tx);return true;}
function removeProject(projectsOrJobId,jobIdOrStorage,storage){if(Array.isArray(projectsOrJobId)&&storage){const next=clone(projectsOrJobId).filter(p=>projectIdentity(p)!==String(jobIdOrStorage||''));writeAllLegacy(next,storage);return next;}return removeProjectIndexed(projectsOrJobId);}

async function putArtifact({artifactId,jobId,blob,filename,mediaType,lineage={}}){
  if(!(blob instanceof Blob))throw new TypeError('Artifact bytes must be a Blob.');if(!artifactId||!jobId)throw new Error('artifactId and jobId are required.');
  fault('during-artifact-blob-write');const id=String(artifactId),owner=String(jobId),byteSize=blob.size,sha256=await hash.sha256Bytes(await blob.arrayBuffer()),db=await openDatabase(),tx=db.transaction(ARTIFACTS,'readwrite'),store=tx.objectStore(ARTIFACTS);let prior=null;
  try{prior=await request(store.get(id));if(prior&&String(prior.jobId)!==owner)throw storageError(`Artifact identity ${id} already belongs to another project.`,'CROSS_PROJECT_ARTIFACT_ID_COLLISION');if(prior){if(String(prior.sha256)!==sha256||Number(prior.byteSize)!==byteSize)throw storageError(`Artifact identity ${id} cannot be reused for different bytes.`,'ARTIFACT_ID_REUSE');await complete(tx);}else{store.put({artifactId:id,jobId:owner,blob,filename:String(filename||id),mediaType:String(mediaType||blob.type||'application/octet-stream'),byteSize,sha256,lineage:clone(lineage),createdAt:now()});await complete(tx);}}catch(error){try{tx.abort();}catch{}throw error;}
  if(prior){const priorDigest=await hash.sha256Bytes(await prior.blob.arrayBuffer());if(priorDigest!==String(prior.sha256)||priorDigest!==sha256||Number(prior.byteSize)!==byteSize)throw storageError(`Artifact identity ${id} cannot be reused because its stored bytes failed integrity verification.`,'ARTIFACT_ID_REUSE');return prior;}
  const verified=await getArtifact(id);if(!verified||String(verified.jobId)!==owner||verified.byteSize!==byteSize||await hash.sha256Bytes(await verified.blob.arrayBuffer())!==sha256){const cleanup=await openDatabase(),cleanupTx=cleanup.transaction(ARTIFACTS,'readwrite');const row=await request(cleanupTx.objectStore(ARTIFACTS).get(id));if(row&&String(row.jobId)===owner)cleanupTx.objectStore(ARTIFACTS).delete(id);await complete(cleanupTx);throw new Error('Artifact byte read-back verification failed; the unverified artifact was removed.');}return verified;
}
async function getArtifact(artifactId){const db=await openDatabase(),tx=db.transaction(ARTIFACTS,'readonly'),row=await request(tx.objectStore(ARTIFACTS).get(String(artifactId)));await complete(tx);return row||null;}
async function deleteArtifact(artifactId,jobId){const id=String(artifactId),owner=String(jobId||''),db=await openDatabase(),tx=db.transaction(ARTIFACTS,'readwrite'),store=tx.objectStore(ARTIFACTS);try{const row=await request(store.get(id));if(!row){await complete(tx);return false;}if(owner&&String(row.jobId)!==owner)throw storageError(`Artifact ${id} belongs to another project and was not deleted.`,'CROSS_PROJECT_ARTIFACT_DELETE');store.delete(id);await complete(tx);return true;}catch(error){try{tx.abort();}catch{}throw error;}}
async function listArtifacts(jobId){const db=await openDatabase(),tx=db.transaction(ARTIFACTS,'readonly'),rows=await request(tx.objectStore(ARTIFACTS).getAll());await complete(tx);return rows.filter(r=>r.jobId===String(jobId));}

const bytesToBase64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s);};
const base64ToBytes=text=>{const s=atob(text),out=new Uint8Array(s.length);for(let i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return out;};
async function compressBytes(bytes){if(typeof CompressionStream!=='function')throw Object.assign(new Error('CompressionStream is required for complete package export.'),{code:'COMPRESSION_STREAM_REQUIRED'});const stream=new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'));return new Uint8Array(await new Response(stream).arrayBuffer());}
async function decompressBytes(bytes){if(typeof DecompressionStream!=='function')throw Object.assign(new Error('DecompressionStream is required for complete package import.'),{code:'DECOMPRESSION_STREAM_REQUIRED'});const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return new Uint8Array(await new Response(stream).arrayBuffer());}
async function exportPackage(jobId){
  const projects=await readAll(),project=projects.find(p=>projectIdentity(p)===String(jobId));if(!project)throw new Error(`Project ${jobId} is not stored.`);const artifacts=await listArtifacts(jobId),artifactEntries=[];
  for(const a of artifacts){const bytes=new Uint8Array(await a.blob.arrayBuffer()),actualSize=bytes.byteLength,actualSha256=await hash.sha256Bytes(bytes);if(actualSize!==Number(a.byteSize)||actualSha256!==String(a.sha256))throw storageError(`Stored artifact ${a.artifactId} failed export-time byte verification.`,'ARTIFACT_INTEGRITY_MISMATCH');artifactEntries.push({artifactId:a.artifactId,jobId:a.jobId,filename:a.filename,mediaType:a.mediaType,byteSize:actualSize,sha256:actualSha256,lineage:a.lineage,createdAt:a.createdAt,base64:bytesToBase64(bytes)});}
  const exportedProject=canonicalProject(project),packageManifest={jobId,projectSha256:projectSha256(exportedProject),artifactCount:artifactEntries.length,artifacts:artifactEntries.map(a=>({artifactId:a.artifactId,filename:a.filename,mediaType:a.mediaType,byteSize:a.byteSize,sha256:a.sha256}))},body={schema:'closed-loop-project-package/1',projectSchema:project.schema,workflow:project.workflow,responseSchema:globalThis.closedLoopWorkflowSchema?.RESPONSE_SCHEMA,project:exportedProject,artifacts:artifactEntries,packageManifest,exportedAt:now()};const packageSha256=hash.sha256Value(body),payload={...body,packageSha256};const compressed=await compressBytes(new TextEncoder().encode(JSON.stringify(payload)));await metaPut('lastVerifiedExport',{jobId,packageSha256,artifactCount:artifactEntries.length,at:now()});return new Blob([compressed],{type:'application/gzip'});
}
async function importPackage(blob){
  const compressed=new Uint8Array(await blob.arrayBuffer()),json=new TextDecoder().decode(await decompressBytes(compressed)),payload=JSON.parse(json),{packageSha256,...body}=payload;
  if(hash.sha256Value(body)!==packageSha256)throw Object.assign(new Error('Project package hash mismatch.'),{existingProjectsUnchanged:true});
  if(body.schema!=='closed-loop-project-package/1')throw Object.assign(new Error('Unsupported project package schema.'),{existingProjectsUnchanged:true});
  const schemaApi=globalThis.closedLoopWorkflowSchema,project=clone(body.project),id=projectIdentity(project);
  if(project?.schema!=='closed-loop-project/2'||project?.workflow!=='mobile-closed-loop/30'||Number(project?.stageCount)!==30||Object.keys(project?.stages||{}).length!==30)throw Object.assign(new Error('Imported project identity or stage count is invalid.'),{existingProjectsUnchanged:true});
  if(body.projectSchema!==project.schema||body.workflow!==project.workflow||body.responseSchema!==schemaApi?.RESPONSE_SCHEMA)throw Object.assign(new Error('Package schema manifest does not match the embedded project.'),{existingProjectsUnchanged:true});
  if(!id)throw Object.assign(new Error('Imported project has no JOB_ID.'),{existingProjectsUnchanged:true});
  try{assertProjectIntegrity(project);}catch(error){throw Object.assign(error,{existingProjectsUnchanged:true});}
  const packageArtifacts=Array.isArray(body.artifacts)?body.artifacts:[],artifactIds=packageArtifacts.map(a=>String(a?.artifactId||''));if(artifactIds.some(x=>!x)||new Set(artifactIds).size!==artifactIds.length)throw Object.assign(new Error('Package artifacts contain a missing or duplicate artifact identity.'),{existingProjectsUnchanged:true});
  const verifiedArtifacts=[];
  for(const a of packageArtifacts){if(a.jobId!==undefined&&String(a.jobId)!==id)throw Object.assign(new Error(`Artifact ${a.artifactId} belongs to a different JOB_ID than the package project.`),{existingProjectsUnchanged:true});const bytes=base64ToBytes(a.base64);if(bytes.byteLength!==Number(a.byteSize))throw Object.assign(new Error(`Artifact ${a.artifactId} byte size mismatch.`),{existingProjectsUnchanged:true});const digest=await hash.sha256Bytes(bytes);if(digest!==a.sha256)throw Object.assign(new Error(`Artifact ${a.artifactId} hash mismatch.`),{existingProjectsUnchanged:true});verifiedArtifacts.push({...clone(a),jobId:id,blob:new Blob([bytes],{type:a.mediaType||'application/octet-stream'})});}
  const manifest=body.packageManifest||{},manifestArtifacts=Array.isArray(manifest.artifacts)?manifest.artifacts:[],manifestIds=manifestArtifacts.map(a=>String(a?.artifactId||''));if(manifestIds.some(x=>!x)||new Set(manifestIds).size!==manifestIds.length)throw Object.assign(new Error('Package manifest contains a missing or duplicate artifact identity.'),{existingProjectsUnchanged:true});if(manifest.jobId!==id||Number(manifest.artifactCount)!==verifiedArtifacts.length||manifestArtifacts.length!==verifiedArtifacts.length||manifest.projectSha256!==projectSha256(project))throw Object.assign(new Error('Package manifest does not reconcile with the embedded project and artifacts.'),{existingProjectsUnchanged:true});
  const manifestById=new Map(manifestArtifacts.map(a=>[String(a.artifactId),a]));for(const a of verifiedArtifacts){const m=manifestById.get(String(a.artifactId));if(!m||m.sha256!==a.sha256||Number(m.byteSize)!==Number(a.byteSize)||m.filename!==a.filename||String(m.mediaType||'')!==String(a.mediaType||''))throw Object.assign(new Error(`Package manifest mismatch for artifact ${a.artifactId}.`),{existingProjectsUnchanged:true});}
  const packagedById=new Map(verifiedArtifacts.map(a=>[String(a.artifactId),a]));for(const artifact of (project.projectData?.artifacts||[]).filter(record=>record?.active!==false&&!record?.invalidatedBy)){const artifactId=String(globalThis.closedLoopWorkflowEngine?.recordId?.(artifact,'artifacts')||''),availability=String(globalThis.closedLoopWorkflowEngine?.recordValue?.(artifact,'AVAILABILITY')||'').toUpperCase();if(availability!=='BYTES_PERSISTED_AND_VERIFIED')continue;const packaged=packagedById.get(artifactId);if(!packaged||String(globalThis.closedLoopWorkflowEngine.recordValue(artifact,'FILENAME')||'')!==String(packaged.filename)||Number(globalThis.closedLoopWorkflowEngine.recordValue(artifact,'BYTE_SIZE'))!==Number(packaged.byteSize)||String(globalThis.closedLoopWorkflowEngine.recordValue(artifact,'SHA256')||'')!==String(packaged.sha256))throw Object.assign(new Error(`Canonical artifact ${artifactId||'UNKNOWN'} does not reconcile with verified package bytes.`),{existingProjectsUnchanged:true});}
  const db=await openDatabase();fault('before-import-transaction');const tx=db.transaction([PROJECTS,ARTIFACTS,META],'readwrite'),projects=tx.objectStore(PROJECTS),artifacts=tx.objectStore(ARTIFACTS),meta=tx.objectStore(META);
  try{
    const prior=await request(projects.get(id)),currentRevision=Number(prior?.revision||0),importedRevision=Math.max(0,Number(project.revision||0)),next=clone(project);next.revision=Math.max(currentRevision,importedRevision)+1;delete next.projectSha256;assertProjectIntegrity(next);const digest=projectSha256(next);const existingArtifacts=await request(artifacts.getAll()),incomingIds=new Set(verifiedArtifacts.map(a=>String(a.artifactId)));
    for(const existing of existingArtifacts){const artifactId=String(existing.artifactId);if(String(existing.jobId)===id&&!incomingIds.has(artifactId))artifacts.delete(artifactId);else if(String(existing.jobId)!==id&&incomingIds.has(artifactId))throw storageError(`Imported artifact identity ${artifactId} already belongs to another project.`,'CROSS_PROJECT_ARTIFACT_ID_COLLISION');}
    fault('during-import-project-write');projects.put({jobId:id,revision:next.revision,project:next,projectSha256:digest,updatedAt:now()});for(const a of verifiedArtifacts){fault('during-import-artifact-write');artifacts.put({artifactId:String(a.artifactId),jobId:id,blob:a.blob,filename:String(a.filename),mediaType:String(a.mediaType||'application/octet-stream'),byteSize:Number(a.byteSize),sha256:String(a.sha256),lineage:clone(a.lineage||{}),createdAt:a.createdAt||now()});}meta.put({key:'selectedProject',value:id,updatedAt:now()});meta.put({key:'lastCommittedRevision',value:{jobId:id,revision:next.revision,projectSha256:digest},updatedAt:now()});meta.put({key:'lastVerifiedImport',value:{jobId:id,packageSha256,artifactCount:verifiedArtifacts.length,at:now()},updatedAt:now()});fault('before-import-commit');await complete(tx);next.projectSha256=digest;try{new BroadcastChannel('closed-loop-reliability').postMessage({type:'PROJECT_CHANGED',jobId:id,revision:next.revision});}catch{}return next;
  }catch(error){try{tx.abort();}catch{}throw Object.assign(error,{existingProjectsUnchanged:true});}
}

async function storageHealth(){let persistent=false,estimate={usage:null,quota:null};try{persistent=await navigator.storage.persist();estimate=await navigator.storage.estimate();}catch{}return {database:DB_NAME,persistent:Boolean(persistent),usage:estimate.usage??null,quota:estimate.quota??null,lastCommittedRevision:await metaGet('lastCommittedRevision'),lastVerifiedExport:await metaGet('lastVerifiedExport'),migrationStatus:await metaGet('migrationStatus')};}
function archiveMigrationPayload(project,archive){if(!project||typeof project!=='object')throw new TypeError('A project is required.');project.projectData=project.projectData&&typeof project.projectData==='object'?project.projectData:{};project.projectData.migrationArchives=Array.isArray(project.projectData.migrationArchives)?project.projectData.migrationArchives:[];const record={...clone(archive),operational:false};project.projectData.migrationArchives.push(record);return record;}
function clearLegacy(storage=globalThis.localStorage){if(!storage)return;for(const key of LEGACY_KEYS)try{storage.removeItem(key);}catch{}}

const ready=(async()=>{if(globalThis.indexedDB)await migrateLegacy();return true;})();
globalThis.closedLoopProjectStore=Object.freeze({archiveMigrationPayload,version:'closed-loop-project-store/2',DB_NAME,DB_VERSION,stores:Object.freeze({projects:PROJECTS,artifacts:ARTIFACTS,meta:META}),STORE_KEY,LEGACY_KEYS,clone,projectIdentity,projectSha256,validateProjectIntegrity,openDatabase,ready,readAll,writeAll,writeProject,replaceProject,transact,removeProject,putArtifact,getArtifact,deleteArtifact,listArtifacts,exportPackage,importPackage,storageHealth,metaGet,metaPut,clearLegacy});
})();