(()=>{
'use strict';
const STORE='mobile-closed-loop-agent',REGISTRY='closed-loop-project-registry-v4',ACTIVE='closed-loop-active-project-v4';
const OPS=['Define Job','Inventory Sources','Research Requirements','Compile Atomic Requirements','Resolve Conflicts','Build Acceptance Tests','Build Failure / Mutation Tests','Author Production Instruction','Preflight Instruction','Freeze Candidate','Run 10 Independent Executions','Verify Every Run','Compare Runs','Root-Cause Defects','Add Regression Tests','Correct Responsible Layer','Freeze New Version','Run 10 New Independent Executions','Repeat Until Converged','Unchanged 10-Execution Confirmation','Freeze Approved Baseline','Generate Finished Product','Deterministic Verification','Independent Semantic Verification','Adversarial Verification','Final Representation Inspection','Process Audit','Product Audit','ACCEPTED / REJECTED / BLOCKED','Verify Release Hash','Release Exact Accepted Artifact'];
const TEN_RUN=new Set([11,18,20]),RUN_SCOPED=new Set([11,12,18,20]);
const INDEPENDENT=new Set([9,11,12,13,14,20,23,24,25,26,27,28,29,30]);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString(),pad=n=>String(n).padStart(2,'0');
const read=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}};
const write=s=>localStorage.setItem(STORE,JSON.stringify(s));
const active=()=>localStorage.getItem(ACTIVE)||'';
const registry=()=>{try{return JSON.parse(localStorage.getItem(REGISTRY)||'{}')}catch{return {}}};
const id=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;
function data(s){if(!s.projectData)s.projectData={};const d=s.projectData;for(const k of ['generatedPrompts','generatedOutputs','runRecords','freshContexts','history'])if(!Array.isArray(d[k]))d[k]=[];if(!d.userJobInput)d.userJobInput={};if(!d.externalResearch)d.externalResearch={questions:[],sources:[],findings:[]};if(!d.workflowArtifacts)d.workflowArtifacts={};return d}
function save(s){write(s);const k=active();if(k){const r=registry();r[k]=JSON.parse(JSON.stringify(s));localStorage.setItem(REGISTRY,JSON.stringify(r));}}
function json(v){return JSON.stringify(v??null,null,2)}
function jobContext(s){const d=data(s),j=s.job||{},u=d.userJobInput||{};return {jobId:j.JOB_ID||d.jobId||'',title:j.JOB_TITLE||d.title||'',objective:u.objective||j.EXACT_USER_OBJECTIVE_VERBATIM||d.objective?.exactUserObjective||'',deliverable:u.deliverable||j.EXACT_DELIVERABLE_REQUESTED||d.objective?.deliverable||'',requestedActions:u.requestedActions||[],questions:u.questions||[],boundaries:u.boundaries||[],suppliedMaterials:u.suppliedMaterials||d.suppliedMaterials||[],constraints:u.constraints||d.constraints||[],prohibitions:u.prohibitions||[],requiredMethods:u.requiredMethods||[],outputProperties:u.outputProperties||[],temporalScope:u.temporalScope||j.DEADLINE_OR_TEMPORAL_SCOPE||'',geographicScope:u.geographicScope||'',acceptanceConditions:u.acceptanceConditions||[],uncertainties:u.uncertainties||[],externalResearchQuestions:u.externalResearchQuestions||d.externalResearch?.questions||[]}}
function authorized(s,n,run){const d=data(s),base={userJobInput:jobContext(s)};const ext={researchQuestions:d.externalResearch?.questions||[],externalSources:d.externalResearch?.sources||[],researchFindings:d.externalResearch?.findings||d.research||[]};const wf={requirements:d.requirements||[],requirementResolution:d.requirementResolution||[],tests:d.tests||[],mutations:d.mutations||[],productionInstruction:d.productionInstruction||{},changes:d.changes||[],blockers:d.blockers||[],defects:d.defects||[],regressions:d.regressions||[],baseline:d.baseline||{},product:d.product||{},audits:d.audits||{},representation:d.representation||{},release:d.release||{},evidenceChains:d.evidenceChains||[]};
if(n===1)return base;
if(n===2)return {...base,researchQuestions:ext.researchQuestions};
if(n===3)return {...base,...ext};
if(n===4)return {...base,...ext};
if(n<=7)return {...base,...ext,requirements:wf.requirements,requirementResolution:wf.requirementResolution,tests:wf.tests,mutations:wf.mutations};
if(n<=10)return {...base,...ext,requirements:wf.requirements,tests:wf.tests,mutations:wf.mutations,productionInstruction:wf.productionInstruction,blockers:wf.blockers};
if(n===11||n===18||n===20)return {...base,requirements:wf.requirements,productionInstruction:wf.productionInstruction,baseline:n===20?wf.baseline:undefined,runId:`RUN-${String(run).padStart(3,'0')}`,frozenCandidate:d.candidate||d.freeze||d.baseline||{}};
if(n===12)return {...base,requirements:wf.requirements,tests:wf.tests,runId:`RUN-${String(run).padStart(3,'0')}`,runOutput:(d.runRecords||[]).find(x=>String(x.runId||'').endsWith(String(run).padStart(3,'0')))||null};
return {...base,...ext,...wf,runRecords:d.runRecords||[],verificationRecords:d.verificationRecords||[],comparisons:d.comparisons||[],convergence:d.convergence||{},confirmation:d.confirmation||{}}}
const TASKS={
1:'Capture the job losslessly. Preserve exactly what the user requested, supplied, constrained, prohibited, assumed, left uncertain, and asked the system to research. Do not research or answer the substantive job yet.',
2:'Perform real outward source discovery for every research question that can affect correctness. Find independent applicable authorities. Do not use the current product, implementation, generated workflow artifacts, project JSON, previous agent conclusions, or previous tests as authority for what the product is required to be.',
3:'Read the discovered external sources and extract substantive findings, obligations, exceptions, prohibitions, applicability facts, dependencies, conflicts, and unresolved research questions. New research questions must route back to external source discovery rather than being guessed.',
4:'Compile atomic requirements from exactly two legitimate origins: explicit user requirements and independently established external authority. Existing implementation behavior and workflow-generated artifacts are not requirement sources.',
5:'Audit the requirement set for duplicates, conflicts, impossible combinations, undefined terms, circular dependencies, missing prerequisites, unsupported requirements, unknown applicability, and requirements without a verification path. Resolve only with legitimate authority.',
6:'Create acceptance verification before production instructions exist. Every active mandatory requirement needs a verification procedure. Prefer deterministic verification whenever the property is deterministically testable. Calculate coverage and block if mandatory coverage is incomplete.',
7:'Create invalid and mutation fixtures that intentionally violate requirements, execute or specify the assigned validators, and establish that invalid cases are rejected. A validator that accepts an intentionally invalid fixture is defective.',
8:'Author the production instruction strictly from the resolved requirements and authorized controls. Include objective, authorized inputs, authority rules, scope, defined terms, ordered procedure, decision rules, tool rules, output contract, failure behavior, and completion criteria. Trace material clauses to requirements or necessary controls.',
9:'Independently preflight the production instruction without performing the target job. Find ambiguity, undefined objects, missing information, unavailable capabilities, conflicts, unverifiable commands, unclear responsibility/order, missing failure behavior, and missing traceability.',
10:'Freeze the exact candidate used by the execution batch. Preserve component identities, versions, hashes where practical, tool configuration, and distribution rules. Any material change terminates this frozen batch.',
11:'Execute the frozen production candidate exactly once in this fresh isolated run. Do not inspect another run, reviewer feedback, failure explanations, or proposed corrections. Produce the required output and a complete execution record.',
12:'Independently verify the assigned run against every applicable requirement using its approved tests and evidence. Return only SATISFIED, VIOLATED, or UNDETERMINED for requirement outcomes. The generator cannot be its own sole verifier.',
13:'Compare all ten verified executions without selecting a favorite. Preserve repeated failures, unique failures, interpretation variance, prohibited output variance, evaluator disagreement, and inconclusive verification as evidence.',
14:'Perform root-cause analysis for every material defect. Trace backward through execution, instruction, requirement, research, source, input, tool, and audit layers and identify the earliest defective layer instead of patching the visible symptom.',
15:'Convert every confirmed defect into a permanent regression test. Preserve a reproducing fixture, evidence that it failed before correction, and evidence that the same regression succeeds after correction.',
16:'Correct the responsible earliest defective layer. Create controlled new identities for changed artifacts, identify everything invalidated downstream, and preserve unchanged artifacts only when their validity is still established.',
17:'Freeze the corrected material as a new candidate. Preserve the exact new component set and prevent stale prior-batch evidence from counting as current.',
18:'Execute the newly frozen corrected candidate exactly once in this fresh isolated run. No old execution conversation or other run output may be visible. Preserve output and provenance separately.',
19:'Determine whether the current candidate is converged from actual metrics. Require 100% mandatory requirement coverage, 100% mandatory verification coverage, 100% applicable regression success, zero critical defects, zero major defects, zero mandatory unresolved unknowns, zero correctness-affecting contradictions/ambiguities, and zero unexplained correctness-affecting execution variance. If any condition fails, route back to the earliest responsible operation.',
20:'Perform one unchanged confirmation execution in a new independent context using exactly the already-converged frozen candidate. No component may change. Preserve this run separately and subject it to the same required verification.',
21:'Freeze the approved production baseline only after unchanged confirmation succeeds. Preserve exact approved component identities and immutable artifact hashes separately from working material.',
22:'Generate the actual requested finished product in a fresh production context using only the approved baseline. Preserve exact output bytes, files, identities, provenance, failures, and deviations. Do not declare release acceptance.',
23:'Run every applicable deterministic validator against the actual finished product bytes, not an earlier representation. Record exact product identity, procedure, expected result, actual result, and evidence.',
24:'Independently verify the actual finished product semantically against every semantic requirement and authoritative evidence. Compare observed meaning to required meaning and use SATISFIED, VIOLATED, or UNDETERMINED.',
25:'Attempt to disprove correctness adversarially. Search for omissions, prohibited material, contradictions, unsupported claims, wrong versions, broken references, hidden assumptions, partial completion, semantic nonsense, terminology drift, unhandled cases, stale information, malformed files, hidden content, export corruption, and historical regressions.',
26:'Inspect the exact representation the recipient will receive: every rendered page/screen/image, transformed file, package member, name, version, layout, clipping condition, hidden content, export result, and file integrity condition.',
27:'Audit process correctness as its own proposition. Establish that approved inputs, instruction, tools, tests, context controls, change controls, and custody rules were actually followed. Do not infer product correctness from a correct process.',
28:'Audit product correctness as its own proposition. Establish every mandatory product requirement from affirmative evidence and actual final-product verification. Do not infer process correctness from a correct-looking product.',
29:'Apply exactly one release state: ACCEPTED, REJECTED, or BLOCKED. Acceptance requires affirmative evidence for every mandatory requirement and successful mandatory validation. Demonstrated mandatory violation produces REJECTED. Missing mandatory evidence/authority/input/capability produces BLOCKED under the controlling rule.',
30:'Verify that every exact artifact selected for release is byte-for-byte the audited artifact using SHA-256. Any mismatch, missing hash, unknown comparison, or post-audit modification prevents release and invalidates authorization.',
31:'Release only the exact ACCEPTED, hash-matched artifact. Preserve delivery identity, evidence chain, provenance, release decision, and permanent regression/defect history. Do not substitute, re-export, modify, or replace the accepted bytes.'};
const OUTPUTS={
1:'Return: JOB CONTROL; EXACT USER OBJECTIVE VERBATIM; DELIVERABLE; SUPPLIED MATERIALS; BOUNDARIES; CONSTRAINTS; PROHIBITIONS; REQUIRED METHODS; ACCEPTANCE CONDITIONS; ASSUMPTIONS; UNKNOWNS; EXTERNAL RESEARCH QUESTIONS; STAGE DECISION and evidence.',
2:'Return: RESEARCH QUESTION MAP; independently discovered SOURCE RECORDS with authority/version/date/relevant portions; AUTHORITY HIERARCHY; SOURCE CONFLICTS; missing sources; blockers; discovery completeness; decision evidence.',
3:'Return: SOURCE-BY-SOURCE FINDINGS; candidate obligations; prohibitions; exceptions; dependencies; applicability conditions; conflicts; research gaps; new research questions; saturation evidence; decision.',
4:'Return one atomic record per requirement with stable REQ_ID, origin (USER or EXTERNAL AUTHORITY), exact traceability, applicability, dependencies, observable satisfaction condition, verification method, failure condition, severity, and status.',
5:'Return requirement-set defect records, source-backed resolutions, blockers, dependency impact, consistency counts, changed requirement identities, and decision evidence.',
6:'Return TEST records, requirement-to-test coverage, method-selection evidence, blocked tests, exact mandatory coverage calculation, and decision.',
7:'Return mutation/failure records, invalid fixture inventory, validator calibration results, defective-validator records, mutation coverage, and decision.',
8:'Return the complete production instruction plus clause traceability, defined terms, decision rules, tool rules, output contract, failure behavior, and completion criteria.',
9:'Return reviewer independence, sentence/clause review records, defects, corrected instruction if needed, repeated full-review evidence, approved instruction identity, and decision.',
10:'Return candidate ID, frozen component manifest, tool configuration, hashes where practical, role-based distribution rules, freeze result, and decision evidence.',
11:'Return RUN_ID; execution status; exact requested output; execution record; tools used; failures; unresolved unknowns; and complete output/file inventory.',
12:'Return verifier independence and one verification record per applicable requirement with TEST_ID, exact evidence, result, defect ID where applicable, and reconciled counts.',
13:'Return one cross-run comparison per requirement, repeated failure groups, unique failures, correctness-affecting variance defects, inconclusive verification, and comparison summary.',
14:'Return one root-cause record per material defect, backward-trace evidence, earliest defective layer, correction required, downstream invalidation map, and decision.',
15:'Return one regression record per confirmed defect, reproducing fixture, pre-correction failure evidence, post-correction success evidence, permanent-suite location/status, and coverage summary.',
16:'Return change set, old-to-new identity map, exact corrections, invalidated artifacts/determinations, required reruns, unchanged-artifact validity evidence, and decision.',
17:'Return new candidate identity and exact frozen component manifest, changed-component lineage, invalidated prior evidence, distribution rules, and freeze decision.',
18:'Return RUN_ID; execution status; exact output; execution record; tools; failures; unknowns; output inventory; and isolation evidence.',
19:'Return source counts, exact convergence calculations, each convergence condition TRUE/FALSE, failed conditions, required return operation, and CONVERGED / NOT CONVERGED / BLOCKED.',
20:'Return confirmation run identity, zero-change evidence, execution output and provenance, complete applicable verification result, new findings, and confirmation decision.',
21:'Return baseline identity, supporting confirmation evidence, approved version/component set, immutable file hashes, distribution rules, and baseline-control decision.',
22:'Return product identity/version, baseline identity, execution identity, actual finished deliverable, execution record, output inventory/hashes, failures and unresolved unknowns.',
23:'Return one deterministic product-test result per applicable test with exact input hash, validator/tool, procedure, expected and actual result, evidence, defects, reconciled counts, and decision.',
24:'Return evaluator independence and one semantic record per active semantic requirement with exact product location, authoritative evidence, observed meaning, required meaning, determination, evidence, and defects.',
25:'Return reviewer independence, one adversarial attack record per applicable category, counterexamples, evidence, defect IDs/severity, regression findings, and decision.',
26:'Return delivery artifact inventory, transformation chain, page/view inspection records, package inspection records, defects, inspection coverage, representation determination, and evidence.',
27:'Return approved-vs-actual input/instruction/tool/test/context/change/custody evidence, process defects/blockers, PROCESS CORRECTNESS = SATISFIED/VIOLATED/UNDETERMINED, and controlling evidence.',
28:'Return mandatory requirement evidence ledger, mandatory deterministic and semantic results, adversarial/representation status, defects/blockers/unknowns, PRODUCT CORRECTNESS = SATISFIED/VIOLATED/UNDETERMINED, and controlling evidence.',
29:'Return product/baseline identity, requirement/validator counts, violations, unknowns, defects, blockers, applied decision rule, exactly one state ACCEPTED/REJECTED/BLOCKED, and affirmative controlling evidence.',
30:'Return release-gate prerequisite, SHA-256 tool/method, one audited-vs-release hash record per file, exact comparisons, mismatch actions, counts, delivery authorization, and exact authorized artifact identities.',
31:'Return exact released artifact identities and hashes, delivery record, evidence-chain preservation location, permanent defect/regression preservation status, and FINAL RELEASE STATUS = RELEASED or NOT RELEASED.'};
function prompt(s,n,run){const ctx=authorized(s,n,run),ind=INDEPENDENT.has(n);return `ROLE\nYou are the assigned ${ind?'independent ':''}reliability-workflow agent for Operation ${pad(n)} — ${OPS[n-1]}.\n\nPROJECT ARCHITECTURE — DO NOT VIOLATE\n1. USER JOB INPUT is what the user supplied, asserted, requested, constrained, uploaded, or defined.\n2. EXTERNAL RESEARCH SOURCES are independently discovered authorities used to establish externally governed facts and requirements.\n3. WORKFLOW-GENERATED ARTIFACTS are requirements, prompts, instructions, tests, executions, evidence, defects, audits, products, hashes, and provenance. They are NOT external authority merely because they exist.\n4. The unfinished product, current implementation, generated code, tests, project JSON, prior agent conclusions, and prior workflow reports cannot establish what the product is required to be. They may be inspected only as implementation/provenance/verification evidence when this operation legitimately requires that evidence.\n5. Preserve UNKNOWN, NONE, NOT APPLICABLE, SATISFIED, VIOLATED, UNDETERMINED, ACCEPTED, REJECTED, and BLOCKED exactly. Missing evidence never becomes satisfaction.\n6. Do not silently resolve an authoritative conflict or bypass a blocker.\n${ind?'7. This operation requires independent evaluation. Do not use the generator as its own sole verifier and do not import contamination from another run/reviewer unless the operation explicitly requires cross-run comparison.\n':''}\nJOB CONTROL\nJOB_ID: ${s.job?.JOB_ID||'UNKNOWN'}\nOPERATION: ${pad(n)} — ${OPS[n-1]}\n${RUN_SCOPED.has(n)?`RUN_ID: RUN-${String(run).padStart(3,'0')}\n`:''}CURRENT PROJECT STATE: ${s.job?.CURRENT_STATE||data(s).currentState||'UNKNOWN'}\n\nAUTHORIZED PROJECT RECORDS FOR THIS OPERATION\n${json(ctx)}\n\nTASK\n${TASKS[n]}\n\nREQUIRED OUTPUT\n${OUTPUTS[n]}\n\nCOMPLETION RULE\nDo not claim this operation complete unless its required output and evidence are actually present. If mandatory evidence, authority, input, or capability needed to establish the result is unavailable, return BLOCKED with the exact missing condition and downstream work that must stop.`}
function inject(){const host=document.getElementById('workspace-project');if(!host)return;const s=read();if(!s)return;const d=data(s),n=Math.max(1,Math.min(31,Number(d.currentOperation||1)));let panel=document.getElementById('agent-work-panel');if(!panel){panel=document.createElement('section');panel.id='agent-work-panel';panel.className='project-panel agent-work';host.prepend(panel)}const saved=(d.generatedPrompts||[]).filter(x=>Number(x.operation||x.stage)===n);panel.innerHTML=`<div class="agent-work-head"><div><div class="agent-kicker">DO THE CURRENT WORK</div><h2>Agent prompt · ${pad(n)} ${esc(OPS[n-1])}</h2><p>Copy this exact project-aware prompt into the agent assigned to this operation. Save the response here so it becomes project history and evidence.</p></div></div>${RUN_SCOPED.has(n)?`<label for="agent-run-select">Run</label><select id="agent-run-select">${Array.from({length:10},(_,i)=>`<option value="${i+1}">RUN-${String(i+1).padStart(3,'0')}</option>`).join('')}</select>`:''}<div class="agent-prompt-actions"><button id="copy-agent-prompt" class="primary" type="button">Copy prompt</button><button id="refresh-agent-prompt" type="button">Refresh from project</button></div><textarea id="agent-prompt-text" class="agent-prompt" readonly aria-label="Generated agent prompt"></textarea><details class="response-capture"><summary>Save the agent response</summary><div><label for="agent-response-text">Complete agent response</label><textarea id="agent-response-text" placeholder="Paste the complete response here without silently editing it."></textarea><label for="agent-output-files">Output files / references</label><input id="agent-output-files" placeholder="Exact filenames or references, comma separated"><div class="agent-prompt-actions"><button id="save-agent-response" class="primary" type="button">Save response to project</button></div><p id="agent-save-status" class="muted"></p></div></details>${saved.length?`<details class="response-capture"><summary>Saved prompts for this operation (${saved.length})</summary><div class="saved-prompt-list">${saved.slice().reverse().map(x=>`<details class="record-card"><summary>${esc(x.promptId||'Prompt')} · ${esc(x.runId||'operation')}</summary><div class="record-body"><pre class="copy">${esc(x.prompt||x.text||'')}</pre></div></details>`).join('')}</div></details>`:''}`;
const run=()=>Number(document.getElementById('agent-run-select')?.value||1),area=document.getElementById('agent-prompt-text');const fill=()=>area.value=prompt(read(),n,run());fill();document.getElementById('agent-run-select')?.addEventListener('change',fill);document.getElementById('refresh-agent-prompt').onclick=fill;document.getElementById('copy-agent-prompt').onclick=async()=>{const text=area.value;try{await navigator.clipboard.writeText(text)}catch{area.select();document.execCommand('copy')}const ss=read(),dd=data(ss),rec={promptId:id('PROMPT'),operation:n,operationName:OPS[n-1],runId:RUN_SCOPED.has(n)?`RUN-${String(run()).padStart(3,'0')}`:'NOT APPLICABLE',createdAt:now(),prompt:text,authorizedInputSnapshot:authorized(ss,n,run()),independentContextRequired:INDEPENDENT.has(n)};dd.generatedPrompts.push(rec);dd.history.unshift({historyId:id('HIST'),dateTime:now(),type:'prompt-copied',summary:`Copied prompt for Operation ${pad(n)} ${OPS[n-1]}`,details:{promptId:rec.promptId,runId:rec.runId}});save(ss);document.getElementById('copy-agent-prompt').textContent='Copied';setTimeout(()=>{const b=document.getElementById('copy-agent-prompt');if(b)b.textContent='Copy prompt'},1200)};document.getElementById('save-agent-response').onclick=()=>{const text=document.getElementById('agent-response-text').value;if(!text.trim()){document.getElementById('agent-save-status').textContent='Paste the complete agent response first.';return}const ss=read(),dd=data(ss),runId=RUN_SCOPED.has(n)?`RUN-${String(run()).padStart(3,'0')}`:'NOT APPLICABLE',promptText=area.value,promptRec={promptId:id('PROMPT'),operation:n,operationName:OPS[n-1],runId,createdAt:now(),prompt:promptText,authorizedInputSnapshot:authorized(ss,n,run()),independentContextRequired:INDEPENDENT.has(n)},receipt={receiptId:id('RECEIPT'),operation:n,operationName:OPS[n-1],runId,contextId:id('CTX'),receivedAt:now(),promptId:promptRec.promptId,completeResponse:text,outputFiles:document.getElementById('agent-output-files').value.split(',').map(x=>x.trim()).filter(Boolean),truncationDetected:'UNKNOWN',refusalOrPartialRefusal:'UNKNOWN',toolFailures:[],deviations:[],nextRequiredVerificationOperation:n===11||n===18||n===20?12:Math.min(31,n+1)};dd.generatedPrompts.push(promptRec);dd.generatedOutputs.push(receipt);if(RUN_SCOPED.has(n))dd.runRecords.push({runId,operation:n,contextId:receipt.contextId,promptId:promptRec.promptId,receiptId:receipt.receiptId,response:text,outputFiles:receipt.outputFiles,recordedAt:receipt.receivedAt});dd.history.unshift({historyId:id('HIST'),dateTime:now(),type:'agent-output-received',summary:`Saved agent response for Operation ${pad(n)} ${OPS[n-1]}`,details:{receiptId:receipt.receiptId,runId}});save(ss);document.getElementById('agent-save-status').textContent=`Saved as ${receipt.receiptId}. The complete response is now in project history.`;document.getElementById('agent-response-text').value='';document.getElementById('agent-output-files').value=''};}
const css=document.createElement('style');css.textContent=`#agent-work-panel{border:1px solid #a7bde5;background:#fbfdff}.agent-work-head h2{margin:0 0 4px!important;font-size:15px!important}.agent-work-head p{margin:0 0 8px;color:#555;font-size:11px}.agent-kicker{font-size:9px;font-weight:900;letter-spacing:.09em;color:#174eaa;margin-bottom:2px}.agent-prompt-actions{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.agent-prompt-actions button{min-height:31px!important;padding:5px 9px!important;font-size:11px!important}.agent-prompt{min-height:190px!important;max-height:380px;font:10.5px/1.38 ui-monospace,SFMono-Regular,Menlo,monospace;background:#f5f7fb;border-color:#b9c8e0!important}.response-capture{border-top:1px solid #dce4f1;margin-top:8px;padding-top:7px}.response-capture>summary{cursor:pointer;font-weight:800;font-size:11px}.response-capture textarea{min-height:120px}.saved-prompt-list{margin-top:7px}@media(max-width:560px){.agent-prompt{min-height:230px}.agent-prompt-actions{display:grid;grid-template-columns:1fr 1fr}}`;document.head.appendChild(css);
let timer;const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(inject,60)});obs.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('closed-loop-core-ready',()=>setTimeout(inject,80));window.addEventListener('load',()=>setTimeout(inject,150));setTimeout(inject,250);
})();