(()=>{
'use strict';
const core=globalThis.closedLoopCore;
const schema=globalThis.closedLoopWorkflowSchema;
const hash=globalThis.closedLoopHash;
if(!core||!schema||!hash)throw new Error('workbook.js, hash.js, and workflow-schema.js must load before prompt-engine.js.');
const show=v=>{if(v===undefined||v===null||v==='')return 'UNKNOWN';if(Array.isArray(v)&&!v.length)return 'NONE';if(typeof v==='object')return JSON.stringify(v,null,2);return String(v)};
const procedures={
1:'Initialize only this current job from this current job’s exact user input. Preserve the verbatim objective, exact deliverable, supplied-material inventory and provenance, inspection state, format requirements, temporal and geographic scope, user-supplied authority, tools, prohibitions, explicit user requirements, assumptions, and unresolved unknowns. Determine whether the requested deliverable can actually be completed in the authorized environment. The application itself does not connect to or modify an external repository. If required repository, runtime, account, network, deployment, or tool access is absent, do not pretend implementation occurred; when a complete reliable implementation-ready specification, architecture, patch plan, acceptance package, or other self-contained substitute can satisfy the underlying user objective, propose that feasible substitute as EXACT_DELIVERABLE_REQUESTED for human intent confirmation and state the execution limitation explicitly. Self-contained work such as research, analysis, specifications, papers, applications, and similar artifacts may be produced directly when the authorized environment is sufficient. The application owns JOB_ID and controlled input identity. Do not create or prescribe a reusable master job or prompt for unrelated jobs. Do not begin substantive external-source research or downstream production work.',
2:'Build the independent external source inventory for this current job only. Treat the desired or suggested source count as a search target, never as authority to invent or pad sources. Select sources according to what the job actually needs: prefer primary, official, controlling authority where such authority exists; otherwise prefer the most authoritative, reputable, direct, and current evidence appropriate to the claim and domain. Verify source identity, issuer or publisher, currency, supersession state, and applicability from the source itself when possible; use reputable secondary sources for corroboration or context when appropriate, not as substitutes for available controlling primary authority. If a target count is supplied, seek that many legitimate useful sources when the domain supports them, continue beyond it when needed for governing coverage, and return fewer rather than adding weak or irrelevant sources. If no legitimate external authority applies after evidence-supported inspection, return an explicit no-applicable-source determination rather than inventing a source. Stage 01 User Job Input and supplied material remain authorized project inputs, but they are not automatically independent external governing sources and must not receive SOURCE_ID merely because they were supplied. Never use the target product, this operating application, its repository, source code, UI, stored state, screenshots, prior versions, previous generated targets, project outputs, generated prompts/instructions, or another implementation of the same target as governing source authority. The application assigns canonical SOURCE_ID values and source-set version after validated ingestion.',
3:'Research only the current accepted Stage 02 independent external source set, source-by-source and pass-by-pass. Examine exact portions and separately capture facts, mandatory obligations, recommendations, optional practices, examples, prohibitions, exceptions, dependencies, applicability facts, restrictions, invalidating material, conflicts, superseded guidance, source evidence, candidate requirements, and unresolved questions. Do not research the target product, this operating application, repository source code, prior implementations, project-generated artifacts, or current UI behavior as requirement authority. Repeat discovery passes until saturation is actually supported by the evidence.',
4:'Compile atomic requirements for this current job from authorized User Job Input plus legitimately applicable Stage 03 external-source research, preserving provenance for each obligation. Propose one independently testable obligation per requirement where possible and record type, mandatory/optional status, governing source or user-input relationship, exact source location when applicable, authority, applicability, dependencies, prohibitions, defined terms, observable satisfaction condition, intended verification method, expected evidence, failure condition, severity, and notes. The application assigns REQ_ID and controlled requirement-set version. Do not derive requirements from the target product or an existing implementation merely because that implementation contains a behavior.',
5:'Resolve the current job’s requirement set. Detect duplicate or conflicting requirements, impossible combinations, undefined terms, circular dependencies, missing prerequisites, unsupported requirements, uncertain applicability, and requirements lacking a verification method. Preserve the substantive defect, governing evidence, proposed resolution or unresolved state, affected requirement, and blockers. Human authority decides genuine user tradeoffs; the application owns controlled versions and downstream invalidation. Never silently guess away a conflict or manufacture authority.',
6:'Build this job’s verification suite before any production instruction is authored. Every active mandatory requirement must have at least one valid proposed test. Use the strongest suitable method, including exact computation, programmatic checks, schema or structure checks, source comparison, rule-based verification, and independent human meaning/content review where deterministic checks cannot establish satisfaction. Define inputs, tools, procedure, expected result, failure condition, and evidence to preserve. The application assigns TEST_ID and calculates exact mandatory requirement-to-test coverage; do not assert application-owned coverage values.',
7:'Build this job’s mutation/failure suite to prove validators reject realistic invalid states. Include applicable missing inputs, invalid values, wrong versions, duplicate identifiers, contradictions, omitted required sections, prohibited material, corrupt references, malformed files, conflicting authority, unavailable tools, unsupported claims, injected source instructions, known-invalid artifacts, and other relevant mutations. Preserve fixture, expected rejection, actual observed result, validator defect where applicable, and evidence. The application owns controlled suite identity and derived coverage.',
8:'Author this job’s production instruction only from the resolved current requirement set and verification architecture. Define objective, authorized inputs, authority rules, failure handling, scope, prohibitions, defined terms, ordered procedure, branches, tool requirements, output contract, TRUE/FALSE/UNKNOWN handling, rejection/blocking rules, completion conditions, and requirement traceability. Do not copy or imitate an existing target implementation as authority. Do not turn this job’s production instruction into a reusable instruction for unrelated jobs unless the current user input explicitly requires such a deliverable. The application assigns the controlled instruction version after accepted ingestion.',
9:'Preflight this job’s production instruction in an independent context where required. Review each material clause for multiple interpretations, undefined objects, unsupplied dependencies, internal conflicts, unavailable capabilities, objective verifiability, responsible operation, ordering, defined failure behavior, and traceability. Preserve findings and evidence. If correction is required, identify the exact correction; the application controls versioning and repeated-review state. Do not execute target production during preflight.',
10:'Review the exact candidate freeze for this job and iteration. The human selects authorized canonical components and the application assigns CANDIDATE_ID and ITERATION_ID, freezes the exact component manifest, and calculates hashes from verified bytes. Preserve substantive observations about role distribution, immutable locations, tool configuration, settings, permissions, and limitations. The agent must not invent or assign candidate identity, versions, hashes, or lifecycle state. The same candidate package must be used unchanged across the ten-run batch.',
11:'Run exactly ten independent executions for this job using the identical frozen candidate in ten fresh contexts. For each application-reserved RUN_ID, report the actual execution observations, contamination state, tool configuration, complete output, tool failures, and evidence. The application owns run/context IDs, timestamps, lifecycle state, and hashes calculated from actual bytes. Runs may not see another run’s output, reviewer comments, prior failure explanations, or proposed corrections. Never select a preferred run to discard the others.',
12:'Verify each of this job’s ten executions independently. Create exactly one current applicable verification record for every required REQ_ID × RUN_ID × TEST_ID triple. Preserve verifier and verifier-context identity, independence status, inputs, procedure, expected result, observed result, exact evidence, substantive determination, defect reference where applicable, and reason for UNDETERMINED. Do not omit, duplicate, substitute wrong-version/wrong-iteration records, or self-validate. The application reconciles matrix counts and completeness mathematically.',
13:'Compare all ten executions for this job requirement-by-requirement. Report every run’s substantive comparison observations, interpretation variance, output variance, authorized versus unauthorized variance evidence, inconclusive tests, repeated and unique failure patterns, correctness-affecting variance, linked defects, and evidence. The application calculates all-ten, any-violation, any-undetermined, and completeness values. Never discard a run because another run appears preferable.',
14:'Root-cause every material defect in this job by tracing backward through product/output, execution, instruction, requirement, research, source, user input, tool, and audit as applicable. Classify the root cause using the controlled categories, identify the earliest defective layer, preserve evidence, and identify required downstream rework. Do not patch only the final symptom when an earlier layer is responsible.',
15:'Convert every confirmed failure in this job into a permanent regression definition. Preserve the failure fixture and identity/hash when available, reproduction procedure, detection method, applicability, permanent test location, and an actual pre-correction execution with evidence that demonstrates the failure. The application assigns REG_ID and lifecycle state. Do not require or claim post-correction success at this stage; correction occurs at Stage 16 and success must be established by a later actual regression execution.',
16:'Revise only the responsible earliest defective layer for this job. Propose the exact responsible-layer correction and preserve triggering defects, RCA, old artifact version, exact modification, required reruns, instruction-change analysis, repeated preflight need, and justified unchanged artifacts. Human authority authorizes genuine decisions; the application assigns CHANGESET_ID, creates new versions, and invalidates downstream work. Never overwrite a controlled version in place.',
17:'After a material upstream correction, execute the declared Stage 17 operation against the new application-assigned iteration and candidate. Use ten new independent contexts for execution, withhold prior outputs, use one identical corrected candidate package across all ten runs, and perform verification, comparison, RCA, regression execution, and any required correction through the declared operation subcontracts. Do not invent iteration, candidate, run, or context identities.',
18:'Review convergence evidence and explain any remaining anomaly, missing evidence, contradiction, ambiguity, defect, or variance. The application calculates mandatory requirement coverage, verification coverage, regression success, defect counts, unresolved unknowns, contradiction/ambiguity counts, unexplained variance, and the final convergence determination from current canonical records. Do not set or override those application-derived values.',
19:'After convergence, perform the declared unchanged-confirmation operations using the exact converged component versions and hashes with zero material changes. Use ten new independent contexts, rerun the complete verification matrix and applicable regression suite, compare all runs, and report any new defect, missed requirement, missed failure case, or correctness-affecting variance. The application owns iteration/run/context identities and evaluates unchanged-confirmation completion.',
20:'Inspect the proposed production baseline only after successful unchanged confirmation. The human authorizes the baseline and the application assigns BASELINE_ID, freezes exact approved versions and artifact bytes, calculates hashes, and records immutable baseline identity. Report substantive discrepancies or blockers only; do not assign baseline identity, hashes, authorization, or lifecycle state.',
21:'Produce the job’s finished deliverable only when the actual authorized execution environment can do so reliably from the approved baseline. The application itself does not connect to or modify an external repository. If implementation depends on repository, runtime, account, network, deployment, or other execution access absent from the authorized environment, do not claim implementation or fabricate product bytes; provide the complete implementation-ready specification or patch plan when that satisfies the feasible deliverable, or return the appropriate BLOCKED or EXECUTION_FAILED disposition. For a self-contained deliverable that can actually be generated here, use a fresh production context and only approved baseline materials. The application assigns PRODUCT_ID and execution identity and is authoritative for actual file bytes, filenames, media types, sizes, hashes, storage references, and lineage after bytes are persisted and verified.',
22:'Perform the substantive deterministic verification work that is actually supported against the finished product and report procedures, expected results, actual observed results, evidence, and defects. Objective artifact identities, byte sizes, cryptographic hashes, expected test-set completeness, counts, and final gate calculations are application-owned. Never claim an unexecuted deterministic check ran.',
23:'Perform independent meaning/content verification on this job’s actual finished product where deterministic checks cannot establish substantive satisfaction. For each applicable requirement preserve requirement identity, product location, external-source evidence where applicable, required meaning, observed meaning, evidence-based comparison, SATISFIED/VIOLATED/UNDETERMINED, defect, and reason a determination could not be made. Use human-facing terminology such as Meaning Verification or Content Verification.',
24:'Perform adversarial verification on this job’s finished product. Test applicable missing material, prohibited material, contradictions, impossible logic, unsupported facts, external-source misrepresentation, wrong versions, broken references, hidden assumptions, partial completion, nonsensical meaning, terminology inconsistency, unhandled exceptions, stale facts, malformed files, hidden content, export corruption, superficial keyword compliance, and historical regressions. Preserve attack, method, expected behavior, actual result, defect, severity, and evidence. Do not claim attacks that were not actually executed.',
25:'Inspect the exact final delivered representation and package. Report substantive rendering/opening observations, clipping, missing or blank content, broken layout, graphics, font substitution, overlap, hidden content, ordering, export corruption, package problems, defects, and irreducible human/reviewer judgments. The application derives filenames, canonical artifact inventory, byte sizes, SHA-256 values, and other objective file facts from actual stored bytes; do not overwrite those facts.',
26:'Reconcile this job’s process evidence and product evidence as two separate propositions. Report substantive discrepancies, unauthorized modification evidence, chain-of-custody issues, defects, blockers, and review findings. The application calculates canonical counts, identities, completeness, and gate state. Neither process correctness nor product correctness proves the other.',
27:'Review the current release evidence for substantive gaps, contradictions, unsupported findings, unresolved defects, blockers, or evidence problems. Do not set a release state. The application evaluates the complete current evidence and creates exactly one idempotent ACCEPTED, REJECTED, or BLOCKED release determination. Human or agent preference cannot override that deterministic result, and ACCEPTED does not itself authorize delivery.',
28:'After Stage 27 is ACCEPTED, use agent investigation only when necessary to explain a discrepancy. The application performs the authoritative immediate pre-release byte comparison, joining audited and delivery artifacts by canonical identity and authorized filename and comparing actual byte size and SHA-256 independent of selection order. Do not assert identity from metadata or array position.',
29:'Investigate any missing traceability link the application identifies. The application constructs the complete evidence graph for every mandatory requirement from canonical IDs and current records: EXTERNAL SOURCE / USER AUTHORITY AS APPLICABLE -> REQUIREMENT -> INSTRUCTION TRACE -> EXECUTION OR PRODUCT ELEMENT -> EVERY APPLICABLE TEST -> EVERY REQUIRED TEST RESULT -> CANONICAL EVIDENCE -> CURRENT RELEASE DECISION -> EVERY APPLICABLE RELEASED ARTIFACT IDENTITY. Do not fabricate a link or substitute a raw response ID for canonical evidence.',
30:'Provide substantive defect/regression findings or correction evidence when needed. The application maintains append-only defect and regression history, stable canonical IDs, supersession relationships, and lifecycle state. Do not rewrite history. Every confirmed defect must retain a permanent regression definition, and later applicable regression executions must succeed before baseline approval.'
};
const recordId=(record,collection)=>String(record?.id||record?.recordId||record?.[schema.RECORD_SCHEMAS[collection]?.idField]||record?.fields?.[schema.RECORD_SCHEMAS[collection]?.idField]||'UNKNOWN');
function selectedContextRecords(state,collection,scope={}){
 const list=Array.isArray(state?.projectData?.[collection])?state.projectData[collection]:[],active=list.filter(x=>x?.active!==false&&!x?.invalidatedBy);
 const keys=['inputVersion','sourceSetVersion','requirementsVersion','testSuiteVersion','instructionVersion','iterationId','candidateId','runId','contextId','baselineId','productId'];
 return active.filter(record=>{const rs=record?.scope||{};for(const key of keys){const expected=scope?.[key];if(expected===undefined||expected===null||expected==='')continue;const actual=rs?.[key];if(actual!==undefined&&actual!==null&&actual!==''&&String(actual)!==String(expected))return false;}if(collection==='runs'&&scope?.runId&&recordId(record,'runs')!==String(scope.runId))return false;if(collection==='freshContexts'&&scope?.contextId&&recordId(record,'freshContexts')!==String(scope.contextId))return false;return true;});
}
function boundedCollection(state,collection,scope={}){
 const selected=selectedContextRecords(state,collection,scope);if(!selected.length)return 'NONE';
 return show({totalSelected:selected.length,records:selected.map(record=>({id:recordId(record,collection),stage:record.stage??'UNKNOWN',scope:record.scope||{},fields:record.fields||record,relationships:record.relationships||{},contentSha256:record.contentSha256||record.sha256||'UNKNOWN'})),omitted:0,selectionRule:'Only active records matching the explicit operation read contract and controlling prompt scope are selected; large artifact bytes are referenced by canonical artifact identity.'});
}
const samePromptScope=(a,b={})=>['iterationId','candidateId','runId','contextId','baselineId','productId'].every(key=>String(a?.[key]??'')===String(b?.[key]??''));
function contextFor(stage,state,operation,scope={}){
 const parts=[];
 if(stage>1){const prior=state?.stages?.[stage-1]?{agentData:state.stages[stage-1].agentData||state.stages[stage-1].acceptedData||{},humanData:state.stages[stage-1].humanData||{},derivedData:state.stages[stage-1].derivedData||{}}:'NONE';parts.push(`PRIOR STAGE DECISION AND ACCEPTED DATA\n${show(prior)}`);}
 const open=(state?.projectData?.blockers||[]).filter(x=>!x.invalidatedBy&&!['CLOSED','RESOLVED','RETIRED'].includes(String(x?.fields?.STATUS||x?.STATUS||x?.status||'OPEN').toUpperCase()));if(open.length)parts.push(`APPLICABLE OPEN BLOCKERS\n${show(open)}`);
 const questions=(state?.projectData?.humanInputRequests||[]).filter(x=>Number(x.stage)===stage&&String(x.status||'OPEN').toUpperCase()==='OPEN'&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope)));if(questions.length)parts.push(`UNRESOLVED HUMAN INPUT REQUESTS\n${show(questions)}`);
 const answered=(state?.projectData?.humanInputAnswers||[]).filter(x=>Number(x.stage)===stage&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({questionId:x.requestId,question:x.question,answer:x.answer,answerType:x.answerType||'UNKNOWN',inputVersion:x.inputVersion||state?.job?.CURRENT_INPUT_VERSION||'UNKNOWN',operatorLabel:x.operatorLabel||x.operator||'UNSPECIFIED',affectedStageFields:x.affectedStageFields||[],affectedRecords:x.affectedRecords||[]}));if(answered.length)parts.push(`ANSWERED HUMAN CLARIFICATIONS\n${show(answered)}`);
 const corrections=(state?.projectData?.rejectedResponses||[]).filter(x=>Number(x.stage)===stage&&x.requestCorrection&&!x.invalidatedBy&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({rejectedResponseId:x.rejectedResponseId,reason:x.reason,rawResponseId:x.rawResponseId}));if(corrections.length)parts.push(`OPERATOR REQUESTED CORRECTIONS / REFINEMENTS\n${show(corrections)}`);const acceptedRefinements=(state?.projectData?.history||[]).filter(x=>x.type==='ACCEPTED_RESPONSE_INVALIDATED'&&Number(x.stage)===stage&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({eventId:x.eventId,reason:x.reason,rawResponseId:x.rawResponseId,promptId:x.promptId}));if(acceptedRefinements.length)parts.push(`ACCEPTED RESULT REFINEMENT REQUESTS\n${show(acceptedRefinements)}`);
 const failed=(state?.projectData?.responseValidations||[]).filter(x=>Number(x.stage)===stage&&!x.valid).filter(x=>{const p=(state?.projectData?.generatedPrompts||[]).find(g=>(g.instructionId||g.promptId)===x.promptId);return p&&p.operation===operation&&samePromptScope(p.scope||{},scope);}).at(-1);if(failed)parts.push(`LATEST APPLICATION VALIDATION FAILURE TO CORRECT\n${show({validationId:failed.validationId,issues:(failed.issues||[]).map(i=>({code:i.code,path:i.path,message:i.message}))})}`);
 const op=schema.operationContract(stage,operation||schema.STAGE_CONTRACTS[stage].operations[0]);for(const collection of op?.readCollections||schema.STAGE_CONTRACTS[stage].readCollections||[])parts.push(`${collection.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ').toUpperCase()}\n${boundedCollection(state,collection,scope)}`);
 return parts.join('\n\n')||'No additional stage-specific canonical records are established.';
}
function scopeFor(stage,state,overrides={}){const j=state?.job||{};const value={projectRevision:Number(state?.revision||0),inputVersion:j.CURRENT_INPUT_VERSION||null,sourceSetVersion:j.CURRENT_SOURCE_SET_VERSION||null,requirementsVersion:j.CURRENT_REQUIREMENTS_VERSION||null,testSuiteVersion:j.CURRENT_TEST_SUITE_VERSION||null,instructionVersion:j.CURRENT_INSTRUCTION_VERSION||null,iterationId:j.CURRENT_ITERATION||null,candidateId:state?.projectData?.candidateFreezes?.filter(x=>x?.active!==false&&!x?.invalidatedBy).at(-1)?.id||null,runId:overrides.runId||null,contextId:overrides.contextId||null,baselineId:j.CURRENT_BASELINE_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_BASELINE_ID))?j.CURRENT_BASELINE_ID:null,productId:j.CURRENT_PRODUCT_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_PRODUCT_ID))?j.CURRENT_PRODUCT_ID:null};return value;}
function responseContractDescriptor(stage,operation){const contract=schema.STAGE_CONTRACTS[stage],op=schema.operationContract(stage,operation);return {schema:schema.RESPONSE_SCHEMA,stage,operation,responseTypes:schema.RESPONSE_TYPES,scopeRequirements:op?.scopeRequirements||contract.scopeRequirements,agentStageFields:contract.allowedStageData,agentWritableCollections:op?.agentWritableCollections||contract.agentWritableCollections,resourceLimits:contract.resourceLimits};}
function responseContract(stage,operation,instructionId,bodySha256,contractSha256,contextSignature,scope){
 const contract=schema.STAGE_CONTRACTS[stage],op=schema.operationContract(stage,operation);const writable=op?.agentWritableCollections||contract.agentWritableCollections;
 const recordShape=Object.fromEntries(writable.map(collection=>[collection,[{tempKey:'response-local-key',targetId:(schema.RECORD_SCHEMAS[collection]?.commitPolicy==='UPDATE_RESERVED'?(scope.runId||scope.productId||'<application-reserved-target-id>'):null),fields:Object.fromEntries(schema.recordAgentFields(collection).map(name=>[name,'<value>'])),relationships:{},evidenceRefs:['evidence-1']}]]));
 return JSON.stringify({schema:schema.RESPONSE_SCHEMA,jobId:'<exact current JOB_ID>',stage,operation,promptIdentity:{instructionId,bodySha256,contractSha256,contextSignature},scope,responseType:'DATA_PROPOSAL',humanInputRequests:[],stageData:Object.fromEntries(contract.allowedStageData.map(name=>[name,'<value>'])),records:recordShape,evidence:[{temporaryKey:'evidence-1',kind:'WORKFLOW_EVIDENCE',description:'Exact evidence supporting proposed values',location:'<source/output location>',content:'<exact evidence or faithful excerpt>'}],unresolved:[],warnings:[],attachments:[]},null,2);
}
function body(stage,state,operation,scope){
 const d=core.STAGES[stage-1],j=state?.job||{};
 const contract=schema.STAGE_CONTRACTS[stage],op=schema.operationContract(stage,operation||contract.operations[0]);
 const fields=contract.allowedStageData.length?contract.allowedStageData.map(x=>`- ${x}`).join('\n'):'- No agent-owned stageData fields; use permitted records/evidence only.';
 const writable=op?.agentWritableCollections||contract.agentWritableCollections;
 const collections=writable.length?writable.map(c=>`- ${c}: ${schema.recordAgentFields(c).join(', ')||'no agent-owned fields'}`).join('\n'):'- NONE';
 return `COPY BLOCK — STAGE ${String(stage).padStart(2,'0')} — ${d.title}

ROLE
You are the ${d.role}. Perform only Stage ${String(stage).padStart(2,'0')} for this single current project.

PROJECT-SCOPE BOUNDARY
This instruction belongs only to JOB_ID ${j.JOB_ID||'UNKNOWN'}. For a creation job, do not treat the requested new target as already existing before Stage 21. For an explicit audit, repair, migration, or modification of an existing target, supplied existing-target artifacts may be inspected as implementation evidence, but they are not independent external authority merely because they exist. The operating application, its repository, source code, UI, stored state, screenshots, prior target versions, generated project artifacts, and other implementations of the same target are never Stage 02 external authority or Stage 03 requirement authority unless an independent governing source is separately established.

JOB CONTROL
JOB_ID: ${j.JOB_ID||'UNKNOWN'}
JOB_TITLE: ${j.JOB_TITLE||'UNKNOWN'}
CURRENT_ITERATION: ${j.CURRENT_ITERATION||'NOT APPLICABLE'}
CURRENT_STAGE: STAGE ${String(stage).padStart(2,'0')}
CURRENT_STATE: ${j.CURRENT_STATE||'UNKNOWN'}
NEXT_REQUIRED_ACTION: ${j.NEXT_REQUIRED_ACTION||'UNKNOWN'}
INPUT_VERSION: ${j.CURRENT_INPUT_VERSION||'UNKNOWN'}
SOURCE_SET_VERSION: ${j.CURRENT_SOURCE_SET_VERSION||'NOT APPLICABLE'}
REQUIREMENTS_VERSION: ${j.CURRENT_REQUIREMENTS_VERSION||'NOT APPLICABLE'}
TEST_SUITE_VERSION: ${j.CURRENT_TEST_SUITE_VERSION||'NOT APPLICABLE'}
INSTRUCTION_VERSION: ${j.CURRENT_INSTRUCTION_VERSION||'NOT APPLICABLE'}
BASELINE_ID: ${j.CURRENT_BASELINE_ID||'NOT APPLICABLE'}
PRODUCT_ID: ${j.CURRENT_PRODUCT_ID||'NOT APPLICABLE'}

AUTHORIZED USER JOB INPUT
VERBATIM REQUEST / OBJECTIVE:
${show(j.EXACT_USER_OBJECTIVE_VERBATIM)}

REQUESTED DELIVERABLE:
${show(j.EXACT_DELIVERABLE_REQUESTED)}

SUPPLIED MATERIALS:
${show(j.SUPPLIED_MATERIALS_INVENTORY)}

USER-SUPPLIED KNOWN AUTHORITY (classification preserved; do not automatically relabel as external authority):
${show(j.KNOWN_AUTHORITATIVE_SOURCES)}

AVAILABLE TOOLS:
${show(j.AVAILABLE_TOOLS)}

PROHIBITED ACTIONS:
${show(j.PROHIBITED_ACTIONS)}

EXPLICIT USER REQUIREMENTS:
${show(j.EXPLICIT_USER_REQUIREMENTS)}

${stage===2?`STAGE 02 SOURCE DISCOVERY GUIDANCE
DESIRED OR SUGGESTED SOURCE COUNT: ${show(j.DESIRED_SOURCE_COUNT)}
Treat this count as guidance, not a quota. When web access is available, search broadly enough to discover the relevant source landscape, then inspect and prefer original authoritative publications rather than summaries or search snippets. Prefer the most authoritative and reputable sources appropriate to the domain, prioritizing primary, official, controlling sources where they exist. Verify identity, currency, applicability, and authority before proposing a source. If no legitimate independent external source of any justified authority or evidentiary role applies, return SOURCE_APPLICABILITY_DETERMINATION = NO_APPLICABLE_EXTERNAL_SOURCE with evidence; never invent a source merely to satisfy a count.
`:''}
AUTHORIZED BOUNDED CONTEXT FOR THIS STAGE
${contextFor(stage,state,operation,scope)}

STAGE-SPECIFIC TASK
${procedures[stage]}

PERMITTED AGENT-OWNED STAGE DATA
${fields}

PERMITTED RECORD COLLECTIONS AND AGENT-OWNED FIELDS
${collections}

COMPLETION CONDITIONS
${(d.completionGate||[]).map(x=>`- ${x}`).join('\n')}

MANDATORY RESPONSE RULES
- Return exactly one JSON object and no Markdown fence, preamble, or trailing prose.
- Use schema ${schema.RESPONSE_SCHEMA} and echo the exact operation, scope, instructionId, bodySha256, contractSha256, and contextSignature supplied below.
- Use only DATA_PROPOSAL, HUMAN_INPUT_REQUIRED, BLOCKED, or EXECUTION_FAILED as responseType.
- Never assign canonical application IDs, versions, timestamps, counts, hashes, statuses, coverage values, release determinations, current stage/state, or other application-owned values. Use temporaryKey and response-local references where relationships are needed.
- Never set a HUMAN or HUMAN_DECISION-owned field. When unavailable human information is required, return HUMAN_INPUT_REQUIRED and structured humanInputRequests. Do not convert a missing human decision into an assumption.
- Include evidence for every agent-produced canonical value that requires provenance.
- Do not include collections or fields outside the current stage contract.
- Preserve TRUE/FALSE/UNKNOWN/NONE/NOT APPLICABLE and SATISFIED/VIOLATED/UNDETERMINED meanings exactly.
- Stage 02 may contain only genuinely independent external sources appropriate to the job: governing/controlling authority where it exists, otherwise reputable direct evidence. Target-product and repository artifacts are implementation evidence, not independent external authority.
- Stage 03 may research only the accepted Stage 02 independent external source set.
- If required authority, evidence, capability, or decision rule is unavailable, return BLOCKED or HUMAN_INPUT_REQUIRED as applicable rather than inventing data.
- If execution itself is unavailable, return EXECUTION_FAILED; do not represent unexecuted work as completed.
- A rejected response or rejected data is not canonical and must not be reused as accepted project truth.
- Before substantive work at this stage, decide whether the current human input, canonical application context, prior accepted outputs, evidence, and available capabilities are sufficient to proceed reliably for this specific job and stage. Do not use a generic hard-coded sufficiency threshold.
- Missing human-authority information requires HUMAN_INPUT_REQUIRED. Missing, stale, or incomplete canonical application context requires BLOCKED with MISSING_APPLICATION_CONTEXT. An unavailable external capability requires BLOCKED with MISSING_CAPABILITY, or EXECUTION_FAILED if an attempted execution failed. At Stage 01, when direct implementation is unavailable or materially too large but a complete reliable self-contained substitute such as an implementation-ready specification is feasible, propose that substitute as EXACT_DELIVERABLE_REQUESTED for human confirmation instead of blocking the entire job. After Stage 01, WORK_TOO_LARGE_FOR_ENVIRONMENT is blocking only when the currently approved deliverable itself cannot be completed reliably in the authorized environment. Never claim unperformed implementation. Self-contained deliverables that can actually be produced in the available environment should still be produced.
- If the result is incomplete or needs refinement, identify the exact missing, incorrect, or insufficient work so the next controlling prompt can correct it without restarting the project.
- This static application does not itself read from or write to an external project repository. Treat repository implementation as unavailable unless the external agent execution context actually provides that capability and the current stage authorizes its use.
- When the environment cannot perform a requested implementation or execution, provide an implementation-ready specification rather than pretending implementation occurred.

RESPONSE ENVELOPE
The application will provide the controlling prompt identity immediately after this hashed instruction body. Echo that identity exactly in promptIdentity.

END HASHED INSTRUCTION BODY`;
}
function buildPromptRecord(stageOrDefinition,state,options={}){
 const stage=Number(stageOrDefinition?.number||stageOrDefinition);if(!Number.isInteger(stage)||stage<1||stage>schema.STAGE_COUNT)throw new Error(`Stage must be 1 through ${schema.STAGE_COUNT}.`);
 const d=core.STAGES[stage-1],existing=(state?.projectData?.generatedPrompts||[]).filter(x=>Number(x.stage)===stage),activeExisting=existing.filter(x=>!x.invalidatedBy);const operation=options.operation||schema.STAGE_CONTRACTS[stage].operations[0];if(!schema.STAGE_CONTRACTS[stage].operations.includes(operation))throw new Error(`Operation ${operation} is not valid for Stage ${stage}.`);
 const opContract=schema.operationContract(stage,operation);const scope=scopeFor(stage,state,options.scope||{}),contextManifest={stage,operation,scope,readCollections:Object.fromEntries((opContract?.readCollections||schema.STAGE_CONTRACTS[stage].readCollections||[]).map(collection=>[collection,selectedContextRecords(state,collection,scope).map(record=>({id:recordId(record,collection),scope:record.scope||{},contentSha256:record.contentSha256||record.sha256||hash.sha256Value(record.fields||record)}))])),answeredHumanClarifications:(state?.projectData?.humanInputAnswers||[]).filter(x=>Number(x.stage)===stage&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({requestId:x.requestId,answerId:x.answerId,inputVersion:x.inputVersion||state?.job?.CURRENT_INPUT_VERSION||null})),operatorCorrectionRequests:(state?.projectData?.rejectedResponses||[]).filter(x=>Number(x.stage)===stage&&x.requestCorrection&&!x.invalidatedBy&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({rejectedResponseId:x.rejectedResponseId,reason:x.reason,rawResponseId:x.rawResponseId})),acceptedResultRefinements:(state?.projectData?.history||[]).filter(x=>x.type==='ACCEPTED_RESPONSE_INVALIDATED'&&Number(x.stage)===stage&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({eventId:x.eventId,reason:x.reason,rawResponseId:x.rawResponseId,promptId:x.promptId})),latestValidationFailure:(state?.projectData?.responseValidations||[]).filter(x=>Number(x.stage)===stage&&!x.valid).filter(x=>{const p=(state?.projectData?.generatedPrompts||[]).find(g=>(g.instructionId||g.promptId)===x.promptId);return p&&p.operation===operation&&samePromptScope(p.scope||{},scope);}).slice(-1).map(x=>({validationId:x.validationId,issues:(x.issues||[]).map(i=>({code:i.code,path:i.path,message:i.message}))}))};
 const contextSignature=hash.sha256Value(contextManifest),bodyText=body(stage,state,operation,scope),bodySha256=hash.sha256Text(bodyText),descriptor=responseContractDescriptor(stage,operation),contractSha256=hash.sha256Value(descriptor);
 const same=activeExisting.find(x=>x.contextSignature===contextSignature&&x.bodySha256===bodySha256&&x.contractSha256===contractSha256&&x.operation===operation);
 const instructionId=same?.instructionId||same?.promptId||`INSTRUCTION-${String(state?.job?.JOB_ID||'UNKNOWN').replace(/[^A-Za-z0-9-]/g,'')}-S${String(stage).padStart(2,'0')}-${String(existing.length+1).padStart(3,'0')}`;
 const identityBlock=`\n\nPROMPT IDENTITY — ECHO EXACTLY\nINSTRUCTION_ID: ${instructionId}\nBODY_SHA256: ${bodySha256}\nCONTRACT_SHA256: ${contractSha256}\nCONTEXT_SIGNATURE: ${contextSignature}\nOPERATION: ${operation}\nPROJECT_REVISION: ${scope.projectRevision}\n\nSTRICT RESPONSE CONTRACT\n${responseContract(stage,operation,instructionId,bodySha256,contractSha256,contextSignature,scope)}\n\nEND COPY BLOCK — STAGE ${String(stage).padStart(2,'0')}`;
 const prompt=bodyText+identityBlock;return {instructionId,promptId:instructionId,stage,operation,role:d.role,bodySha256,sha256:bodySha256,contractSha256,contextSignature,contextManifest,scope,scopeSha256:hash.sha256Value(scope),prompt,fullTextSha256:hash.sha256Text(prompt)};
}
function build(stageOrDefinition,state,options){return buildPromptRecord(stageOrDefinition,state,options).prompt;}
core.buildStagePrompt=build;
globalThis.closedLoopPromptEngine=Object.freeze({version:'closed-loop-prompt-engine/5',build,buildPromptRecord,procedures,contextFor,scopeFor,responseContractDescriptor,responseContract});
})();