(()=>{
'use strict';
const core=globalThis.closedLoopCore;
const schema=globalThis.closedLoopWorkflowSchema;
const hash=globalThis.closedLoopHash;
if(!core||!schema||!hash)throw new Error('workbook.js, hash.js, and workflow-schema.js must load before prompt-engine.js.');
const show=v=>{if(v===undefined||v===null||v==='')return 'UNKNOWN';if(Array.isArray(v)&&!v.length)return 'NONE';if(typeof v==='object')return JSON.stringify(v,null,2);return String(v)};
const procedures={
1:'Initialize only this current job from the exact current User Job Input. Preserve the verbatim objective, requested deliverable, supplied-material inventory and provenance, required format, temporal/geographic scope, user-supplied authority, available tools, prohibitions, explicit requirements, assumptions, and unresolved unknowns. Use the application-assigned JOB_ID and controlled input identity; never assign or alter them. Before normalizing the job, determine whether the requested deliverable can actually be produced in the available external agent environment. This static application itself has no external repository, account, deployment, or arbitrary execution access. If required implementation access is unavailable or the work is too large for reliable direct completion, define the most complete implementation-ready specification, architecture, patch plan, acceptance criteria, or other feasible deliverable instead of pretending implementation occurred. Self-contained deliverables that can actually be produced should still be produced. Do not begin Stage 02 research or downstream production work.',
2:'Build the independent external source inventory for this current job only. Treat DESIRED OR SUGGESTED SOURCE COUNT as optional search-breadth guidance, never a quota and never authority to invent or pad sources. Search broadly enough to discover the relevant source landscape, then prefer the most authoritative, reputable, direct, and current source appropriate to each proposition; prioritize primary, official, controlling authority where it exists and use high-quality secondary sources for corroboration or context when appropriate. Verify identity, issuer/publisher, currency, supersession, applicability, and actual inspected content before relying on a source. Return fewer sources rather than weak or irrelevant ones; continue beyond the target when governing coverage requires it. User Job Input and supplied materials remain authorized project inputs but are not automatically independent external sources. Existing target/repository artifacts may be implementation evidence for an explicit audit or repair job, but they are not independent governing authority merely because they exist. The application assigns SOURCE_ID and source-set version after validated ingestion. If no legitimate external source applies, return the evidence-supported no-applicable-source determination rather than inventing one.',
3:'Research only the current accepted Stage 02 independent external source set, source-by-source and pass-by-pass. Inspect exact relevant portions and separately capture facts, mandatory obligations, recommendations, optional practices, examples, prohibitions, exceptions, dependencies, applicability conditions, restrictions, invalidating material, conflicts, superseded guidance, source evidence, candidate requirements, and unresolved questions. Do not use the target product, this operating application, repository implementation, previous generated artifacts, or prior agent conclusions as independent requirement authority. Repeat discovery passes until saturation is supported by evidence, not merely asserted.',
4:'Compile atomic requirement proposals from authorized User Job Input and legitimately applicable Stage 03 research. Each proposed requirement should express one independently testable obligation where practical and preserve mandatory/optional status, source or user-input provenance, exact source location when applicable, authority, applicability, dependencies, prohibitions, defined terms, observable satisfaction condition, intended verification method, expected evidence, failure condition, severity, and notes. The application assigns REQ_ID and controlled requirement-set identity. Do not infer requirements from implementation behavior merely because it exists.',
5:'Resolve defects in the current requirement set before production instructions are written. Detect duplicates, conflicts, impossible combinations, undefined terms, circular dependencies, missing prerequisites, unsupported requirements, uncertain applicability, and missing verification paths. Preserve the substantive defect, governing evidence, proposed resolution or unresolved state, affected requirements, and blockers. Human authority decides genuine user tradeoffs; the application controls canonical versions and downstream invalidation. Never silently guess away a conflict or manufacture authority.',
6:'Build verification-test proposals before any production instruction is authored. Every active mandatory requirement must have at least one applicable ready test. Use the strongest suitable method: exact computation, programmatic/schema/structure checks, source comparison, rule-based verification, or independent human meaning/content review when deterministic testing cannot establish satisfaction. Define inputs, tools, procedure, expected result, failure condition, and evidence to preserve. The application assigns TEST_ID and calculates mandatory requirement-to-test coverage; do not set IDs, counts, or coverage values.',
7:'Build substantive failure/mutation-test proposals that demonstrate validators reject realistic invalid states. Include applicable missing inputs, invalid values, wrong versions, duplicate identifiers, contradictions, omitted required sections, prohibited material, corrupt references, malformed files, conflicting authority, unavailable tools, unsupported claims, injected source instructions, known-invalid artifacts, and other relevant mutations. Preserve fixture, expected rejection, actual observed result, validator defect where applicable, and evidence. The application controls canonical IDs, suite identity, lifecycle state, and derived coverage.',
8:'Author the production instruction from the resolved current requirements and verification architecture. Define objective, authorized inputs, authority rules, failure handling, scope, prohibitions, defined terms, ordered procedure, branches, tool requirements, output contract, TRUE/FALSE/UNKNOWN handling, rejection/blocking rules, completion conditions, and exact requirement traceability. Do not copy an existing implementation as authority. Make the instruction model-agnostic and explicit enough for capable OpenAI, Anthropic, or other instruction-following agents without relying on vendor-specific hidden behavior. The application controls canonical instruction identity/version after accepted ingestion.',
9:'Preflight the current production instruction independently without executing target production. Review every material clause for ambiguity, undefined objects, unsupplied dependencies, internal conflicts, unavailable capabilities, objective verifiability, responsible operation, ordering, failure behavior, output-contract completeness, and traceability. Preserve findings and evidence. If correction is needed, identify the exact defect and proposed correction; the application controls versioning and repeated-review state.',
10:'Review the exact candidate selected by human authority for this iteration. The application assigns CANDIDATE_ID and ITERATION_ID, freezes the selected component identities and actual bytes, calculates hashes, and prevents mutation in place. Report only permitted substantive observations about component completeness, role distribution, tool configuration, settings, permissions, limitations, or discrepancies. The same application-frozen candidate must be used unchanged across the ten-run batch.',
11:'Execute the application-reserved run in the exact fresh context and frozen candidate identified by scope. Report only actual execution observations, contamination facts, tool configuration, complete substantive output, tool failures, limitations, and evidence. The application owns RUN_ID, CONTEXT_ID, candidate identity, timestamps, lifecycle state, receipt identity, canonical artifact identity, byte size, and hashes. Do not see or use another run’s output, reviewer comments, prior failure explanations, or proposed corrections.',
12:'Independently verify the current iteration by producing exactly one applicable verification proposal for every required current REQ_ID × RUN_ID × TEST_ID triple authorized by the operation. Preserve verifier/context independence, inputs, procedure, expected result, observed result, exact evidence, substantive SATISFIED/VIOLATED/UNDETERMINED determination, defect relationship where applicable, and reason for UNDETERMINED. Do not omit or duplicate triples, substitute stale tests/runs, or self-validate. The application calculates expected triples, uniqueness, counts, and matrix completeness.',
13:'Compare all ten current executions requirement-by-requirement. Report substantive per-run observations, interpretation/output variance, whether variance appears authorized, inconclusive tests, repeated and unique failure patterns, correctness-affecting variance, linked defects, and evidence. The application calculates all-ten satisfaction, any-violation, any-undetermined, counts, and completeness. Never discard a run because another appears preferable.',
14:'Root-cause every current material defect by tracing backward through product/output, execution, instruction, requirement, research, source, user input, tool, and audit as applicable. Identify the earliest defective layer, classify the substantive cause using allowed categories, preserve evidence, and identify required downstream rework. An unknown root cause remains unresolved; do not patch only the final symptom when an earlier layer is responsible.',
15:'Convert every confirmed defect into a permanent regression definition and actual pre-correction execution evidence. Preserve failure fixture and byte identity where available, reproduction procedure, detection method, applicability, permanent test location, expected corrected behavior, and evidence proving the current/pre-correction failure. The application assigns REG_ID and lifecycle state. Do not claim post-correction success at Stage 15; correction occurs later and success must come from an actual later regression execution.',
16:'Propose correction only to the earliest responsible defective layer. Preserve triggering defects, RCA, old artifact identity/version, exact proposed modification, required reruns, instruction-change analysis, repeated-preflight need, and justified unchanged artifacts. Human authority authorizes genuine decisions. The application assigns CHANGESET_ID, creates new versions, performs conservative downstream invalidation, and never modifies controlled versions in place.',
17:'Perform only the declared Stage 17 operation for the application-created corrected iteration/candidate. FREEZE is application/human controlled; EXECUTE_RUN uses the exact reserved run/context; VERIFY creates current verification proposals; COMPARE reports cross-run findings; ROOT_CAUSE analyzes current defects; REGRESSION defines or executes regressions as permitted; CORRECT proposes responsible-layer changes. Use ten new independent contexts, one identical corrected frozen candidate, and withhold prior outputs. Never invent iteration, candidate, run, or context identities.',
18:'Review the latest completed corrected iteration for convergence anomalies or missing evidence. The application calculates requirement coverage, exact verification coverage, applicable regression success, critical/major defect counts, mandatory unknowns, contradictions, ambiguities, unexplained correctness-affecting variance, and the final convergence Boolean from that exact iteration. Do not set or override application-derived convergence values.',
19:'Perform only the declared unchanged-confirmation operation using the exact converged Stage 17 candidate identity and hashes with zero material change. Use the application-reserved new contexts/runs, rerun the complete required verification matrix and applicable regressions, compare all runs, and report any new defect, missed requirement, missed failure case, or unexplained correctness-affecting variance. The application owns confirmation iteration/run/context identities and evaluates unchanged confirmation.',
20:'Inspect the proposed production baseline only after successful unchanged confirmation. Human authority authorizes the baseline. The application assigns BASELINE_ID, freezes exact approved versions and artifact bytes, calculates hashes, and records immutable baseline identity/status. Report substantive discrepancies or blockers only; do not assign baseline identity, hashes, authorization, or lifecycle state.',
21:'Produce the approved deliverable in a fresh production context using only approved baseline materials when the actual external agent environment can do so reliably. This static application itself cannot modify an external repository, account, deployment, or system. If the approved deliverable is an implementation-ready specification because direct implementation is unavailable or too large, produce that complete specification rather than pretend code was changed. Self-contained artifacts that can actually be produced should be produced. The application reserves PRODUCT_ID and execution identity and is authoritative for actual persisted artifact bytes, filenames, media types, sizes, SHA-256, storage references, versions, and lineage. Report only permitted substantive execution results, deviations, failures, and artifact claims.',
22:'Perform the substantive deterministic checks actually supported against the current finished product bytes and report test procedure, expected result, actual observed result, evidence, and defect linkage. Never claim a check ran when it did not. The application determines the expected current deterministic-test set and owns product/file identities, hashes, counts, completeness, and gate calculations.',
23:'Perform independent meaning/content verification where deterministic checks cannot establish substantive satisfaction. For every current requirement that needs meaning review, preserve product location, source/user authority evidence as applicable, required meaning, observed meaning, evidence-based comparison, substantive SATISFIED/VIOLATED/UNDETERMINED result, defect link, and reason for UNDETERMINED. The reviewer must be independent from product generation; the application owns counts/completeness and canonical identities.',
24:'Perform actual adversarial verification against the current product. Test applicable missing material, prohibited material, contradictions, impossible logic, unsupported facts, source misrepresentation, wrong versions, broken references, hidden assumptions, partial completion, nonsensical meaning, terminology inconsistency, unhandled exceptions, stale facts, malformed files, hidden content, export corruption, superficial keyword compliance, and active historical regression patterns. Preserve attack, method, expected behavior, actual result, severity, defects, and evidence. Do not claim attacks that were not executed.',
25:'Inspect the exact final representations and package selected by the application. Report substantive rendering/opening observations, clipping, blank/missing content, broken layout, graphics, font substitution, overlap, hidden content, ordering, export corruption, package defects, and irreducible reviewer/human judgments with evidence. The application derives canonical artifact inventory, filenames, byte sizes, SHA-256, objective file facts, and coverage counts from actual stored bytes; do not overwrite those facts.',
26:'Independently review process evidence and product evidence as separate propositions and report substantive discrepancies, unauthorized-modification evidence, chain-of-custody issues, missing evidence, defects, blockers, and review findings. The application calculates canonical counts, identities, completeness, reconciliation state, and gate results. Neither process correctness nor product correctness proves the other.',
27:'Review the complete current release evidence for substantive gaps, contradictions, unsupported findings, unresolved defects, blockers, stale evidence, or other release-relevant problems. Do not set a release state. The application alone evaluates the complete current evidence and creates exactly one idempotent ACCEPTED, REJECTED, or BLOCKED release determination. Human or agent preference cannot override it, and ACCEPTED does not itself authorize delivery.',
28:'After the current Stage 27 result is ACCEPTED, investigate only discrepancies the application cannot explain deterministically. The application performs the authoritative immediate pre-release byte comparison, joining audited canonical artifacts and selected delivery bytes by canonical identity plus authorized filename and comparing actual byte size and SHA-256 independent of file-selection order. Do not assert identity from metadata, names alone, or array position.',
29:'Investigate any traceability gap identified by the application. The application constructs the complete evidence graph for every current mandatory requirement from canonical IDs: external source or human authority as applicable → requirement → instruction trace → execution or product element → every applicable test → every required test result → canonical evidence → current release decision → every applicable released artifact identity. Do not fabricate links or substitute a raw response ID for canonical evidence.',
30:'Provide substantive defect/regression findings or correction evidence when needed. The application maintains append-only defect and regression history, stable canonical IDs, supersession relationships, counts, integrity state, and lifecycle state. Never rewrite history. Every confirmed defect must retain a permanent regression definition, and the latest applicable actual regression execution must succeed before baseline approval.'
};
const recordId=(record,collection)=>String(record?.id||record?.recordId||record?.[schema.RECORD_SCHEMAS[collection]?.idField]||record?.fields?.[schema.RECORD_SCHEMAS[collection]?.idField]||'UNKNOWN');
function selectedContextRecords(state,collection,scope={}){
 const list=Array.isArray(state?.projectData?.[collection])?state.projectData[collection]:[],active=list.filter(x=>x?.active!==false&&!x?.invalidatedBy);
 const keys=['inputVersion','sourceSetVersion','requirementsVersion','testSuiteVersion','instructionVersion','iterationId','candidateId','runId','contextId','baselineId','productId'];
 return active.filter(record=>{const rs=record?.scope||{};for(const key of keys){const expected=scope?.[key];if(expected===undefined||expected===null||expected==='')continue;const actual=rs?.[key];if(actual!==undefined&&actual!==null&&actual!==''&&String(actual)!==String(expected))return false;}if(collection==='runs'&&scope?.runId&&recordId(record,'runs')!==String(scope.runId))return false;if(collection==='freshContexts'&&scope?.contextId&&recordId(record,'freshContexts')!==String(scope.contextId))return false;return true;});
}
function boundedCollection(state,collection,scope={}){
 const selected=selectedContextRecords(state,collection,scope);if(!selected.length)return 'NONE';
 return show({totalSelected:selected.length,records:selected.map(record=>({id:recordId(record,collection),stage:record.stage??'UNKNOWN',scope:record.scope||{},fields:record.fields||record,relationships:record.relationships||{},contentSha256:record.contentSha256||record.sha256||'UNKNOWN'})),omitted:0,selectionRule:'Only active records matching the explicit operation read contract and controlling prompt scope are selected; large artifact bytes are referenced by canonical artifact identity.'});
}
const samePromptScope=(declared,current={})=>['iterationId','candidateId','runId','contextId','baselineId','productId'].every(key=>{const value=declared?.[key];return value===undefined||value===null||value===''||String(value)===String(current?.[key]??'');});
function contextFor(stage,state,operation,scope={}){
 const parts=[];
 if(stage>1){const prior=state?.stages?.[stage-1]?{agentData:state.stages[stage-1].agentData||state.stages[stage-1].acceptedData||{},humanData:state.stages[stage-1].humanData||{},derivedData:state.stages[stage-1].derivedData||{}}:'NONE';parts.push(`PRIOR STAGE DECISION AND ACCEPTED DATA\n${show(prior)}`);}
 const open=(state?.projectData?.blockers||[]).filter(x=>!x.invalidatedBy&&!['CLOSED','RESOLVED','RETIRED'].includes(String(x?.fields?.STATUS||x?.STATUS||x?.status||'OPEN').toUpperCase()));if(open.length)parts.push(`APPLICABLE OPEN BLOCKERS\n${show(open)}`);
 const questions=(state?.projectData?.humanInputRequests||[]).filter(x=>Number(x.stage)===stage&&String(x.status||'OPEN').toUpperCase()==='OPEN'&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope)));if(questions.length)parts.push(`UNRESOLVED HUMAN INPUT REQUESTS\n${show(questions)}`);
 const answered=(state?.projectData?.humanInputAnswers||[]).filter(x=>Number(x.stage)===stage&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({questionId:x.requestId,question:x.question,answer:x.answer,answerType:x.answerType||'UNKNOWN',inputVersion:x.inputVersion||state?.job?.CURRENT_INPUT_VERSION||'UNKNOWN',operatorLabel:x.operatorLabel||x.operator||'UNSPECIFIED',affectedStageFields:x.affectedStageFields||[],affectedRecords:x.affectedRecords||[]}));if(answered.length)parts.push(`ANSWERED HUMAN CLARIFICATIONS\n${show(answered)}`);
 const corrections=(state?.projectData?.rejectedResponses||[]).filter(x=>Number(x.stage)===stage&&x.requestCorrection&&!x.invalidatedBy&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({rejectedResponseId:x.rejectedResponseId,reason:x.reason,rawResponseId:x.rawResponseId}));if(corrections.length)parts.push(`OPERATOR REQUESTED CORRECTIONS / REFINEMENTS\n${show(corrections)}`);
 const failed=(state?.projectData?.responseValidations||[]).filter(x=>Number(x.stage)===stage&&x.valid===false&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).at(-1);if(failed)parts.push(`LATEST APPLICATION VALIDATION FAILURE TO CORRECT\n${show({validationId:failed.validationId,issues:(failed.issues||[]).map(i=>({code:i.code,path:i.path,message:i.message}))})}`);
 const op=schema.operationContract(stage,operation||schema.STAGE_CONTRACTS[stage].operations[0]);for(const collection of op?.readCollections||schema.STAGE_CONTRACTS[stage].readCollections||[])parts.push(`${collection.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ').toUpperCase()}\n${boundedCollection(state,collection,scope)}`);
 return parts.join('\n\n')||'No additional stage-specific canonical records are established.';
}
function scopeFor(stage,state,overrides={}){const j=state?.job||{},has=key=>Object.prototype.hasOwnProperty.call(overrides,key),pick=(key,fallback)=>has(key)?overrides[key]:fallback;return {projectRevision:Number(state?.revision||0),inputVersion:j.CURRENT_INPUT_VERSION||null,sourceSetVersion:j.CURRENT_SOURCE_SET_VERSION||null,requirementsVersion:j.CURRENT_REQUIREMENTS_VERSION||null,testSuiteVersion:j.CURRENT_TEST_SUITE_VERSION||null,instructionVersion:j.CURRENT_INSTRUCTION_VERSION||null,iterationId:pick('iterationId',j.CURRENT_ITERATION||null),candidateId:pick('candidateId',state?.projectData?.candidateFreezes?.filter(x=>x?.active!==false&&!x?.invalidatedBy).at(-1)?.id||null),runId:pick('runId',null),contextId:pick('contextId',null),baselineId:pick('baselineId',j.CURRENT_BASELINE_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_BASELINE_ID))?j.CURRENT_BASELINE_ID:null),productId:pick('productId',j.CURRENT_PRODUCT_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_PRODUCT_ID))?j.CURRENT_PRODUCT_ID:null)};}
function responseContractDescriptor(stage,operation){const contract=schema.STAGE_CONTRACTS[stage],op=schema.operationContract(stage,operation);return {schema:schema.RESPONSE_SCHEMA,stage,operation,responseTypes:schema.RESPONSE_TYPES,scopeRequirements:op?.scopeRequirements||contract.scopeRequirements,agentStageFields:contract.allowedStageData,agentWritableCollections:op?.agentWritableCollections||contract.agentWritableCollections,resourceLimits:contract.resourceLimits};}
function responseContract(stage,operation,instructionId,bodySha256,contractSha256,contextSignature,scope){
 const contract=schema.STAGE_CONTRACTS[stage],op=schema.operationContract(stage,operation);const writable=op?.agentWritableCollections||contract.agentWritableCollections;
 const recordShape=Object.fromEntries(writable.map(collection=>[collection,[{tempKey:'response-local-key',targetId:(schema.RECORD_SCHEMAS[collection]?.commitPolicy==='UPDATE_RESERVED'?(scope.runId||scope.productId||'<application-reserved-target-id>'):null),fields:Object.fromEntries(schema.recordAgentFields(collection).map(name=>[name,'<value>'])),relationships:{},evidenceRefs:['evidence-1']}]]));
 return JSON.stringify({schema:schema.RESPONSE_SCHEMA,jobId:'<exact current JOB_ID>',stage,operation,promptIdentity:{instructionId,bodySha256,contractSha256,contextSignature},scope,responseType:'DATA_PROPOSAL',humanInputRequests:[],stageData:Object.fromEntries(contract.allowedStageData.map(name=>[name,'<value>'])),records:recordShape,evidence:[{temporaryKey:'evidence-1',kind:'WORKFLOW_EVIDENCE',description:'Exact evidence supporting proposed values',location:'<source/output location>',content:'<exact evidence or faithful excerpt>'}],unresolved:[],warnings:[],attachments:[]},null,2);
}
function body(stage,state,operation,scope){
 const d=core.STAGES[stage-1],j=state?.job||{};
 const contract=schema.STAGE_CONTRACTS[stage],op=schema.operationContract(stage,operation||contract.operations[0]);
 const fields=contract.allowedStageData.length?contract.allowedStageData.map(x=>`- ${x}`).join('\n'):'- No agent-owned stageData fields; use permitted records/evidence only.';
 const writable=op?.agentWritableCollections||contract.agentWritableCollections;
 const collections=writable.length?writable.map(c=>`- ${c}: ${schema.recordAgentFields(c).join(', ')||'no agent-owned fields'}`).join('\n'):'- NONE';
 return `COPY BLOCK — STAGE ${String(stage).padStart(2,'0')} — ${d.title}

ROLE
You are the ${d.role}. Perform only Stage ${String(stage).padStart(2,'0')} for this single current project.

PROJECT-SCOPE BOUNDARY
This instruction belongs only to JOB_ID ${j.JOB_ID||'UNKNOWN'}. For a creation job, do not treat the requested new target as already existing before Stage 21. For an explicit audit, repair, migration, or modification job, supplied existing-target artifacts may be inspected as implementation evidence, but they are not independent external authority merely because they exist. The operating application, repository implementation, generated project artifacts, and prior agent conclusions are never Stage 02 independent governing authority or Stage 03 requirement authority without a separately established independent source.

JOB CONTROL
JOB_ID: ${j.JOB_ID||'UNKNOWN'}
JOB_TITLE: ${j.JOB_TITLE||'UNKNOWN'}
CURRENT_ITERATION: ${j.CURRENT_ITERATION||'NOT APPLICABLE'}
CURRENT_STAGE: STAGE ${String(stage).padStart(2,'0')}
CURRENT_STATE: ${j.CURRENT_STATE||'UNKNOWN'}
NEXT_REQUIRED_ACTION: ${j.NEXT_REQUIRED_ACTION||'UNKNOWN'}
INPUT_VERSION: ${j.CURRENT_INPUT_VERSION||'UNKNOWN'}
SOURCE_SET_VERSION: ${j.CURRENT_SOURCE_SET_VERSION||'NOT APPLICABLE'}
REQUIREMENTS_VERSION: ${j.CURRENT_REQUIREMENTS_VERSION||'NOT APPLICABLE'}
TEST_SUITE_VERSION: ${j.CURRENT_TEST_SUITE_VERSION||'NOT APPLICABLE'}
INSTRUCTION_VERSION: ${j.CURRENT_INSTRUCTION_VERSION||'NOT APPLICABLE'}
BASELINE_ID: ${j.CURRENT_BASELINE_ID||'NOT APPLICABLE'}
PRODUCT_ID: ${j.CURRENT_PRODUCT_ID||'NOT APPLICABLE'}

AUTHORIZED USER JOB INPUT
VERBATIM REQUEST / OBJECTIVE:
${show(j.EXACT_USER_OBJECTIVE_VERBATIM)}

REQUESTED DELIVERABLE:
${show(j.EXACT_DELIVERABLE_REQUESTED)}

SUPPLIED MATERIALS:
${show(j.SUPPLIED_MATERIALS_INVENTORY)}

USER-SUPPLIED KNOWN AUTHORITY (classification preserved; do not automatically relabel as external authority):
${show(j.KNOWN_AUTHORITATIVE_SOURCES)}

AVAILABLE TOOLS:
${show(j.AVAILABLE_TOOLS)}

PROHIBITED ACTIONS:
${show(j.PROHIBITED_ACTIONS)}

EXPLICIT USER REQUIREMENTS:
${show(j.EXPLICIT_USER_REQUIREMENTS)}

${stage===2?`STAGE 02 SOURCE DISCOVERY GUIDANCE
DESIRED OR SUGGESTED SOURCE COUNT: ${show(j.DESIRED_SOURCE_COUNT)}
Treat this count as guidance, not a quota. When web access is available, search broadly enough to discover the relevant source landscape, then inspect and prefer original authoritative publications rather than summaries or search snippets. Prefer the most authoritative and reputable sources appropriate to the domain, prioritizing primary, official, controlling sources where they exist. Verify identity, currency, applicability, and authority before proposing a source. If no legitimate external governing source applies, return SOURCE_APPLICABILITY_DETERMINATION = NO_APPLICABLE_EXTERNAL_SOURCE with evidence; never invent a source merely to satisfy a count.
`:''}
AUTHORIZED BOUNDED CONTEXT FOR THIS STAGE
${contextFor(stage,state,operation,scope)}

STAGE-SPECIFIC TASK
${procedures[stage]}

PERMITTED AGENT-OWNED STAGE DATA
${fields}

PERMITTED RECORD COLLECTIONS AND AGENT-OWNED FIELDS
${collections}

COMPLETION CONDITIONS
${(d.completionGate||[]).map(x=>`- ${x}`).join('\n')}

MANDATORY RESPONSE RULES
- Return exactly one JSON object and no Markdown fence, preamble, or trailing prose.
- Use schema ${schema.RESPONSE_SCHEMA} and echo the exact operation, scope, instructionId, bodySha256, contractSha256, and contextSignature supplied below.
- Use only DATA_PROPOSAL, HUMAN_INPUT_REQUIRED, BLOCKED, or EXECUTION_FAILED as responseType.
- Never assign canonical application IDs, versions, timestamps, counts, hashes, statuses, coverage values, release determinations, current stage/state, or other application-owned values. Use temporaryKey and response-local references where relationships are needed.
- Never set a HUMAN or HUMAN_DECISION-owned field. When unavailable human information is required, return HUMAN_INPUT_REQUIRED and structured humanInputRequests. Do not convert a missing human decision into an assumption.
- Include evidence for every agent-produced canonical value that requires provenance.
- Do not include collections or fields outside the current stage and operation contract.
- Preserve TRUE/FALSE/UNKNOWN/NONE/NOT APPLICABLE and SATISFIED/VIOLATED/UNDETERMINED meanings exactly.
- Stage 02 may contain only genuinely independent external sources appropriate to the job; target/repository artifacts are implementation evidence, not independent external authority.
- Stage 03 may research only the current accepted Stage 02 independent external source set.
- If required authority, evidence, capability, or decision rule is unavailable, return BLOCKED or HUMAN_INPUT_REQUIRED as applicable rather than inventing data.
- If execution itself is unavailable, return EXECUTION_FAILED; do not represent unexecuted work as completed.
- A rejected response or rejected data is not canonical and must not be reused as accepted project truth.
- Before substantive work at this stage, decide whether the current human input, canonical application context, prior accepted outputs, evidence, and available capabilities are sufficient to proceed reliably for this specific job and stage. Do not use a generic hard-coded sufficiency threshold.
- Missing human-authority information requires HUMAN_INPUT_REQUIRED. Missing, stale, or incomplete canonical application context requires BLOCKED with MISSING_APPLICATION_CONTEXT. A materially inadequate accepted prior-stage result requires BLOCKED with INADEQUATE_PRIOR_OUTPUT and must identify the earliest result needing refinement. An unavailable external capability requires BLOCKED with MISSING_CAPABILITY, or EXECUTION_FAILED if an attempted execution failed. Work too large for the available environment requires BLOCKED with WORK_TOO_LARGE_FOR_ENVIRONMENT plus a complete implementation-ready specification; do not claim execution occurred. Self-contained deliverables that can actually be produced in the available environment should still be produced.
- If the result is incomplete or needs refinement, identify the exact missing, incorrect, or insufficient work so the next controlling prompt can correct it without restarting the project.
- This static application does not itself read from or write to an external project repository. Treat repository implementation as unavailable unless the external agent execution context actually provides that capability and the current stage authorizes its use.
- When the environment cannot perform a requested implementation or execution, provide an implementation-ready specification rather than pretending implementation occurred.

RESPONSE ENVELOPE
The application will provide the controlling prompt identity immediately after this hashed instruction body. Echo that identity exactly in promptIdentity.

END HASHED INSTRUCTION BODY`;
}
function buildPromptRecord(stageOrDefinition,state,options={}){
 const stage=Number(stageOrDefinition?.number||stageOrDefinition);if(!Number.isInteger(stage)||stage<1||stage>schema.STAGE_COUNT)throw new Error(`Stage must be 1 through ${schema.STAGE_COUNT}.`);
 const d=core.STAGES[stage-1],existing=(state?.projectData?.generatedPrompts||[]).filter(x=>Number(x.stage)===stage),activeExisting=existing.filter(x=>!x.invalidatedBy);const operation=options.operation||schema.STAGE_CONTRACTS[stage].operations[0];if(!schema.STAGE_CONTRACTS[stage].operations.includes(operation))throw new Error(`Operation ${operation} is not valid for Stage ${stage}.`);
 const opContract=schema.operationContract(stage,operation);const scope=scopeFor(stage,state,options.scope||{}),contextManifest={stage,operation,scope,readCollections:Object.fromEntries((opContract?.readCollections||schema.STAGE_CONTRACTS[stage].readCollections||[]).map(collection=>[collection,selectedContextRecords(state,collection,scope).map(record=>({id:recordId(record,collection),scope:record.scope||{},contentSha256:record.contentSha256||record.sha256||hash.sha256Value(record.fields||record)}))])),answeredHumanClarifications:(state?.projectData?.humanInputAnswers||[]).filter(x=>Number(x.stage)===stage&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({requestId:x.requestId,answerId:x.answerId,inputVersion:x.inputVersion||state?.job?.CURRENT_INPUT_VERSION||null})),operatorCorrectionRequests:(state?.projectData?.rejectedResponses||[]).filter(x=>Number(x.stage)===stage&&x.requestCorrection&&!x.invalidatedBy&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).map(x=>({rejectedResponseId:x.rejectedResponseId,reason:x.reason,rawResponseId:x.rawResponseId})),latestValidationFailure:(state?.projectData?.responseValidations||[]).filter(x=>Number(x.stage)===stage&&x.valid===false&&(!x.operation||x.operation===operation)&&(!x.scope||samePromptScope(x.scope,scope))).slice(-1).map(x=>({validationId:x.validationId,rawResponseId:x.rawResponseId,issues:(x.issues||[]).map(i=>({code:i.code,path:i.path,message:i.message}))}))};
 const contextSignature=hash.sha256Value(contextManifest),bodyText=body(stage,state,operation,scope),bodySha256=hash.sha256Text(bodyText),descriptor=responseContractDescriptor(stage,operation),contractSha256=hash.sha256Value(descriptor);
 const same=activeExisting.find(x=>x.contextSignature===contextSignature&&x.bodySha256===bodySha256&&x.contractSha256===contractSha256&&x.operation===operation);
 const instructionId=same?.instructionId||same?.promptId||`INSTRUCTION-${String(state?.job?.JOB_ID||'UNKNOWN').replace(/[^A-Za-z0-9-]/g,'')}-S${String(stage).padStart(2,'0')}-${String(existing.length+1).padStart(3,'0')}`;
 const identityBlock=`\n\nPROMPT IDENTITY — ECHO EXACTLY\nINSTRUCTION_ID: ${instructionId}\nBODY_SHA256: ${bodySha256}\nCONTRACT_SHA256: ${contractSha256}\nCONTEXT_SIGNATURE: ${contextSignature}\nOPERATION: ${operation}\nPROJECT_REVISION: ${scope.projectRevision}\n\nSTRICT RESPONSE CONTRACT\n${responseContract(stage,operation,instructionId,bodySha256,contractSha256,contextSignature,scope)}\n\nEND COPY BLOCK — STAGE ${String(stage).padStart(2,'0')}`;
 const prompt=bodyText+identityBlock;return {instructionId,promptId:instructionId,stage,operation,role:d.role,bodySha256,sha256:bodySha256,contractSha256,contextSignature,contextManifest,scope,scopeSha256:hash.sha256Value(scope),prompt,fullTextSha256:hash.sha256Text(prompt)};
}
function build(stageOrDefinition,state,options){return buildPromptRecord(stageOrDefinition,state,options).prompt;}
core.buildStagePrompt=build;
globalThis.closedLoopPromptEngine=Object.freeze({version:'closed-loop-prompt-engine/4',build,buildPromptRecord,procedures,contextFor,scopeFor,responseContractDescriptor,responseContract});
})();
