from pathlib import Path
p=Path('prompt-engine.js')
s=p.read_text()
old="function scopeFor(stage,state,overrides={}){const j=state?.job||{};const value={projectRevision:Number(state?.revision||0),inputVersion:j.CURRENT_INPUT_VERSION||null,sourceSetVersion:j.CURRENT_SOURCE_SET_VERSION||null,requirementsVersion:j.CURRENT_REQUIREMENTS_VERSION||null,testSuiteVersion:j.CURRENT_TEST_SUITE_VERSION||null,instructionVersion:j.CURRENT_INSTRUCTION_VERSION||null,iterationId:j.CURRENT_ITERATION||null,candidateId:state?.projectData?.candidateFreezes?.filter(x=>x?.active!==false&&!x?.invalidatedBy).at(-1)?.id||null,runId:overrides.runId||null,contextId:overrides.contextId||null,baselineId:j.CURRENT_BASELINE_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_BASELINE_ID))?j.CURRENT_BASELINE_ID:null,productId:j.CURRENT_PRODUCT_ID&&!['NONE','NOT APPLICABLE'].includes(String(j.CURRENT_PRODUCT_ID))?j.CURRENT_PRODUCT_ID:null};return value;}"
new="const scopePlaceholder=value=>['','UNKNOWN','NONE','NOT APPLICABLE','UNASSIGNED','PENDING'].includes(String(value??'').trim().toUpperCase());\nfunction scopeFor(stage,state,overrides={}){const j=state?.job||{},own=(key,fallback)=>Object.prototype.hasOwnProperty.call(overrides,key)?overrides[key]:fallback,iterationId=own('iterationId',j.CURRENT_ITERATION||null),candidate=state?.projectData?.candidateFreezes?.filter(x=>x?.active!==false&&!x?.invalidatedBy).filter(x=>!iterationId||String(x?.fields?.ITERATION_ID??x?.ITERATION_ID??x?.scope?.iterationId??'')===String(iterationId)).at(-1);return {projectRevision:Number(state?.revision||0),inputVersion:j.CURRENT_INPUT_VERSION||null,sourceSetVersion:j.CURRENT_SOURCE_SET_VERSION||null,requirementsVersion:j.CURRENT_REQUIREMENTS_VERSION||null,testSuiteVersion:j.CURRENT_TEST_SUITE_VERSION||null,instructionVersion:j.CURRENT_INSTRUCTION_VERSION||null,iterationId,candidateId:own('candidateId',candidate?recordId(candidate,'candidateFreezes'):null),runId:own('runId',null),contextId:own('contextId',null),baselineId:own('baselineId',j.CURRENT_BASELINE_ID&&!scopePlaceholder(j.CURRENT_BASELINE_ID)?j.CURRENT_BASELINE_ID:null),productId:own('productId',j.CURRENT_PRODUCT_ID&&!scopePlaceholder(j.CURRENT_PRODUCT_ID)?j.CURRENT_PRODUCT_ID:null)};}\nfunction assertRequiredPromptScope(stage,operation,scope){const required=schema.operationContract(stage,operation)?.scopeRequirements||[],laneKeys=['runId','contextId'],missing=required.filter(key=>laneKeys.includes(key)&&scopePlaceholder(scope?.[key]));if(missing.length){const error=new Error(`Controlling instruction cannot be created until application execution-lane identity exists for: ${missing.join(', ')}.`);error.code='MISSING_REQUIRED_PROMPT_SCOPE';error.missingScope=missing;throw error;}return scope;}"
if s.count(old)!=1: raise SystemExit(f'scopeFor anchor mismatch: {s.count(old)}')
s=s.replace(old,new,1)
old2="const opContract=schema.operationContract(stage,operation);const scope=scopeFor(stage,state,options.scope||{}),feedback=recoveryFeedback(state,stage,operation,scope),contextManifest="
new2="const opContract=schema.operationContract(stage,operation);const scope=assertRequiredPromptScope(stage,operation,scopeFor(stage,state,options.scope||{})),feedback=recoveryFeedback(state,stage,operation,scope),contextManifest="
if s.count(old2)!=1: raise SystemExit(f'build scope anchor mismatch: {s.count(old2)}')
s=s.replace(old2,new2,1)
old3="scopeFor,responseContractDescriptor,responseContract});"
new3="scopeFor,assertRequiredPromptScope,responseContractDescriptor,responseContract});"
if s.count(old3)!=1: raise SystemExit(f'export anchor mismatch: {s.count(old3)}')
s=s.replace(old3,new3,1)
p.write_text(s)
