from pathlib import Path

def replace(path,old,new,count=1):
 p=Path(path);text=p.read_text();actual=text.count(old)
 if actual<count: raise SystemExit(f'{path}: expected {count}, found {actual}: {old[:120]!r}')
 p.write_text(text.replace(old,new,count))

old="""function runBatchMarkup(n){if(![11,12,17,19].includes(n))return '';const runs=currentRunSlots(n),selected=selectedRun(n),rows=runs.map(r=>({RUN_ID:engine.recordId(r,'runs'),CONTEXT_ID:recordValue(r,'CONTEXT_ID'),ITERATION_ID:recordValue(r,'ITERATION_ID'),CANDIDATE_ID:recordValue(r,'CANDIDATE_ID'),operation:r.operation||'EXECUTE_RUN',promptIdentity:r.promptInstructionId||r.currentPromptId||'NOT YET GENERATED',rawResponseStatus:r.rawResponseStatus||'NOT RECEIVED',validationStatus:r.validationStatus||'NOT VALIDATED',proposalStatus:r.proposalStatus||'NONE',acceptedStatus:r.completionState||r.status||recordValue(r,'EXECUTION_STATUS')||'RESERVED',receipt:r.receiptId||'NONE'}));const picker=(schema.operationContract(n,selectedOperation(n))?.scopeRequirements||[]).includes('runId')&&runs.length?`<div class=\"field\"><label>Run slot for this instruction</label><select id=\"run-slot-picker\">${runs.map(r=>{const id=engine.recordId(r,'runs');return `<option value=\"${esc(id)}\"${selected&&engine.recordId(selected,'runs')===id?' selected':''}>${esc(id)} · ${esc(recordValue(r,'CONTEXT_ID')||'NO CONTEXT')}</option>`;}).join('')}</select></div>`:'';return `<div class=\"panel\"><h2 class=\"section-title\">Run batch</h2>${picker}${rows.length?details('Application-reserved run/context slots',rows,true):'<div class=\"empty-state\">No run batch has been reserved.</div>'}</div>`;}"""
new="""function runBatchMarkup(n){if(![11,12,17,19].includes(n))return '';const runs=currentRunSlots(n),selected=selectedRun(n),rows=runs.map(r=>({RUN_ID:engine.recordId(r,'runs'),CONTEXT_ID:recordValue(r,'CONTEXT_ID'),ITERATION_ID:recordValue(r,'ITERATION_ID'),CANDIDATE_ID:recordValue(r,'CANDIDATE_ID'),operation:r.operation||'EXECUTE_RUN',promptIdentity:r.promptInstructionId||r.currentPromptId||'NOT YET GENERATED',rawResponseStatus:r.rawResponseStatus||'NOT RECEIVED',validationStatus:r.validationStatus||'NOT VALIDATED',proposalStatus:r.proposalStatus||'NONE',acceptedStatus:r.completionState||r.status||recordValue(r,'EXECUTION_STATUS')||'RESERVED',receipt:r.receiptId||'NONE'})),requiresRun=(schema.operationContract(n,selectedOperation(n))?.scopeRequirements||[]).includes('runId'),picker=requiresRun&&runs.length?`<div class=\"field\"><label>Run slot for this instruction</label><select id=\"run-slot-picker\">${runs.map(r=>{const id=engine.recordId(r,'runs');return `<option value=\"${esc(id)}\"${selected&&engine.recordId(selected,'runs')===id?' selected':''}>${esc(id)} · ${esc(recordValue(r,'CONTEXT_ID')||'NO CONTEXT')}</option>`;}).join('')}</select></div>`:'',batchAction=requiresRun&&runs.length?`<div class=\"button-row\"><button id=\"save-run-prompts\">Save all ${runs.length} run instructions</button></div><p class=\"section-intro\">Save the complete run batch in one project revision so independent run instructions can be dispatched without making earlier run prompts disappear.</p>`:'';return `<div class=\"panel\"><h2 class=\"section-title\">Run batch</h2>${picker}${batchAction}${rows.length?details('Application-reserved run/context slots',rows,true):'<div class=\"empty-state\">No run batch has been reserved.</div>'}</div>`;}"""
replace('app-core.js',old,new)

anchor="""async function savePromptRecord(n){
  const existing=currentPromptRecord(n);if(existing)return existing;
  const preview=clone(current);preview.revision=Number(current.revision||0)+1;
  const candidate=globalThis.closedLoopPromptEngine.buildPromptRecord(n,preview,promptOptions(n)),next=clone(current),record={...candidate,generatedAt:new Date().toISOString(),iteration:current.job.CURRENT_ITERATION||'NOT APPLICABLE'};
  engine.registerGeneratedPrompt(next,record);await persistReplacement(next);
  const committed=currentPromptRecord(n);if(!committed||committed.instructionId!==record.instructionId)throw new Error('The generated prompt was not committed with its controlling revision.');return committed;
}
"""
addition=anchor+"""async function saveRunBatchPrompts(){
  const stage=current.activeStage,operation=selectedOperation(stage),requirements=schema.operationContract(stage,operation)?.scopeRequirements||[];if(!requirements.includes('runId'))throw new Error('The selected operation is not run-scoped.');const runs=currentRunSlots(stage);if(!runs.length)throw new Error('Reserve the run batch before saving run instructions.');
  const targetRevision=Number(current.revision||0)+1,next=clone(current),preview=clone(current);preview.revision=targetRevision-1;let created=0;
  for(const run of runs){const runId=engine.recordId(run,'runs'),contextId=String(recordValue(run,'CONTEXT_ID')||run.relationships?.CONTEXT_ID||run.scope?.contextId||'');if(!runId||!contextId)throw new Error('Every run slot must have an application-reserved RUN_ID and CONTEXT_ID before prompt generation.');const options={operation,scope:{runId,contextId}},already=safe(next.projectData.generatedPrompts).find(x=>promptMatches(x,stage,options));if(already)continue;const candidate=globalThis.closedLoopPromptEngine.buildPromptRecord(stage,preview,options),record={...candidate,generatedAt:new Date().toISOString(),iteration:current.job.CURRENT_ITERATION||'NOT APPLICABLE'};engine.registerGeneratedPrompt(next,record);preview.projectData.generatedPrompts.push(clone(record));created++;}
  if(!created){announce('all run instructions already saved');return current;}await persistReplacement(next);const currentRevision=Number(current.revision||0),active=safe(current.projectData.generatedPrompts).filter(x=>Number(x.stage)===stage&&!x.invalidatedBy&&x.operation===operation&&Number(x.scope?.projectRevision)===currentRevision),runIds=new Set(active.map(x=>String(x.scope?.runId||'')));if(runs.some(r=>!runIds.has(engine.recordId(r,'runs'))))throw new Error('The complete run instruction batch was not committed at one controlling project revision.');announce(`${runs.length} run instructions saved in one project revision`);render();return current;
}
"""
replace('app-core.js',anchor,addition)

old="""if($('#reserve-run-batch'))$('#reserve-run-batch').onclick=reserveRunBatch;if($('#freeze-candidate'))"""
new="""if($('#reserve-run-batch'))$('#reserve-run-batch').onclick=reserveRunBatch;if($('#save-run-prompts'))$('#save-run-prompts').onclick=async()=>{try{await saveRunBatchPrompts();}catch(error){alert(error.message||error);}};if($('#freeze-candidate'))"""
replace('app-core.js',old,new)

# Browser proof: retained Stage 19 has the current unchanged-confirmation run batch. Batch-save all prompts,
# switch lanes, and prove copying an already-saved run prompt does not increment global revision.
p=Path('verify-browser-extra.mjs');text=p.read_text();marker="  console.log('extra:proposal-reload');"
insert="""  console.log('extra:parallel-run-prompt-batch');
  await openStage(cdp,19);const opReady=await evalValue(cdp,`(()=>{const o=document.querySelector('#operation-picker');if(!o)return false;o.value='EXECUTE_RUN';o.dispatchEvent(new Event('change',{bubbles:true}));return true})()`);assert(opReady,'Stage 19 EXECUTE_RUN operation picker is unavailable.');await waitExpr(cdp,`document.querySelector('#save-run-prompts')&&document.querySelectorAll('#run-slot-picker option').length===10`);const beforeBatch=(await activeProject(cdp)).revision;await click(cdp,'#save-run-prompts');await sleep(350);let batchProject=await activeProject(cdp),batchPrompts=batchProject.projectData.generatedPrompts.filter(x=>Number(x.stage)===19&&x.operation==='EXECUTE_RUN'&&!x.invalidatedBy&&Number(x.scope?.projectRevision)===Number(batchProject.revision)),batchRuns=[...new Set(batchPrompts.map(x=>x.scope?.runId).filter(Boolean))],batchContexts=[...new Set(batchPrompts.map(x=>x.scope?.contextId).filter(Boolean))];assert(Number(batchProject.revision)===Number(beforeBatch)+1,'Run prompt batch did not commit in exactly one project revision.');assert(batchRuns.length===10&&batchContexts.length===10,'Run prompt batch did not preserve ten distinct run/context lanes in one revision.');const firstInstruction=batchPrompts[0].instructionId,secondRun=batchRuns[1],revisionAfterBatch=batchProject.revision;await evalValue(cdp,`(()=>{const s=document.querySelector('#run-slot-picker');s.value=${JSON.stringify('${SECOND_RUN_PLACEHOLDER}')};return true})()`);
"""
# inject JS expression for dynamically known secondRun rather than placeholder via a second replacement below
insert=insert.replace("await evalValue(cdp,`(()=>{const s=document.querySelector('#run-slot-picker');s.value=${JSON.stringify('${SECOND_RUN_PLACEHOLDER}')};return true})()`);", "await evalValue(cdp,`(()=>{const s=document.querySelector('#run-slot-picker');if(!s)return false;s.value=${JSON.stringify(secondRun)};s.dispatchEvent(new Event('change',{bubbles:true}));return true})()`);await sleep(180);const selectedText=await evalValue(cdp,`document.querySelector('#generated-prompt')?.textContent||''`);assert(selectedText.includes(secondRun)&&!selectedText.includes(`INSTRUCTION_ID: ${firstInstruction}`),'Run picker did not display the selected saved run instruction.');await click(cdp,'#copy-prompt');await sleep(180);batchProject=await activeProject(cdp);assert(Number(batchProject.revision)===Number(revisionAfterBatch),'Copying an already-saved run instruction unexpectedly created a new project revision.');assert((await evalValue(cdp,`window.__copiedPrompt||''`)).includes(secondRun),'Copy instruction did not copy the selected run-scoped prompt.');\n\n")
if marker not in text: raise SystemExit('browser marker missing')
text=text.replace(marker,insert+marker,1);p.write_text(text)

# Source-level assertion prevents accidental reintroduction even if retained browser fixture shape changes.
p=Path('verify-prompt-semantics.mjs');text=p.read_text();marker="console.log(JSON.stringify({promptSemanticContradictions:true"
insert="""const appSource=fs.readFileSync('app-core.js','utf8');if(!appSource.includes('saveRunBatchPrompts')||!appSource.includes('Save all ${runs.length} run instructions')||!appSource.includes('complete run instruction batch was not committed at one controlling project revision'))throw new Error('Run-scoped prompts are not batch-saved in one controlling project revision.');
"""
if marker not in text: raise SystemExit('semantic marker missing')
text=text.replace(marker,insert+'\n'+marker,1);p.write_text(text)
