import fs from 'node:fs';
import {createHash} from 'node:crypto';
let s=fs.readFileSync('workflow-engine.js','utf8');
const before=s;
s=s.replace('ds=determinations.map(x=>x.determination)','ds=determinations');
s=s.replace(".filter(x=>x.determination!=='SATISFIED')",".filter(x=>x!=='SATISFIED')");
s=s.replace(/semantic/gi,'adjudication');
function replaceFunction(name,body){const start=s.indexOf(`function ${name}(`);if(start<0)throw new Error(`Missing ${name}`);let brace=s.indexOf('{',start),depth=0,end=-1;for(let i=brace;i<s.length;i++){if(s[i]==='{')depth++;else if(s[i]==='}'&&--depth===0){end=i+1;break;}}if(end<0)throw new Error(`Unclosed ${name}`);s=s.slice(0,start)+body.trim()+s.slice(end);}
replaceFunction('evaluateEvidenceContract',String.raw`
function evaluateEvidenceContract(test,result,canonicalEvidence,project){
  const evidence=evidenceRecordsFor(project,result,canonicalEvidence),reasons=[],mode=upper(recordValue(test,'EXECUTION_MODE')),artifactReq=upper(recordValue(test,'ARTIFACT_REQUIREMENTS')),requiresAttachment=Boolean(test&&artifactReq&&!adjudication_NONE.has(artifactReq));
  if(!evidence.length)reasons.push('No canonical evidence record is linked to the result; narrative alone is non-controlling.');
  for(const item of evidence){const authority=upper(recordValue(item,'AUTHORITY_TYPE')),attachmentId=String(recordValue(item,'ATTACHMENT_ID')||item?.relationships?.ATTACHMENT_ID||'').trim();if(adjudicationEmpty(recordValue(item,'KIND')))reasons.push('Canonical evidence kind is missing.');if(!authority||authority==='UNKNOWN')reasons.push('Canonical evidence authority type is missing or unknown.');if(adjudicationEmpty(recordValue(item,'CONTENT'))&&adjudicationEmpty(recordValue(item,'DESCRIPTION'))&&adjudicationEmpty(recordValue(item,'LOCATION')))reasons.push('Canonical evidence contains no preserved observation payload.');if(attachmentId&&attachmentId!=='UNKNOWN'){const a=records(project,'artifacts').find(x=>recordId(x,'artifacts')===attachmentId);if(!a||upper(recordValue(a,'AVAILABILITY'))!=='BYTES_PERSISTED_AND_VERIFIED')reasons.push('Referenced evidence attachment bytes are not application-verified.');}}
  if(requiresAttachment&&!evidence.some(item=>{const id=String(recordValue(item,'ATTACHMENT_ID')||item?.relationships?.ATTACHMENT_ID||'').trim();return id&&id!=='UNKNOWN';}))reasons.push('The controlling test requires an attachment-backed evidence record.');
  const executionId=resultExecutionIdentity(project,result),contextId=resultContextIdentity(project,result);
  if(test&&mode!=='APPLICATION_DETERMINISTIC'&&!executionId)reasons.push('Execution identity is not established.');
  if(test&&['INDEPENDENT_AGENT_REVIEW','EXTERNAL_AGENT_TOOL','HUMAN_INSPECTION','EXTERNAL_SYSTEM'].includes(mode)&&!contextId)reasons.push('Execution/reviewer context identity is not established.');
  return {sufficient:reasons.length===0,reasons,evidenceIds:evidence.map(e=>recordId(e,'evidenceRecords')),executionId,contextId};
}
`);
replaceFunction('detectCurrentContradictions',String.raw`
function detectCurrentContradictions(project){
  const out=[],push=(type,key,details,severity='RELEASE_MATERIAL')=>out.push({type,key,details,severity}),adjudicationCollections=['verification','deterministicResults','meaningResults','adversarialResults','representationInspections','preflightRecords','confirmationRecords','processAudits','productAudits','regressionExecutions','products'];
  const evaluation=(collection,r)=>evaluateResultConsistency(collection,r,testForResult(project,r),project),supports=(e,state)=>e.determination===state||e.claimedDetermination===state;
  for(const collection of adjudicationCollections)for(const r of recordsForCurrentScope(project,collection)){const e=evaluation(collection,r),id=recordId(r,collection)||String(r.id||r.recordId||'UNKNOWN');if(e.claimedDetermination==='SATISFIED'&&e.determination!=='SATISFIED')push('CLAIMED_FAVORABLE_EFFECTIVE_CONFLICT',collection+':'+id,[e.claimedDetermination,e.determination,...e.reasons]);}
  const groups=new Map();for(const r of recordsForCurrentScope(project,'verification')){const key=verificationKey(r),e=evaluation('verification',r),state=e.determination==='UNDETERMINED'&&['SATISFIED','VIOLATED'].includes(e.claimedDetermination)?e.claimedDetermination:e.determination;if(!groups.has(key))groups.set(key,new Set());groups.get(key).add(state);}for(const [key,ds] of groups)if(ds.size>1)push('VERIFICATION_DETERMINATION_CONFLICT',key,[...ds]);
  const det=recordsForCurrentScope(project,'deterministicResults'),meaning=recordsForCurrentScope(project,'meaningResults'),adv=recordsForCurrentScope(project,'adversarialResults');for(const m of meaning){const req=resultRequirementId(project,m),me=evaluation('meaningResults',m);if(supports(me,'VIOLATED')&&det.some(d=>resultRequirementId(project,d)===req&&supports(evaluation('deterministicResults',d),'SATISFIED')))push('DETERMINISTIC_MEANING_CONFLICT',req,['DETERMINISTIC SATISFIED claim/effective state','MEANING VIOLATED claim/effective state']);if(supports(me,'SATISFIED')&&adv.some(a=>resultRequirementId(project,a)===req&&supports(evaluation('adversarialResults',a),'VIOLATED')))push('MEANING_ADVERSARIAL_CONFLICT',req,['MEANING SATISFIED claim/effective state','ADVERSARIAL VIOLATION claim/effective state']);}
  const artifacts=new Map();for(const a of recordsForCurrentScope(project,'artifacts')){const id=recordId(a,'artifacts'),sig=[recordValue(a,'VERSION'),recordValue(a,'BYTE_SIZE'),recordValue(a,'SHA256')].join('|');if(artifacts.has(id)&&artifacts.get(id)!==sig)push('ARTIFACT_IDENTITY_CONFLICT',id,[artifacts.get(id),sig]);else artifacts.set(id,sig);}const product=recordsForCurrentScope(project,'products').at(-1),baseline=recordsForCurrentScope(project,'baselines').at(-1);if(product&&baseline&&String(recordValue(product,'BASELINE_ID')||product.relationships?.BASELINE_ID||'')!==recordId(baseline,'baselines'))push('PRODUCT_BASELINE_CONFLICT',recordId(product,'products'),['Product baseline differs from current baseline.']);return out;
}
`);
const preflightOld="if(collection==='preflightRecords'){for(const key of ['MULTIPLE_INTERPRETATIONS','UNDEFINED_OBJECTS','UNSUPPLIED_DEPENDENCIES','INTERNAL_CONFLICTS','UNAVAILABLE_CAPABILITIES','FINDINGS'])if(adjudicationAdverse(recordValue(record,key)))reasons.push(key+' contains an unresolved preflight finding.');for(const key of ['OBJECTIVELY_VERIFIABLE','RESPONSIBLE_OPERATION_ASSIGNED','ORDER_CLEAR','FAILURE_BEHAVIOR_DEFINED','TRACEABILITY'])if(!truth(recordValue(record,key)))reasons.push(key+' is not affirmatively established.');if(!evidence.sufficient)reasons.push(...evidence.reasons);determination=reasons.length?'UNDETERMINED':'SATISFIED';}";
const preflightNew="if(collection==='preflightRecords'){const adverseTokens=new Set(['TRUE','YES','PRESENT','FOUND','UNRESOLVED','VIOLATED','FAILED','BLOCKED']);for(const key of ['MULTIPLE_INTERPRETATIONS','UNDEFINED_OBJECTS','UNSUPPLIED_DEPENDENCIES','INTERNAL_CONFLICTS','UNAVAILABLE_CAPABILITIES']){const value=recordValue(record,key);if(typeof value==='boolean'?value:adverseTokens.has(upper(value)))reasons.push(key+' establishes an unresolved preflight defect.');}const findings=upper(recordValue(record,'FINDINGS'));if(['DEFECT FOUND','MATERIAL DEFECT','UNRESOLVED DEFECT','MATERIAL AMBIGUITY','MATERIAL CONFLICT'].includes(findings))reasons.push('FINDINGS establishes an unresolved preflight defect.');if(!evidence.sufficient)reasons.push(...evidence.reasons);determination=reasons.length?'UNDETERMINED':'SATISFIED';}";
if(!s.includes(preflightOld))throw new Error('Preflight adjudication block not found');s=s.replace(preflightOld,preflightNew);
const oldStage7="const outcome=upper(recordValue(mutation,'EXECUTION_OUTCOME')||recordValue(mutation,'ACTUAL_RESULT'));if(!['REJECTED_INVALID','ACCEPTED_INVALID','UNDETERMINED','NOT_RUN'].includes(outcome))add([recordId(mutation,'failureTests')+': controlled EXECUTION_OUTCOME is required (REJECTED_INVALID/ACCEPTED_INVALID/UNDETERMINED/NOT_RUN).']);";
const newStage7="const explicitOutcome=upper(recordValue(mutation,'EXECUTION_OUTCOME')),legacyActual=upper(recordValue(mutation,'ACTUAL_RESULT')),expected=upper(recordValue(mutation,'EXPECTED_REJECTION')),legacyOutcome=!explicitOutcome&&expected.includes('REJECT')&&['REJECTED','REJECT','DENIED','BLOCKED'].includes(legacyActual)?'REJECTED_INVALID':!explicitOutcome&&expected.includes('REJECT')&&['ACCEPTED','PASS','PASSED','SUCCESS','SUCCEEDED'].includes(legacyActual)?'ACCEPTED_INVALID':'',outcome=explicitOutcome||legacyOutcome;if(!['REJECTED_INVALID','ACCEPTED_INVALID','UNDETERMINED','NOT_RUN'].includes(outcome))add([recordId(mutation,'failureTests')+': controlled EXECUTION_OUTCOME is required (REJECTED_INVALID/ACCEPTED_INVALID/UNDETERMINED/NOT_RUN); only the finite legacy rejection/acceptance vocabulary is migrated.']);";
if(!s.includes(oldStage7))throw new Error('Stage 7 adjudication wrapper was not found.');s=s.replace(oldStage7,newStage7);
if(s===before)throw new Error('Expected adjudication fixups were not found.');fs.writeFileSync('workflow-engine.js',s);
let ingestion=fs.readFileSync('response-ingestion.js','utf8');const authorityOld="AUTHORITY_TYPE:source.authorityType||'UNKNOWN'";if(!ingestion.includes(authorityOld))throw new Error('Evidence authority default not found');ingestion=ingestion.replace(authorityOld,"AUTHORITY_TYPE:source.authorityType||'EXTERNAL_AGENT_RESPONSE'");fs.writeFileSync('response-ingestion.js',ingestion);
let schema=fs.readFileSync('workflow-schema.js','utf8');schema=schema.replace('"EXPECTED_REJECTION",\n      "ACTUAL_RESULT",\n      "EVIDENCE"','"EXPECTED_REJECTION",\n      "ACTUAL_RESULT",\n      "EXECUTION_OUTCOME",\n      "EVIDENCE"');schema=schema.replace("'MUTATION_ID','REQ_ID','VIOLATION_MODE','FIXTURE','EXPECTED_REJECTION','ACTUAL_RESULT','VALIDATOR_DEFECT_ID','EVIDENCE'","'MUTATION_ID','REQ_ID','VIOLATION_MODE','FIXTURE','EXPECTED_REJECTION','ACTUAL_RESULT','EXECUTION_OUTCOME','VALIDATOR_DEFECT_ID','EVIDENCE'");const overrideMarker="'MEANING-REVIEW':Object.freeze({TEST_ID:Object.freeze({valueType:'REFERENCE',enumValues:Object.freeze([]),nullable:false,normalizerKey:null,closedProperties:null})}),";if(!schema.includes(overrideMarker))throw new Error('Record override marker not found');schema=schema.replace(overrideMarker,"'MUTATION':Object.freeze({EXECUTION_OUTCOME:Object.freeze({valueType:'STRING',enumValues:Object.freeze(['REJECTED_INVALID','ACCEPTED_INVALID','UNDETERMINED','NOT_RUN']),nullable:false,normalizerKey:null,closedProperties:null})}),\n  "+overrideMarker);fs.writeFileSync('workflow-schema.js',schema);
const runtimeFiles=['workbook.js','hash.js','workflow-schema.js','workflow-engine.js','prompt-engine.js','response-ingestion.js','project-store.js','app-core.js'];const gitBlobSha=file=>{const bytes=fs.readFileSync(file);return createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex');};const manifest=runtimeFiles.map(file=>`${file}:${gitBlobSha(file)}\n`).join('');const token=`runtime-${createHash('sha256').update(manifest).digest('hex').slice(0,16)}`;let html=fs.readFileSync('index.html','utf8');for(const file of runtimeFiles)html=html.replace(new RegExp(`${file.replace('.','\\.')}\\?v=[^\"]+`,'g'),`${file}?v=${token}`);fs.writeFileSync('index.html',html);console.log(`adjudication fixups applied; ${token}`);
