(()=>{
const OUTPUT=['UNSPECIFIED','PLAIN_TEXT','MARKDOWN','DOCX','PDF','XLSX','CSV','JSON','ZIP','CODE','OTHER'];
const SEVERITY=['CRITICAL','MAJOR','MINOR'];
const ARTIFACT=['INPUT','SOURCE_SET','REQUIREMENTS','TEST_SUITE','INSTRUCTION','TOOL_CONFIGURATION','RUN_OUTPUT','BASELINE','PRODUCT','EVIDENCE','PACKAGE','OTHER'];
function norm(){for(const x of D.jobs){if(x.inference===undefined)x.inference=false;if(!x.regressions)x.regressions=[];if(!x.blockers)x.blockers=[];for(const k of ['sources','requirements','tests','runs','defects','artifacts'])if(!x[k])x[k]=[]}}norm();save();
function psel(values,value,code){return '<select onchange="'+code+'">'+values.map(v=>'<option '+(v===value?'selected':'')+'>'+v+'</option>').join('')+'</select>'}
intake=function(){let x=j();A.innerHTML=`<div class=c><small>${x.id} • INPUT-v${String(x.inputVersion||1).padStart(3,'0')}</small><label>Job title</label><input value="${esc(x.title)}" oninput="j().title=this.value;save()"><label>Exact final job objective</label><textarea oninput="j().objective=this.value;save()">${esc(x.objective)}</textarea><label>Exact final requested deliverable</label><textarea oninput="j().deliverable=this.value;save()">${esc(x.deliverable)}</textarea><label>Supplied files/messages/links/data</label><textarea oninput="j().materials=this.value;save()">${esc(x.materials)}</textarea><label>Explicit constraints</label><textarea oninput="j().constraints=this.value;save()">${esc(x.constraints)}</textarea><label>Required output format</label>${psel(OUTPUT,x.format||'UNSPECIFIED',"j().format=this.value;save()") }<label>Deadline / temporal scope</label><input value="${esc(x.deadline)}" oninput="j().deadline=this.value;save()"><label>Known authoritative sources</label><textarea oninput="j().authorities=this.value;save()">${esc(x.authorities)}</textarea><label>Available tools/access</label><textarea oninput="j().tools=this.value;save()">${esc(x.tools)}</textarea><label>Prohibited actions</label><textarea oninput="j().prohibited=this.value;save()">${esc(x.prohibited)}</textarea><label>Known unknown information</label><textarea oninput="j().unknowns=this.value;save()">${esc(x.unknowns)}</textarea><label>Inference expressly permitted</label>${psel(['FALSE','TRUE'],x.inference?'TRUE':'FALSE',"j().inference=this.value==='TRUE';save()") }<div class=row><button onclick=flow()>Done</button><button class=s onclick="j().inputVersion=(j().inputVersion||1)+1;save();intake()">New Input Version</button></div></div>`}
const originalPrompt=promptFor;
function template(n){if(n===2)return '{"sources":[{"title":"...","type":"STATUTE","origin":"...","version":"...","effective_date":"...","authority":"CONTROLLING","role":"MANDATORY","relevant_portions":"...","conflicts":"..."}]}';if(n===4)return '{"requirements":[{"requirement":"...","type":"AUTHORITATIVE","source_id":"existing SOURCE_ID or UNKNOWN","source_location":"...","authority":"CONTROLLING","applicability":"...","dependencies":"...","prohibitions":"...","verification_method":"SOURCE_COMPARISON","expected_evidence":"...","failure_condition":"...","status":"CANDIDATE","mandatory":true}]}';if(n===6)return '{"tests":[{"requirement_id":"existing REQ_ID","method":"SOURCE_COMPARISON","inputs_required":"...","procedure":"...","expected_result":"...","failure_condition":"...","evidence_produced":"..."}]}';if(n===14)return '{"defects":[{"requirement_id":"...","observed_failure":"...","category":"EXECUTION_DEFECT","severity":"MAJOR","root_cause":"...","correction":"..."}]}';if(n===15)return '{"regressions":[{"original_defect_id":"...","requirement_id":"...","failure_fixture":"...","detection_method":"...","expected_rejection_or_correction":"..."}]}';if(n===21)return '{"artifacts":[{"name":"...","kind":"PRODUCT","version":"v001","hash":"...","location":"..."}]}';return '{"records":[]}' }
promptFor=function(n){return originalPrompt(n)+`\n\nSTRICT ALLOWED VALUES\nSOURCE_TYPE: ${E.sourceType.join(' | ')}\nSOURCE_ROLE: ${E.sourceRole.join(' | ')}\nAUTHORITY: ${E.authority.join(' | ')}\nREQUIREMENT_TYPE: ${E.reqType.join(' | ')}\nREQUIREMENT_STATUS: ${E.reqStatus.join(' | ')}\nVERIFICATION_METHOD: ${E.verify.join(' | ')}\nVERIFICATION_RESULT: ${E.vresult.join(' | ')}\nDEFECT_CATEGORY: ${E.defect.join(' | ')}\nDEFECT_SEVERITY: ${SEVERITY.join(' | ')}\nARTIFACT_KIND: ${ARTIFACT.join(' | ')}\n\nSTRUCTURED APP IMPORT\nWhen this stage creates registry records, append APP_RECORDS_JSON as the LAST item in your response. Use JSON only and only the allowed enum values. Do not invent IDs; the app generates IDs when it imports records.\nAPP_RECORDS_JSON:\n${template(n)}`}
function jsonAfter(text,marker='APP_RECORDS_JSON:'){let i=text.lastIndexOf(marker);if(i<0)return null;i=text.indexOf('{',i+marker.length);if(i<0)return null;let depth=0,str=false,escp=false;for(let k=i;k<text.length;k++){let c=text[k];if(str){if(escp)escp=false;else if(c==='\\')escp=true;else if(c==='"')str=false;continue}if(c==='"'){str=true;continue}if(c==='{')depth++;if(c==='}'){depth--;if(depth===0)return text.slice(i,k+1)}}return null}
const SC={sources:{p:'SRC',en:{type:E.sourceType,authority:E.authority,role:E.sourceRole}},requirements:{p:'REQ',en:{type:E.reqType,authority:E.authority,verification_method:E.verify,status:E.reqStatus}},tests:{p:'TEST',en:{method:E.verify}},defects:{p:'DEFECT',en:{category:E.defect,severity:SEVERITY}},regressions:{p:'REG',en:{}},artifacts:{p:'ART',en:{kind:ARTIFACT}}};
function valid(kind,r){for(const [f,vals] of Object.entries(SC[kind].en)){if(r[f]!==undefined&&!vals.includes(r[f]))return `${f}=${r[f]} is invalid. Allowed: ${vals.join(', ')}`}return ''}
window.importStructured=function(n,notify=true){let raw=jsonAfter(j().st[n-1].result);if(!raw){if(notify)alert('No APP_RECORDS_JSON object was found.');return 0}let obj;try{obj=JSON.parse(raw)}catch(e){alert('APP_RECORDS_JSON is invalid JSON: '+e.message);return 0}let count=0;for(const [kind,arr] of Object.entries(obj)){if(!SC[kind]||!Array.isArray(arr))continue;for(const rec0 of arr){const err=valid(kind,rec0);if(err){alert(kind+' record rejected: '+err);continue}const rec={...rec0,id:rec0.id||uid(SC[kind].p),created_at:new Date().toISOString()};j()[kind].push(rec);count++}}save();if(notify)alert('Imported '+count+' structured record'+(count===1?'':'s')+'. IDs were generated by the app.');return count}
const originalProcess=process;process=function(n){let s=j().st[n-1],u=(s.result||'').toUpperCase();importStructured(n,false);if(u.includes('STAGE_STATUS: BLOCKED')&&!j().blockers.some(b=>b.stage===n&&b.open)){j().blockers.push({id:uid('BLOCK'),stage:n,open:true,result:s.result,created_at:new Date().toISOString()});save()}originalProcess(n)}
const originalStage=stage;stage=function(n){originalStage(n);let cards=A.querySelectorAll('.c');if(cards[2]){let b=document.createElement('button');b.className='s';b.textContent='Import Structured Records';b.onclick=()=>importStructured(n,true);cards[2].appendChild(document.createTextNode(' '));cards[2].appendChild(b)}}
regs=function(){if(!j())return jobs();let x=j(),keys=['sources','requirements','tests','runs','defects','regressions','artifacts','blockers'];A.innerHTML='<div class=c><b>Structured registries</b><p><small>These are populated from agent output. The app generates IDs; you do not manually create them.</small></p></div>'+keys.map(k=>`<div class=c><b>${k.toUpperCase()}</b> — ${(x[k]||[]).length}${(x[k]||[]).slice(-8).reverse().map(r=>`<div style="border-top:1px solid #263653;margin-top:8px;padding-top:8px"><b>${esc(r.id||'')}</b><pre>${esc(JSON.stringify(r,null,2))}</pre></div>`).join('')}</div>`).join('')}
head();jobs();
})();