from pathlib import Path

# Schema: NEXT_REQUIRED_ACTION is a structured application-owned object.
p=Path('workflow-schema.js')
s=p.read_text()
old="function jobFieldDefinition(name){\n  if(APPLICATION_JOB_FIELDS.includes(name))return field(name,PRODUCER.APPLICATION,{derivation:`Application derives ${name} from canonical project state.`});"
new="function jobFieldDefinition(name){\n  if(name==='NEXT_REQUIRED_ACTION')return field(name,PRODUCER.APPLICATION,{valueType:'OBJECT',derivation:'operationalNextAction() derives the complete structured operator action from current canonical state.'});\n  if(APPLICATION_JOB_FIELDS.includes(name))return field(name,PRODUCER.APPLICATION,{derivation:`Application derives ${name} from canonical project state.`});"
if old not in s:
    raise SystemExit('jobFieldDefinition anchor missing')
s=s.replace(old,new,1)
p.write_text(s)

# Engine: structured operational next action is the only primary-action authority.
p=Path('workflow-engine.js')
s=p.read_text()
start=s.index('function operationalNextAction(project,currentStage){')
end=s.index('\n\nfunction applicationTestCapabilities()',start)
replacement="""const ACTION_TYPES=Object.freeze(['RUN_APP_TESTS','AI_REVIEW','EXTERNAL_AGENT_TOOL','HUMAN_INSPECTION','EXTERNAL_SYSTEM','ATTACH_REQUIRED_FILES','CONTINUE_AGENT_CONVERSATION','PASTE_FINAL_JSON','REVIEW_PROPOSAL','BLOCKED','COMPLETE']);
function actionReceiptState(project,stage){
  const latestReceipt=safe(project?.projectData?.outputReceipts).filter(item=>Number(item.stage)===Number(stage)).at(-1)||null;
  const latestAccepted=acceptedChanges(project,stage).at(-1)||null;
  return {canonicalStateChanged:latestReceipt?.canonicalStateChanged===true||Boolean(latestAccepted&&latestReceipt?.canonicalStateChanged!==false),acceptedChange:latestReceipt?.acceptedChange||latestReceipt?.changeId||latestAccepted?.changeId||null,downstreamInvalidated:safe(latestReceipt?.downstreamInvalidated||latestReceipt?.invalidatedStages),newPromptRequired:Boolean(latestReceipt?.newPromptRequired)};
}
function actionEnvelope(project,stage,values={}){
  const action={actionType:'PASTE_FINAL_JSON',heading:'Complete the current stage',explanation:'Return the current final structured response and any required returned files.',primaryButton:null,secondaryAction:null,filesToSend:[],filesToWithhold:[],expectedReturnFiles:[],blockingReason:null,...actionReceiptState(project,stage),...values};
  if(!ACTION_TYPES.includes(action.actionType))throw new Error('Unknown operational action type: '+action.actionType+'.');
  action.filesToSend=safe(action.filesToSend);action.filesToWithhold=safe(action.filesToWithhold);action.expectedReturnFiles=safe(action.expectedReturnFiles);action.downstreamInvalidated=safe(action.downstreamInvalidated);return action;
}
function operationalNextAction(project,currentStage){
  const stage=Number(currentStage||1),requests=unresolvedHumanRequests(project,stage),proposals=safe(project?.projectData?.responseProposals).filter(item=>Number(item.stage)===stage&&!item.invalidatedBy&&['PENDING','PENDING_OPERATOR_REVIEW'].includes(upper(item.status||item.state)));
  if(proposals.length)return actionEnvelope(project,stage,{actionType:'REVIEW_PROPOSAL',heading:'Review the proposed canonical change',explanation:'Validation succeeded. Review current values, proposed values, provenance, and validation status before accepting or rejecting the complete proposal.',primaryButton:'Review proposal'});
  if(requests.length)return actionEnvelope(project,stage,{actionType:'CONTINUE_AGENT_CONVERSATION',heading:'Answer the current human-only question',explanation:'Continue the same human conversation. Do not repeat already-captured project facts. Saving an answer creates a new User Job Input version, invalidates the old prompt/proposal, and requires a replacement prompt for this same stage.',primaryButton:'Continue conversation',newPromptRequired:true});
  if(stage===16){const correction=stage16CorrectionPlan(project);if(correction.actionType==='BLOCKED')return actionEnvelope(project,stage,{actionType:'BLOCKED',heading:correction.heading,explanation:correction.explanation,blockingReason:correction.explanation});if(correction.actionType==='HUMAN_AUTHORITY')return actionEnvelope(project,stage,{actionType:'CONTINUE_AGENT_CONVERSATION',heading:correction.heading,explanation:correction.explanation,primaryButton:'Provide human authority'});return actionEnvelope(project,stage,{actionType:'REVIEW_PROPOSAL',heading:correction.heading,explanation:correction.explanation,primaryButton:'Review correction'});}
  if([23,24].includes(stage)){const reviewer=records(project,'freshContexts').filter(r=>isActiveRecord(r)&&Number(r.stage)===stage).at(-1);if(!reviewer){const handoff=executionHandoff(project,{stage,operation:'COMPLETE'});return actionEnvelope(project,stage,{actionType:'AI_REVIEW',heading:'Open a fresh independent reviewer context',explanation:'Use a reviewer context that did not generate the product. Register its external context identifier before sending the exact bounded review material.',primaryButton:'Register reviewer context',filesToSend:handoff.send,filesToWithhold:handoff.withhold,expectedReturnFiles:handoff.expectBack});}}
  const plan=testExecutionPlan(project),relevant=[12,22,23,24].includes(stage)?plan.items:[];
  const blocked=relevant.find(item=>!item.executableNow);
  if(blocked){const missingBytes=!blocked.artifactReady||/artifact|bytes?|file/i.test(String(blocked.blockingReason||'')),handoff=blocked.handoff||{send:[],withhold:[],expectBack:[]};return actionEnvelope(project,stage,{actionType:missingBytes?'ATTACH_REQUIRED_FILES':'BLOCKED',heading:missingBytes?'Attach the exact required files':'Verification is blocked',explanation:blocked.blockingReason||'The declared verification route is not executable with current capability and artifact state.',primaryButton:missingBytes?'Attach required files':null,filesToSend:handoff.send,filesToWithhold:handoff.withhold,expectedReturnFiles:handoff.expectBack,blockingReason:blocked.blockingReason||'Required execution evidence is not currently obtainable.'});}
  const native=relevant.find(item=>item.executionMode==='APPLICATION_DETERMINISTIC'&&item.executableNow&&(item.operatorAction==='RUN_IN_APP'||item.operatorAction==='NO_ACTION'));
  if(native){const handoff=native.handoff||{send:[],withhold:[],expectBack:[]};return actionEnvelope(project,stage,{actionType:'RUN_APP_TESTS',heading:'Run application verification',explanation:'No external action is required for the current supported deterministic test. The application executes registered Test IR against exact verified inputs and records an application-owned result.',primaryButton:'Run tests',filesToSend:handoff.send,filesToWithhold:handoff.withhold,expectedReturnFiles:handoff.expectBack});}
  const item=relevant.find(item=>item.operatorAction!=='NO_ACTION');
  if(item){const handoff=item.handoff||{send:[],withhold:[],expectBack:[]},common={filesToSend:handoff.send,filesToWithhold:handoff.withhold,expectedReturnFiles:handoff.expectBack};if(item.operatorAction==='SEND_TO_INDEPENDENT_REVIEWER')return actionEnvelope(project,stage,{...common,actionType:'AI_REVIEW',heading:'Send to a fresh independent reviewer',explanation:'Prepare the exact bounded verification package, send only the listed material, withhold the listed context, and return the contracted structured result and evidence.',primaryButton:'Prepare verification package'});if(item.operatorAction==='SEND_TO_TOOL_AGENT')return actionEnvelope(project,stage,{...common,actionType:'EXTERNAL_AGENT_TOOL',heading:'Run verification with the required external tool capability',explanation:'Use an external tool-capable environment that actually provides '+(item.requiredCapability||'the declared capability')+'. Send the exact listed files and return the contracted evidence.',primaryButton:'Prepare verification package'});if(item.operatorAction==='HUMAN_INSPECTION')return actionEnvelope(project,stage,{...common,actionType:'HUMAN_INSPECTION',heading:'Human inspection is required',explanation:'Perform the exact inspection and preserve an explicit human-owned observation. An AI assertion that a human inspected the product is insufficient.',primaryButton:'Open inspection instructions'});if(item.operatorAction==='USE_EXTERNAL_SYSTEM')return actionEnvelope(project,stage,{...common,actionType:'EXTERNAL_SYSTEM',heading:'Use the required external system',explanation:'Perform the declared operation in '+(item.requiredCapability||'the required external system')+' and return evidence attributable to that system.',primaryButton:'Prepare external-system package'});}
  if(stage===1){const handoff=executionHandoff(project,{stage:1,operation:'COMPLETE'});return actionEnvelope(project,stage,{actionType:'CONTINUE_AGENT_CONVERSATION',heading:'Complete Stage 01 intake with the agent',explanation:'Send the listed supplied project files once to the Stage 01 agent. Continue the same conversation until every foreseeable human-only BLOCKING_NOW and ASK_NOW_NONBLOCKING item is answered or explicitly deferred. After the accepted intentStatements ledger is committed, later stages use canonical project memory and must not ask you to resend this material merely to recover already-captured information. Paste final JSON only when Stage 01 is ready.',primaryButton:'Continue conversation',filesToSend:handoff.send,filesToWithhold:handoff.withhold,expectedReturnFiles:handoff.expectBack});}
  return actionEnvelope(project,stage,{actionType:'PASTE_FINAL_JSON',heading:'Return the final structured response',explanation:'Use the current Stage '+String(stage).padStart(2,'0')+' instruction. Continue the external work or conversation until the executor is ready to return one final strict JSON response and any required files.',primaryButton:'Paste final JSON'});
}"""
s=s[:start]+replacement+s[end:]
old="  project.job.NEXT_REQUIRED_ACTION=completed===30?'Preserve the completed workflow and exact release evidence.':operationalNextAction(project,currentStage);"
new="  project.job.NEXT_REQUIRED_ACTION=completed===30?actionEnvelope(project,30,{actionType:'COMPLETE',heading:'Workflow complete',explanation:'Preserve the completed workflow, permanent defect/regression history, exact release evidence, and authorized delivery bytes.',primaryButton:null}):operationalNextAction(project,currentStage);"
if old not in s:
    raise SystemExit('recalculate NEXT_REQUIRED_ACTION anchor missing')
s=s.replace(old,new,1)
p.write_text(s)

# UI: render the structured action; existing dimensions and visual shell are untouched.
p=Path('app-core.js')
s=p.read_text()
anchor="const statusClass=v=>{const s=String(v||'').trim().toUpperCase().replace(/[_-]+/g,' ').replace(/\\s+/g,' ');if(!s)return '';if(['REJECTED','VIOLATED','FAILED','DEFECTIVE','UNAUTHORIZED','NOT AUTHORIZED'].includes(s))return 'danger';if(s.startsWith('NOT ')||['BLOCKED','UNKNOWN','UNDETERMINED','PENDING','IN PROGRESS','NOT STARTED'].includes(s))return 'warn';if(['ACCEPTED','AUTHORIZED','SATISFIED','COMPLETE','READY','SUCCESS','CONVERGED','CONFIRMED'].includes(s))return 'success';return '';};\n"
helpers="""function canonicalCurrentStage(){return Math.max(1,Math.min(30,Number(String(current?.job?.CURRENT_STAGE||'').match(/\\d+/)?.[0]||current?.activeStage||1)));}
function currentNextAction(){const value=current?.job?.NEXT_REQUIRED_ACTION;if(value&&typeof value==='object'&&!Array.isArray(value))return value;return {actionType:'PASTE_FINAL_JSON',heading:'Next required action',explanation:String(value||'No next action recorded.'),primaryButton:null,secondaryAction:null,filesToSend:[],filesToWithhold:[],expectedReturnFiles:[],blockingReason:null,canonicalStateChanged:false,acceptedChange:null,downstreamInvalidated:[],newPromptRequired:false};}
function actionActor(action){return ({RUN_APP_TESTS:'Application',AI_REVIEW:'Fresh independent reviewer',EXTERNAL_AGENT_TOOL:'External tool-capable agent',HUMAN_INSPECTION:'Human operator',EXTERNAL_SYSTEM:'External system',ATTACH_REQUIRED_FILES:'Human operator',CONTINUE_AGENT_CONVERSATION:'Human and external agent',PASTE_FINAL_JSON:'Human operator',REVIEW_PROPOSAL:'Human operator',BLOCKED:'No executor until blocker is resolved',COMPLETE:'No further workflow execution'})[action.actionType]||'Current operator';}
function actionList(title,items,formatter){const rows=safe(items);return rows.length?details(title,rows.map(formatter),true):'';}
function nextActionMarkup(withPrimaryButton=true){const action=currentNextAction(),button=withPrimaryButton&&action.primaryButton?(action.actionType==='RUN_APP_TESTS'?`<button class=\"primary\" id=\"run-native-tests\" type=\"button\">${esc(action.primaryButton)}</button>`:['AI_REVIEW','EXTERNAL_AGENT_TOOL','EXTERNAL_SYSTEM'].includes(action.actionType)?`<button class=\"primary\" id=\"download-execution-package\" type=\"button\">${esc(action.primaryButton)}</button>`:`<button class=\"primary\" data-stage=\"${canonicalCurrentStage()}\" type=\"button\">${esc(action.primaryButton)}</button>`):'',send=actionList('Files you must send',action.filesToSend,item=>({artifactId:item.artifactId||item.id||'',filename:item.filename||'',sha256:item.sha256||'',role:item.role||''})),withhold=actionList('Files you must not send',action.filesToWithhold,item=>({item:item.artifactIdOrCategory||item.artifactId||item.category||'',reason:item.reason||''})),returns=actionList('Files or evidence you must return',action.expectedReturnFiles,item=>({kind:item.kind||'',filenameOrPattern:item.filenameOrPattern||item.filename||'',required:item.required!==false?'YES':'NO'}));return `<div class=\"panel next-action-panel\" id=\"next-required-action\" tabindex=\"-1\"><h2 class=\"section-title\">${esc(action.heading||'Next required action')}</h2><p class=\"section-intro\"><strong>Who acts:</strong> ${esc(actionActor(action))}</p><div class=\"notice ${action.actionType==='BLOCKED'||action.actionType==='ATTACH_REQUIRED_FILES'?'warn':''}\">${esc(action.explanation||action.blockingReason||'')}</div>${send}${withhold}${returns}<div class=\"record-rows action-certainty\">${field('Canonical state changed',action.canonicalStateChanged?'YES':'NO')}${field('Accepted change',action.acceptedChange||'NONE')}${field('Downstream invalidated',safe(action.downstreamInvalidated).length?action.downstreamInvalidated.join(', '):'NONE')}${field('New prompt required',action.newPromptRequired?'YES':'NO')}</div>${button?`<div class=\"button-row\">${button}</div>`:''}<details class=\"record-card\"><summary>Advanced action details<span>Details</span></summary><div class=\"record-body\">${details('Structured operational action',action,true)}</div></details></div>`;}
"""
if 'function currentNextAction()' not in s:
    if anchor not in s:
        raise SystemExit('app-core statusClass anchor missing')
    s=s.replace(anchor,anchor+helpers,1)
old_panel='<div class="panel next-action-panel"><h2 class="section-title">Next required action</h2><div class="notice">${esc(current.job.NEXT_REQUIRED_ACTION||\'No next action recorded.\')}</div><div class="button-row overview-actions"><button class="primary" data-stage="${currentStage}">Continue current stage</button></div></div>'
if old_panel in s:
    s=s.replace(old_panel,'${nextActionMarkup(true)}',1)
elif '${nextActionMarkup(true)}' not in s:
    raise SystemExit('overview next-action panel anchor missing')
p.write_text(s)
