import fs from 'node:fs';
import crypto from 'node:crypto';
const must=(x,m)=>{if(!x)throw new Error(m)};
const human=fs.readFileSync('human-ui.js','utf8');
const loader=fs.readFileSync('workbook.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const test=JSON.parse(fs.readFileSync('TEST_PROJECT.json','utf8'));
const stages=[
'Initialize the Job','Build the Source Inventory','Research the Requirements','Compile the Requirement Specification','Resolve the Requirement Set','Build the Verification Suite Before Writing the Production Instruction','Build Failure Tests','Author the Production Instruction','Preflight the Production Instruction','Freeze the Test Candidate','Run Ten Independent Executions','Verify Each Execution Independently','Compare the Ten Executions','Root-Cause Every Defect','Convert Every Confirmed Failure into a Regression Test','Revise the Responsible Layer','Re-run the Complete Ten-Execution Iteration','Continue Until Convergence','Run an Unchanged Confirmation Iteration','Freeze the Production Baseline','Generate the Finished Product','Run Deterministic Verification on the Finished Product','Run Independent Semantic Verification','Run Adversarial Verification','Inspect the Final Representation','Reconcile Process and Product Evidence','Apply the Release Gate','Verify Artifact Identity Before Release','Preserve the Complete Evidence Chain','Preserve Failures Permanently'];
must(test.schema==='human-project/30','retained project must use human-project/30');
must(test.currentStage===30,'retained real project must reach Stage 30');
must(Object.keys(test.stageStates||{}).length===30,'exactly 30 stage states required');
must(stages.every(s=>human.includes(s)),'human UI must contain exact 30 stage names');
must(!/human-project\/31/.test(human),'31-operation schema must not be active');
must(!/Release Exact Accepted Artifact/.test(human),'extra release operation must not exist');
must(!/Freeze New Version/.test(human),'Freeze New Version must not be a separate stage');
must(/Reconcile Process and Product Evidence/.test(human),'Stage 26 reconciliation must exist');
must(/Preserve Failures Permanently/.test(human),'Stage 30 must exist');
must(!/Current agent work|agent-fab|agent-now/.test(human),'persistent agent controls must not dominate project UI');
must(/downstreamBlocked/.test(human)&&/completion gate/.test(human),'blockers and completion gates must be enforced');
must(/validateImport/.test(human)&&/Duplicate REQ_ID/.test(human),'project imports must be schema/identity validated');
must(/crypto\.subtle\.digest\('SHA-256'/.test(human),'file SHA-256 calculation must exist');
must(/allReleaseHashesEqualAuditedHashes/.test(human),'artifact identity gate must be enforced');
must(/permanentRegistry/.test(human),'Stage 30 permanent registry must be represented');
must(test.userJobInput?.objective?.includes('generator GEN-042'),'retained project must be a real generator handoff job, not app conformance');
must(!/application conformance|Evaluate the Closed-Loop Reliability application/i.test(JSON.stringify(test)),'retained project must not self-evaluate the application');
must(test.sourceInventory?.length>=3,'test project needs real source inventory');
must(test.requirements?.length>=10&&test.tests?.length===test.requirements.length,'test project needs atomic requirements and coverage');
must(test.mutations?.every(m=>m.validatorRun&&m.actualResponse&&m.evidence),'mutation tests require actual validator evidence');
const initial=test.runRecords.filter(r=>r.iterationId==='ITERATION-001');
const rerun=test.runRecords.filter(r=>r.iterationId==='ITERATION-002');
must(initial.length===10&&rerun.length===10,'test project requires two genuine ten-run iterations');
must(initial.every(r=>r.freshContextCreated&&r.otherRunOutputVisible===false&&r.contaminationFound===false),'initial runs require isolation records');
must(rerun.every(r=>r.freshContextCreated&&r.otherRunOutputVisible===false&&r.contaminationFound===false),'reruns require isolation records');
must(test.verificationRecords?.length===test.requirements.length*20,'both ten-run verification matrices must be preserved');
must(test.defects?.some(d=>d.defectId==='DEFECT-001')&&test.rootCauseRecords?.some(r=>r.defectId==='DEFECT-001'),'defect and root cause must be preserved');
must(test.regressions?.some(r=>r.originalDefectId==='DEFECT-001'&&r.preCorrectionResult&&r.postCorrectionResult),'regression needs pre/post evidence');
must(test.convergence?.allConditionsSimultaneouslyTrue===true,'convergence must be based on all conditions');
must(test.confirmation?.zeroChange===true&&test.confirmation?.runsCompleted===10,'unchanged confirmation must be recorded');
must(test.baseline?.immutable===true,'production baseline must be immutable');
must(test.product?.files?.length===1,'finished product file required');
const pf=test.product.files[0];
must(/^[a-f0-9]{64}$/.test(pf.sha256),'product SHA-256 must be valid');
must(crypto.createHash('sha256').update(pf.content).digest('hex')===pf.sha256,'product content hash must match');
must(test.deterministicResults?.every(r=>r.determination==='SATISFIED'),'deterministic product tests must succeed');
must(test.semanticResults?.every(r=>r.evaluatorIndependentFromGenerator===true&&r.determination==='SATISFIED'),'independent semantic verification required');
must(test.representation?.finalDetermination==='SATISFIED','representation inspection required');
must(test.reconciliation?.processCorrectness==='SATISFIED'&&test.reconciliation?.productCorrectness==='SATISFIED'&&test.reconciliation?.reconciledDetermination==='SATISFIED','Stage 26 must reconcile separate process/product results');
must(test.releaseGate?.state==='ACCEPTED','release gate must be accepted only after prerequisites');
must(test.artifactIdentity?.allReleaseHashesEqualAuditedHashes===true,'release bytes must match audited bytes');
must(test.evidenceChains?.length===test.requirements.length&&test.evidenceChains.every(c=>c.allRequiredChainLinksPresent===true),'one complete evidence chain per mandatory requirement');
must(test.permanentRegistry?.appendOnly===true&&test.permanentRegistry?.baselineExecutions?.every(x=>x.baselineApprovalBlockedByRegression===false),'permanent regression registry required');
must(test.generatedPrompts?.length===30&&test.outputReceipts?.length===30,'generated instructions and output receipts must remain inspectable for every stage');
must(index.match(/<html/gi)?.length===1,'one application entry point required');
must(!index.includes('agent-workflow.js'),'obsolete parallel agent UI must not be loaded');
must(loader.includes('real-generator-handoff-30-stage'),'loader must invalidate old retained project revision');
console.log('repository verification: exact 30-stage architecture, real test project, gates, isolation, evidence, release identity, and permanent registry established');
