import fs from 'node:fs';import vm from 'node:vm';
class MemoryStorage{constructor(seed={}){this.map=new Map(Object.entries(seed));this.failPrimary=false;}getItem(k){return this.map.has(k)?this.map.get(k):null;}setItem(k,v){if(this.failPrimary&&k==='closed-loop-reliability-projects-v3')throw new Error('quota injected');this.map.set(k,String(v));}removeItem(k){this.map.delete(k)}}
const ctx={console,Event:class Event{constructor(type){this.type=type}},dispatchEvent(){}};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('project-store.js','utf8'),ctx);const store=ctx.closedLoopStore;
const stages=Object.fromEntries(Array.from({length:30},(_,i)=>[i+1,{status:i===0?'COMPLETE':'NOT STARTED'}]));
const retained={schema:'x',job:{JOB_ID:'JOB-20260823144121',JOB_TITLE:'Mobile Closed-Loop Agent Reliability Workbook'},stages,retainedSpecRevision:'r1',unknownTop:{keep:true}};
const user={schema:'x',job:{JOB_ID:'JOB-USER-1',JOB_TITLE:'Legitimate user project'},stages,unknownTop:{preserve:'yes'},projectData:{customUnknown:{nested:42}}};
const legacy=new MemoryStorage({'closed-loop-reliability-projects-v2':JSON.stringify([user])});let loaded=store.readAll(legacy);if(loaded.length!==1||loaded[0].job.JOB_ID!=='JOB-USER-1'||loaded[0].projectData.customUnknown.nested!==42)throw Error('Legacy migration read lost legitimate project data');
let reconciled=store.reconcileRetained(loaded,retained);if(reconciled.length!==2||reconciled.filter(x=>x.job.JOB_ID==='JOB-20260823144121').length!==1)throw Error('Retained reconciliation failed');store.writeAll(reconciled,{storage:legacy,skipNavigationOnly:false});let round=store.readAll(legacy);if(round.length!==2||round.find(x=>x.job.JOB_ID==='JOB-USER-1')?.unknownTop?.preserve!=='yes')throw Error('Unknown fields lost on round trip');
const before=legacy.getItem(store.PRIMARY_KEY);legacy.failPrimary=true;let failed=false;try{store.writeAll([...reconciled,{job:{JOB_ID:'JOB-USER-2'},stages}],{storage:legacy,skipNavigationOnly:false})}catch(e){failed=/without committing canonical changes/.test(String(e.message))}if(!failed)throw Error('Injected storage failure was not rejected');if(legacy.getItem(store.PRIMARY_KEY)!==before)throw Error('Storage failure changed canonical project bytes');legacy.failPrimary=false;
let dup=false;try{store.writeAll([user,user],{storage:legacy})}catch{dup=true}if(!dup)throw Error('Duplicate JOB_ID was accepted');let malformed=false;try{store.validateImport({job:{JOB_ID:'BAD'},stages:{1:{}}},'x')}catch{malformed=true}if(!malformed)throw Error('Malformed import accepted');
const exportBytes=JSON.stringify(user,null,2),imported=store.validateImport(JSON.parse(exportBytes),'x');if(JSON.stringify(imported)!==JSON.stringify(user))throw Error('Import/export model round trip lost fields');
const navA=JSON.stringify([{...user,activeView:'Overview',activeStage:1}]),navB=JSON.stringify([{...user,activeView:'Records',activeStage:22}]);if(!store.navigationOnlyChange(navA,navB))throw Error('Navigation-only changes not recognized');
console.log(JSON.stringify({legacyMigration:true,legitimateProjectsPreserved:true,retainedNoDuplicate:true,unknownFieldsRoundTrip:true,atomicStorageFailure:true,malformedImportRejected:true,duplicateJobRejected:true,navigationWriteSuppression:true},null,2));
