import fs from 'node:fs';import vm from 'node:vm';globalThis.Event=globalThis.Event||class Event{constructor(type){this.type=type;}};globalThis.dispatchEvent=globalThis.dispatchEvent||(()=>true);
for(const file of ['workbook.js','hash.js','workflow-schema.js','test-runtime.js','workflow-engine.js','prompt-engine.js','response-ingestion.js','project-store.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});
const core=globalThis.closedLoopCore,schema=globalThis.closedLoopWorkflowSchema,runtime=globalThis.closedLoopTestRuntime,engine=globalThis.closedLoopWorkflowEngine,prompts=globalThis.closedLoopPromptEngine;const assert=(v,m)=>{if(!v)throw new Error(m);};
assert(core.PROJECT_SCHEMA==='closed-loop-project/3','Project schema is not /3.');assert(schema.RESPONSE_SCHEMA==='closed-loop-stage-response/3','Response schema is not /3.');assert(runtime.SPEC_VERSION==='closed-loop-test-spec/1','Test IR schema mismatch.');assert(core.STAGES.length===30&&core.WORKFLOW_ID==='mobile-closed-loop/30','Workflow identity/stage count changed.');assert(core.STAGES[15].title==='CORRECT THE ROOT CAUSE','Stage 16 visible title is wrong.');
const migrated=core.migrateState({...core.createBlankState('JOB-MIGRATE-V2'),schema:'closed-loop-project/2'});assert(migrated.schema===core.PROJECT_SCHEMA,'/2 -> /3 migration failed.');assert(migrated.projectData.migrationArchives.some(x=>x.schema==='closed-loop-project/2'),'/2 source payload not preserved.');
for(const op of ['LOAD_ARTIFACT','READ_BYTES','DECODE_UTF8','PARSE_JSON','PARSE_CSV','PARSE_XML','SELECT_JSON_PATH','SELECT_XML','COUNT','SUM','MIN','MAX','SORT','UNIQUE','HASH_SHA256','REGEX','COMPARE','ASSERT_EQ','ASSERT_GT','ASSERT_GTE','ASSERT_LT','ASSERT_LTE','ASSERT_MATCH','ASSERT_CONTAINS','ASSERT_NOT_CONTAINS','ASSERT_SET_EQUAL','BYTE_COMPARE'])assert(runtime.OPS.includes(op),'Missing Test IR op '+op);assert(!runtime.OPS.includes('CUSTOM_PIPELINE'),'CUSTOM_PIPELINE survived as runtime language.');
const html=fs.readFileSync('index.html','utf8');assert(html.includes("worker-src 'self'"),'Worker CSP missing.');const scripts=[...html.matchAll(/<script defer src="([^"]+)"/g)].map(m=>m[1].split('?')[0]);assert(JSON.stringify(scripts)===JSON.stringify(['workbook.js','hash.js','workflow-schema.js','test-runtime.js','workflow-engine.js','prompt-engine.js','response-ingestion.js','project-store.js','app-core.js']),'Runtime dependency order wrong.');assert(!/max-height:88px/.test(html),'Unauthorized prompt-box size override returned.');assert(/.expandable-prompt{max-height:280px}/.test(html),'Established prompt preview size was not preserved.');
const p=core.createBlankState('JOB-SPEC-V3');p.job.EXACT_USER_OBJECTIVE_VERBATIM='Build the requested project exactly from the supplied requirements.';p.job.EXPLICIT_USER_REQUIREMENTS='Never ask me twice for project information I already supplied. Preserve it and reuse it in later stages.';engine.ensureShape(p);engine.recalculate(p);const intake=engine.currentIntakeCoverageManifest(p);assert(intake.entries.length>=2&&intake.entries.every(x=>x.inputUnitId&&x.rawValueSha256),'Intake manifest does not enumerate human input.');
const stage1=prompts.buildPromptRecord(1,p).prompt;let stage4Blocked=false;try{prompts.buildPromptRecord(4,p);}catch(error){stage4Blocked=error?.code==='STAGE04_PREREQUISITES_INCOMPLETE';}assert(stage4Blocked,'Stage 04 prompt was generated from incomplete Stage 01/03 state.');assert(stage1.includes('EXECUTION DIRECTIVE — DO THIS NOW'),'Stage prompt lacks executable directive.');assert(stage1.includes('APPLICATION-ENUMERATED INTAKE COVERAGE MANIFEST'),'Stage 01 manifest absent.');assert(stage1.includes('INTAKE_EXHAUSTION'),'Stage 01 human-intent exhaustion proof is absent.');assert(prompts.procedures[4].includes('Do not ask the human to attach, resend, retype, or summarize'),'Stage 04 repeat-input prohibition absent.');for(const forbidden of ['PATENT / REGULATED FILING','SOFTWARE / MULTI-FILE SYSTEM','BUILDING / ARCHITECTURE / AEC','PHYSICAL / MECHANICAL / CAD / CAM / CNC / ADDITIVE'])assert(!stage1.includes(forbidden),'Hard-coded subject branch remains: '+forbidden);
const stage6=prompts.buildPromptRecord(6,p).prompt;assert(stage6.includes('Operation argument contracts:')&&stage6.includes('Runtime authoring limits:'),'Stage 06 does not publish Test IR contracts/limits.');assert(stage6.includes('EXECUTABLE_KIND = TEST_IR'),'Stage 06 still names the wrong executable kind.');
const badIntake=engine.validateIntakeAccounting(p,JSON.stringify({entries:[]}));assert(!badIntake.valid,'Incomplete intake accounting was accepted.');const completeIntake=engine.validateIntakeAccounting(p,JSON.stringify({entries:intake.entries.map(x=>({inputUnitId:x.inputUnitId,disposition:'INCORPORATED',reason:''}))}));assert(completeIntake.valid,'Complete intake accounting was rejected.');
assert(runtime.validateSpec({version:runtime.SPEC_VERSION,steps:[{op:'NOPE'}]},{}).valid===false,'Unknown Test IR operation accepted.');assert(runtime.validateSpec({version:runtime.SPEC_VERSION,steps:[{op:'PARSE_CSV'}]},{}).valid===false,'Ambiguous CSV defaults accepted.');assert(runtime.validateSpec({version:runtime.SPEC_VERSION,steps:[{op:'ASSERT_EQ',value:0.1}]},{}).valid===false,'Precision-sensitive float equality accepted without tolerance.');

assert(schema.JOB_FIELDS.JOB_TITLE.producer===schema.PRODUCER.HUMAN_DECISION&&schema.JOB_FIELDS.JOB_OWNER.producer===schema.PRODUCER.HUMAN_DECISION,'Job title/owner producer class is wrong.');
assert(schema.RECORD_SCHEMAS.tests.fieldDefinitions.EXECUTABLE_SPEC_VERSION.producer===schema.PRODUCER.APPLICATION,'Test IR version is not application-owned.');
const action=engine.operationalNextAction(p,4);assert(action&&typeof action==='object'&&action.actionType&&Object.prototype.hasOwnProperty.call(action,'canonicalStateChanged')&&Object.prototype.hasOwnProperty.call(action,'newPromptRequired'),'Next action is not a structured application object.');
const appSource=fs.readFileSync('app-core.js','utf8');assert(!appSource.includes("new Worker('test-worker.js')"),'app-core still duplicates Test IR worker coordination.');assert(appSource.includes("'closed-loop-project/2'"),'UI import boundary does not accept /2 for deterministic migration.');const storeSource=fs.readFileSync('project-store.js','utf8');assert(storeSource.includes("project?.schema!=='closed-loop-project/3'"),'Complete package import still rejects current /3 project schema.');
console.log(JSON.stringify({projectSchema:core.PROJECT_SCHEMA,responseSchema:schema.RESPONSE_SCHEMA,testIrSchema:runtime.SPEC_VERSION,stageCount:core.STAGES.length,intakeCoverage:1,subjectNeutralPrompt:true,stage04ObligationManifest:true,promptDirective:true,promptPreviewPreserved:true}));
