(async()=>{
  const CONTROL_KEY='closed-loop-workbook-operational-controls';
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const now=()=>new Date().toISOString();
  const id=(p,rows)=>`${p}-${String((rows?.length||0)+1).padStart(3,'0')}`;
  const blankControls=()=>({
    A:[],B:[],C:[],D:[],E:[],F:[],
    meta:{updatedAt:now()}
  });
  const loadControls=()=>{try{return {...blankControls(),...JSON.parse(localStorage.getItem(CONTROL_KEY)||'{}')}}catch{return blankControls()}};
  let controls=loadControls();
  const saveControls=()=>{controls.meta={...(controls.meta||{}),updatedAt:now()};localStorage.setItem(CONTROL_KEY,JSON.stringify(controls))};
  const field=(label,name,value='',type='text',options=[])=>`<label>${esc(label)}</label>${type==='textarea'?`<textarea data-f=\"${esc(name)}\">${esc(value)}</textarea>`:type==='select'?`<select data-f=\"${esc(name)}\">${options.map(o=>`<option${o===value?' selected':''}>${esc(o)}</option>`).join('')}</select>`:`<input data-f=\"${esc(name)}\" type=\"${type}\" value=\"${esc(value)}\">`}`;
  const boolField=(label,name,value='UNKNOWN')=>field(label,name,value,'select',['TRUE','FALSE','UNKNOWN']);
  const readForm=box=>Object.fromEntries([...box.querySelectorAll('[data-f]')].map(el=>[el.dataset.f,el.value]));
  const recordCard=(title,r,lines=[])=>`<div class=\"card\"><h3>${esc(title)}</h3>${lines.map(([k,l])=>`<div><b>${esc(l||k)}:</b> ${esc(r[k]||'')}</div>`).join('')}</div>`;
  const records=(key,title,lines)=>controls[key].length?controls[key].map(r=>recordCard(`${title} — ${r.id||''}`,r,lines)).join(''):`<p class=\"muted\">No ${esc(title.toLowerCase())} records yet.</p>`;
  function addRecord(key,prefix,data){data.id=data.id||id(prefix,controls[key]);data.createdAt=data.createdAt||now();controls[key].push(data);saveControls();renderControls(key)}
  function openBlockers(){return controls.B.filter(r=>r.CURRENT_STATUS==='OPEN').length}
  function unresolvedChanges(){return controls.C.filter(r=>r.CHANGE_STATUS!=='CLOSED_REVALIDATED').length}
  function renderControls(active='A'){
    if(globalThis.view!=='control')return;
    nav.innerHTML=['A','B','C','D','E','F'].map(k=>`<button class=\"${k===active?'active':''}\" onclick=\"renderOperationalControl('${k}')\">Appendix ${k}</button>`).join('');
    const summary=`<div class=\"card\"><h2>Operational controls A–F</h2><p>These are reusable workflow mechanisms attached to the 30-stage workbook. They create and preserve records, stop or invalidate workflow when required, and support release identity. They are not six extra stages.</p><div><b>Open blockers:</b> ${openBlockers()} &nbsp; <b>Changes awaiting revalidation:</b> ${unresolvedChanges()}</div></div>`;
    content.innerHTML=summary+controlPanel(active);
  }
  function controlPanel(k){
    if(k==='A')return `<div class=\"card op\" data-op=\"A\"><h2>Appendix A — Fresh agent context launch control</h2><p class=\"muted\">Use whenever a stage requires a fresh execution, verification, semantic review, adversarial review, or confirmation context. A contaminated context is unusable and must be restarted under a new run record.</p>${field('JOB_ID','JOB_ID',job?.textContent?.replace('UNASSIGNED JOB','')||'')}${field('STAGE','STAGE')}${field('ROLE','ROLE')}${field('ITERATION_ID','ITERATION_ID')}${field('RUN_ID','RUN_ID')}${field('CONTEXT_ID','CONTEXT_ID')}${field('CONTEXT_NAME','CONTEXT_NAME')}${field('CONTEXT_START_DATE_AND_TIME','CONTEXT_START_DATE_AND_TIME',now())}${field('STAGE_COPY_BLOCK_VERSION_OR_HASH','STAGE_COPY_BLOCK_VERSION_OR_HASH')}${field('AUTHORIZED_FILES_AND_VERSIONS_ATTACHED','AUTHORIZED_FILES_AND_VERSIONS_ATTACHED','','textarea')}${field('FROZEN_INPUT_VERSION','FROZEN_INPUT_VERSION')}${field('FROZEN_SOURCE_SET_VERSION','FROZEN_SOURCE_SET_VERSION')}${field('FROZEN_REQUIREMENTS_VERSION','FROZEN_REQUIREMENTS_VERSION')}${field('FROZEN_INSTRUCTION_VERSION','FROZEN_INSTRUCTION_VERSION')}${field('FROZEN_TEST_SUITE_VERSION','FROZEN_TEST_SUITE_VERSION')}${field('FROZEN_TOOL_CONFIGURATION_VERSION','FROZEN_TOOL_CONFIGURATION_VERSION')}${boolField('OTHER_RUN_OUTPUT_VISIBLE','OTHER_RUN_OUTPUT_VISIBLE')}${boolField('REVIEWER_COMMENT_VISIBLE','REVIEWER_COMMENT_VISIBLE')}${boolField('PRIOR_FAILURE_EXPLANATION_VISIBLE','PRIOR_FAILURE_EXPLANATION_VISIBLE')}${boolField('PROPOSED_CORRECTION_VISIBLE','PROPOSED_CORRECTION_VISIBLE')}${boolField('REQUIRED_TOOLS_AVAILABLE','REQUIRED_TOOLS_AVAILABLE')}${field('EXECUTION_DEVIATIONS','EXECUTION_DEVIATIONS','','textarea')}${field('OUTPUT_ID','OUTPUT_ID')}${field('OUTPUT_FILENAME','OUTPUT_FILENAME')}${field('OUTPUT_VERSION','OUTPUT_VERSION')}${field('OUTPUT_SHA256','OUTPUT_SHA256')}${boolField('CONTEXT_CONTAMINATED','CONTEXT_CONTAMINATED')}${field('DEFECT_ID','DEFECT_ID')}${boolField('RUN_USABLE','RUN_USABLE')}${field('CONTROLLING_EVIDENCE','CONTROLLING_EVIDENCE','','textarea')}<div class=\"tools\"><button class=\"primary\" onclick=\"saveOperationalRecord('A')\">Save launch record</button></div></div>${records('A','Fresh-context launch',[['STAGE'],['ROLE'],['ITERATION_ID'],['RUN_ID'],['CONTEXT_ID'],['CONTEXT_CONTAMINATED'],['RUN_USABLE'],['DEFECT_ID']])}`;
    if(k==='B')return `<div class=\"card op\" data-op=\"B\"><h2>Appendix B — Universal blocker mechanism</h2><p class=\"muted\">Create immediately when a mandatory fact cannot be established. OPEN blockers stop affected downstream work; UNKNOWN is never converted to TRUE.</p>${field('BLOCKER_ID','BLOCKER_ID',id('BLOCKER',controls.B))}${field('JOB_ID','JOB_ID',job?.textContent||'')}${field('DATE_OPENED','DATE_OPENED',now())}${field('CURRENT_STATUS','CURRENT_STATUS','OPEN','select',['OPEN','RESOLVED','SUPERSEDED'])}${field('STAGE_DISCOVERED','STAGE_DISCOVERED')}${field('AFFECTED_REQ_IDS','AFFECTED_REQ_IDS')}${field('AFFECTED_TEST_IDS','AFFECTED_TEST_IDS')}${field('AFFECTED_ARTIFACTS_AND_VERSIONS','AFFECTED_ARTIFACTS_AND_VERSIONS','','textarea')}${field('MISSING_ITEM_TYPE','MISSING_ITEM_TYPE','EVIDENCE','select',['EVIDENCE','AUTHORITY','INPUT','CAPABILITY','DECISION_RULE','OTHER'])}${field('MISSING_EVIDENCE_AUTHORITY_INPUT_OR_CAPABILITY','MISSING_EVIDENCE_AUTHORITY_INPUT_OR_CAPABILITY','','textarea')}${field('WHY_MANDATORY_SATISFACTION_CANNOT_BE_ESTABLISHED','WHY_MANDATORY_SATISFACTION_CANNOT_BE_ESTABLISHED','','textarea')}${field('KNOWN_SOURCE_OR_OWNER_OF_MISSING_ITEM','KNOWN_SOURCE_OR_OWNER_OF_MISSING_ITEM','UNKNOWN')}${field('ATTEMPTS_TO_RESOLVE','ATTEMPTS_TO_RESOLVE','','textarea')}${field('AVAILABLE_RESOLUTION_PATH','AVAILABLE_RESOLUTION_PATH','UNKNOWN')}${field('DOWNSTREAM_WORK_STOPPED','DOWNSTREAM_WORK_STOPPED','','textarea')}${field('BLOCKER_OWNER','BLOCKER_OWNER')}${field('TARGET_RESOLUTION_DATE','TARGET_RESOLUTION_DATE','UNKNOWN')}${field('RESOLUTION','RESOLUTION','NOT RESOLVED','textarea')}${field('RESOLUTION_EVIDENCE','RESOLUTION_EVIDENCE','NOT RESOLVED','textarea')}${field('DATE_RESOLVED','DATE_RESOLVED','NOT RESOLVED')}${field('REQUIREMENTS_AND_TESTS_REEVALUATED','REQUIREMENTS_AND_TESTS_REEVALUATED','NOT RESOLVED')}${field('DOWNSTREAM_VALIDATION_RERUN','DOWNSTREAM_VALIDATION_RERUN','NOT RESOLVED')}${field('CLOSURE_AUTHORIZED_BY','CLOSURE_AUTHORIZED_BY','NOT RESOLVED')}<div class=\"tools\"><button class=\"primary\" onclick=\"saveOperationalRecord('B')\">Save blocker</button></div></div>${records('B','Blocker',[['BLOCKER_ID'],['CURRENT_STATUS'],['STAGE_DISCOVERED'],['AFFECTED_REQ_IDS'],['MISSING_ITEM_TYPE'],['DOWNSTREAM_WORK_STOPPED']])}`;
    if(k==='C')return `<div class=\"card op\" data-op=\"C\"><h2>Appendix C — Universal change and invalidation log</h2><p class=\"muted\">Append-only material-change record. Every changed artifact receives a new version and all affected downstream determinations are invalidated until revalidation is complete.</p>${field('CHANGE_ID','CHANGE_ID',id('CHANGE',controls.C))}${field('DATE_AND_TIME','DATE_AND_TIME',now())}${field('JOB_ID','JOB_ID',job?.textContent||'')}${field('ITERATION_ID','ITERATION_ID')}${field('TRIGGER','TRIGGER','USER CHANGE','select',['USER CHANGE','NEW SOURCE','DEFECT','BLOCKER RESOLUTION','TOOL CHANGE','TEST FAILURE','EXPORT CHANGE','OTHER'])}${field('EARLIEST_RESPONSIBLE_LAYER','EARLIEST_RESPONSIBLE_LAYER','REQUIREMENT','select',['SOURCE','RESEARCH','REQUIREMENT','TEST','INSTRUCTION','INPUT','EXECUTION','TOOL','AUDIT','PRODUCT','REPRESENTATION'])}${field('AFFECTED_ARTIFACT_ID','AFFECTED_ARTIFACT_ID')}${field('OLD_VERSION','OLD_VERSION')}${field('OLD_SHA256','OLD_SHA256')}${field('NEW_VERSION','NEW_VERSION')}${field('NEW_SHA256','NEW_SHA256')}${field('EXACT_CHANGE','EXACT_CHANGE','','textarea')}${field('REASON','REASON','','textarea')}${field('ROOT_CAUSE_ID_OR_AUTHORITY','ROOT_CAUSE_ID_OR_AUTHORITY')}${boolField('MATERIAL_CHANGE','MATERIAL_CHANGE')}${field('DOWNSTREAM_ARTIFACTS_INVALIDATED','DOWNSTREAM_ARTIFACTS_INVALIDATED','','textarea')}${field('DOWNSTREAM_DETERMINATIONS_INVALIDATED','DOWNSTREAM_DETERMINATIONS_INVALIDATED','','textarea')}${field('TESTS_TO_RERUN','TESTS_TO_RERUN','','textarea')}${field('ITERATIONS_TO_RERUN','ITERATIONS_TO_RERUN','','textarea')}${field('AUDITS_TO_RERUN','AUDITS_TO_RERUN','','textarea')}${boolField('RELEASE_GATE_MUST_BE_RERUN','RELEASE_GATE_MUST_BE_RERUN')}${boolField('HASH_IDENTITY_MUST_BE_RERUN','HASH_IDENTITY_MUST_BE_RERUN')}${field('AUTHORIZED_BY','AUTHORIZED_BY')}${field('CHANGE_IMPLEMENTED_BY','CHANGE_IMPLEMENTED_BY')}${field('IMPLEMENTATION_EVIDENCE','IMPLEMENTATION_EVIDENCE','','textarea')}${boolField('REVALIDATION_COMPLETE','REVALIDATION_COMPLETE')}${field('REVALIDATION_EVIDENCE','REVALIDATION_EVIDENCE','NOT COMPLETE','textarea')}${field('CHANGE_STATUS','CHANGE_STATUS','OPEN','select',['OPEN','IMPLEMENTED_NOT_REVALIDATED','CLOSED_REVALIDATED','BLOCKED'])}<div class=\"tools\"><button class=\"primary\" onclick=\"saveOperationalRecord('C')\">Append change record</button></div></div>${records('C','Change',[['CHANGE_ID'],['TRIGGER'],['EARLIEST_RESPONSIBLE_LAYER'],['AFFECTED_ARTIFACT_ID'],['OLD_VERSION'],['NEW_VERSION'],['CHANGE_STATUS']])}`;
    if(k==='D')return `<div class=\"card op\" data-op=\"D\"><h2>Appendix D — Exact final release control</h2><p class=\"muted\">Delivery is authorized only when Stage 27 is ACCEPTED and the exact files selected for delivery match the audited bytes. This record does not create a fourth release state.</p>${field('RELEASE_ID','RELEASE_ID',id('RELEASE',controls.D))}${field('JOB_ID','JOB_ID',job?.textContent||'')}${field('PRODUCT_ID','PRODUCT_ID')}${field('PRODUCT_VERSION','PRODUCT_VERSION')}${field('BASELINE_ID','BASELINE_ID')}${field('RELEASE_GATE_ID','RELEASE_GATE_ID')}${field('RELEASE_GATE_STATE','RELEASE_GATE_STATE','BLOCKED','select',['ACCEPTED','REJECTED','BLOCKED'])}${field('PROCESS_AUDIT_VERSION_AND_DETERMINATION','PROCESS_AUDIT_VERSION_AND_DETERMINATION')}${field('PRODUCT_AUDIT_VERSION_AND_DETERMINATION','PRODUCT_AUDIT_VERSION_AND_DETERMINATION')}${field('REPRESENTATION_AUDIT_VERSION_AND_DETERMINATION','REPRESENTATION_AUDIT_VERSION_AND_DETERMINATION')}${field('EVIDENCE_CHAIN_VERSION_AND_DETERMINATION','EVIDENCE_CHAIN_VERSION_AND_DETERMINATION')}${field('HASH_AUDIT_ID_AND_DETERMINATION','HASH_AUDIT_ID_AND_DETERMINATION')}${field('MANDATORY_REQUIREMENT_COVERAGE','MANDATORY_REQUIREMENT_COVERAGE')}${field('MANDATORY_VERIFICATION_COVERAGE','MANDATORY_VERIFICATION_COVERAGE')}${field('REGRESSION_TEST_SUCCESS','REGRESSION_TEST_SUCCESS')}${field('CRITICAL_DEFECTS','CRITICAL_DEFECTS','0','number')}${field('MAJOR_DEFECTS','MAJOR_DEFECTS','0','number')}${field('MANDATORY_UNRESOLVED_UNKNOWNS','MANDATORY_UNRESOLVED_UNKNOWNS','0','number')}${field('CORRECTNESS_AFFECTING_CONTRADICTIONS','CORRECTNESS_AFFECTING_CONTRADICTIONS','0','number')}${field('CORRECTNESS_AFFECTING_AMBIGUITIES','CORRECTNESS_AFFECTING_AMBIGUITIES','0','number')}${field('UNEXPLAINED_CORRECTNESS_AFFECTING_VARIANCE','UNEXPLAINED_CORRECTNESS_AFFECTING_VARIANCE','0','number')}${field('ARTIFACT_ID','ARTIFACT_ID')}${field('EXACT_FILENAME','EXACT_FILENAME')}${field('FILE_SIZE_BYTES','FILE_SIZE_BYTES','0','number')}${field('AUDITED_SHA256','AUDITED_SHA256')}${field('RELEASE_SHA256','RELEASE_SHA256')}${boolField('HASHES_IDENTICAL','HASHES_IDENTICAL')}${field('DELIVERY_LOCATION_OR_METHOD','DELIVERY_LOCATION_OR_METHOD')}${field('DELIVERY_DATE_AND_TIME','DELIVERY_DATE_AND_TIME')}${boolField('DELIVERY_CONFIRMED','DELIVERY_CONFIRMED')}${field('RELEASE_EVIDENCE_REPOSITORY','RELEASE_EVIDENCE_REPOSITORY')}${field('RELEASE_AUTHORIZED_BY','RELEASE_AUTHORIZED_BY')}${field('AUTHORIZATION_DATE_AND_TIME','AUTHORIZATION_DATE_AND_TIME')}${field('FINAL_RELEASE_STATUS','FINAL_RELEASE_STATUS','NOT RELEASED','select',['RELEASED','NOT RELEASED'])}${field('CONTROLLING_EVIDENCE','CONTROLLING_EVIDENCE','','textarea')}<div class=\"tools\"><button class=\"primary\" onclick=\"saveOperationalRecord('D')\">Save final release record</button></div></div>${records('D','Final release',[['RELEASE_ID'],['PRODUCT_ID'],['PRODUCT_VERSION'],['RELEASE_GATE_STATE'],['EXACT_FILENAME'],['HASHES_IDENTICAL'],['FINAL_RELEASE_STATUS']])}`;
    if(k==='E')return `<div class=\"card op\" data-op=\"E\"><h2>Appendix E — New-job reset control</h2><p class=\"muted\">A different job starts from a clean copy at Stage 01. Old baseline and release decisions do not carry forward automatically. This control resets the existing application state; it does not create a second app.</p>${field('NEW_JOB_ID','NEW_JOB_ID')}${field('NEW_JOB_TITLE','NEW_JOB_TITLE')}${field('JOB_OWNER','JOB_OWNER')}${field('DATE_OPENED','DATE_OPENED',now())}${field('MASTER_TEMPLATE_VERSION','MASTER_TEMPLATE_VERSION')}${field('MASTER_TEMPLATE_SHA256','MASTER_TEMPLATE_SHA256')}${field('NEW_WORKBOOK_FILENAME','NEW_WORKBOOK_FILENAME')}${field('NEW_WORKBOOK_VERSION','NEW_WORKBOOK_VERSION','v001')}${field('NEW_FOLDER_ROOT','NEW_FOLDER_ROOT')}${field('SUPPLIED_INPUT_FILES','SUPPLIED_INPUT_FILES','','textarea')}${field('SUPPLIED_INPUT_HASHES','SUPPLIED_INPUT_HASHES','','textarea')}${boolField('EXACT_USER_REQUEST_CAPTURED_IN_STAGE_01','EXACT_USER_REQUEST_CAPTURED_IN_STAGE_01')}${boolField('OLD_JOB_MATERIAL_REUSED','OLD_JOB_MATERIAL_REUSED')}${field('AUTHORITY_FOR_REUSE','AUTHORITY_FOR_REUSE','NONE')}${boolField('APPLICABILITY_REESTABLISHED_FOR_NEW_JOB','APPLICABILITY_REESTABLISHED_FOR_NEW_JOB')}${field('OLD_BASELINE_STATUS_CARRIED_FORWARD','OLD_BASELINE_STATUS_CARRIED_FORWARD','FALSE')}${field('OLD_RELEASE_DECISION_CARRIED_FORWARD','OLD_RELEASE_DECISION_CARRIED_FORWARD','FALSE')}${boolField('OLD_REQUIREMENT_OR_TEST_CARRIED_FORWARD_WITHOUT_REVALIDATION','OLD_REQUIREMENT_OR_TEST_CARRIED_FORWARD_WITHOUT_REVALIDATION')}${field('NEW_JOB_START_STAGE','NEW_JOB_START_STAGE','STAGE 01')}${field('RESET_COMPLETED_BY','RESET_COMPLETED_BY')}${field('RESET_DATE_AND_TIME','RESET_DATE_AND_TIME',now())}${field('RESET_EVIDENCE','RESET_EVIDENCE','','textarea')}<div class=\"tools\"><button class=\"primary\" onclick=\"executeNewJobReset()\">Reset existing app for this new job</button></div></div>${records('E','New-job initialization',[['NEW_JOB_ID'],['NEW_JOB_TITLE'],['NEW_JOB_START_STAGE'],['RESET_COMPLETED_BY'],['RESET_DATE_AND_TIME']])}`;
    return `<div class=\"card op\" data-op=\"F\"><h2>Appendix F — Universal agent-output receipt</h2><p class=\"muted\">Complete immediately after every agent response or generated artifact. Agent completion is not independent completion; every output is routed to the required verification stage.</p>${field('RECEIPT_ID','RECEIPT_ID',id('RECEIPT',controls.F))}${field('JOB_ID','JOB_ID',job?.textContent||'')}${field('STAGE','STAGE')}${field('AGENT_ROLE','AGENT_ROLE')}${field('AGENT_OR_SYSTEM_IDENTIFIER','AGENT_OR_SYSTEM_IDENTIFIER')}${field('CONTEXT_ID','CONTEXT_ID')}${field('ITERATION_ID','ITERATION_ID')}${field('RUN_ID','RUN_ID')}${field('REQUEST_DATE_AND_TIME','REQUEST_DATE_AND_TIME')}${field('RESPONSE_DATE_AND_TIME','RESPONSE_DATE_AND_TIME',now())}${field('COPY_BLOCK_VERSION_OR_HASH','COPY_BLOCK_VERSION_OR_HASH')}${field('INPUT_VERSIONS','INPUT_VERSIONS','','textarea')}${field('SOURCE_SET_VERSION','SOURCE_SET_VERSION')}${field('REQUIREMENTS_VERSION','REQUIREMENTS_VERSION')}${field('INSTRUCTION_VERSION','INSTRUCTION_VERSION')}${field('TEST_SUITE_VERSION','TEST_SUITE_VERSION')}${field('TOOL_CONFIGURATION_VERSION','TOOL_CONFIGURATION_VERSION')}${field('OUTPUT_ARTIFACT_ID','OUTPUT_ARTIFACT_ID')}${field('OUTPUT_VERSION','OUTPUT_VERSION')}${field('OUTPUT_FILES','OUTPUT_FILES','','textarea')}${field('OUTPUT_HASHES','OUTPUT_HASHES','','textarea')}${boolField('COMPLETE_RESPONSE_SAVED','COMPLETE_RESPONSE_SAVED')}${boolField('AGENT_CLAIMED_COMPLETION','AGENT_CLAIMED_COMPLETION')}${boolField('INDEPENDENT_COMPLETION_ESTABLISHED','INDEPENDENT_COMPLETION_ESTABLISHED')}${boolField('TRUNCATION_DETECTED','TRUNCATION_DETECTED')}${boolField('REFUSAL_OR_PARTIAL_REFUSAL','REFUSAL_OR_PARTIAL_REFUSAL')}${field('TOOL_FAILURES','TOOL_FAILURES','NONE','textarea')}${field('MISSING_OR_UNREADABLE_ATTACHMENTS','MISSING_OR_UNREADABLE_ATTACHMENTS','NONE','textarea')}${field('MALFORMED_OUTPUT_FILES','MALFORMED_OUTPUT_FILES','NONE','textarea')}${field('OTHER_DEVIATIONS','OTHER_DEVIATIONS','NONE','textarea')}${field('DEFECT_IDS','DEFECT_IDS','NONE')}${field('BLOCKER_IDS','BLOCKER_IDS','NONE')}${field('NEXT_REQUIRED_VERIFICATION_STAGE','NEXT_REQUIRED_VERIFICATION_STAGE')}${field('RECEIPT_COMPLETED_BY','RECEIPT_COMPLETED_BY')}${field('RECEIPT_EVIDENCE','RECEIPT_EVIDENCE','','textarea')}<div class=\"tools\"><button class=\"primary\" onclick=\"saveOperationalRecord('F')\">Save output receipt</button></div></div>${records('F','Agent-output receipt',[['RECEIPT_ID'],['STAGE'],['AGENT_ROLE'],['OUTPUT_ARTIFACT_ID'],['INDEPENDENT_COMPLETION_ESTABLISHED'],['NEXT_REQUIRED_VERIFICATION_STAGE']])}`;
  }
  globalThis.renderOperationalControl=k=>renderControls(k);
  globalThis.saveOperationalRecord=k=>{const box=document.querySelector(`[data-op=\"${k}\"]`);if(!box)return;const data=readForm(box);if(k==='A'){
      const contaminated=['OTHER_RUN_OUTPUT_VISIBLE','REVIEWER_COMMENT_VISIBLE','PRIOR_FAILURE_EXPLANATION_VISIBLE','PROPOSED_CORRECTION_VISIBLE','CONTEXT_CONTAMINATED'].some(x=>data[x]==='TRUE');
      if(contaminated)data.RUN_USABLE='FALSE';
    }
    if(k==='B'&&data.CURRENT_STATUS==='OPEN'&&!data.DOWNSTREAM_WORK_STOPPED.trim())data.DOWNSTREAM_WORK_STOPPED='REQUIRED — affected downstream work is blocked until resolution evidence exists.';
    if(k==='C'&&data.MATERIAL_CHANGE==='TRUE'&&data.CHANGE_STATUS==='CLOSED_REVALIDATED'&&data.REVALIDATION_COMPLETE!=='TRUE')data.CHANGE_STATUS='IMPLEMENTED_NOT_REVALIDATED';
    if(k==='D'){
      const hashes=data.AUDITED_SHA256&&data.RELEASE_SHA256&&data.AUDITED_SHA256===data.RELEASE_SHA256;
      data.HASHES_IDENTICAL=hashes?'TRUE':'FALSE';
      const zero=['CRITICAL_DEFECTS','MAJOR_DEFECTS','MANDATORY_UNRESOLVED_UNKNOWNS','CORRECTNESS_AFFECTING_CONTRADICTIONS','CORRECTNESS_AFFECTING_AMBIGUITIES','UNEXPLAINED_CORRECTNESS_AFFECTING_VARIANCE'].every(x=>Number(data[x])===0);
      const authorize=data.RELEASE_GATE_STATE==='ACCEPTED'&&hashes&&zero;
      if(!authorize)data.FINAL_RELEASE_STATUS='NOT RELEASED';
    }
    addRecord(k,{A:'CONTEXT',B:'BLOCKER',C:'CHANGE',D:'RELEASE',F:'RECEIPT'}[k]||k,data)
  };
  globalThis.executeNewJobReset=()=>{const box=document.querySelector('[data-op=\"E\"]');if(!box)return;const data=readForm(box);if(!data.NEW_JOB_ID.trim()){alert('NEW_JOB_ID is required.');return}data.OLD_BASELINE_STATUS_CARRIED_FORWARD='FALSE';data.OLD_RELEASE_DECISION_CARRIED_FORWARD='FALSE';data.NEW_JOB_START_STAGE='STAGE 01';data.RESET_DATE_AND_TIME=now();controls=blankControls();controls.E.push({...data,id:id('RESET',controls.E),createdAt:now()});saveControls();if(typeof originalNewJob==='function')originalNewJob();setTimeout(()=>{try{if(globalThis.job)globalThis.job.textContent=data.NEW_JOB_ID}catch{};globalThis.view='control';renderControls('E')},0)};
  let originalRender,originalNewJob;
  try{
    if(typeof DecompressionStream!=="function")throw new Error("This browser does not support the required gzip decompression API.");
    const names=["workbook.module.gz.1","workbook.module.gz.2","workbook.module.gz.3"];
    const responses=await Promise.all(names.map(name=>fetch(name,{cache:"no-store"})));
    for(const response of responses)if(!response.ok)throw new Error(`Runtime load failed: HTTP ${response.status}`);
    const parts=await Promise.all(responses.map(response=>response.arrayBuffer()));
    const total=parts.reduce((n,part)=>n+part.byteLength,0),bytes=new Uint8Array(total);
    let offset=0;for(const part of parts){bytes.set(new Uint8Array(part),offset);offset+=part.byteLength;}
    const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));
    const source=await new Response(stream).text();
    const url=URL.createObjectURL(new Blob([source],{type:"text/javascript"}));
    try{await import(url);}finally{URL.revokeObjectURL(url);}
    originalRender=globalThis.render;
    originalNewJob=globalThis.newJob;
    globalThis.render=function(){if(globalThis.view==='control')return renderControls('A');return originalRender?.apply(this,arguments)};
    if(globalThis.view==='control')renderControls('A');
  }catch(error){
    console.error(error);
    const target=document.getElementById("content");
    if(target)target.textContent=`Application runtime failed to load: ${error.message}`;
  }
})();