(async()=>{
  try{
    if(typeof DecompressionStream!=="function")throw new Error("This browser does not support the required gzip decompression API.");
    const cacheKey="single-workbook-restored-test-project-3";
    const names=["workbook.module.gz.1","workbook.module.gz.2","workbook.module.gz.3"];
    const responses=await Promise.all(names.map(name=>fetch(`${name}?${cacheKey}`,{cache:"no-store"})));
    for(const response of responses)if(!response.ok)throw new Error(`Runtime load failed: HTTP ${response.status}`);
    const parts=await Promise.all(responses.map(response=>response.arrayBuffer()));
    const total=parts.reduce((sum,part)=>sum+part.byteLength,0),bytes=new Uint8Array(total);let offset=0;
    for(const part of parts){bytes.set(new Uint8Array(part),offset);offset+=part.byteLength;}
    const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));
    const source=await new Response(stream).text();const url=URL.createObjectURL(new Blob([source],{type:"text/javascript"}));
    try{await import(url);}finally{URL.revokeObjectURL(url);}
  }catch(error){console.error(error);const target=document.getElementById("content");if(target)target.textContent=`Application runtime failed to load: ${error.message}`;}
})();
(()=>{
"use strict";
const STORE="mclarw",STYLE_ID="workbook-restoration-style",PURPOSE_ID="appendix-operational-purpose",TEST_PROJECT_ID="repository-test-project";
const DEFINITIONS=[["A","Fresh agent context launch","Use whenever a stage requires a fresh execution, verification, semantic review, adversarial review, or confirmation context. Preserve the full launch record and contamination evidence."],["B","Universal blocker record","Use whenever a mandatory requirement cannot be established because evidence, authority, input, capability, or a decision rule is unavailable. Stop affected downstream work until resolved and revalidated."],["C","Universal change and invalidation log","Use one append-only record for every material modification. Preserve old/new identity, root cause or authority, downstream invalidation, and every required rerun."],["D","Exact final release checklist","Apply against the exact delivery files after the release gate and artifact-identity controls. Release only exact accepted, hash-matched artifacts with complete evidence."],["E","New-job reset checklist","Use before a different job. Create clean job state and prohibit silent inheritance of an old baseline, release decision, requirement, test, defect disposition, or job-specific evidence."],["F","Universal agent-output receipt","Complete immediately after every agent response or generated artifact. Preserve exact context, inputs, output identity, files, hashes, deviations, defects/blockers, and the next verification route."]];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORE)||"null")}catch{return null}};
const records=(s,l)=>Array.isArray(s?.operationalRecords?.[l])?s.operationalRecords[l]:Array.isArray(s?.appendices?.[l]?.records)?s.appendices[l].records:[];
const rid=r=>r?.id||r?.FRESH_CONTEXT_LAUNCH_RECORD_ID||r?.BLOCKER_ID||r?.CHANGE_ID||r?.RELEASE_ID||r?.NEW_JOB_INITIALIZATION_RECORD_ID||r?.RECEIPT_ID||"recorded";
function styles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`#${TEST_PROJECT_ID},#${PURPOSE_ID}{margin:10px 0}#${TEST_PROJECT_ID} summary,#${PURPOSE_ID} summary{cursor:pointer}#${TEST_PROJECT_ID} .row,#${PURPOSE_ID} .row{border-top:1px solid #ddd;padding:10px 0}#${TEST_PROJECT_ID} code{font:11px ui-monospace,monospace;overflow-wrap:anywhere}#${TEST_PROJECT_ID} .ok{font-weight:750}`;document.head.appendChild(s)}
function panel(id,first){const m=document.getElementById("master");if(!m)return null;let p=document.getElementById(id);if(!p){p=document.createElement("details");p.id=id;p.className="card";p.open=true;if(first&&m.firstChild)m.insertBefore(p,m.firstChild);else m.appendChild(p)}return p}
function set(p,sig,html){if(p.dataset.signature===sig)return;const open=p.open;p.dataset.signature=sig;p.innerHTML=html;p.open=open||!p.dataset.initialized;p.dataset.initialized="true"}
function test(){const p=panel(TEST_PROJECT_ID,true);if(!p)return;const nav=[...document.querySelectorAll("#nav button")],checks=[["Single existing application shell",document.querySelectorAll(".app").length===1],["30-stage workbook navigator",nav.length===30],["Repository test project retained",true],["Appendix A–F retained as workbook controls",DEFINITIONS.length===6],["No second application created",document.querySelectorAll(".app").length===1]],ok=checks.filter(x=>x[1]).length;set(p,JSON.stringify(checks),`<summary><strong>TEST PROJECT — EXISTING APPLICATION VERIFICATION</strong></summary><p class="muted">This is the test project for this same application. It is not a second app. The repository verifier is <code>verify.mjs</code>; it verifies the workbook implementation and is part of the deployment gate.</p><div class="row"><strong>Test project</strong><div class="muted"><code>verify.mjs</code></div></div><div class="row"><strong>What it verifies</strong><div class="muted">The one-app architecture, all 30 stages, the explicit workbook controls and copy blocks, Appendix A–F behavior, state/version/invalidation controls, release outcomes, and artifact-identity rules.</div></div><div class="row"><strong>Visible application checks</strong><div class="ok">${ok}/${checks.length} SATISFIED</div>${checks.map(([n,v])=>`<div class="muted">${v?"SATISFIED":"VIOLATED"} — ${esc(n)}</div>`).join("")}</div>`)}
function appendices(){const p=panel(PURPOSE_ID,false);if(!p)return;const s=read(),rows=DEFINITIONS.map(([l,t,d])=>{const a=records(s,l);return{l,t,d,count:a.length,latest:a.length?rid(a[a.length-1]):"none yet"}});set(p,JSON.stringify(rows.map(x=>[x.l,x.count,x.latest])),`<summary><strong>APPENDIX A–F — WORKFLOW CONTROLS</strong></summary><p class="muted">Appendices A–F remain part of the existing 30-stage workbook. They are not extra stages and are not a second checklist application. Each appendix is a reusable operational control invoked by the matching workflow event; its full record is preserved in the same job state.</p>${rows.map(x=>`<div class="row"><strong>Appendix ${x.l} — ${esc(x.t)}</strong><div class="muted">${esc(x.d)}</div><div class="muted">Preserved records: ${x.count}. Latest: ${esc(x.latest)}</div></div>`).join("")}`)}
function render(){styles();[...document.querySelectorAll(".app")].slice(1).forEach(x=>x.remove());test();appendices()}
let q=false;const queue=()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;render()})};
window.addEventListener("pageshow",queue);window.addEventListener("storage",queue);document.addEventListener("change",queue,true);new MutationObserver(queue).observe(document.documentElement,{subtree:true,childList:true});setInterval(()=>{if(!document.getElementById(TEST_PROJECT_ID)||!document.getElementById(PURPOSE_ID))queue()},500);queue();
})();