21:{role:'baseline configuration auditor',inputs:['job','userInputs','externalSources','requirements','acceptanceTests','mutationTests','productionInstructions','candidates','regressionTests','convergenceCycles','executions','verificationRecords','comparisons'],task:'Freeze the exact candidate that passed convergence and unchanged confirmation as the approved immutable production baseline.',output:'Return the baseline identity, approved version set, component hashes, tool configuration, convergence evidence, confirmation evidence, and distribution rules.'},
22:{role:'final production execution agent',inputs:['job','userInputs','externalSources','requirements','productionInstructions','baselines'],task:'In a fresh production context, generate the actual user-requested deliverable using only approved baseline materials. Do not return a plan, template, or description instead of the product.',output:'Return the exact finished product and native product record with PRODUCT_ID, BASELINE_ID, exact artifact identity, manifest, bytes or external-result evidence, byte length, and SHA-256.'},
23:{role:'deterministic product verifier',inputs:['requirements','acceptanceTests','baselines','products'],task:'Run every applicable deterministic validator against the actual Stage 22 product bytes or exact release package. Verify all deterministically testable properties and preserve exact commands, inputs, outputs, and evidence.',output:'Return deterministic-check records. Any mandatory failure rejects the product; any unestablishable mandatory result is BLOCKED.'},
24:{role:'independent semantic product evaluator',inputs:['externalSources','requirements','products','deterministicChecks'],task:'Independently compare the actual finished product meaning against every active semantic requirement and exact source evidence. The generator may not be its sole semantic validator.',output:'Return one semantic-check record per applicable requirement with exact product location, required meaning, observed meaning, evidence, and SATISFIED, VIOLATED, or UNDETERMINED.'},
25:{role:'independent adversarial product reviewer',inputs:['externalSources','requirements','mutationTests','regressionTests','products','deterministicChecks','semanticChecks'],task:'Attempt to disprove correctness by searching for omissions, prohibited material, contradictions, impossible logic, unsupported facts, wrong versions, broken references, hidden assumptions, partial work, stale facts, malformed files, hidden content, export corruption, and superficial mentions that do not satisfy requirements.',output:'Return adversarial-check records, counterexamples, evidence, defect IDs, and required return stage.'},
26:{role:'independent final-representation inspector',inputs:['requirements','products','deterministicChecks','semanticChecks','adversarialChecks'],task:'Inspect the exact files and rendered representations that will be delivered, including every transformation and packaged file. Do not infer success from upstream validation.',output:'Return representation-inspection records covering every page/view/file, transformation chain, package inventory, defects, coverage counts, and determination.'},
27:{role:'independent process auditor',inputs:['job','userInputs','externalSources','requirements','acceptanceTests','mutationTests','productionInstructions','candidates','executions','verificationRecords','comparisons','defects','regressionTests','corrections','convergenceCycles','baselines'],task:'Audit process correctness independently: approved inputs, sources, requirements, instructions, tools, tests, execution isolation, version transitions, corrections, chain of custody, and traceability. Do not infer product correctness from process correctness.',output:'Return process-audit records with exact evidence and PASS, FAIL, or BLOCKED.'},
28:{role:'independent product auditor',inputs:['externalSources','requirements','acceptanceTests','regressionTests','products','deterministicChecks','semanticChecks','adversarialChecks','representationInspections'],task:'Audit product correctness independently: affirmative evidence for every mandatory requirement, every mandatory validator, semantic support, representation, and unresolved defects. Do not infer process correctness from product correctness.',output:'Return product-audit records with exact evidence and PASS, FAIL, or BLOCKED.'},
29:{role:'independent release-gate auditor',inputs:['requirements','verificationRecords','defects','regressionTests','products','deterministicChecks','semanticChecks','adversarialChecks','representationInspections','processAudits','productAudits'],task:'Apply the release definitions exactly and select one state only: ACCEPTED, REJECTED, or BLOCKED. Absence of detected defects is not affirmative proof.',output:'Return exactly one release-decision record with counts, controlling rule, requirements, tests, defects, blockers, and affirmative evidence.'},
30:{role:'independent artifact-identity auditor',inputs:['products','decisions'],task:'Require an ACCEPTED release decision, compute SHA-256 over the exact audited product bytes, recompute SHA-256 immediately before release over the exact selected bytes, and compare character for character. Do not edit or transform the artifact during this check.',output:'Return hash-verification records with product identity, algorithm, audited hash, release hash, exact byte length/source, comparison, and evidence. Any mismatch or unknown stops release.'},
31:{role:'release and traceability custodian',inputs:['job','externalSources','requirements','productionInstructions','executions','products','deterministicChecks','semanticChecks','adversarialChecks','representationInspections','processAudits','productAudits','decisions','hashVerifications','workflowArtifacts'],task:'Release only the exact ACCEPTED artifact whose release hash equals its audited hash. Preserve the complete source to requirement to instruction to execution to product element to test to result to evidence to release-decision chain.',output:'Return exactly one release record naming the exact artifact, destination, release status, evidence, and traceability reference. REJECTED or BLOCKED work must be NOT_RELEASED.'}
};
