from pathlib import Path
import hashlib

PATH=Path('specification/closed-loop-reliability-controlling-implementation-specification.txt')
OLD='3336446403ea39391e05f0b0b4d2f2189817cf48962e05df1950df552f2f8564'
NEW='6ffd7b3ef6c141754d4381c43c33767c3d8f265833f06a7fccb7518bba818bd9'
raw=PATH.read_bytes()
assert hashlib.sha256(raw).hexdigest()==OLD, 'Unexpected starting specification bytes.'
s=raw.decode('utf-8')

def insert_after(marker, addition):
    global s
    assert s.count(marker)==1, marker[:80]
    s=s.replace(marker, marker+addition, 1)

def replace(old,new):
    global s
    assert s.count(old)==1, old[:80]
    s=s.replace(old,new,1)

insert_after('8. retain the files for later authorized use.\n', '\nStore-once refers to physical byte storage: identical bytes may share one stored blob. Canonical artifact identity is per supplied occurrence and role — the same bytes supplied again, or under a different filename or role, remain distinct ARTIFACT_ID records referencing shared storage. Deduplication never merges canonical artifact records.\n')
insert_after('- the final response claims completion while accessible material remains unexamined.\n', "\nBefore accepted semantic intake, every user-supplied file is presumptively required for Stage 01 inspection unless it is mechanically empty, a byte-identical duplicate of an included file, or explicitly excluded by the human through SAVE_HUMAN_INPUT; after accepted intake, later transfer requirements follow Section 29.15 materiality.\n\nFile-inspection status is the closed set INCLUDED_IN_HANDOFF, which the application establishes; EXTERNAL_INSPECTION_CLAIMED, which is agent-asserted; INSPECTION_SUPPORTED, which is the claim plus complete consistent per-unit dispositions and source locations; and INSPECTION_ESTABLISHED_TO_REQUIRED_BASIS, which is the minimum basis the file's contract requires. Stage 01 completion requires INCLUDED_IN_HANDOFF as an application fact and at least INSPECTION_SUPPORTED for every required file; the word inspected always means at the recorded basis and is never represented as an application-proven semantic fact. A required artifact whose semantic content is INACCESSIBLE_OR_BLOCKED and not proven immaterial leaves Stage 01 BLOCKED unless human authority removes it from project scope through a new input version.\n")
insert_after('DESIRED_SOURCE_COUNT is advisory only and MUST NOT cap or exclude a controlling source. Narrowing a release-bearing search universe requires explicit reasoning and an independent search-adequacy review. NO_APPLICABLE_EXTERNAL_SOURCE is permitted only after the bounded search was executed, every discovered candidate source received a disposition, the independent adequacy review accepted the procedure, and no material unresolved discovery risk remains.\n', '\nThe versioned source-class checklist derives from the closed generic class set — governing law and regulation; standards and specifications; controlling contracts and prior agreements; authoritative technical documentation; official registries and databases; scholarly and measurement literature; and project-supplied references — filtered by the Stage 01 objective and declared jurisdiction or system scope. Omitting an entire applicable class requires explicit reasoning and is challenged by the SEARCH_ADEQUACY_REVIEW. The contract also declares explicit stopping criteria: every registered location searched; query saturation, meaning no new candidate source in the final registered query round; authority-chain closure, meaning every authority cited by an accepted controlling source received a disposition; the declared date or version cutoff; a disposition for every inaccessible location; and the residual-risk statement. Search completion without every declared criterion is invalid.\n')
insert_after('An unregistered field, multiply classified field, ambiguous producer, undeclared default, or operation writing outside its declared set is invalid.\n', '''\nRegistry completeness is specification-controlled, not implementation-chosen. Every field named anywhere in this specification receives its complete FIELD_REGISTRY contract either from an explicit statement of this specification or from these closed default rules, applied in order:
1. a field defined in Section 15 uses its Section 15 row and the Section 15 value contracts;
2. STAGE_DECISION, DECISION_EVIDENCE, and every *_DETERMINATION, CONTROLLING_REASON, CONTROLLING_EVIDENCE, and FINAL_* field is an APPLICATION-derived gate summary;
3. every count, coverage, or completeness field — including TOTAL_*, *_COVERAGE, ALL_*, EXPECTED_*, ACTUAL_*, MISSING_*, EXECUTED, SATISFIED, VIOLATED, UNDETERMINED, and RUNS — is an APPLICATION-derived summary under Sections 14.1 and 16.2;
4. every *_RECORDS field is a Section 14.8 projection of its owning Section 38 family, and substantive ownership follows that family's declared partitions;
5. every *_VERSION and *_ID field is an APPLICATION-allocated identity under Section 34.2 or its owning version registry;
6. fields assigned by Sections 14.2, 14.3, and 14.6 follow those assignments;
7. every remaining stage field is an APPLICATION-recomputed summary or immutable reference under Section 14.8; substantive agent or human content never exists as a bare stage field and lives only in its owning family.
A field whose contract is neither explicitly specified nor uniquely produced by these rules is UNDEFINED_FIELD_CONTRACT and blocks specification acceptance; the resolution is a specification change, never an implementation choice.

The same closure governs STAGE_OPERATION_REGISTRY. For every operation: executor class, response permissions, and writable-family constraints come from Section 14.6; required scope from Section 14.7; acceptance mode from Section 17.12; writable families are exactly the Section 38 families whose records the operation's Section 37 description and Section 14.6 contract create or complete, and the Stage 17 and Stage 19 iteration operations reuse the families of their corresponding Stage 10-16 and Stage 15 operations under the new iteration scope; the completion predicate is the owning stage's Section 37 Completion clause; retry behavior is Section 35.6 for exact retries and replacement-prompt regeneration otherwise; independence requirements are exactly those Sections 26.1-26.6 impose on the operation's role. A stage-operation property neither fixed by this specification nor uniquely derivable from these rules is UNDEFINED_OPERATION_CONTRACT and blocks acceptance.

The generated FIELD_REGISTRY, STAGE_OPERATION_REGISTRY, and normalizer and derivation registries are reviewed under the Section 2.2 omission-challenge discipline, and their digests are pinned in the Section 46.2 acceptance artifact.
''')
replace('TRADEOFF_OR_SCOPE_DECISION, and HUMAN_AUTHORITY_CORRECTION.','TRADEOFF_OR_SCOPE_DECISION, VISUAL_BASELINE_AUTHORIZATION, and HUMAN_AUTHORITY_CORRECTION.')
insert_after('An archive mismatch does not alter the logical package identity; it rejects the transport representation.\n','\nThe deterministic profile governs application-produced archives only. An inbound archive from an external actor is a nonauthoritative convenience container: it must pass the Section 19.9 safety rules, is exploded into named attachment slots with per-member byte verification, and its original bytes are preserved as evidence. External actors are never required to produce the deterministic profile; the authoritative inbound representation remains response.json plus attachment-slot files.\n')
insert_after('Independent review can be generally routable at Stage 06. Actual context independence is established when the review is reserved and performed.\n','\nRequired capability availability is the closed conjunction CAPABILITY_READY: the capability is identified and current; authorized for the exact target and purpose; holds the required permissions and access; the required inputs are transferable within declared limits; the execution route is usable; and the required evidence class is obtainable. Any conjunct UNKNOWN makes the capability UNKNOWN, and required routing is BLOCKED.\n')
replace('Stage 06 proof-expression/evidence-basis review,','Stage 06 proof-expression, evidence-basis, and native-versus-external representability review,')
insert_after('Independence is recorded separately for APPLICATION_SESSION_DISTINCTNESS, APPLICATION_INPUT_ISOLATION, USER_TRANSFER_CONFORMITY, EXTERNAL_CONTEXT_IDENTIFIER_DISTINCTNESS, PROVIDER_CONTEXT_INDEPENDENCE, EXECUTOR_OR_REVIEWER_ROLE_SEPARATION, and ENVIRONMENT_INDEPENDENCE where required. APPLICATION_ESTABLISHED means only that application-observable dimensions required by the contract are satisfied. Distinct IDs do not prove hidden provider-state independence. A required UNKNOWN dimension blocks or leaves the result undetermined.\n','\nEvery external operation contract declares MINIMUM_INPUT_BINDING_BASIS from APPLICATION_OBSERVED, VERIFIED_EXTERNAL, EXTERNALLY_SUPPORTED, and SELF_ASSERTED. An echoed manifest identity and per-member digests establish at most EXTERNALLY_SUPPORTED. SELF_ASSERTED or UNKNOWN cannot satisfy an operation whose contract requires byte-exact input possession, and gates derive admissibility from the recorded basis.\n')
insert_after('Every current applicable release-bearing proposition has exactly one current PROOF_OBLIGATION_ID identifying its proof expression, required leaves, evidence classes, allowed epistemic bases, artifacts, dependencies, freshness, independence, verification timing, current satisfaction, blockers, and scope hash. Optional, advisory, stale, historical, or unregistered results cannot satisfy it.\n','\nEQUIVALENT applies only to proposition-to-proposition sameness. The relation between a test and a proof leaf, and between a proof expression and its proposition, is sufficiency, established by the accepted Stage 06 PROOF_REVIEW. A LEAF references exactly one of: a canonical test with its required disposition, an observation-backed proposition, an applicability or activation condition, or a prerequisite proof obligation; each leaf declares its truth extraction, required evidence classes, and scope binding, and no other leaf target is valid in version 1. An ANY_OF expression is accepted only when the review establishes that each branch alone suffices to establish the parent proposition; an AT_LEAST_K expression is accepted only when every permitted K-combination suffices or an explicitly reviewed combinatorial sufficiency contract covers it. A branch that weakens proof strength is rejected at Stage 06.\n')
insert_after('Time-sensitive evidence records observedAt, its DEVICE_REPORTED, SOURCE_ASSERTED, or VERIFIED_EXTERNAL basis, validFrom, validUntil, supersession, freshness requirement, status, and reason. Required freshness that cannot be established is UNKNOWN. Current justificatory evidence is acyclic.\n','\nVERIFIED_EXTERNAL is achieved only under a registered attestation-verification contract fixing the evidence type, the attesting tool or system identity, the verification method, the bound inputs including the operation challengeNonce or reservation, the freshness rule, and the failure semantics. Absent such a registered contract, the basis remains EXTERNALLY_SUPPORTED or weaker.\n')
replace('Materiality is MATERIAL, NONMATERIAL, or UNKNOWN. NONMATERIAL requires affirmative reasoning that the item cannot alter any current proposition, proof obligation, artifact identity, dependency, gate, release eligibility, delivery scope, or delivery state. UNKNOWN is treated as MATERIAL for exclusion and blocking.','Materiality is MATERIAL, NONMATERIAL, or UNKNOWN. MATERIAL means the item could change the truth value, applicability, proof admissibility, evidence sufficiency, identity, due state, dependency closure, gate result, authorization, or delivery status of at least one current release-bearing proposition or action. NONMATERIAL requires affirmative reasoning that the item cannot alter any current proposition, proof obligation, artifact identity, dependency, gate, release eligibility, delivery scope, or delivery state. UNKNOWN is treated as MATERIAL for exclusion and blocking. Every materiality determination that excludes content, reduces required work, or downgrades an obligation is recorded as a materialityReviews record; where it reduces a possible obligation it requires independent review under Section 26.5.')
insert_after('The application applies this distinction.\n','\nA contradiction that contains sufficient refutation of an applicable mandatory proposition does not prevent REJECTED under Section 36.4 rule 1; contradiction produces BLOCKED only where no sufficient mandatory refutation already controls.\n')
insert_after('Every set-valued array has one named versioned normalizer. Every contentSha256, recordSha256, project hash, package hash, proof hash, scope hash, and terminal hash has a closed JSON-pointer inclusion and omission set registered in workflow-schema.js. No implementation selects preimage fields implicitly.\n','\nFor every registered hash kind, the preimage inclusion set is exactly the canonical fields of the subject record or manifest, excluding only the digest field itself and every field whose value depends on that digest, fields declared audit-only or derived-summary, and fields the owning schema explicitly excludes with a registered reason. The scope-hash preimage is exactly the Section 14.7 dimensions of the operation, and the terminal-hash preimage is exactly the records enumerated in Section 36.9. An unregistered hash kind or pointer set is UNDEFINED_HASH_PREIMAGE and blocks the computation and every dependent gate. Default array semantics are ordered and order-significant; an array is set-valued only when its JSON pointer is explicitly registered with an element-identity key, a duplicate rule that rejects duplicates, and a sort rule of canonical byte order over the element identity. An unregistered pointer treated as a set is UNDEFINED_SET_SEMANTICS and blocks.\n')
insert_after('Every normalizer and application derivation has an immutable registry ID, version, implementation-owner file, canonical input contract, output contract, hash or build identity, and invalidation consequences. Every derived value records the exact derivation ID and source-record hashes. A changed normalizer or derivation invalidates affected current values and results unless an explicit compatibility migration proves byte- and semantic-equivalent output.\n','\nEvery release-bearing derivation and normalizer is completely defined by this specification or by an explicitly named versioned normative algorithm. The semantics defined in Sections 14.6, 15, 16.1, 26, 29, 30, 31, 34.1, 34.2, and 36 control their registry entries, and an entry cannot deviate from them. A release-bearing derivation or normalizer whose semantics are not so defined is UNDEFINED_DERIVATION and blocks acceptance.\n')
insert_after('A registry finding that objectively refutes an earlier premise invalidates that premise through the responsible-stage map and requires recalculation in order.\n','\nRESPONSIBLE_STAGE_MAP is mechanically derived: every canonical family maps to its Section 38 declared stage, and every global family maps to the earliest stage whose gate consumes it; a mutation in a family invalidates from that stage under Section 36.1. Registry findings are classified TERMINAL_ONLY_DEFECT, which blocks Stage 30 only, or PREMISE_REFUTING_DEFECT, which invalidates from the mapped responsible stage. A defect in the release-calculation semantics themselves is an implementation defect handled through the Sections 40-44 regression discipline, never by silently recalculating Stage 27.\n')
insert_after('Authorization for one recipient, purpose, destination, or channel is not authorization for another. UNKNOWN destination or disclosure authority blocks authorization where the material requires it.\n','\nAn authorization with a real-time validity condition declares its permitted time basis under closed-loop-trusted-time/1. Where only DEVICE_REPORTED time exists, validity is UNKNOWN and every dependent action, including a Section 23.3 external action, is BLOCKED; device-reported time may annotate but cannot establish current validity.\n')
replace('Completion: Current input version exists; required files were inspected; every raw unit is accounted for;','Completion: Current input version exists; every required file reached its required inspection basis; every raw unit is accounted for;')
replace('Covers intent confirmations, tradeoffs, scope changes, disclosure authorizations, risk authorizations, baseline authorization, delivery intent, and corrections to human-authority facts.','Covers intent confirmations, tradeoffs, scope changes, disclosure authorizations, risk authorizations, baseline authorization, visual-baseline authorization, delivery intent, and corrections to human-authority facts.')
insert_after('- do not imply authentication.\n','\nEvery HUMAN_DECISION purpose and CAPTURE_DELIVERY_INTENT declares its minimum identityAssurance in FIELD_REGISTRY. Until authentication exists, SELF_ASSERTED is the only available level and is explicitly accepted for every current purpose; every recorded decision carries its actual assurance. A purpose whose declared minimum exceeds the available assurance is BLOCKED.\n')
insert_after('An intentional visual deviation requires a specific normative UI requirement and a new human-authorized baseline record. Repository history is evidence for locating a candidate baseline but does not substitute for the frozen identity; if the baseline was not previously explicit, repository and deployment history identify the last user-approved state before the unrequested visual change and the resulting baseline is frozen before repair acceptance. Nonvisual work must produce zero unapproved visual diffs.\n','\nIf exactly one qualifying predecessor state is mechanically identifiable, it is the proposed baseline. Otherwise, or when historical approval cannot be established, baseline selection is recorded through RECORD_HUMAN_DECISION with purpose VISUAL_BASELINE_AUTHORIZATION, and visual acceptance is BLOCKED until that decision exists.\n')
replace('222. A candidate-selection, baseline, disclosure, risk, controlled-exception, regression-retirement, backup-policy, tradeoff, or human-correction decision commits only through RECORD_HUMAN_DECISION with the exact registered purpose and target.','222. A candidate-selection, baseline, disclosure, risk, controlled-exception, regression-retirement, backup-policy, tradeoff, visual-baseline, or human-correction decision commits only through RECORD_HUMAN_DECISION with the exact registered purpose and target.')
insert_after('235. Per-member sequential export satisfies logical package export when a combined multi-file share is unavailable.\n','''236. A field, stage-operation property, hash preimage, set pointer, derivation, or normalizer that is neither explicitly specified nor uniquely derivable by the closed default rules fails acceptance as its UNDEFINED_* disposition.
237. The generated FIELD_REGISTRY, STAGE_OPERATION_REGISTRY, and derivation and normalizer registries are Section 2.2-reviewed and digest-pinned in the acceptance artifact.
238. An inbound external archive is exploded into named attachment slots with per-member verification; the deterministic archive profile is never demanded from an external actor.
239. An external operation requiring byte-exact input possession rejects SELF_ASSERTED or UNKNOWN input-binding basis.
240. VERIFIED_EXTERNAL is granted only under a registered attestation-verification contract; otherwise the basis remains EXTERNALLY_SUPPORTED or weaker.
241. ANY_OF branches and every permitted AT_LEAST_K combination carry accepted sufficiency review before any branch result can satisfy the proposition.
242. A contradiction containing sufficient mandatory refutation yields REJECTED, not BLOCKED.
243. A time-limited authorization without its permitted trusted-time basis is UNKNOWN and blocks dependent actions.
244. A MOBILE_ACCEPTANCE_CHALLENGE is single-use; reused, mismatched, or expired evidence is rejected.
245. Ambiguous or unestablished visual-baseline history blocks visual acceptance until VISUAL_BASELINE_AUTHORIZATION is recorded.
246. A required Stage 01 artifact with inaccessible semantic content blocks completion unless human authority removes it from scope through a new input version.
247. Identical bytes supplied twice or under different roles remain distinct canonical artifacts sharing physical storage.
248. CAPABILITY_READY requires its full closed conjunction; any UNKNOWN conjunct blocks required routing.
249. A HUMAN_DECISION purpose whose declared minimum identityAssurance exceeds the available level is BLOCKED.
''')
insert_after('The required mobile acceptance executes on an actual iPhone in Safari. Simulator, desktop responsive mode, and another browser are supplementary only and cannot satisfy the physical-device requirement. "Current" is frozen by the target record; a material iOS, Safari/WebKit, application build, origin, storage behavior, or target-device change before final delivery invalidates the affected mobile result and requires revalidation.\n','\nThe minimum required target-identity tuple is: the physical-device human observation; reported iOS version; observed Safari user-agent string; viewport dimensions and device-pixel ratio; exact deployed commit and deployment-manifest digest; origin; and test-project identity. WebKit build identity and exact hardware model may remain UNKNOWN without blocking; every other tuple member is required.\n')
insert_after('At completion, the application exports `mobile-acceptance-evidence.json` containing the target ID, challenge, build identity, origin, test-project identity, operation receipts, console/runtime findings available to the application, screenshots or recording references, exported project digest, performer identity assurance, physical-device assertion, and evidence basis. CI verifies every mechanically verifiable binding before accepting the record. The physical-device fact remains HUMAN_OBSERVATION or stronger external attestation according to the actual evidence and is never mislabeled application-proven.\n','\nThe evidence file reaches CI through the repository as a committed file or authenticated workflow input from a submitter recorded in the acceptance artifact. Each MOBILE_ACCEPTANCE_CHALLENGE is single-use: CI accepts at most one evidence file per challenge and rejects reused, unknown, or expired challenges and any evidence bound to a different commit, manifest, origin, target, or test project; a superseding run requires a new challenge. The gate minimum for the physical-device fact is HUMAN_OBSERVATION by the recorded performer at the recorded identity assurance; that basis is explicitly sufficient and is never relabeled application-proven.\n')
s=s.replace('\r\n','\n').replace('\r','\n').lstrip('\n').rstrip('\n')+'\n'
out=s.encode('utf-8')
assert len(out)==309472, len(out)
assert hashlib.sha256(out).hexdigest()==NEW, hashlib.sha256(out).hexdigest()
PATH.write_bytes(out)
