from pathlib import Path

p=Path('workflow-engine.js')
s=p.read_text()
marker="const SCOPE_KEYS=Object.freeze(['inputVersion'"
if marker not in s: raise SystemExit('workflow-engine insertion marker missing')
helpers=r'''
function currentHumanInputRecord(project){
  ensureShape(project);
  const version=String(project.job.CURRENT_INPUT_VERSION||'').trim();
  const rows=safe(project.projectData.inputVersions);
  return rows.slice().reverse().find(row=>String(row.version||'')===version)||rows.at(-1)||null;
}
function intakeCoverageManifest(project){
  ensureShape(project);
  const row=currentHumanInputRecord(project),inputVersion=String(project.job.CURRENT_INPUT_VERSION||row?.version||'').trim();
  const payload=clone(row?.payload||project.projectData.userEntered||{}),units=[];
  const definitions=schema.JOB_FIELDS||{};
  const humanNames=Object.entries(definitions).filter(([,d])=>['HUMAN','HUMAN_DECISION'].includes(d?.producer)).map(([name])=>name);
  const add=(sourceLocation,fieldName,rawValue,kind='HUMAN_FIELD')=>{
    if(rawValue===undefined||rawValue===null)return;
    if(typeof rawValue==='string'&&!rawValue.trim())return;
    if(Array.isArray(rawValue)&&!rawValue.length)return;
    const text=typeof rawValue==='string'?rawValue:JSON.stringify(rawValue),rawValueSha256=hash.sha256Value(rawValue);
    const sourceUnitId='INPUT-'+hash.sha256Value({inputVersion,sourceLocation,rawValueSha256}).slice(0,24).toUpperCase();
    units.push({sourceUnitId,sourceLocation,fieldName,kind,rawValue:clone(rawValue),text,rawValueSha256});
  };
  for(const name of humanNames)add(`/inputVersions/${row?.inputVersionId||inputVersion||'CURRENT'}/payload/${name}`,name,Object.prototype.hasOwnProperty.call(payload,name)?payload[name]:project.job[name]);
  for(const [i,item] of safe(payload.clarifications).entries())add(`/inputVersions/${row?.inputVersionId||inputVersion||'CURRENT'}/payload/clarifications/${i}`,'clarification',item,'HUMAN_CLARIFICATION');
  const identity={schema:'closed-loop-intake-manifest/1',inputVersion,units:units.map(({sourceUnitId,sourceLocation,fieldName,kind,rawValueSha256})=>({sourceUnitId,sourceLocation,fieldName,kind,rawValueSha256}))};
  return {...identity,units,manifestSha256:hash.sha256Value(identity)};
}
function parseIntakeCapture(value){if(value&&typeof value==='object'&&!Array.isArray(value))return value;try{return JSON.parse(String(value||''));}catch{return null;}}
function evaluateIntakeCoverage(project,inputSetContents){
  const manifest=intakeCoverageManifest(project),capture=parseIntakeCapture(inputSetContents),errors=[];
  if(!capture||typeof capture!=='object'||Array.isArray(capture))return {complete:false,coverage:0,total:manifest.units.length,accounted:0,errors:['INPUT_SET_CONTENTS must be valid closed-loop-intake-capture/1 JSON.'],manifest};
  if(capture.schema!=='closed-loop-intake-capture/1')errors.push('Intake capture schema must be closed-loop-intake-capture/1.');
  if(String(capture.inputVersion||'')!==String(manifest.inputVersion||''))errors.push('Intake capture inputVersion does not match the current User Job Input version.');
  if(String(capture.manifestSha256||'')!==String(manifest.manifestSha256||''))errors.push('Intake capture manifestSha256 does not match the current application intake manifest.');
  const allowed=new Set(['INCORPORATED','RETAINED_CONTEXT','UNRESOLVED_HUMAN_ONLY','LATER_RESOLVABLE','INAPPLICABLE']),ids=new Set(manifest.units.map(u=>u.sourceUnitId)),seen=new Set(),accounted=new Set();
  for(const [i,u] of safe(capture.units).entries()){
    const id=String(u?.sourceUnitId||'');if(!ids.has(id)){errors.push(`Unknown intake sourceUnitId ${id||'(missing)'} at units[${i}].`);continue;}if(seen.has(id)){errors.push(`Duplicate intake accounting for ${id}.`);continue;}seen.add(id);
    const disposition=upper(u?.disposition);if(!allowed.has(disposition)){errors.push(`Invalid intake disposition for ${id}.`);continue;}const statements=safe(u?.extractedStatements);
    if(disposition!=='INAPPLICABLE'&&!statements.length)errors.push(`${id} has no extractedStatements; every semantically distinct project-relevant meaning must be preserved.`);
    const statementKeys=new Set();for(const [j,st] of statements.entries()){const key=String(st?.statementKey||'').trim(),text=String(st?.text||'').trim(),cls=String(st?.statementClass||'').trim();if(!key||!text||!cls)errors.push(`${id} extractedStatements[${j}] requires statementKey, text, and statementClass.`);if(key&&statementKeys.has(key))errors.push(`${id} repeats statementKey ${key}.`);statementKeys.add(key);}
    if(disposition==='INAPPLICABLE'&&!String(u?.reason||'').trim())errors.push(`${id} is INAPPLICABLE without a reason.`);accounted.add(id);
  }
  for(const id of ids)if(!seen.has(id))errors.push(`Controlled input unit ${id} is omitted from Stage 01 accounting.`);const total=ids.size,coverage=total?accounted.size/total:1;
  return {complete:errors.length===0&&coverage===1,coverage,total,accounted:accounted.size,errors,manifest,capture};
}
function obligationManifest(project){
  ensureShape(project);
  const prerequisites={stage1Complete:project.stages?.[1]?.status==='COMPLETE',stage3Complete:project.stages?.[3]?.status==='COMPLETE'};
  const input=intakeCoverageManifest(project),intakeEval=evaluateIntakeCoverage(project,project.job.INPUT_SET_CONTENTS),obligations=[],seen=new Set();
  const add=(originType,originId,sourceLocation,text,provenance={})=>{const t=typeof text==='string'?text.trim():JSON.stringify(text);if(!t||['NONE','NOT APPLICABLE'].includes(upper(t)))return;const contentSha256=hash.sha256Value(text),obligationId='OBL-'+hash.sha256Value({originType,originId,sourceLocation,contentSha256}).slice(0,24).toUpperCase();if(seen.has(obligationId))return;seen.add(obligationId);obligations.push({obligationId,originType,originId,sourceLocation,text:t,contentSha256,provenance:clone(provenance)});};
  for(const u of input.units)add('USER_JOB_INPUT',u.sourceUnitId,u.sourceLocation,u.rawValue,{inputVersion:input.inputVersion,rawValueSha256:u.rawValueSha256});
  const cap=intakeEval.capture;if(cap){for(const u of safe(cap.units))for(const [i,st] of safe(u.extractedStatements).entries())add('STAGE01_CAPTURE',String(st.statementKey||`${u.sourceUnitId}:${i}`),`/job/INPUT_SET_CONTENTS/units/${u.sourceUnitId}/extractedStatements/${i}`,st.text,{sourceUnitId:u.sourceUnitId,statementClass:st.statementClass});for(const [i,st] of safe(cap.conversationStatements).entries())add('STAGE01_CONVERSATION',String(st.statementKey||`conversation:${i}`),`/job/INPUT_SET_CONTENTS/conversationStatements/${i}`,st.text,{question:st.question,status:st.status,statementClass:st.statementClass});}
  for(const name of ['EXACT_DELIVERABLE_REQUESTED','ASSUMPTIONS','UNKNOWN_INFORMATION'])add('STAGE01_JOB_DEFINITION',name,`/stages/1/agentData/${name}`,project.stages?.[1]?.agentData?.[name]??project.job?.[name],{stage:1});
  const current=col=>recordsForCurrentScope(project,col);for(const collection of ['research','candidateRequirements'])for(const rec of current(collection)){const id=recordId(rec,collection)||hash.sha256Value(rec).slice(0,16),fields=recordFields(rec);for(const [fieldName,value] of Object.entries(fields)){if(fieldName===schema.RECORD_SCHEMAS?.[collection]?.idField)continue;if(value===undefined||value===null||value===''||(Array.isArray(value)&&!value.length))continue;add('STAGE03_'+collection.toUpperCase(),`${id}:${fieldName}`,`/${collection}/${id}/${fieldName}`,value,{stage:3,recordId:id,fieldName,relationships:clone(rec.relationships||{})});}}
  for(const rec of current('sources')){const id=recordId(rec,'sources');add('SOURCE_IDENTITY',id,`/sources/${id}`,{id,fields:recordFields(rec)},{stage:2,recordId:id});}
  const identity={schema:'closed-loop-obligation-manifest/1',inputVersion:input.inputVersion,sourceSetVersion:project.job.CURRENT_SOURCE_SET_VERSION||null,researchVersion:project.job.CURRENT_RESEARCH_VERSION||null,prerequisites,obligations:obligations.map(({obligationId,originType,originId,sourceLocation,contentSha256,provenance})=>({obligationId,originType,originId,sourceLocation,contentSha256,provenance}))};return {...identity,obligations,manifestSha256:hash.sha256Value(identity)};
}
function obligationRefsFromRequirement(record){const value=record?.fields?.USER_INPUT_RELATIONSHIP??record?.USER_INPUT_RELATIONSHIP;return Array.isArray(value)?value.map(String):String(value||'').split(/[\s,;]+/).filter(v=>/^OBL-/i.test(v));}
function evaluateObligationAccounting(project,{requirements=[],evidence=[]}={}){
  const manifest=obligationManifest(project),errors=[];if(!manifest.prerequisites.stage1Complete)errors.push('Stage 01 is not COMPLETE; Stage 04 obligation accounting cannot close.');if(!manifest.prerequisites.stage3Complete)errors.push('Stage 03 is not COMPLETE; Stage 04 obligation accounting cannot close.');
  const ids=new Set(manifest.obligations.map(o=>o.obligationId)),mapped=new Map(),disposed=new Map(),allowed=new Set(['RETAINED_NONNORMATIVE_CONTEXT','INAPPLICABLE','BLOCKED']);for(const req of safe(requirements))for(const id of obligationRefsFromRequirement(req)){if(!ids.has(id))errors.push(`Requirement references unknown obligation ${id}.`);else mapped.set(id,(mapped.get(id)||0)+1);}
  for(const ev of safe(evidence))if(upper(ev?.kind)==='OBLIGATION_DISPOSITION'){let d;try{d=typeof ev.content==='string'?JSON.parse(ev.content):ev.content;}catch{errors.push('OBLIGATION_DISPOSITION evidence content is malformed JSON.');continue;}const keys=d&&typeof d==='object'&&!Array.isArray(d)?Object.keys(d):[];if(keys.length!==3||!['obligationId','disposition','reason'].every(k=>keys.includes(k))){errors.push('OBLIGATION_DISPOSITION must contain exactly obligationId, disposition, and reason.');continue;}const id=String(d.obligationId||'');if(!ids.has(id)){errors.push(`Disposition references unknown obligation ${id||'(missing)'}.`);continue;}if(disposed.has(id))errors.push(`Duplicate disposition for ${id}.`);disposed.set(id,d);if(!allowed.has(upper(d.disposition)))errors.push(`Invalid non-requirement disposition for ${id}.`);if(!String(d.reason||'').trim())errors.push(`Disposition for ${id} requires a reason.`);}
  for(const id of ids){if(mapped.has(id)&&disposed.has(id))errors.push(`${id} is both mapped to a requirement and disposed.`);else if(!mapped.has(id)&&!disposed.has(id))errors.push(`${id} has no requirement mapping or valid non-requirement disposition.`);}const accounted=[...ids].filter(id=>(mapped.has(id)?1:0)+(disposed.has(id)?1:0)===1).length,total=ids.size;return {complete:errors.length===0&&accounted===total,coverage:total?accounted/total:1,total,accounted,errors,manifest};
}
'''
s=s.replace(marker,helpers+'\n'+marker,1)
old="""case 1:{\n      if(!String(project.job.EXACT_USER_OBJECTIVE_VERBATIM||'').trim())reasons.push('Verbatim User Job Input is required.');\n      requireAccepted();\n      const latest=changes.at(-1),confirmed=safe(project.projectData.stageConfirmations).some(item=>Number(item.stage)===1&&item.confirmed===true&&!item.invalidatedBy&&item.acceptedChangeId===latest?.changeId&&item.inputVersion===project.job.CURRENT_INPUT_VERSION);\n      if(!confirmed)reasons.push('Human confirmation bound to the current accepted change and input version is required.');\n      break;\n    }"""
new="""case 1:{\n      if(!String(project.job.CURRENT_INPUT_VERSION||'').trim())reasons.push('A current User Job Input version is required.');\n      if(!String(project.job.EXACT_USER_OBJECTIVE_VERBATIM||'').trim())reasons.push('Verbatim User Job Input is required.');\n      requireAccepted();\n      for(const name of ['EXACT_DELIVERABLE_REQUESTED','ASSUMPTIONS','UNKNOWN_INFORMATION','INPUT_SET_CONTENTS'])if(project.job[name]===undefined||project.job[name]===null||String(project.job[name]).trim()==='')reasons.push(`Stage 01 required field ${name} is missing.`);\n      const accounting=evaluateIntakeCoverage(project,project.job.INPUT_SET_CONTENTS);if(!accounting.complete)reasons.push(...accounting.errors);\n      if(unresolvedHumanRequests(project,1).length)reasons.push('Stage 01 has unresolved blocking human-authority questions.');\n      const latest=changes.at(-1),confirmed=safe(project.projectData.stageConfirmations).some(item=>Number(item.stage)===1&&item.confirmed===true&&!item.invalidatedBy&&item.acceptedChangeId===latest?.changeId&&item.inputVersion===project.job.CURRENT_INPUT_VERSION);\n      if(!confirmed)reasons.push('Human confirmation bound to the current accepted change and input version is required.');\n      break;\n    }"""
if old not in s: raise SystemExit('Stage 1 gate anchor missing')
s=s.replace(old,new,1)
old3="""case 3:{\n      requireAccepted();const sourceIds=all('sources').map(record=>recordId(record,'sources')),noSource=upper(project.stages[2]?.agentData?.SOURCE_APPLICABILITY_DETERMINATION)==='NO_APPLICABLE_EXTERNAL_SOURCE';\n      if(!sourceIds.length){if(!noSource)reasons.push('Stage 03 cannot proceed without a current Stage 02 source set or valid no-source determination.');break;}\n      requireCount('research',1);const researched=new Set(collection('research').map(record=>String(recordValue(record,'SOURCE_ID')||record.relationships?.SOURCE_ID||''))),missing=sourceIds.filter(id=>!researched.has(id));if(missing.length)reasons.push(`Research is missing for source(s): ${missing.join(', ')}.`);break;\n    }"""
new3="""case 3:{\n      requireAccepted();const sourceIds=all('sources').map(record=>recordId(record,'sources')),noSource=upper(project.stages[2]?.agentData?.SOURCE_APPLICABILITY_DETERMINATION)==='NO_APPLICABLE_EXTERNAL_SOURCE',data=project.stages[3]?.agentData||{};\n      if(!sourceIds.length&&!noSource)reasons.push('Stage 03 cannot proceed without a current Stage 02 source set or valid no-source determination.');\n      if(sourceIds.length){requireCount('research',1);const researched=new Set(collection('research').map(record=>String(recordValue(record,'SOURCE_ID')||record.relationships?.SOURCE_ID||''))),missing=sourceIds.filter(id=>!researched.has(id));if(missing.length)reasons.push(`Research is missing for source(s): ${missing.join(', ')}.`);if(!truth(data.ALL_KNOWN_CONTROLLING_SOURCES_EXAMINED))reasons.push('Stage 03 has not established that all known controlling sources were examined.');if(!truth(data.SECOND_CONFLICT_AND_EXCEPTION_PASS_COMPLETED))reasons.push('Stage 03 second conflict and exception pass is not complete.');if(numeric(data.LATEST_PASS_NUMBER)<2)reasons.push('Stage 03 requires at least two documented research passes when applicable sources exist.');if(!falsey(data.NEW_MATERIAL_CATEGORY_FOUND_IN_LATEST_PASS))reasons.push('Stage 03 latest pass still found a new material category; research is not exhausted.');}\n      const gaps=String(data.RESEARCH_GAPS_AND_BLOCKERS||'').trim();if(gaps&&!['NONE','NOT APPLICABLE','N/A'].includes(upper(gaps)))reasons.push('Stage 03 research gaps or blockers remain unresolved.');\n      break;\n    }"""
if old3 not in s: raise SystemExit('Stage 3 gate anchor missing')
s=s.replace(old3,new3,1)
p.write_text(s)

p=Path('prompt-engine.js');s=p.read_text()
old1="Perform complete human-authority intake only. The application has enumerated every current controlled human-input unit in APPLICATION INTAKE MANIFEST. Classify every supplied unit exactly once and preserve every materially relevant fact, requirement, constraint, decision, prohibition, requested output, acceptance condition, material reference, and unresolved human-only issue."
new1="Perform complete human-authority intake only. The application has enumerated every current controlled human-input unit in APPLICATION INTAKE MANIFEST. Inspect every controlled unit and extract EVERY semantically distinct project-relevant fact, requirement, constraint, decision, prohibition, requested output, acceptance condition, material reference, and unresolved human-only issue. Preserve distinctions exactly: do not summarize away, merge, generalize, compress, paraphrase into loss, or omit separate meanings merely because they appear in one long user statement or artifact. Classify every supplied unit exactly once and preserve every distinct project-relevant meaning it contains."
if old1 not in s: raise SystemExit('Stage1 procedure anchor missing')
s=s.replace(old1,new1,1)
s=s.replace("Ask genuinely human-only questions conversationally before final JSON.","Classify every foreseeable unresolved issue as BLOCKING_NOW, ASK_NOW_NONBLOCKING, or LATER_RESOLVABLE. Ask every BLOCKING_NOW and ASK_NOW_NONBLOCKING human-only question conversationally before final JSON; nonblocking means the human may answer UNKNOWN or DEFERRED, not that the question may be skipped. Do not ask the human to repeat information already supplied or information reliably obtainable from accessible supplied material, authorized research, or a later stage. When supplied artifact bytes are accessible, inspect them deeply enough to extract human-authority statements relevant to defining the job; when bytes are unavailable, preserve the named material and do not make the human describe it merely because bytes are unavailable.",1)
old3p="Research only the current accepted Stage 02 independent external source set, source-by-source and pass-by-pass. Examine exact portions and separately capture facts, mandatory obligations, recommendations, optional practices, examples, prohibitions, exceptions, dependencies, applicability facts, restrictions, invalidating material, conflicts, superseded guidance, source evidence, candidate requirement proposals, and unresolved questions. Use response-local references rather than assigning canonical requirement identities. Do not treat the target product, this operating application, repository source code, prior implementations, project-generated artifacts, or current UI behavior as independent requirement authority. Repeat discovery passes until saturation is actually supported by the evidence."
new3p="Research only the current accepted Stage 02 independent external source set, source-by-source and pass-by-pass. Exhaust the accepted source set before completion: every current Stage 02 source must have current research coverage; separately capture facts, mandatory obligations, recommendations, optional practices, examples, explanatory material, prohibitions, exceptions, dependencies, applicability facts, restrictions, invalidating material, conflicts, superseded guidance, source evidence, candidate requirement proposals, and unresolved questions. Perform a second conflict-and-exception pass and continue passes until the latest complete pass finds no new material requirement category, all known controlling sources are examined, and no unresolved research gap or blocker remains. Use response-local references rather than assigning canonical requirement identities. Do not treat the target product, this operating application, repository source code, prior implementations, project-generated artifacts, or current UI behavior as independent requirement authority."
if old3p not in s: raise SystemExit('Stage3 procedure anchor missing')
s=s.replace(old3p,new3p,1)
anchor="if(stage===4&&state?.stages?.[1]){const intake={agentData:state.stages[1].agentData||state.stages[1].acceptedData||{},humanData:state.stages[1].humanData||{},derivedData:state.stages[1].derivedData||{}};parts.push(`ACCEPTED STAGE 01 JOB DEFINITION — CURRENT HUMAN-AUTHORITY CAPTURE\\n${show(intake)}`);}"
addition=anchor+"\n if(stage===4&&state?.stages?.[3]){const stage3={agentData:state.stages[3].agentData||state.stages[3].acceptedData||{},humanData:state.stages[3].humanData||{},derivedData:state.stages[3].derivedData||{},sources:workflow.recordsForCurrentScope(state,'sources'),research:workflow.recordsForCurrentScope(state,'research'),candidateRequirements:workflow.recordsForCurrentScope(state,'candidateRequirements'),sourceConflicts:workflow.recordsForCurrentScope(state,'sourceConflicts')};parts.push(`ACCEPTED STAGE 03 RESEARCH — COMPLETE CURRENT CANONICAL RESEARCH\\n${show(stage3)}`);}"
if anchor not in s: raise SystemExit('Stage4 Stage1 context anchor missing')
s=s.replace(anchor,addition,1)
anchor2="const opContract=schema.operationContract(stage,operation);"
guard="if(stage===4){const intake=workflow.evaluateIntakeCoverage(state,state?.job?.INPUT_SET_CONTENTS);if(state?.stages?.[1]?.status!=='COMPLETE'||!intake.complete){const e=new Error('Stage 04 prompt generation is blocked until Stage 01 is COMPLETE with 100% controlled-input accounting.');e.code='STAGE04_STAGE01_INCOMPLETE';throw e;}if(state?.stages?.[3]?.status!=='COMPLETE'){const e=new Error('Stage 04 prompt generation is blocked until Stage 03 research is COMPLETE and exhausted.');e.code='STAGE04_STAGE03_INCOMPLETE';throw e;}}\n "
if anchor2 not in s: raise SystemExit('buildPromptRecord guard anchor missing')
s=s.replace(anchor2,guard+anchor2,1)
p.write_text(s)
