from pathlib import Path
import re
P=Path('workflow-engine.js'); s=P.read_text()
def one(a,b):
 global s
 if s.count(a)!=1: raise SystemExit('engine match count '+str(s.count(a))+': '+a[:80])
 s=s.replace(a,b,1)
one("if([23,24,25].includes(stage))for(const a of artifacts)if(String(a.scope?.productId||'')===String(current.productId||''))addArtifact(a);","if([22,23,24,25].includes(stage))for(const a of artifacts)if(String(a.scope?.productId||'')===String(current.productId||''))addArtifact(a);")
# Strengthen effective adjudication so release math cannot treat structurally present but proposition-incapable evidence as proof.
for col,needle in [
('verification',"else if(collection==='verification'){if(!evidence.sufficient)reasons.push(...evidence.reasons);"),
('deterministicResults',"else if(collection==='deterministicResults'){if(!evidence.sufficient)reasons.push(...evidence.reasons);"),
('meaningResults',"else if(collection==='meaningResults'){if(!evidence.sufficient)reasons.push(...evidence.reasons);"),
('adversarialResults',"else if(collection==='adversarialResults'){if(!evidence.sufficient)reasons.push(...evidence.reasons);")]:
 repl=needle+"const epistemic=evaluateEvidenceSufficiency(project,{requirement:records(project,'requirements').find(r=>requirementId(r)===resultRequirementId(project,record))||null,test,result:record});if(!epistemic.sufficient)reasons.push(...epistemic.reasons);"
 one(needle,repl)
needle="else if(collection==='representationInspections'){if(!evidence.sufficient)reasons.push(...evidence.reasons);"
one(needle,needle+"const epistemic=evaluateEvidenceSufficiency(project,{result:record});if(!epistemic.sufficient)reasons.push(...epistemic.reasons);")
# Stage 29: structural links are insufficient unless the evidence class can establish the proposition.
one("effective=effectiveDetermination(collection,result,test,project),contract=evaluateEvidenceContract(test,result,null,project);if(effective!=='SATISFIED')missing.push('NON_SATISFIED_EFFECTIVE_RESULT:'+tid);if(!contract.sufficient)missing.push('INSUFFICIENT_EVIDENCE:'+tid);","effective=effectiveDetermination(collection,result,test,project),contract=evaluateEvidenceContract(test,result,null,project),sufficiency=evaluateEvidenceSufficiency(project,{requirement,test,result});if(effective!=='SATISFIED')missing.push('NON_SATISFIED_EFFECTIVE_RESULT:'+tid);if(!contract.sufficient||!sufficiency.sufficient)missing.push('INSUFFICIENT_EVIDENCE:'+tid);")
# Make the Stage 29 explanation state why the evidence proves the proposition, not merely that a record exists.
pat=r"function evidenceChainExplanation\(project,chain\)\{.*?\}\nfunction operationalNextAction"
rep="""function evidenceChainExplanation(project,chain){const req=String(recordValue(chain,'REQ_ID')||chain.relationships?.REQ_ID||''),requirement=recordsForCurrentScope(project,'requirements').find(r=>requirementId(r)===req)||records(project,'requirements').find(r=>requirementId(r)===req)||null,tests=safe(recordValue(chain,'TEST_ID')),results=safe(recordValue(chain,'TEST_RESULT_ID')),evidence=safe(recordValue(chain,'EVIDENCE_ID')),identities=safe(recordValue(chain,'ARTIFACT_HASH_IDENTITY')),support=[],unresolved=[...safe(recordValue(chain,'MISSING_LINKS'))],resultCollections=['verification','deterministicResults','meaningResults','adversarialResults'];for(const t of tests)support.push(t+' applies to '+req);for(const id of results){let hit=null;for(const collection of resultCollections){const record=recordsForCurrentScope(project,collection).find(r=>recordId(r,collection)===String(id));if(record){hit={collection,record};break;}}if(!hit){unresolved.push('CURRENT_RESULT:'+id);continue;}const test=testForResult(project,hit.record),effective=effectiveDetermination(hit.collection,hit.record,test,project),contract=evaluateEvidenceContract(test,hit.record,null,project),sufficiency=evaluateEvidenceSufficiency(project,{requirement,test,result:hit.record});support.push('Effective determination for '+id+' is '+effective);if(contract.sufficient&&sufficiency.sufficient)support.push((contract.evidenceIds||sufficiency.presentEvidenceIds||[]).join(', ')+' satisfies the structural evidence contract and is capable of proving the proposition for '+id);else unresolved.push('INSUFFICIENT_EVIDENCE:'+id);if(effective!=='SATISFIED')unresolved.push('NON_SATISFIED_EFFECTIVE_RESULT:'+id);}for(const e of evidence)support.push(e+' is canonical evidence linked to the current proposition');for(const id of identities){const record=recordsForCurrentScope(project,'artifactIdentities').find(x=>recordId(x,'artifactIdentities')===id);if(record&&upper(recordValue(record,'AUTHORIZATION'))==='AUTHORIZED'&&truth(recordValue(record,'EXACT_HASH_MATCH'))&&truth(recordValue(record,'EXACT_SIZE_MATCH')))support.push(id+' proves audited delivery bytes match: '+String(recordValue(record,'PRE_DELIVERY_SHA256')||'UNKNOWN'));else unresolved.push('UNAUTHORIZED_ARTIFACT_IDENTITY:'+id);}return {proposition:'Delivered artifact satisfies '+req,support,unresolved:[...new Set(unresolved)]};}
function operationalNextAction"""
s,n=re.subn(pat,rep,s,count=1,flags=re.S)
if n!=1: raise SystemExit('evidenceChainExplanation replacement failed')
# Explicit contradiction facts for impossible release/delivery states. Avoid releaseMetrics here to prevent recursion.
old="if(product&&baseline&&String(recordValue(product,'BASELINE_ID')||product.relationships?.BASELINE_ID||'')!==recordId(baseline,'baselines'))push('PRODUCT_BASELINE_CONFLICT',recordId(product,'products'),['Product baseline differs from current baseline.']);return out;"
new="""if(product&&baseline&&String(recordValue(product,'BASELINE_ID')||product.relationships?.BASELINE_ID||'')!==recordId(baseline,'baselines'))push('PRODUCT_BASELINE_CONFLICT',recordId(product,'products'),['Product baseline differs from current baseline.']);const release=recordsForCurrentScope(project,'releaseRecords').at(-1),releaseAccepted=upper(recordValue(release,'DETERMINATION'))==='ACCEPTED';if(releaseAccepted){const blockers=openBlockers(project);if(blockers.length)push('ACCEPTED_RELEASE_WITH_BLOCKER',recordId(release,'releaseRecords'),blockers.map(b=>recordId(b,'blockers')));const violated=[...recordsForCurrentScope(project,'verification').map(r=>['verification',r]),...recordsForCurrentScope(project,'deterministicResults').map(r=>['deterministicResults',r]),...recordsForCurrentScope(project,'meaningResults').map(r=>['meaningResults',r]),...recordsForCurrentScope(project,'adversarialResults').map(r=>['adversarialResults',r])].filter(([collection,r])=>effectiveDetermination(collection,r,testForResult(project,r),project)==='VIOLATED').map(([collection,r])=>collection+':'+(recordId(r,collection)||String(r.id||'UNKNOWN')));if(violated.length)push('ACCEPTED_RELEASE_WITH_MANDATORY_VIOLATION',recordId(release,'releaseRecords'),violated);const material=unresolvedMaterialDefects(project);if(material.length)push('ACCEPTED_RELEASE_WITH_MATERIAL_DEFECT',recordId(release,'releaseRecords'),material.map(d=>recordId(d,'defects')));}if(upper(project?.release?.authorization)==='AUTHORIZED'){const identities=recordsForCurrentScope(project,'artifactIdentities'),identityArtifactIds=identities.map(r=>String(recordValue(r,'ARTIFACT_ID')||r.relationships?.ARTIFACT_ID||'')).filter(Boolean).sort(),authorizedIds=safe(project.release.authorizedArtifactIds).map(String).sort(),identityCurrent=releaseAccepted&&identities.length>0&&identities.every(r=>upper(recordValue(r,'AUTHORIZATION'))==='AUTHORIZED'&&truth(recordValue(r,'EXACT_HASH_MATCH'))&&truth(recordValue(r,'EXACT_SIZE_MATCH')))&&hash.sha256Value(identityArtifactIds)===hash.sha256Value(authorizedIds);if(!identityCurrent)push('STALE_DELIVERY_AUTHORIZATION','DELIVERY_AUTHORIZATION',['Delivery authorization is not backed by the current accepted release and current exact Stage 28 artifact identities.']);}return out;"""
one(old,new)
P.write_text(s)
print('engine patch applied')
