from pathlib import Path
import re
P=Path('app-core.js'); s=P.read_text()
def one(a,b):
 global s
 if s.count(a)!=1: raise SystemExit('app match count '+str(s.count(a))+': '+a[:100])
 s=s.replace(a,b,1)
# Verification guidance: primary action first, exact handoff visible, architecture details collapsed.
pat=r"function testExecutionGuidanceMarkup\(n\)\{.*?\n\}\nfunction interactionModeMarkup"
rep="""function testExecutionGuidanceMarkup(n){
  const operation=selectedOperation(n),verificationStage=n===6||n===12||[22,23,24].includes(n)||(n===17&&['VERIFY','REGRESSION'].includes(operation))||(n===19&&['VERIFY','REGRESSION_VERIFY'].includes(operation));if(!verificationStage)return '';
  const plan=engine.testExecutionPlan(current);if(!plan.total&&n!==6)return '';
  const actionRows=plan.items.map(item=>({test:item.testId,requirement:item.requirementId,executor:item.executorClass,executionMode:item.executionMode,capability:item.requiredCapability,ready:item.executableNow?'YES':'NO',action:item.operatorAction,blockingReason:item.blockingReason||'NONE',files:item.requiredArtifactIds.map((id,index)=>`${id} — ${item.requiredArtifactNames[index]||'file'}`).join('; ')||'NONE',returnEvidence:item.returnRequirements.requiredEvidenceDescription})),handoff=engine.executionHandoff(current,{stage:n,operation}),handoffRows=[...handoff.send.map(x=>({direction:'SEND',item:`${x.artifactId} — ${x.filename}`,reason:`SHA-256 ${x.sha256}`})),...handoff.withhold.map(x=>({direction:'DO NOT SEND',item:x.artifactIdOrCategory,reason:x.reason})),...handoff.expectBack.map(x=>({direction:'RETURN',item:x.filenameOrPattern||x.kind,reason:x.required?'REQUIRED':'OPTIONAL'}))],blocked=plan.items.filter(x=>!x.executableNow),next=blocked[0]||plan.items.find(x=>x.operatorAction!=='NO_ACTION')||plan.items[0]||null,actionText=!next?'No accepted test definition exists yet.':!next.executableNow?`Blocked — ${next.testId}: ${next.blockingReason||'execution cannot proceed.'}`:next.operatorAction==='SEND_TO_INDEPENDENT_REVIEWER'?`Open a fresh independent reviewer context for ${next.testId}. Send only the exact files listed below and return the required JSON/evidence.`:next.operatorAction==='SEND_TO_TOOL_AGENT'?`Run ${next.testId} in an environment that actually has ${next.requiredCapability}. Send the exact files listed below and return the required evidence.`:next.operatorAction==='HUMAN_INSPECTION'?`Complete the human inspection for ${next.testId} and preserve the requested human observation evidence.`:next.operatorAction==='USE_EXTERNAL_SYSTEM'?`Run ${next.testId} in the required external system (${next.requiredCapability}) and return its exact evidence/files.`:`No operator action — the application can perform ${next.testId} deterministically.`,heading=n===6?'Verification execution plan':'Verification — what you need to do now',intro=n===6?'Stage 06 defines who will execute each test, with what capability, files, and proof. No test is represented as executed here.':'The application derives this action from the accepted test definition. You do not need to interpret internal execution modes.';
  const downloadButtons=handoff.send.map(x=>`<button type="button" data-download-artifact="${esc(x.artifactId)}">Download ${esc(x.filename)}</button>`).join('');
  return `<div class="panel" id="execution-guidance"${blocked.length?' tabindex="-1"':''}><h2 class="section-title">${esc(heading)}</h2><p class="section-intro">${esc(intro)}</p><div class="notice ${blocked.length?'warn':''}"><strong>What you need to do now</strong><br>${esc(actionText)}</div>${plan.unsupportedApplicationTestIds.length?`<div class="notice danger"><strong>Invalid application executor claim.</strong><br>No registered application-native executor exists for ${esc(plan.unsupportedApplicationTestIds.join(', '))}. Request a corrected Stage 6 test definition; do not substitute or fabricate native execution.</div>`:''}${handoffRows.length?details('Exact handoff — send / do not send / return',handoffRows,true):''}${downloadButtons?`<div class="button-row">${downloadButtons}</div>`:''}<details class="record-card"><summary>Advanced verification details<span>Audit</span></summary><div class="record-body"><p class="section-intro">Executor class, execution mode, capability readiness, and blocking diagnostics are shown here for audit. A filename, hash claim, or code block is not file possession, and browser-local custody does not transfer bytes to an external executor.</p>${actionRows.length?details('Derived execution routing',actionRows):'<div class="empty-state">No accepted test definition exists yet.</div>'}</div></details></div>`;
}
function interactionModeMarkup"""
s,n=re.subn(pat,rep,s,count=1,flags=re.S)
if n!=1: raise SystemExit('testExecutionGuidanceMarkup replacement failed')
# Concise stage purpose only where the operator needs orientation.
anchor="function provenanceAnchor(kind,id){"
helpfn="""function stagePurposeMarkup(n){const text={6:'AI is creating verification tests now. Test definition is not execution.',7:'Invalid examples are being created and actually checked so a validator cannot appear reliable without rejecting known-invalid cases.',10:'Select the exact verified files that make up this candidate. The application freezes their identities and hashes.',11:'The same frozen candidate is executed 10 times in independent fresh contexts.',12:'Each run is checked against the stored tests. Verifiers must remain independent from the generating run.',15:'Every confirmed defect becomes a permanent regression: definition, reproduced failure, later correction proof, and active future protection remain distinct.',17:'The corrected candidate is rerun through the complete ten-execution verification loop.',19:'The unchanged final candidate is rerun in ten new contexts to confirm stability without changing the candidate.',21:'The approved final product is created from the baseline. These exact stored output bytes become the product under test.',22:'The exact finished-product bytes are checked by the executor declared in each deterministic test. The application never invents execution that did not occur.',23:'Requirements needing meaning judgment go to an independent reviewer with only the context needed for that comparison.',24:'The finished product is deliberately challenged for failures and regressions without feeding the reviewer prior conclusions.',25:'The exact delivery files and required rendered/package representations are inspected.',26:'Process evidence and product evidence are reconciled as separate propositions.',27:'The application calculates whether release is allowed. Neither the agent nor the operator sets the release state.',29:'The application proves every mandatory requirement has a current structural evidence chain and evidence capable of proving the proposition.'}[n];return text?`<div class="notice"><strong>This stage</strong><br>${esc(text)}</div>`:'';}
"""
if helpfn.strip() not in s:
 if s.count(anchor)!=1: raise SystemExit('stage help anchor missing')
 s=s.replace(anchor,helpfn+anchor,1)
one("${locked?`<div class=\"notice warn\">${esc(lock)}</div>`:''}${n===1?","${locked?`<div class=\"notice warn\">${esc(lock)}</div>`:''}${stagePurposeMarkup(n)}${n===1?")
# Canonical artifact downloads verify bytes before transfer.
old="function files(){const all=[...safe(current.projectData.artifacts),...Object.values(current.stages).flatMap(s=>safe(s.authorizedFiles))];return `<div class=\"panel\"><h2 class=\"section-title\">Files and artifacts</h2><p class=\"section-intro\">Hashes are calculated only from actual bytes available to the browser. Metadata-only or external references remain identified as such.</p>${all.length?details('Recorded file identities',all,true):'<div class=\"empty-state\">No file bytes or artifact metadata have been recorded.</div>'}</div>`;}"
new="""async function downloadCanonicalArtifact(artifactId){const id=String(artifactId||''),canonical=engine.records(current,'artifacts').find(record=>engine.recordId(record,'artifacts')===id&&engine.isActiveRecord(record));if(!canonical)throw new Error('The selected canonical artifact is missing or inactive.');if(String(engine.recordValue(canonical,'AVAILABILITY')||'').toUpperCase()!=='BYTES_PERSISTED_AND_VERIFIED')throw new Error('The selected artifact does not have application-verified stored bytes.');const stored=await projectStore.getArtifact(id);if(!stored||String(stored.jobId)!==String(current.job.JOB_ID))throw new Error('The exact stored artifact bytes are unavailable for this project.');const bytes=await stored.blob.arrayBuffer(),actualSha256=await globalThis.closedLoopHash.sha256Bytes(bytes),expectedSha256=String(engine.recordValue(canonical,'SHA256')||''),expectedSize=Number(engine.recordValue(canonical,'BYTE_SIZE')),expectedFilename=String(engine.recordValue(canonical,'FILENAME')||stored.filename||id);if(bytes.byteLength!==expectedSize||actualSha256!==expectedSha256||String(stored.sha256)!==expectedSha256||Number(stored.byteSize)!==expectedSize||String(stored.filename)!==expectedFilename)throw new Error('Stored bytes no longer match the canonical filename, byte size, and SHA-256. Download was blocked.');const url=URL.createObjectURL(stored.blob),a=document.createElement('a');a.href=url;a.download=expectedFilename;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);announce('verified artifact ready for transfer: '+expectedFilename);}
function files(){const canonical=safe(current.projectData.artifacts).filter(record=>engine.isActiveRecord(record)),all=[...canonical,...Object.values(current.stages).flatMap(s=>safe(s.authorizedFiles))],downloads=canonical.filter(record=>String(engine.recordValue(record,'AVAILABILITY')||'').toUpperCase()==='BYTES_PERSISTED_AND_VERIFIED').map(record=>{const id=engine.recordId(record,'artifacts'),name=engine.recordValue(record,'FILENAME')||id;return `<div class="button-row project-archive-row"><span>${esc(id)} · ${esc(name)} · SHA-256 ${esc(engine.recordValue(record,'SHA256')||'UNKNOWN')}</span><button type="button" data-download-artifact="${esc(id)}">Download exact bytes</button></div>`;}).join('');return `<div class="panel"><h2 class="section-title">Files and artifacts</h2><p class="section-intro">Hashes are calculated only from actual bytes available to the browser. Download re-verifies the stored Blob against the current canonical filename, byte size, and SHA-256 before transfer.</p>${downloads?`<div class="record-stack">${downloads}</div>`:'<div class="empty-state">No application-verified artifact bytes are currently downloadable.</div>'}${all.length?details('Recorded file identities',all,true):'<div class="empty-state">No file bytes or artifact metadata have been recorded.</div>'}</div>`;}"""
one(old,new)
wire="document.querySelectorAll('[data-jump-provenance]').forEach(b=>b.onclick=()=>{const node=$('#provenance-navigation');if(node?.tagName==='DETAILS')node.open=true;node?.scrollIntoView({behavior:'smooth',block:'start'});node?.focus();});"
one(wire,wire+"document.querySelectorAll('[data-download-artifact]').forEach(b=>b.onclick=()=>downloadCanonicalArtifact(b.dataset.downloadArtifact).catch(error=>{announce('artifact download blocked');alert(error.message||error);}));")
P.write_text(s)
print('app patch applied')
