name: Temporary repository snapshot

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Upload repository snapshot
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: repository-snapshot-${{ github.event.pull_request.head.sha }}
          path: |
            .
            !.git/**
          include-hidden-files: true
          compression-level: 0
          retention-days: 1
